"""Book 13 (Low-Latency Software) -- en. Curation only; the rules live in tools/termlink/.

Market vocabulary is ordinary English: most one-word terms carry an everyday
sense outside their defining chapter. STOP keeps a term linkable in its own
chapter and nowhere else; DROP removes it everywhere. Seeded 2026-09-25 as a copy of
Book 9's config (itself a copy of Book 8's) (itself a copy of Book 7's) (itself a copy of Book 6's) (itself seeded from Book 2's) (its STOP/DROP entries are inert unless this book defines the
term; its EXTRA_PROTECT masks are shared practice); curate after the text lands. Regenerate with:
  python3 tools/link_defined_terms.py --book 13 --unwrap --apply
  python3 tools/link_defined_terms.py --book 13 --apply
"""
AMBIG_POLICY = "drop"
# Ordinary English in every chapter but their own: linked only where defined.
STOP = {
    # Book 13: pervasive in every chapter; linked only where chapter 1 defines them.
    "latency",
    "Latency",
    "hot path",
    "Hot path",
    "Bar",
    "Breadth",
    "Unwind",
    "Predictor",
    "Accrued interest",
    "Annuity",
    "Base currency",
    "Cap",
    "Clean price",
    "Convexity",
    "Coupon",
    "Covenants",
    "Credit event",
    "Currency pair",
    "DV01",
    "Dirty price",
    "Discount yield",
    "Drawdown",
    "Effective duration",
    "Fails charge",
    "Fixed leg",
    "Fixing order",
    "Floating leg",
    "Floor",
    "Gilt",
    "Growth rate",
    "Hazard rate",
    "High yield",
    "Hold time",
    "Investment grade",
    "Linker",
    "Mark-out",
    "Negative convexity",
    "Net basis",
    "Normal volatility",
    "Odds",
    "Off-the-run",
    "On-the-run",
    "Par",
    "Pass-through",
    "Pip",
    "Policy rate",
    "Prepayment",
    "Quote currency",
    "Real yield",
    "Reference index",
    "Reserves",
    "Seniority",
    "Specialness",
    "Strip",
    "Swaption",
    "Tranche",
    "Yield to maturity",
    "Z-spread",
    "accrued interest",
    "annuity",
    "base currency",
    "cap",
    "clean price",
    "convexity",
    "coupon",
    "covenants",
    "credit event",
    "currency pair",
    "dirty price",
    "discount yield",
    "drawdown",
    "effective duration",
    "fails charge",
    "fixed leg",
    "fixing order",
    "floating leg",
    "floor",
    "gilt",
    "growth rate",
    "hazard rate",
    "high yield",
    "hold time",
    "investment grade",
    "linker",
    "mark-out",
    "negative convexity",
    "net basis",
    "normal volatility",
    "odds",
    "off-the-run",
    "on-the-run",
    "par",
    "pass-through",
    "pip",
    "policy rate",
    "prepayment",
    "quote currency",
    "real yield",
    "reference index",
    "reserves",
    "seniority",
    "specialness",
    "strip",
    "swaption",
    "tranche",
    "yield to maturity",
    "z-spread",
}
DROP = {
    "Bundle",
    "Edge",
    "Inventory",
    "Pack",
    "Tail",
    "Turn",
    "Width",
    "bundle",
    "edge",
    "inventory",
    "pack",
    "tail",
    "turn",
    "width",
}
NO_CAPITAL = set()
EXTRA = {}
_G = r'(?:[^{}]|\{[^{}]*\})'
EXTRA_PROTECT = [
    r'\\texttt\{' + _G + r'*\}',                        # identifiers, not prose
    r'\\omcode\{[^{}]*\}\{[^{}]*\}\{[^{}]*\}\{' + _G + r'*\}',   # listing captions feed the list of listings
    r'\\begin\{omsources\}.*?\\end\{omsources\}',        # titles of other people's documents
    r'\\begin\{dated\}\{[^{}]*\}\{' + _G + r'*\}',        # box titles
    r'\\bfield\{[^{}]*\}',
    r'basis\s+points?',                                  # the unit, not the futures basis
    r'[Ss]pecial\s+(?:dividend|opening|case|purpose)s?',
    r'(?:zero|low|high)-coupon',                         # compounds, not the defined coupon
    r'fat-tailed',
]
