"""Build the serving fixture of firm.lobmodel from the pipeline's fitted model: data/forest.txt, data/vectors.csv (200
validation rows of the 10 features and the flat forest's output) and cpp/lobmodel_branches.hpp. Deterministic: running
it again leaves every file unchanged."""
from __future__ import annotations

import pathlib
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import firm_lobmodel as lm  # noqa: E402
from firm_mlinfer import cpp_branches, write_forest  # noqa: E402


def main():
    with tempfile.TemporaryDirectory() as d:
        out, _ = lm.make_pipeline(d, lm.DEFAULT).run("fit")
    fit = out["fit"]
    write_forest(fit["forest"], HERE / "data" / "forest.txt")
    with open(HERE / "data" / "vectors.csv", "w") as fh:
        for x, y in zip(fit["vectors"], fit["flat"], strict=True):
            fh.write(",".join(repr(float(v)) for v in x) + f",{float(y)!r}\n")
    head = "// Generated by make_lobmodel_fixture.py from data/forest.txt: do not edit.\n#pragma once\n\n"
    (HERE / "cpp" / "lobmodel_branches.hpp").write_text(head + cpp_branches(fit["forest"], "lobmodel_branches"))


if __name__ == "__main__":
    main()
