"""Book 17 (The Industry: Firms, Roles and Careers) chapter briefs: data for tools/make_briefs.py --book 17.

`uses` lists terms defined elsewhere that the chapter relies on (not redefined); owners in parentheses:
(B16.10) = One Quant Book 16, chapter 10, checked against the multi-line \\index{} harvest of Books 1-16 on
2026-09-29 (3,383 definitions); (B18.7) = the batch book by its outline (to be confirmed at the sync);
(ch13) = an earlier chapter of this book.

Ownership. Books 1-16 keep their terms. Book 1 owns the firm types (market maker, proprietary trading firm, hedge
fund, multi-manager platform, asset manager, assets under management, sell side, buy side, sales-trader, commodity
trading advisor, options market maker, wholesaler); Book 2 the legal entity identifier, liability-driven investment
and the Kelly criterion; Book 3 the crypto business vocabulary (centralised exchange, token, token unlock, token
market-making agreement, crypto-asset service provider) and follow-the-sun trading; Book 4 the Sharpe ratio, utility,
certainty equivalent and relative risk aversion; Book 5 structured product and structuring margin; Book 6 model
validation, model risk management, three lines of defence, product control, XVA desk; Book 7 survivorship bias and
breadth; Book 8 pod, statistical arbitrage, trend following; Book 10 high-frequency trading and algorithmic trading;
Book 11 electronic market maker and revenue capture; Book 12 machine-learning engineer and model owner; Book 15
on-call rotation; Book 16 the compensation-policy, restrictive-covenant, business-model and organisation terms (bonus
pool, formulaic payout, discretionary bonus, deferred compensation, vesting schedule, malus, clawback, material risk
taker, deferral buyout, non-compete clause, garden leave, non-solicitation clause, payout rate, pass-through fee,
compensation ratio, quant developer, chief risk officer, front/middle/back office, limited liability partnership,
members' capital, emerging manager, track record portability, decision journal, Herfindahl--Hirschman index).
This book owns industry-landscape, employer-type, role, career-path, pay-structure and pay-data terms: the role
titles of Part III (except quant developer, machine-learning engineer and sales-trader, which it uses), LCA,
prevailing wage, wage level, the filings vocabulary of chapter 11, the tax and location vocabulary of chapters 15
and 27. Book 18 owns interview-process and question-method terms (online assessment, final round, take-home,
competitions as application items, offer negotiation, exploding offer, counter-offer).

Point of view. Book 16 is the employer's view (how a firm is run, what pay policy costs it); this book is the
employee's and the observer's: what can be known from outside, what a job is, what pay is worth to the person.
Chapters that touch Book 16's ground (ch4-5 against B16 ch3-4, ch7 against B16 ch5, ch11-13 against B16 ch1, 2, 10,
ch28 against B16 ch11) re-read it from that side with a prose pointer and do not repeat its tutorials or data.

Rules of this book (batch file, user ruling 3). Every number is dated, sourced to a public document and printed as a
range; headcounts, offices, AUM and pay live in `dated` boxes. Firm profiles use only filings, annual reports,
regulatory disclosures, the firms' own publications and reputable press, with one ledger row per attribution.
Criticism only from court or regulatory records, stated neutrally with the outcome. No ranking by prestige, no "best
employer" list; a cited league table names its publisher and date. Never an individual's pay or private details:
the "highest-paid director" line of UK accounts, named-executive pay in proxy statements and named pension-fund
executives' pay are never printed; firm-level aggregates only (staff costs, average headcount, median-employee pay).
Pay cells built from fewer than ten filings are suppressed. No legal, tax or career advice: the book explains how
things work, where the rules are, and how to compute with them.

Data (derived tables only are committed, under data/industry/ with LICENSES.md; raw files are streamed in the
scratchpad and never committed): US DOL OFLC LCA disclosure files FY2021-FY2026 (public domain; dol.gov refuses
scripts, so the Internet Archive's copies are fetched and both URLs are ledgered), BLS OEWS industry-occupation
tables (public domain), SEC Form ADV bulk files and EDGAR filings (public), Companies House accounts (iXBRL where
filed), EBA high-earner reports and banks' Pillar 3 remuneration tables, NCES IPEDS completions (public domain),
official tax schedules and official rent statistics. Pay ranges are base-salary ranges where the source is LCA or
OEWS, total-cost-per-head ranges where the source is a filing, and tail counts where the source is a high-earner
report: every figure says which.

Running project (code/firm/, all new, Python only; checked against the 466 existing directories on 2026-09-29):
  industrymap (ch1)  profiles (ch2)  lineage (ch3)  formadv (ch4)  teamtenure (ch5)  firmsize (ch6)
  bankmix (ch7)  ownercost (ch8)  payband (ch9)  tokencomp (ch10)  filings (ch11)  industrypnl (ch12)
  payoffer (ch13)  paydata (ch14)  aftertax (ch15)  roles (ch16-25, one role card and one analysis per chapter)
  workload (ch26)  locations (ch27)  careerpath (ch28)  edupipe (ch29)  careerdec (ch30)
They build on firmecon, partnership, podshop, multistrat, ddrules, bonuspool, gardenleave, bankdesk (Book 16),
marketmap and calendar (Books 3 and 1), autocall (Book 5), modelval and modelcard (Book 6), tokenloan (Book 3).
"""
SLUG = "industry"
PFX = "in"
HEAD = "One Quant Book 17 — The Industry: Firms, Roles and Careers"

_U_FIRMS = ["market maker (B1.1)", "proprietary trading firm (B1.1)", "hedge fund (B1.1)",
            "multi-manager platform (B1.1)", "asset manager (B1.1)", "assets under management (B1.1)"]
_U_SELL = ["sell side (B1.2)", "buy side (B1.3)", "broker-dealer (B1.2)", "franchise (B1.2)", "flow trading (B1.2)"]
_U_ECON = ["net trading revenue (B16.1)", "compensation ratio (B16.1)", "operating margin (B16.1)",
           "non-GAAP measure (B16.1)", "return on equity (B16.1)"]
_U_PAY = ["bonus pool (B16.10)", "formulaic payout (B16.10)", "discretionary bonus (B16.10)",
          "deferred compensation (B16.10)", "vesting schedule (B16.10)", "malus (B16.10)", "clawback (B16.10)",
          "material risk taker (B16.10)", "deferral buyout (B16.10)"]
_U_COV = ["non-compete clause (B16.11)", "garden leave (B16.11)", "non-solicitation clause (B16.11)",
          "confidentiality agreement (B16.11)", "trade secret (B16.11)"]
_U_LCA = ["labor condition application (ch14)", "prevailing wage (ch14)", "wage level (ch14)",
          "Standard Occupational Classification (ch14)", "small-cell suppression (ch14)"]
_ROLE_TUT = ("The role's pay evidence: LCA base-salary ranges (10th-90th percentile, median) for the role family by "
             "employer type and wage level from data/industry/lca_ranges.csv through firm.paydata, cells under ten "
             "filings suppressed, beside the OEWS range for the matching occupation in the securities industry.")

PARTS = [
    ("part.in.landscape", [
        dict(slug="01-a-map-of-the-industry", title="A Map of the Industry",
             hook="In one fiscal year's US labour-condition filings the job title quantitative researcher appears under employers of at least five business models -- electronic market makers, systematic funds, multi-manager platforms, banks and asset managers -- with offered base salaries spread over a factor of about three. The title names a task, not a job; the employer's business model decides what the task is for. (Numbers from the chapter's own LCA table.)",
             sections=["Five questions that place an employer: whose capital, who pays, horizon, product, size",
                       "The taxonomy: business models and their sub-types",
                       "Size: headcount, capital and revenue bands",
                       "How the series maps onto the industry",
                       "Reading an employer from outside: codes, registrations and filings"],
             defines=["principal trading firm", "industry classification code", "employer taxonomy"],
             uses=_U_FIRMS + _U_SELL + ["commodity trading advisor (B1.3)", "electronic market maker (B11.1)",
                   "commodity trading house (B3.1)", "centralised exchange (B3.15)", "legal entity identifier (B2.28)",
                   "exchange (B1.4)", "broker (B1.4)"],
             tutorial="Classify a committed sample of about sixty employers (public identifiers only: SIC code from EDGAR, NAICS code from their LCA filings, regulator registrations -- SEC adviser, FINRA broker-dealer, NFA, FCA permissions -- and LEI) into the taxonomy with firm.industrymap's rules; compare the code-based class with the business-model class sourced in the ledger. End state: a taxonomy tree with counts per class, and a confusion table showing where industry codes misplace trading firms.",
             build="`firm.industrymap`: the employer taxonomy as data (business model, sub-type, size band, products), classification rules from public identifiers (NAICS, SIC, registration categories), the map from employer types to the series' books, and an agreement score between code-based and sourced classes; Python.",
             problem="Classifying from the outside -- named result: the share of the sample that industry codes alone place in the right business model, and the smallest set of public registrations that raises it above 90 per cent.",
             facts=["NAICS 2022 structure for 5231, 5239, 5221, 5242 and 5415 (US Census Bureau) and the 2017-to-2022 recoding of 523110/523120 into 523150", "SEC SIC codes 6211, 6282, 6199, 6798 (EDGAR company search definitions)", "FIA Principal Traders Group's description of principal trading firms (dated)", "FCA register permission names: dealing in investments as principal, managing investments (dated)", "SEC Form ADV and FINRA BrokerCheck as public registration records", "GLEIF LEI data licence (CC0)", "EU NACE Rev. 2.1 class 64.99/66.12 equivalents (Eurostat)"],
             data="data/industry/employer_sample.csv (public identifiers, ledger ids); counts from data/industry/lca_ranges.csv."),
        dict(slug="02-proprietary-market-makers-and-high-frequency-firms", title="Proprietary Market Makers and High-Frequency Firms",
             hook="One electronic market maker files a Form 10-K every February; firms of comparable or larger size file nothing in the United States but the audited statement of financial condition of their broker-dealer, the accounts of their UK subsidiary at Companies House, and -- when they borrow -- a rating agency's or a newspaper's account of what their lenders were shown. Most of what is public about the industry's largest private firms comes through such side doors.",
             sections=["What the public record holds for a private trading firm",
                       "Origins: from the floors to the screens",
                       "Profiles: products, ownership, headcount and offices",
                       "Culture and technology as the firms describe them",
                       "Size and concentration: what venue and regulator data show"],
             defines=["open outcry", "floor trader", "firm profile"],
             uses=_U_FIRMS[:2] + ["principal trading firm (ch1)", "electronic market maker (B11.1)", "revenue capture (B11.1)",
                   "high-frequency trading (B10.24)", "latency arbitrage (B11.9)", "wholesaler (B1.10)",
                   "payment for order flow (B1.10)", "designated market maker (B1.29)", "limited liability partnership (B16.2)",
                   "technology treadmill (B16.2)", "net trading revenue (B16.1)"],
             tutorial="Build ten firm profiles from sourced facts with firm.profiles: load data/industry/profiles/*.csv (one row per fact: field, low, high, as-of date, ledger id), validate that every fact is sourced, dated and a range, flag facts older than the staleness limit, and render the comparison table and a chart of founding year against headcount range (log axis). End state: the profile table and the chart.",
             build="`firm.profiles`: a sourced-fact store for firm profiles (Fact(firm, field, low, high, unit, as_of, ledger_id)), validation rules (no fact without a ledger id and a date; point values only where the source gives one; ranges widened to the source's rounding), staleness checks, and LaTeX and CSV renderers; Python.",
             problem="What can the public know? -- named result: the disclosure gap, the share of a standard profile's fields that public sources fill for listed against private firms, and the median relative width of the private firms' headcount ranges.",
             facts=["Virtu Financial Form 10-K for 2025: headcount, offices, business lines (dated)", "X-17A-5 audited statements of financial condition of US broker-dealers of Jane Street, Citadel Securities, Hudson River Trading, Jump Trading, Tower Research, DRW (EDGAR; dated)", "Companies House accounts of UK subsidiaries (Jane Street Europe, Citadel Securities (Europe), HRT Europe, Jump Trading International, XTX Markets Ltd, Tower Research Capital Europe): average employees, turnover (dated)", "firms' own publications on founding, offices and technology (careers and technology blogs, conference talks, open-source releases: OCaml at Jane Street, Firedancer at Jump) (dated)", "Citadel Securities' own statement of its US retail volume share (dated)", "reputable press on reported revenues of private market makers (Bloomberg, FT, WSJ; context only, dated)", "Aquilina, Budish and O'Neill (2022, QJE) on latency races and the concentration of race wins", "CME floor history and the 2021 closure of most open-outcry pits (CME Group release)"],
             data="data/industry/profiles/*.csv (sourced facts)."),
        dict(slug="03-the-options-market-making-houses", title="The Options Market-Making Houses",
             hook="Three of today's largest global options market makers trace their start to a single trading floor, the Amsterdam options exchange opened in 1978; others grew out of the Chicago Board Options Exchange's floor (1973) and the Philadelphia Stock Exchange's. The floor's lesson -- price every strike, hold the book, hedge the risk -- still shapes how these firms hire and train.",
             sections=["Three lineages: Amsterdam, Chicago, Philadelphia",
                       "Training programmes as the firms describe them",
                       "How an options house differs from an electronic delta-one firm",
                       "Size and footprint"],
             defines=["options market-making house", "spin-out"],
             uses=["options market maker (B1.24)", "quoting obligation (B1.24)", "market-maker appointment (B1.30)",
                   "lead market maker (B1.19)", "mass quote (B11.19)", "live surface fit (B11.19)",
                   "open outcry (ch2)", "floor trader (ch2)", "firm profile (ch2)", "proprietary trading firm (B1.1)"],
             tutorial="Two public views of the business: (i) the lineage graph -- firms and founders' former employers as sourced edges (founded-by, spun-out-of) with firm.lineage, drawn as a directed graph with founding years; (ii) the market-maker share of US listed options volume over time from OCC's volume-by-account-type statistics (fallback: an exchange's own published origin statistics), as derived annual shares. End state: the lineage graph and the share chart.",
             build="`firm.lineage`: a sourced genealogy of trading firms (nodes with founding year and place; edges founded-by, spun-out-of, acquired-by, each with a ledger id), queries (ancestors, descendants, founding-decade counts), and a TikZ/CSV exporter; Python; reused in chapter 28.",
             problem="Three floors, one screen -- named result: the market makers' share of US listed options contracts in 2010 and 2025 (range across months), and the share of the sampled options houses founded by people from the three floors.",
             facts=["European Options Exchange founded Amsterdam 1978 (Euronext history)", "Optiver founded 1986, IMC 1989, Da Vinci 2006 (firms' own sites)", "Cboe founded 1973; Susquehanna founded 1987 (firm site); Wolverine, Peak6, Group One, Akuna founding years (firms' own sites)", "the firms' published descriptions of graduate trading programmes (dated)", "OCC monthly volume by account type (customer, firm, market maker) (theocc.com; may refuse scripts -- fallback Cboe statistics)", "Cboe and Nasdaq options market-maker quoting obligations (pointer to Book 1 ch. 24)", "Optiver and IMC headcount and offices from their own publications or Dutch filings (KvK filings are paid: firm publications and press only) (dated)"],
             data="data/industry/lineage.csv (sourced edges); data/industry/options_mm_share.csv (derived)."),
        dict(slug="04-quantitative-hedge-funds-and-systematic-managers", title="Quantitative Hedge Funds and Systematic Managers",
             hook="The most secretive funds in the business still file one public form: every registered US adviser states in Form ADV its regulatory assets under management, its number of employees and how many of them do investment advisory work, and the gross assets of each private fund it runs. Read side by side, the forms make managers that publish nothing else comparable.",
             sections=["Three families: research-driven multi-strategy funds, trend followers, statistical-arbitrage houses",
                       "What Form ADV and the private-fund statistics reveal",
                       "Assets, gross assets and concentration",
                       "Secrecy and publication: what these firms put in the public domain"],
             defines=["systematic manager", "discretionary manager", "regulatory assets under management", "exempt reporting adviser"],
             uses=["hedge fund (B1.1)", "assets under management (B1.1)", "commodity trading advisor (B1.3)",
                   "trend following (B8.19)", "statistical arbitrage (B8.1)", "master--feeder structure (B16.4)",
                   "general partner (B16.4)", "Herfindahl--Hirschman index (B16.30)", "market concentration (B16.30)",
                   "leverage (B1.6)", "industry classification code (ch1)"],
             tutorial="Stream a committed extract of the SEC's monthly Form ADV bulk file with firm.formadv: select advisers with private funds reported as hedge funds, compute RAUM per employee and per advisory employee, gross private-fund assets over RAUM, and the concentration of hedge-fund RAUM (top-10 share, Herfindahl--Hirschman index); highlight a sourced list of systematic managers. End state: a log-log scatter of RAUM against employees and the concentration table.",
             build="`firm.formadv`: a reader for the SEC's Form ADV bulk files (Item 5.A employees, 5.B advisory employees, 5.F RAUM, Schedule D 7.B.1 private-fund gross assets and fund type), streamed from the zip, with per-adviser metrics and concentration measures (wraps firm.moats' HHI if its interface fits, otherwise its own); Python; reused in ch. 5, 8 and 12.",
             problem="Assets per head -- named result: the interquartile range of RAUM per employee for hedge-fund advisers, the same for the sourced systematic managers, and the top-ten share and HHI of hedge-fund RAUM.",
             facts=["Form ADV Part 1A instructions: Items 5.A, 5.B, 5.F, Schedule D 7.B.1 (SEC)", "SEC FOIA bulk data: Information about registered investment advisers and exempt reporting advisers (monthly files; format, size)", "SEC Private Funds Statistics (latest quarter): qualifying hedge funds, gross and net assets (dated)", "Form ADV of named systematic managers: Renaissance Technologies, Two Sigma, D. E. Shaw, AQR, Man Group's US adviser, Winton, CFM, Squarepoint, Qube (dated; each only with its ADV row)", "the firms' published research (AQR papers, Man Institute, CFM arXiv papers) as evidence of what they publish", "Form ADV glossary: regulatory assets under management; exempt reporting adviser (Advisers Act 203(l), 203(m))"],
             data="data/industry/adv_hedge_advisers.csv (derived from the ADV bulk file); data/industry/systematic_managers.csv (sourced list)."),
        dict(slug="05-multi-manager-platforms", title="Multi-Manager Platforms",
             hook="The Form ADV of the largest multi-manager platforms shows their employee counts rising several-fold in a decade, while the press reports each year dozens of teams hired and dozens let go. For a portfolio manager the platform is a job with a known exit condition: a drawdown limit.",
             sections=["The platform from the employee's side",
                       "Size: assets, employees and teams",
                       "Team turnover: what the public record shows",
                       "Drawdown limits and how long a team lasts",
                       "How platforms hire"],
             defines=["team turnover rate", "team tenure"],
             uses=["multi-manager platform (B1.1)", "pod (B8.28)", "drawdown limit (B8.28)", "pass-through fee (B16.3)",
                   "payout rate (B16.3)", "centre book (B16.3)", "netting risk (B16.3)", "de-risking ladder (B16.8)",
                   "track record portability (B16.25)", "Sharpe ratio (B4.11)", "regulatory assets under management (ch4)"],
             tutorial="Two readings: (i) platform growth from Form ADV snapshots 2016-2026 with firm.formadv (employees, RAUM, private funds); (ii) team tenure implied by drawdown rules: on firm.multistrat's pods with Sharpe ratios drawn from a stated range, apply a two-step drawdown ladder (wrapping firm.podshop and firm.ddrules) and measure the survival curve of teams and the share of cut teams that were skilled. End state: ADV growth table and survival curves under two ladders.",
             build="`firm.teamtenure`: team survival under drawdown rules (Kaplan--Meier estimate from simulated teams, median tenure, false-cut rate), the relation between a platform's annual team turnover rate and the ladder, and a comparison hook for press-reported turnover ranges; Python; wraps firm.podshop and firm.ddrules.",
             problem="How long does a team last? -- named result: median team tenure under the ladder for teams of Sharpe ratio 0.5 and 1.0, and the share of cut teams whose true Sharpe ratio was above 0.5.",
             facts=["Form ADV rows of Millennium Management, Citadel Advisors, Point72 Asset Management, Balyasny, ExodusPoint, Schonfeld, Verition: employees and RAUM 2016-2026 (dated)", "press reports of team counts and team departures at platforms (Bloomberg, FT, WSJ; dated ranges; else EXCLUDED)", "any platform-published description of risk limits (only with a citable source)", "Grossman and Zhou (1993) pointer to Book 8 ch. 28"],
             data="data/industry/adv_platforms.csv (derived); synthetic teams."),
        dict(slug="06-medium-frequency-proprietary-shops", title="Medium-Frequency Proprietary Shops",
             hook="Most proprietary trading firms are small. FINRA's annual industry snapshot counts broker-dealers by size and business line, and the firms that trade only for their own account are overwhelmingly firms of a few dozen people or fewer; the few thousand-person firms of chapter 2 are the tail of a long distribution.",
             sections=["Medium frequency: horizons, capacity and infrastructure",
                       "The size distribution of proprietary firms",
                       "Newer entrants and firms that grew out of crypto",
                       "Profit splits, arcades and funded-trader programmes",
                       "What a small firm means for the employee"],
             defines=["medium-frequency trading", "trading arcade", "funded-trader programme"],
             uses=["proprietary trading firm (B1.1)", "statistical arbitrage (B8.1)", "strategy capacity (B7.28)",
                   "members' capital (B16.2)", "own funds (B16.2)", "K-factor requirement (B16.2)",
                   "dealing on own account (B16.17)", "formulaic payout (B16.10)", "principal trading firm (ch1)"],
             tutorial="Fit the size distribution of proprietary firms: FINRA industry snapshot counts by size band and business type, and investment-firm class counts from the EBA/FCA reports where published, as derived tables; fit a Pareto tail with firm.firmsize (maximum likelihood on binned data, with its standard error) and compute the share of employment in firms under fifty staff. End state: a log-log size-distribution chart with the fitted tail.",
             build="`firm.firmsize`: size-distribution tools for binned public counts (binned Pareto and lognormal maximum likelihood, tail index with standard error, employment shares, goodness of fit); Python.",
             problem="The long tail -- named result: the Pareto tail index of proprietary-firm sizes with its standard error, and the share of the category's employment at firms under fifty people.",
             facts=["FINRA Industry Snapshot 2025/2026: registered firms by size and by business line (proprietary trading) (dated)", "EBA or FCA statistics on investment firms by class under IFR/MIFIDPRU (dated)", "CFTC v. Traders Global Group (My Forex Funds), complaint 2023 and outcome (court record) -- neutral, with the outcome", "FCA statements on trading arcades or funded-trader schemes, if any (dated; else EXCLUDED)", "sourced examples of medium-frequency firms that grew out of crypto (firm publications)"],
             data="data/industry/finra_snapshot.csv, data/industry/investment_firm_classes.csv (derived)."),
        dict(slug="07-bank-markets-divisions", title="Bank Markets Divisions",
             hook="Banks report their markets revenue in two lines, fixed income, currencies and commodities against equities, and the split differs across banks by more than their size does: in the same year some earn more than half their markets revenue from equities, most from rates and credit. The mix is the product strength, and it decides which quant jobs the bank has.",
             sections=["What banks publish about their markets businesses",
                       "American banks",
                       "The French banks and equity derivatives",
                       "Other European and Asian banks",
                       "League tables: who compiles them and what they measure",
                       "Quant headcounts: what is and is not public"],
             defines=["FICC", "league table", "revenue pool"],
             uses=_U_SELL + ["prime services (B1.2)", "risk-weighted assets (B1.2)", "structured product (B5.19)",
                   "allocated equity (B16.5)", "binding capital constraint (B16.5)", "quantitative investment strategy (B9.27)",
                   "franchise P\\&L (B9.24)", "central risk book (B9.25)", "XVA desk (B6.20)"],
             tutorial="A derived table of markets revenue by bank and year, 2019-2025, from filings (US 10-Ks, European annual reports and results) for about twelve banks, converted at annual average FX rates with sources: firm.bankmix computes each bank's equities share, the dispersion of mixes, their stability across years and their sensitivity to the VIX yearly mean. Banks are ordered by equities share, not by size. End state: a stacked chart of FICC and equities by bank and a table of shares.",
             build="`firm.bankmix`: bank segment revenue mapping (each bank's reported lines to FICC and equities, with the filing's own definitions noted), currency conversion from sourced annual averages, mix metrics and their year-to-year stability; Python; reads Book 16's data/desk/vix_annual.csv.",
             problem="Where the equity derivatives are -- named result: each bank's equities share of markets revenue as a range over 2021-2025, and the share of the group's equities revenue earned by the three most equity-heavy banks.",
             facts=["markets revenue lines 2019-2025 of JPMorgan Chase, Goldman Sachs, Morgan Stanley, Citigroup, Bank of America (Forms 10-K) (dated)", "BNP Paribas Global Markets (FICC, equity and prime services) and Societe Generale Global Markets (equities, fixed income and currencies) from results and universal registration documents (dated)", "Barclays, Deutsche Bank, UBS, HSBC, Nomura markets lines (annual reports) (dated)", "a source for the French banks' equity-derivatives specialisation (AMF or Banque de France publications on structured products; academic studies) (dated)", "Coalition Greenwich index press releases: what it measures and who it covers (publisher and date only)", "Euromoney FX survey description (publisher and date only)", "ECB/Fed H.10 annual average exchange rates"],
             data="data/industry/bank_markets_revenue.csv (derived, filing and page per row)."),
        dict(slug="08-asset-managers-pensions-sovereign-funds-and-insurers", title="Asset Managers, Pensions, Sovereign Funds and Insurers",
             hook="Norway's sovereign fund manages well over a trillion dollars with about seven hundred employees and reports its management costs at a few basis points of the fund; a pension fund of a tenth of the size may employ more people, because it manages more in-house. On the asset-owner side, quants sit where the owner has decided to do the work itself.",
             sections=["Asset owners and their in-house teams",
                       "Where quants sit: allocation, risk, liability matching, factor and index engineering",
                       "Long-only quantitative managers",
                       "Insurers: asset-liability management and the actuarial quant",
                       "Pace, pay and stability on the asset-owner side"],
             defines=["asset owner", "sovereign wealth fund", "defined-benefit pension plan", "internal management"],
             uses=["asset manager (B1.1)", "mandate (B1.3)", "benchmark (B1.3)", "passive management (B1.3)",
                   "active management (B1.3)", "tracking error (B1.3)", "liability-driven investment (B2.7)",
                   "factor product (B8.29)", "asset--liability management (B6.24)", "management fee (B1.3)",
                   "assets under management (B1.1)"],
             tutorial="A derived table from about eight asset owners' annual reports (assets, employees, operating costs, share managed internally): firm.ownercost computes cost in basis points, staff per $10bn, and a model of internal against external management cost (team size and staff cost per head against external fee rates). End state: a chart of cost in basis points against the share managed internally, and the break-even table.",
             build="`firm.ownercost`: asset-owner cost model (internal team cost as headcount times staff cost per head plus systems, against external fees on the same assets), the break-even mandate size, and sensitivity to the fee rate; Python.",
             problem="Build or hire the team -- named result: the mandate size above which internal management is cheaper than an external fee of 10 to 40 basis points, for staff cost per head in the range the chapter's filings give.",
             facts=["NBIM (Norges Bank Investment Management) annual report 2025: market value, employees, management cost ratio (dated)", "CPP Investments annual report FY2026: net assets, employees, operating expenses (dated)", "Ontario Teachers', APG/ABP, CalPERS, Australia's Future Fund, GPIF annual reports: assets, staff, costs, internal share (dated)", "Thinking Ahead Institute Global Pension Assets Study (press summary; dated)", "EIOPA insurance statistics: investments of EU insurers (dated)", "International Forum of Sovereign Wealth Funds / Santiago Principles definition of a sovereign wealth fund"],
             data="data/industry/asset_owners.csv (derived, source per row)."),
        dict(slug="09-exchanges-brokers-vendors-and-regulators-as-employers", title="Exchanges, Brokers, Vendors and Regulators as Employers",
             hook="Listed exchange groups publish what trading firms do not: headcount, revenue and pay costs every year. So do regulators, which also publish the pay bands of their grades. The rest of the ecosystem is the most transparent part of the industry to work in.",
             sections=["Exchange groups and clearing houses",
                       "Brokers and trading-technology vendors",
                       "Data vendors",
                       "Regulators and central banks",
                       "Moving between the sides"],
             defines=["financial market infrastructure", "pay band"],
             uses=["exchange (B1.4)", "broker (B1.4)", "central counterparty (B1.5)", "clearing member (B1.30)",
                   "market data feed (B1.4)", "independent software vendor (B14.27)", "self-regulatory organisation (B16.17)",
                   "revenue per head (ch12, forward)"],
             tutorial="A derived table of listed exchange groups' and vendors' revenue, operating profit and employees (CME, ICE, Nasdaq, Cboe, LSEG, Deutsche Boerse, Euronext, HKEX, SGX, JPX) for 2021-2025, and the published pay bands of three regulators with firm.payband (grade, band, locality adjustment, conversion to annual ranges). End state: revenue per head by firm and a chart of regulators' bands against LCA ranges for comparable occupations.",
             build="`firm.payband`: public pay-scale reader (grades, steps, bands, locality supplements), conversion to annual ranges in one currency, and comparison with other range sources; Python; reused in ch. 14 and 24.",
             problem="Revenue per head at the infrastructure -- named result: the range of revenue and of operating profit per employee across exchange groups in 2025, and the ratio of a regulator's top quantitative-analyst band to the LCA median for the same occupation.",
             facts=["exchange groups' 10-K and annual reports 2021-2025: revenue, operating income, employees (dated)", "SEC SK pay schedule and locality (sec.gov careers) (dated)", "CFTC CT pay schedule (dated)", "FCA and Bank of England annual reports: staff numbers and pay-band disclosures (dated)", "ESMA staff numbers (annual report) (dated)", "CPMI-IOSCO Principles for Financial Market Infrastructures (2012): definition"],
             data="data/industry/infrastructure_employers.csv, data/industry/regulator_payscales.csv (derived)."),
        dict(slug="10-crypto-native-firms", title="Crypto-Native Firms",
             hook="The largest US-listed crypto exchange cut its staff by about a fifth in June 2022 and again in January 2023, then hired back as prices rose: in crypto, headcount follows the price of the asset the industry trades. (Verify against the firm's filings and releases.)",
             sections=["Kinds of employer: market makers, funds, exchanges, protocol teams and foundations",
                       "What is different: round-the-clock operations, custody, token pay, regulatory status",
                       "Headcount through the cycle",
                       "Paid in tokens",
                       "When the firm fails: the employee in the bankruptcy record"],
             defines=["protocol foundation", "token compensation", "token warrant"],
             uses=["centralised exchange (B3.15)", "token (B3.14)", "token unlock (B3.24)", "token market-making agreement (B3.24)",
                   "crypto-asset service provider (B3.24)", "Markets in Crypto-Assets Regulation (B3.24)", "hot wallet (B3.24)",
                   "stablecoin (B3.14)", "vesting schedule (B16.10)", "follow-the-sun trading (B3.29)"],
             tutorial="Headcount against the cycle: employees and stock-based compensation of listed crypto firms from their 10-Ks and releases against the annual mean of the bitcoin price (a public-domain or openly licensed price series as derived statistics); then value a token grant with firm.tokencomp. End state: a chart of headcount changes against price changes and the distribution of a four-year token grant's value.",
             build="`firm.tokencomp`: token-grant valuation (vesting with cliff, lock-up, lognormal price paths at a stated volatility, a liquidity discount, tax at vesting against tax at sale as parameters), with the probability that tax due at vesting exceeds the value at sale; Python; wraps firm.tokenloan's option pricing where it fits.",
             problem="Paid in tokens -- named result: the median and 10th-90th percentile value of a four-year token grant with a one-year cliff at 80 per cent volatility against the same nominal in cash, and the probability that tax at vesting exceeds the proceeds.",
             facts=["Coinbase Global Forms 10-K 2020-2025 and 8-K releases: headcount, layoffs of June 2022 and January 2023 (dated)", "other listed crypto employers' headcounts (Galaxy Digital, Bakkt or others with filings) (dated)", "FTX Trading Ltd. chapter 11 docket: treatment of employee claims (court record; neutral with outcome)", "IRS Rev. Rul. 2023-14 and Notice 2014-21 on tokens received for services; HMRC Cryptoassets Manual on employment income (dated)", "Electric Capital developer report: monthly active developers (dated, publisher named)", "Ethereum Foundation or another protocol foundation's own published description of its role"],
             data="data/industry/crypto_headcount.csv (derived); price series as derived annual statistics."),
    ]),
    ("part.in.money", [
        dict(slug="11-reading-a-trading-firms-accounts", title="Reading a Trading Firm's Accounts",
             hook="For nothing but a download, the UK register gives ten years of a trading firm's accounts, many of them machine-readable: turnover, operating profit, average number of employees, staff costs, and for a partnership the profit shared among its members. Staff costs over average employees is the most honest pay figure in the industry -- and it still hides the partners.",
             sections=["Where the filings are: registries, EDGAR, annual reports, prospectuses, divisional and Pillar 3 reports",
                       "What statutory accounts contain",
                       "Machine-readable filings: inline XBRL and XBRL",
                       "Pitfalls: entity against group, members against employees, currencies and one-offs",
                       "Per-head measures and their caveats"],
             defines=["company registry", "statutory accounts", "consolidated accounts", "inline XBRL", "staff costs",
                      "average headcount", "members' remuneration", "FOCUS report", "Pillar 3 disclosure"],
             uses=_U_ECON + ["limited liability partnership (B16.2)", "members' capital (B16.2)", "transfer pricing (B16.15)",
                   "broker-dealer (B1.2)", "net capital rule (B16.2)", "firm profile (ch2)"],
             tutorial="Pull five years of one firm's filings: a committed snapshot (facts extracted from the firm's Companies House iXBRL accounts and, for a US broker-dealer, its X-17A-5 statement of financial condition, each fact with filing id, URL and page) read with firm.filings; reconcile turnover, operating profit, staff costs and average headcount; compute staff cost per head and, for an LLP, members' remuneration per member. A fetch script re-pulls the originals into the scratchpad (never committed); tests run offline on the snapshot and on a synthetic iXBRL fixture. End state: a five-year table and a chart of revenue and staff cost per head.",
             build="`firm.filings`: an inline-XBRL facts parser (standard library only: contexts, units, scale, sign and format attributes), an EDGAR company-facts JSON reader, a Snapshot of facts with provenance, and a mapping to firm.firmecon's Statement lines; Python.",
             problem="Five years at Companies House -- named result: the firm's staff cost per head and revenue per head as ranges over five years, and the share of profit before members' remuneration paid to members (for an LLP) or distributed (for a company).",
             facts=["Companies Act 2006 s. 411 (staff numbers and costs) and the LLP (Accounts and Audit) Regulations 2008 with the LLP SORP on members' remuneration", "Companies House: iXBRL filing share, free document download, the Accounts Data Product and its licence (dated)", "SEC EDGAR fair-access policy (user agent, rate limit) and company-facts API", "SEC Rule 17a-5: public parts of the annual report (statement of financial condition) (dated)", "CRR Part Eight, Article 450 (remuneration disclosure) and EBA ITS templates REM1-REM5 (dated)", "ESMA European Single Electronic Format (ESEF) requirement", "Rule 144A offering memoranda are not public: what the press reports of them is context only", "the chosen firm's filings, five years (dated)"],
             data="data/industry/filings_snapshot/*.csv (extracted facts with provenance); tests/fixtures synthetic iXBRL."),
        dict(slug="12-revenue-and-profit-across-the-industry", title="Revenue and Profit across the Industry",
             hook="Put every firm that files side by side and revenue per employee ranges over more than a factor of ten, from bank markets divisions and asset managers at the low end to the most profitable private market makers; and within a firm it can double from a quiet year to a volatile one. The table is the industry's income, and its gaps are the firms that file nothing.",
             sections=["A sourced table of filed numbers",
                       "Per head: what it measures and what it hides",
                       "Volatility regimes: how results move with the market",
                       "Who is missing: survivorship and disclosure bias"],
             defines=["revenue per head", "profit per head", "disclosure bias"],
             uses=_U_ECON + ["survivorship bias (B7.3)", "staff costs (ch11)", "average headcount (ch11)", "statutory accounts (ch11)",
                   "regulatory assets under management (ch4)", "firm profile (ch2)"],
             tutorial="Build the industry table: data/industry/filings_perhead.csv (about twenty filers, 2019-2025, from ch. 11's snapshots, Book 16's derived tables and new filings) read with firm.industrypnl; normalise currencies and inflation; regress log revenue per head on the VIX yearly mean with firm fixed effects, by firm type. End state: a chart of revenue per head by firm type across years (log axis) and a table of elasticities with standard errors.",
             build="`firm.industrypnl`: a firm-year panel with per-head metrics, currency and inflation normalisation from sourced series, fixed-effects regression on a volatility measure, ranges by firm type and year; Python; wraps firm.firmecon and firm.filings.",
             problem="The good year -- named result: the elasticity of revenue per head to the VIX yearly mean by firm type, with its standard error, and the range of the 2020 to 2023 revenue-per-head ratio across market makers.",
             facts=["filings per firm: Virtu, Flow Traders, the UK accounts of private market makers (ch. 2), Man Group, exchange groups (ch. 9), bank markets segments (ch. 7), 2019-2025 (dated)", "Cboe VIX index history as derived annual means (Book 16's table)", "annual average FX (Fed H.10, ECB) and CPI (BLS via FRED)", "press reports of private firms' revenues (context only, dated; never in the table)"],
             data="data/industry/filings_perhead.csv (derived, source per cell)."),
        dict(slug="13-how-pay-works", title="How Pay Works",
             hook="New York's State Comptroller estimates each spring the average bonus paid in the city's securities industry, on top of salaries; the figure has swung by more than a third between consecutive years. An average bonus hides the structure that decides what pay is worth to the person who receives it: how much is fixed, how much is deferred, and what is lost on leaving.",
             sections=["Base and bonus: the two-part structure and why it exists",
                       "Formulaic and discretionary pay from the employee's side",
                       "Deferral, vesting, forfeiture and clawback: what deferred pay is worth",
                       "Sign-ons, guarantees and buyouts",
                       "Partnership, equity and carried interest",
                       "Structure by firm type"],
             defines=["base salary", "total compensation", "sign-on bonus", "guaranteed bonus", "forfeiture",
                      "good-leaver provision", "restricted stock unit", "carried interest", "partnership share"],
             uses=_U_PAY + ["payout rate (B16.3)", "high-water mark (B1.3)", "performance fee (B1.3)", "compensation ratio (B16.1)",
                   "limited liability partnership (B16.2)", "members' capital (B16.2)", "certainty equivalent (B4.9)",
                   "relative risk aversion (B4.9)", "utility function (B4.9)", "members' remuneration (ch11)"],
             tutorial="Value three stylised offers with firm.payoffer -- a bank role with a share of variable pay deferred in stock over four years, a market-maker role with base and discretionary bonus, a platform analyst's package with a payout share, a sign-on and a one-year guarantee -- with all parameters labelled illustrative and ranged where a public source exists: expected present value, the 10th-90th percentile range, the value forfeited on leaving in each year, and the certainty equivalent under CRRA utility. End state: box plots of the three distributions and a table of certainty equivalents.",
             build="`firm.payoffer`: a pay package as data (base, bonus distribution, deferral fraction and vesting schedule, forfeiture on leaving, good-leaver terms, sign-on, guarantee, clawback trigger, partnership share or carried interest), present value and distribution by simulation with a leaving hazard, certainty equivalent (CRRA), and the buyout needed to make a move neutral; Python; reused in ch. 22, 28 and 30 (and available to Book 18 ch. 7).",
             problem="Three offers, one choice -- named result: each offer's certainty equivalent at relative risk aversion 1 and 3, and the deferral buyout that makes moving in year two neutral.",
             facts=["New York State Comptroller: securities industry bonus estimate for 2025 and its history (dated)", "EU CRD V deferral and instrument rules and UK PRA/FCA remuneration rules after PS9/23 and the 2025 deferral changes (pointer to Book 16 ch. 10; dated)", "US bank proxy statements or 10-Ks describing firm-wide deferral policies for employees (firm policy only, never named executives) (dated)", "UK carried-interest tax reform from April 2025/2026 and US IRC s. 1061 three-year holding period (dated)", "press ranges of platform payout percentages (dated; context only)", "US RSU taxation at vesting (IRC s. 83) (dated)"],
             data="Illustrative parameters (labelled), ranged by the ledger's sources."),
        dict(slug="14-pay-levels-by-role-firm-type-and-seniority", title="Pay Levels by Role, Firm Type and Seniority",
             hook="Every public source of pay sees one slice. US visa filings see offered base salaries for sponsored positions, and nothing of bonuses; employer surveys by the government cap what they report; filed accounts see total staff cost per head, bonuses included, but average away the roles; high-earner reports count only the people above a million euros. A range worth printing is built from several slices, each with its caveat.",
             sections=["What each source measures",
                       "Building ranges from labour-condition filings",
                       "Ranges by role, firm type and seniority",
                       "From base to total: what staff cost per head says about bonuses",
                       "The tail: high-earner counts and risk-taker disclosures"],
             defines=["labor condition application", "prevailing wage", "wage level", "Standard Occupational Classification",
                      "top-coding", "small-cell suppression", "high earner", "median-employee pay"],
             uses=_U_PAY[:3] + ["material risk taker (B16.10)", "bootstrap (B4.13)", "survivorship bias (B7.3)", "staff costs (ch11)",
                   "average headcount (ch11)", "Pillar 3 disclosure (ch11)", "pay band (ch9)", "base salary (ch13)",
                   "total compensation (ch13)", "employer taxonomy (ch1)"],
             tutorial="The LCA pipeline end to end with firm.paydata, on the committed derived tables and a small synthetic fixture of raw rows: classify employers (firm.industrymap plus the sourced employer list) and roles (SOC code plus title patterns), annualise offered wages, take wage level as the seniority proxy, compute percentiles with bootstrap intervals, suppress cells under ten; then join OEWS ranges, the US pay-ratio rule's median-employee pay of listed firms, staff cost per head from filings and EBA high-earner counts. End state: the chapter's range table and a chart of base ranges by role and firm type.",
             build="`firm.paydata`: streaming LCA reader (openpyxl read_only, chunked; raw files never committed), classifiers, annualisation, percentile ranges with suppression, and a PayEvidence record (source, measure, population, caveat) that every other source is converted into; Python.",
             problem="Four sources, one number -- named result: the implied ratio of total pay to base, staff cost per head over LCA median base for the same firm type, as a range with the caveats that bound it.",
             facts=["DOL OFLC LCA disclosure data FY2021-FY2026: files, record layout, field definitions, the statement that determinations may change on appeal (dated)", "20 CFR 655 Subpart H and Form ETA-9035 (the attestation)", "OFLC prevailing-wage guidance: four wage levels (dated)", "SOC 2018 manual and O*NET 13-2099.01 Financial Quantitative Analysts", "BLS OEWS May 2025 national industry-specific estimates for NAICS 5231/5239/5221 and the wage top-code (dated)", "SEC pay-ratio rule, Item 402(u) of Regulation S-K: median-employee pay disclosed by listed firms (firm-level only) (dated)", "EBA high-earners report on 2024 data (April 2026): counts by country and business area (dated)", "banks' Pillar 3 REM tables (UK and EU): material risk takers, fixed and variable totals by business area (dated)", "NY Comptroller average securities-industry pay (dated)", "US federal works are public domain (17 U.S.C. 105)"],
             data="data/industry/lca_ranges.csv, lca_titles.csv, oews_finance.csv, pay_ratio_medians.csv, eba_high_earners.csv, pillar3_rem.csv (all derived); LICENSES.md."),
        dict(slug="15-pay-regulation-and-tax-by-location", title="Pay Regulation and Tax by Location",
             hook="From 2014 the European Union capped a bank risk-taker's bonus at twice fixed pay; the United Kingdom removed the cap in October 2023, citing its effect of raising fixed pay. The same package also leaves very different amounts after tax in London, New York, Amsterdam, Zurich, Singapore, Hong Kong and Dubai, and a special regime for incomers can change the answer in some of them.",
             sections=["Pay regulation: the bonus cap, deferral rules and who they cover",
                       "Income tax on salary and bonus",
                       "Expatriate regimes",
                       "Deferred and equity pay: when it is taxed",
                       "What a number is worth after tax"],
             defines=["bonus cap", "marginal tax rate", "average tax rate", "expatriate tax regime", "tax residence"],
             uses=_U_PAY + ["investment firm (B16.17)", "carried interest (ch13)", "restricted stock unit (ch13)",
                   "base salary (ch13)", "total compensation (ch13)"],
             tutorial="Compute after-tax pay with firm.aftertax on sourced 2026 schedules for eight locations: net pay for packages from 150 thousand to 3 million in local-currency equivalents with a range of base shares, the marginal rate on the last unit of bonus, and the effect of each expatriate regime where one exists. End state: a chart of average tax rate against gross pay (log axis) for the eight locations and a table of net pay for one package.",
             build="`firm.aftertax`: tax and social-contribution schedules as dated data with a ledger id per parameter (brackets, allowance tapers, contribution ceilings, local taxes, expatriate regimes), net pay, marginal and average rates, and bonus-against-salary treatment; tests against hand-computed cases and the authorities' published worked examples; Python.",
             problem="A million, eight ways -- named result: net pay from a package of one million (30 per cent base, 70 per cent bonus) in each of the eight locations, and the ratio of the highest to the lowest.",
             facts=["Directive 2013/36/EU art. 94(1)(g) as amended; Directive (EU) 2019/2034 art. 32 (investment firms)", "PRA PS9/23 and FCA PS23/15 (cap removed from 31 October 2023)", "US Dodd-Frank s. 956 proposals (2016; 2024 re-proposal) and their status (dated)", "HMRC income tax and NIC rates 2026/27; IRS 2026 brackets; New York State and City rates; Illinois flat rate (dated)", "Netherlands box 1 2026 and the 30 per cent ruling changes; Italy impatriate regime (2024 reform); France impatrie regime (CGI art. 155 B); Switzerland Zurich and Zug; Singapore resident rates (YA2026); Hong Kong two-tier standard rate from 2024/25; UAE absence of personal income tax (dated)", "UK non-dom abolition and the FIG regime from 6 April 2025 (dated)", "OECD Taxing Wages 2026 as a cross-check (licence to verify)"],
             data="data/industry/tax_2026.csv (parameters, source id each)."),
    ]),
    ("part.in.roles", [
        dict(slug="16-trader", title="Trader",
             hook="In 2021 the largest US derivatives exchange group announced that most of its open-outcry pits would not reopen; nearly all its futures volume was already electronic. The trader's job had moved from shouting to clicking to supervising algorithms, and at a market maker today one trader may watch strategies quoting thousands of instruments.",
             sections=["Three traders: market maker, bank flow desk, hedge fund",
                       "From click trading to supervising algorithms",
                       "Controls and accountability: registrations, certification, kill switches",
                       "A documented day"],
             defines=["risk trader", "execution trader", "click trader", "algorithm supervisor", "certification regime"],
             uses=["market maker (B1.1)", "sales-trader (B1.2)", "flow trading (B1.2)", "franchise P\\&L (B9.24)",
                   "kill switch (B11.27)", "loss limit (B11.27)", "pre-trade risk check (B11.27)", "algorithmic trading (B10.24)",
                   "open outcry (ch2)", "floor trader (ch2)"] + _U_LCA[:3],
             tutorial=_ROLE_TUT + " Then the supervisor's load with firm.roles: alerts from a set of strategies as a Poisson stream, handling times from a stated distribution, and the waiting-time tail of a single supervisor (queueing results from Book 4 ch. 8). End state: the pay-range chart and the number of strategies one supervisor can watch at a stated alert-response standard.",
             build="`firm.roles` (first increment): the role registry (role card: firm types, horizon, P&L ownership, reporting line, SOC codes and title patterns for LCA matching, the series books that teach it) and the supervision-load model; Python; each later chapter of Part III adds its role card and one analysis.",
             problem="One trader, many algorithms -- named result: the largest number of strategies one supervisor can oversee with at most a 1 per cent chance that an alert waits more than a minute, under the chapter's stated alert and handling rates, and its sensitivity to the alert rate.",
             facts=["CME Group release on open-outcry pits (2021) and electronic share of volume (dated)", "FINRA Series 57 Securities Trader Representative requirement (dated)", "FCA SM&CR certification functions including the algorithmic trading certification function (dated)", "MiFID II RTS 6 (Delegated Regulation 2017/589) staff and kill-functionality requirements", "firms' own published descriptions of a trader's day (careers pages; dated)", "EU/UK certification of traders at banks (FCA Handbook SYSC 27) (dated)"],
             data="data/industry/lca_ranges.csv; synthetic alert streams."),
        dict(slug="17-quant-researcher", title="Quant Researcher",
             hook="A high-frequency researcher sees the result of a change after a day of thousands of independent trades; a researcher whose signal rebalances monthly sees twelve observations a year, and needs decades to tell a Sharpe ratio of one-half from zero. The same title covers jobs whose feedback differs by a factor of a thousand.",
             sections=["Three research jobs: high frequency, medium frequency, asset manager",
                       "Horizon, data and feedback speed",
                       "Ownership of P&L and of credit",
                       "What a researcher ships",
                       "Where researchers come from"],
             defines=["quantitative researcher", "feedback speed"],
             uses=["Sharpe ratio (B4.11)", "breadth (B7.15)", "research log (B7.1)", "research review (B7.1)",
                   "credit attribution (B16.9)", "research portfolio (B16.9)", "medium-frequency trading (ch6)"] + _U_LCA[:3],
             tutorial=_ROLE_TUT + " Then feedback speed with firm.roles: the time needed to reject a zero Sharpe ratio at 95 per cent as a function of the signal's horizon and true Sharpe ratio (standard error of the estimated Sharpe ratio, Lo 2002), by role. End state: the pay-range chart and a log-log chart of years-to-significance against horizon.",
             build="`firm.roles` (increment): the quant-researcher role card and the feedback-speed function (years to significance, independent bets per year from horizon and breadth); Python.",
             problem="How long until you know? -- named result: the time to reject a zero Sharpe ratio for a true Sharpe ratio of 2 at a one-day horizon, of 1 at a one-week horizon and of 0.5 at a one-month horizon.",
             facts=["Lo (2002), The statistics of Sharpe ratios, Financial Analysts Journal", "firms' own descriptions of quantitative-research roles (careers pages; dated)", "pointer to Book 7 ch. 15 (breadth) and Book 16 ch. 9 (credit attribution)"],
             data="data/industry/lca_ranges.csv."),
        dict(slug="18-bank-quant", title="Bank Quant",
             hook="In April 2011 US bank supervisors issued guidance requiring every model to be developed, validated and governed; the United Kingdom followed with its own principles in force from May 2024. Each model now has an owner, a developer and a validator, and a bank's quant job title says which of the three it is.",
             sections=["Desk strategist", "Library quant", "Risk quant", "Model validator", "Valuation-adjustment quant",
                       "Who they answer to and what they ship"],
             defines=["desk strategist", "library quant", "risk quant", "model validator"],
             uses=["model validation (B6.26)", "model risk management (B6.26)", "model inventory (B6.26)", "model tiering (B6.26)",
                   "effective challenge (B6.26)", "three lines of defence (B6.26)", "XVA desk (B6.20)", "internal models approach (B6.23)",
                   "product control (B6.27)", "model owner (B12.28)"] + _U_LCA[:3],
             tutorial=_ROLE_TUT + " Then the validation workload with firm.roles (wrapping firm.modelval and firm.modelcard): an inventory of models by tier, review frequency and hours per review as labelled parameters anchored to the public guidance, and the validator headcount it implies. End state: the pay-range chart by bank-quant family and the headcount curve.",
             build="`firm.roles` (increment): the four bank-quant role cards, a reporting-line graph with an independence check (a validator must not report to the model's owner), and the validation-workload model; Python.",
             problem="Who validates the validators? -- named result: the validator headcount for an inventory of 1,000 models split by tier under the chapter's review cycle, and its sensitivity to the share of tier-one models.",
             facts=["Federal Reserve SR 11-7 / OCC 2011-12 (April 2011)", "PRA SS1/23, model risk management principles, effective 17 May 2024", "ECB guide to internal models (dated)", "Basel FRTB internal models approach (pointer Book 6 ch. 23)", "banks' own descriptions of strat and quantitative-research groups (firm publications; dated)"],
             data="data/industry/lca_ranges.csv."),
        dict(slug="19-quant-developer", title="Quant Developer",
             hook="In the labour-condition filings, positions titled quant developer are filed under at least three occupation codes -- software developers, financial quantitative analysts and others -- with different wage ranges. Three different jobs share the title: the researcher's engineer, the desk's library developer and the trading-system developer.",
             sections=["The researcher's engineer", "The desk's library developer", "The trading-system developer",
                       "What each ships and how it is judged", "Moving between the three"],
             defines=["research engineer", "library developer", "trading-system developer"],
             uses=["quant developer (B16.21)", "embedded team (B16.21)", "central team (B16.21)", "machine-learning engineer (B12.28)",
                   "tick-to-trade latency (B13.1)", "latency budget (B13.1)", "library quant (ch18)"] + _U_LCA,
             tutorial=_ROLE_TUT + " Then the title study with firm.roles: normalise job titles, cross-tabulate the quant-developer family against SOC codes, and compare wage ranges by SOC group with bootstrap intervals. End state: a stacked chart of SOC codes within the title and the range gap.",
             build="`firm.roles` (increment): a job-title normaliser (patterns, seniority prefixes, abbreviations), the title-by-SOC cross-tabulation, and the three quant-developer role cards; Python.",
             problem="One title, three jobs -- named result: the SOC mix of quant-developer filings and the difference in median offered base between the software-developer and the quantitative-analyst codes, with its bootstrap interval.",
             facts=["SOC 2018: 15-1252, 13-2099, 15-2041, 15-2051 definitions", "O*NET 13-2099.01", "Book 16 ch. 21's definition of the quant developer (pointer)"],
             data="data/industry/lca_titles.csv (derived)."),
        dict(slug="20-software-engineer", title="Software Engineer",
             hook="A listed electronic market maker of about a thousand people states in its annual report what share of its staff works in technology; a large technology company employs a hundred times as many people. At a trading firm an engineer is one of a few hundred, a few steps from the P&L, and on call while markets are open.",
             sections=["Core, low-latency, infrastructure, hardware and network engineering",
                       "How a trading firm differs from a technology company",
                       "Pay and progression compared with technology firms",
                       "Public engineering: blogs, talks and open source"],
             defines=["low-latency engineer", "FPGA engineer", "site reliability engineer"],
             uses=["latency (B13.1)", "tail latency (B13.1)", "kernel bypass (B13.13)", "colocation (B14.9)",
                   "on-call rotation (B15.28)", "blameless review (B15.28)", "service-level objective (B15.28)",
                   "platform team (B16.19)", "product team (B16.19)", "research engineer (ch19)", "trading-system developer (ch19)"] + _U_LCA,
             tutorial=_ROLE_TUT + " Then the comparison with firm.roles: SOC 15-1252 filings at trading firms against a sourced list of large technology employers, by wage level, as a ratio of medians with bootstrap intervals. End state: a chart of the ratio by wage level.",
             build="`firm.roles` (increment): the engineering role cards and a two-population range comparison (ratio of medians, bootstrap interval, cell suppression); Python.",
             problem="Trading firm or technology company? -- named result: the ratio of median offered base at trading firms to large technology employers for software developers at each wage level, with bootstrap intervals.",
             facts=["Virtu 10-K and Flow Traders annual report: share of staff in technology (dated)", "large technology employers' 10-K headcounts (dated, for scale)", "firms' engineering blogs, talks and open-source releases (Jane Street, HRT, Optiver, IMC, Jump) (dated)", "Book 13-15 pointers"],
             data="data/industry/lca_ranges.csv; data/industry/tech_employers.csv (sourced list)."),
        dict(slug="21-machine-learning-and-data-engineer", title="Machine-Learning and Data Engineer",
             hook="Filings for data scientists at finance employers rose several-fold between fiscal years 2020 and 2025 in the labour-condition data, faster than any other quantitative title; the occupation code itself only entered the US classification in 2018.",
             sections=["Research-embedded machine-learning roles", "Platform machine-learning roles",
                       "The data engineer", "Growth and pay"],
             defines=["data scientist", "data engineer"],
             uses=["machine-learning engineer (B12.28)", "model owner (B12.28)", "handoff specification (B12.28)",
                   "machine-learning platform (B12.28)", "alternative data (B7.12)", "feature store (B12.24)", "embedded team (B16.21)",
                   "research engineer (ch19)"] + _U_LCA,
             tutorial=_ROLE_TUT + " Then the trend with firm.roles: yearly filing counts and median base for SOC 15-2051 and machine-learning titles at finance employers against all employers, FY2021-FY2026, with Poisson intervals on counts. End state: a growth chart and a table of ranges.",
             build="`firm.roles` (increment): the machine-learning and data role cards and a filing-trend function (counts by year with intervals, growth rate with its standard error); Python.",
             problem="The fastest-growing title -- named result: the annual growth rate of data-scientist filings at finance employers FY2021-FY2025 with its interval, and the median-base premium over software developers at the same wage level.",
             facts=["SOC 2018 introduction of 15-2051 Data Scientists (BLS)", "pointer to Book 12 ch. 28 and Book 15"],
             data="data/industry/lca_trends.csv (derived)."),
        dict(slug="22-portfolio-manager-and-pod-analyst", title="Portfolio Manager and Pod Analyst",
             hook="A portfolio manager at a platform is paid a share of the team's P&L after costs and loses the job at a set drawdown: the deal is a call option on one's own skill with a knock-out. Its value depends on the Sharpe ratio the manager actually has, which neither side knows at the start.",
             sections=["The deal: capital, payout, limits and costs", "The deal as an option with a knock-out",
                       "The analyst: from research to running capital", "Track records and moving",
                       "Portfolio managers outside the platforms"],
             defines=["portfolio manager", "pod analyst", "sub-portfolio manager"],
             uses=["pod (B8.28)", "drawdown limit (B8.28)", "payout rate (B16.3)", "pass-through fee (B16.3)",
                   "de-risking ladder (B16.8)", "track record portability (B16.25)", "emerging manager (B16.25)",
                   "formulaic payout (B16.10)", "Sharpe ratio (B4.11)", "team tenure (ch5)", "total compensation (ch13)"],
             tutorial=_ROLE_TUT + " Then the deal with firm.roles (wrapping firm.podshop and firm.payoffer): payout of a stated range of P&L, a two-step drawdown ladder and capital as parameters; for true Sharpe ratios from 0 to 2, the distribution of three-year pay and the probability of being stopped out. End state: expected pay and stop-out probability against Sharpe ratio.",
             build="`firm.roles` (increment): the portfolio-manager and analyst role cards and the PM-deal model (payout, deficits carried forward, ladder, capital changes after cuts); Python.",
             problem="The deal -- named result: the true Sharpe ratio at which the manager's expected three-year pay exceeds a stated salaried alternative, and the stop-out probability there.",
             facts=["press ranges of platform payout percentages and drawdown rules (dated; context only; else EXCLUDED)", "Form ADV counts of advisory employees at platforms (ch. 5)", "pointer to Book 16 ch. 3 and 25"],
             data="Synthetic, parameters labelled; LCA ranges for analyst titles."),
        dict(slug="23-structurer-sales-and-sales-trader", title="Structurer, Sales and Sales-Trader",
             hook="The European trade association of structured-products issuers publishes each quarter what its members sold -- billions of euros of notes a year, most of them sold to individuals through banks' networks. Behind each note is a structurer who designed it, a salesperson who placed it, and a margin both are paid from.",
             sections=["The structurer", "Institutional sales and coverage", "The sales-trader",
                       "Quantitative skills in client-facing roles", "The rules for client-facing work"],
             defines=["structurer", "institutional salesperson", "product governance"],
             uses=["structured product (B5.19)", "structured note (B5.19)", "structuring margin (B5.19)", "autocallable (B5.18)",
                   "sales-trader (B1.2)", "franchise (B1.2)", "client tiering (B9.24)", "high-touch trading (B10.20)"] + _U_LCA[:3],
             tutorial=_ROLE_TUT + " Then the note's margin with firm.roles (wrapping firm.autocall): the structuring margin of a stylised autocallable at two rate levels and two volatility levels, and the revenue per structurer implied by a sourced range of issuance volumes. End state: a margin table and the pay-range chart.",
             build="`firm.roles` (increment): the client-facing role cards and the structuring-margin analysis; Python; wraps firm.autocall.",
             problem="The margin in the note -- named result: the structuring margin of the chapter's autocallable at 1 and 4 per cent rates, and the revenue per structurer for a desk's issuance in the sourced range.",
             facts=["EUSIPA quarterly market reports: volumes by product type and country (dated)", "MiFID II art. 16(3) and 24(2) product governance; ESMA guidelines on product governance (2023)", "ESMA knowledge and competence guidelines; FINRA Series 7 and 63 (dated)", "pointer Book 5 ch. 18-19"],
             data="data/industry/eusipa_volumes.csv (derived)."),
        dict(slug="24-risk-operations-product-control-and-compliance", title="Risk, Operations, Product Control and Compliance",
             hook="European remuneration rules require the pay of staff in control functions to be mostly fixed and independent of the businesses they control; the rule shapes the career as much as the pay. The control functions employ many of the industry's quants, and they are a route into it as often as a destination.",
             sections=["Risk management", "Operations", "Product control", "Compliance",
                       "Control functions as careers and as routes to the front office"],
             defines=["control function", "product controller", "compliance officer"],
             uses=["chief risk officer (B16.12)", "risk committee (B16.12)", "four-eyes principle (B16.12)",
                   "front office (B16.13)", "middle office (B16.13)", "back office (B16.13)", "product control (B6.27)",
                   "independent price verification (B6.27)", "market abuse (B16.16)", "operational risk (B6.28)",
                   "pay band (ch9)"] + _U_LCA[:3],
             tutorial=_ROLE_TUT + " Then the ratio of control-function to front-office medians by employer type with firm.roles, against the fixed-pay emphasis the EBA guidelines require. End state: a chart of the ratio by employer type.",
             build="`firm.roles` (increment): the control-function role cards and the cross-family ratio analysis; Python.",
             problem="The price of independence -- named result: the ratio of control-function to front-office median offered base at banks and at trading firms, with bootstrap intervals.",
             facts=["EBA Guidelines on sound remuneration policies (EBA/GL/2021/04): control-function pay (dated)", "FCA SM&CR SMF16 and SMF17 (dated)", "GARP FRM and other professional certifications (factual descriptions only; dated)", "pointer Book 16 ch. 12-16"],
             data="data/industry/lca_ranges.csv."),
        dict(slug="25-leadership-roles", title="Leadership Roles",
             hook="Under the UK senior managers regime each firm must name the person responsible for each prescribed function and give them a written statement of their responsibilities; the regulator can hold that person to account for a failure in their area. At the top of a trading firm, a job title is also a legal accountability.",
             sections=["Head of desk", "Chief risk, technology and operating officers", "Partner",
                       "Chief executive and founder", "Accountability regimes"],
             defines=["head of desk", "senior manager function", "statement of responsibilities"],
             uses=["chief risk officer (B16.12)", "revenue budget (B16.6)", "risk appetite (B16.6)",
                   "limited liability partnership (B16.2)", "members' capital (B16.2)", "retention ratio (B16.2)",
                   "partnership share (ch13)", "members' remuneration (ch11)"],
             tutorial="Making partner with firm.roles (wrapping firm.partnership): a new partner's points, capital contribution, profit share and dilution when later partners are admitted, over five years under the stated retention rule; and, as data, the number of senior-manager functions a firm of each type must allocate. End state: a chart of the new partner's income and capital at risk by year.",
             build="`firm.roles` (increment): the leadership role cards, the accountability map (functions to roles) and the partner-economics analysis; Python; wraps firm.partnership.",
             problem="Making partner -- named result: the new partner's expected five-year income and capital at risk under the chapter's points and retention rules, and the break-even share of profit against staying a salaried head of desk.",
             facts=["FCA/PRA SM&CR senior manager functions and statements of responsibilities (dated)", "FINRA principal registrations (Series 24) (dated)", "EBA/ESMA joint guidelines on suitability of management body members (dated)", "UK LLP Act 2000 (pointer Book 16 ch. 2)"],
             data="Illustrative parameters (labelled)."),
    ]),
    ("part.in.life", [
        dict(slug="26-hours-rhythm-and-intensity", title="Hours, Rhythm and Intensity",
             hook="Measured in UTC, the world's futures markets leave only a few hours of the week with nothing open, around Friday night and Saturday; the crypto markets leave none. A desk's hours are set by the markets it trades before any firm decides anything, and on-call is the price of markets that never close.",
             sections=["Market hours by product, in one time zone",
                       "On-call and markets that never close",
                       "Working-time rules",
                       "What is documented and what is anecdote"],
             defines=["coverage requirement", "working-time opt-out", "exempt employee"],
             uses=["follow-the-sun trading (B3.29)", "on-call rotation (B15.28)", "runbook (B15.28)",
                   "incident commander (B15.28)", "round-the-clock trading (B16.30)", "futures contract (B1.18)"],
             tutorial="Compute a desk's coverage requirement with firm.workload (wrapping firm.marketmap and firm.calendar): the sourced sessions of the markets it trades in UTC, the weekly staffed hours, the fewest shifts that cover them with overlap, the headcount under a 48-hour week, and the on-call nights per engineer for a rota of given size. End state: a weekly UTC heatmap of open markets and the shift table.",
             build="`firm.workload`: coverage requirement from a market set, shift and headcount planning under a working-time limit, on-call load per person, and a documented-against-anecdote tag on every input; Python; wraps firm.marketmap and firm.calendar.",
             problem="Who watches Sunday night? -- named result: the smallest headcount that covers a futures-and-crypto book around the clock under a 48-hour average week with two people on each shift, and the on-call nights per engineer per month for a rota of eight.",
             facts=["CME Globex, Eurex, ICE, SGX session hours (exchange pages; dated)", "Directive 2003/88/EC arts. 6 and 22; UK Working Time Regulations 1998 regs. 4-5 (the opt-out)", "US FLSA white-collar exemption, 29 CFR 541, and the 2024 salary rule vacated in November 2024 (dated)", "bank-published policies on junior hours (firm publications or reputable press; dated; only as documented)", "Book 3 ch. 29's market registry (pointer)"],
             data="Sessions from firm.marketmap's sourced registry; synthetic rota."),
        dict(slug="27-locations", title="Locations",
             hook="The same gross package, after income tax and the median rent of a two-bedroom flat, leaves amounts that differ by a factor of two or more between the industry's cities, and the ordering changes with the size of the package and the share paid as bonus.",
             sections=["The trading cities and what is there",
                       "Pay, tax and housing",
                       "Visas and work permits",
                       "Moving: relocation, remote work and the cost of leaving"],
             defines=["specialty-occupation visa", "skilled-worker visa", "price level index", "disposable pay after housing"],
             uses=["colocation (B14.9)", "tax residence (ch15)", "average tax rate (ch15)", "expatriate tax regime (ch15)",
                   "labor condition application (ch14)", "firm profile (ch2)"],
             tutorial="Compare cities with firm.locations (wrapping firm.aftertax): official rent statistics for ten cities, after-tax pay for a range of packages, disposable pay after housing, and LCA worksite counts by US metro for quantitative titles. End state: a chart of disposable pay after housing against gross pay by city and the LCA worksite table.",
             build="`firm.locations`: city records (tax jurisdiction, rent series with source and date, price level index, visa facts by ledger id), disposable-pay comparisons and break-even packages between two cities; Python; wraps firm.aftertax.",
             problem="The same offer in five cities -- named result: disposable pay after tax and median two-bedroom rent for the chapter's package in five cities, and the gross package that equalises London and New York.",
             facts=["official rent statistics: US Census ACS or HUD fair market rents; ONS private rents; CBS; INSEE/OLAP; Singapore URA; Hong Kong RVD (dated)", "Eurostat price level indices (licence CC BY 4.0)", "USCIS H-1B cap, weighted selection and any fee changes in force in 2026 (dated)", "UK Skilled Worker and Global Talent thresholds after July 2025 (dated)", "EU Blue Card Directive 2021/1883; Netherlands highly skilled migrant thresholds 2026; Singapore Employment Pass COMPASS and salary floor 2025-26; Hong Kong Top Talent Pass; UAE Golden Visa (dated)", "firms' published office lists (dated)", "LCA worksite cities (derived)"],
             data="data/industry/rents.csv, data/industry/lca_worksites.csv (derived)."),
        dict(slug="28-career-paths-and-moves", title="Career Paths and Moves",
             hook="A trader who resigns in January may serve three months of notice, spend six more on garden leave and then sit out a non-compete, and lose on the way the deferred pay that has not yet vested: a move is often a year out of the market and a year's bonus left behind, which is why the new employer's buyout is part of the offer.",
             sections=["Entry routes: internships, graduate programmes, lateral hires, doctorates",
                       "Bank to buy side and back",
                       "Non-competes and garden leave in practice",
                       "Going independent and starting a firm",
                       "Exits"],
             defines=["internship", "return offer", "graduate programme", "lateral hire", "notice period"],
             uses=_U_COV + ["deferral buyout (B16.10)", "deferred compensation (B16.10)", "emerging manager (B16.25)",
                   "seed investor (B16.25)", "track record portability (B16.25)", "spin-out (ch3)", "forfeiture (ch13)",
                   "good-leaver provision (ch13)", "sign-on bonus (ch13)"],
             tutorial="Value a move with firm.careerpath (wrapping firm.payoffer and firm.gardenleave): unvested deferrals forfeited, notice, garden leave and non-compete months, the probability and size of a buyout, and the raise needed to make the move worth it; then a career chain whose transition probabilities are labelled assumptions, with the expected pay path and its spread; and the spin-out edges of chapter 3's lineage graph. End state: the break-even raise surface and the pay-path fan.",
             build="`firm.careerpath`: move valuation (forfeiture, time out of market, buyout), a Markov career chain with labelled transition assumptions and pay by state, and path statistics; Python; wraps firm.payoffer, firm.gardenleave and firm.lineage.",
             problem="Move now or wait for the vest? -- named result: the raise that makes a move neutral as a function of the month of leaving and the buyout probability, and its value on the day before the largest tranche vests.",
             facts=["Book 16 ch. 11 pointers for the law", "FTC non-compete rule set aside (Ryan LLC v. FTC, N.D. Tex., 20 August 2024) and the FTC's withdrawal of its appeal (2025) (dated)", "UK government statements on limiting non-competes (2023 onward) and their status (dated)", "California Business and Professions Code s. 16600-16600.5; Illinois Freedom to Work Act thresholds; New York proposals (dated)", "UK statutory minimum notice, Employment Rights Act 1996 s. 86", "firms' published graduate and internship programmes (dated)"],
             data="Illustrative parameters (labelled)."),
        dict(slug="29-education-pipelines", title="Education Pipelines",
             hook="US universities award each year a few thousand master's degrees in financial mathematics and financial engineering, counted by programme code in the federal completions survey; the number has grown with the industry's hiring, and it is small beside the statisticians, mathematicians and computer scientists the same firms also hire.",
             sections=["Degrees that feed each kind of firm",
                       "The specialised master's programmes: size, cost and placement",
                       "Doctorates and the academic route",
                       "Competitions and what they signal",
                       "Learning outside a programme"],
             defines=["placement report", "Classification of Instructional Programs"],
             uses=["quantitative researcher (ch17)", "return offer (ch28)", "graduate programme (ch28)",
                   "labor condition application (ch14)", "survivorship bias (B7.3)"],
             tutorial="Count the pipeline with firm.edupipe: IPEDS completions by programme code and award level, 2010-2024 (public domain), for financial mathematics and engineering, statistics, mathematics, computer science and physics, beside HESA counts for the United Kingdom where openly licensed; and a sourced table of programmes' own placement reports, read for their response rates. End state: a chart of completions by field (log axis) and the placement-report table with its caveats.",
             build="`firm.edupipe`: IPEDS and HESA readers, degree-count series by code and level, and a placement-report record (cohort, response rate, reported median, what the report excludes); Python.",
             problem="How many quants does the world train? -- named result: annual US master's completions in the financial programme codes, and their ratio to the yearly count of LCA filings in quantitative titles at finance employers.",
             facts=["NCES IPEDS completions survey and CIP 2020 codes 27.0305, 27.0501, 27.0101, 11.0701, 30.7104 (dated)", "HESA open data licence and subject counts (dated)", "published placement reports of several financial-engineering master's programmes (dated; response rates)", "International Mathematical Olympiad, ICPC and Putnam formats (official sites)"],
             data="data/industry/ipeds_completions.csv, data/industry/placement_reports.csv (derived)."),
        dict(slug="30-choosing", title="Choosing",
             hook="Four offers -- a bank quant role, a market maker's trading role, an analyst seat at a platform and a technology firm's engineering job -- differ in expected pay, in its spread, in hours, in city and in what the next five years teach. No single number ranks them; a person's weights do, and the useful question is how far those weights can move before the choice changes.",
             sections=["The attributes that differ across firm types",
                       "Pay risk as a certainty equivalent",
                       "Temperament, skills and the work itself",
                       "A multi-attribute framework and its sensitivity",
                       "Revisiting the decision"],
             defines=["multi-attribute value model", "swing weighting", "dominated alternative", "rank acceptability"],
             uses=["certainty equivalent (B4.9)", "relative risk aversion (B4.9)", "utility function (B4.9)", "Kelly criterion (B2.29)",
                   "decision journal (B16.26)", "outcome bias (B16.26)", "pre-mortem (B16.26)", "total compensation (ch13)",
                   "disposable pay after housing (ch27)", "coverage requirement (ch26)"],
             tutorial="Compare four offers with firm.careerdec: attribute values from the earlier chapters' tools (firm.payoffer certainty equivalents, firm.locations disposable pay, firm.workload hours, firm.careerpath five-year value), swing weights, dominance screening, and rank acceptability under weights sampled uniformly on the simplex (stochastic multicriteria acceptability analysis). End state: a rank-acceptability chart and the weight regions where each offer wins.",
             build="`firm.careerdec`: attribute scaling, a multi-attribute value model, swing weighting, dominance screening, rank-acceptability indices by weight sampling, and a report of the weights that flip the choice; Python; wraps firm.payoffer, firm.aftertax, firm.locations, firm.workload and firm.careerpath.",
             problem="Four offers -- named result: each offer's first-rank acceptability index under uniform weights, and the smallest change in the weight on pay risk that changes the preferred offer.",
             facts=["Keeney and Raiffa (1976), Decisions with Multiple Objectives", "von Winterfeldt and Edwards (1986) on swing weights", "Lahdelma, Hokkanen and Salminen (1998), SMAA, European Journal of Operational Research", "pointer Book 4 ch. 9 and Book 16 ch. 26"],
             data="Outputs of the earlier chapters' tools; labelled illustrative attribute inputs."),
    ]),
]
