"""Book 9 (Strategies II: Volatility, Relative Value, Macro and the Bank Desks) chapter briefs: data for
tools/make_briefs.py --book 9.

`uses` lists terms defined elsewhere that the chapter relies on (not redefined); owners in parentheses:
(B5.14) = One Quant Book 5, chapter 14, checked against the harvested \\index{} entries of Books 1-8 on
2026-09-25 (2,019 terms); (ch3) = an earlier chapter of this book.

Ownership: Books 1-8 keep their terms. Book 5 owns the options and volatility vocabulary (variance risk
premium, variance swap, dispersion trade, implied correlation, gamma scalping, event variance, convertible
arbitrage, VIX option); Book 1 owns volatility index, VIX future, dealer gamma, zero-day option, delta hedging;
Book 6 owns capital-structure arbitrage and the Merton model; Book 2 owns the rates, FX and credit mechanics
(basis trade, cheapest-to-deliver, implied repo rate, swap spread, asset-swap spread, new-issue concession,
on-the-run, cross-currency basis, benchmark fix, month-end rebalancing, portfolio trade, axe); Book 3 owns the
commodity spreads (crack, spark, crush), storage and power market terms and wash trading, sandwich attack and
front-running in crypto; Book 8 owns carry crash, carry strategy and the equity and futures strategies. This
book owns the named volatility, relative-value, macro and bank-desk strategies and the manipulation patterns
and their detectors.

Every chapter except 17 carries strategy files (section 6.3 of WRITING_A_QUANT_BOOK.md), the chapter's count
from the outline's bracketed number. Chapter 29 follows section 6.3's rule for manipulation: mechanism, why it
is illegal, the enforcement case, the surveillance detector; nothing operational beyond the public record.

Running project (code/firm/, all new and unique; checked against the 234 existing):
  synthvol, shortvol (ch1)  dispersion (ch2)  volrv (ch3)  eventvol (ch4)  vixetp (ch5)  gammaflow (ch6)
  tailhedge (ch7)  convarb (ch8)  capstruct (ch9)  bondrv (ch10)  basistrade (ch11)  swapspread (ch12)
  supplytrade (ch13)  fxcarry (ch14)  fxflows (ch15)  sysmacro (ch16)  macrobook (ch17)  creditrv (ch18)
  syscredit (ch19)  mbsrv (ch20)  commspread (ch21)  physopt (ch22)  powergas (ch23)  flowmm (ch24)
  crbook (ch25)  deltaone (ch26)  qis (ch27)  sphedge (ch28)  surveil (ch29)
"""
SLUG = "strategies-2"
PFX = "s2"
HEAD = "One Quant Book 9 — Strategies II: Volatility, Relative Value, Macro and the Bank Desks"

_U_BT = ["backtest (B7.16)", "information coefficient (B7.6)", "transaction cost analysis (B7.23)",
         "capacity curve (B7.28)"]
_U_VOL = ["implied volatility (B1.25)", "realised volatility (B1.25)", "delta hedging (B1.26)", "vega (B5.4)"]

PARTS = [
    ("part.s2.vol", [
        dict(slug="01-harvesting-the-variance-risk-premium", title="Harvesting the Variance Risk Premium",
             hook="Selling index volatility has paid on most days for decades, because implied volatility usually exceeds the volatility that follows; its losses arrive together, in days, and have closed funds.",
             sections=["The premium and why it exists", "Implementations: options, variance swaps, overwriting", "Delta-hedged option returns", "Blow-ups and how to size for them"],
             defines=["short-volatility strategy", "delta-hedged option return", "option overwriting"],
             uses=["variance risk premium (B5.14)", "variance swap (B5.14)", "straddle (B5.4)", "volatility index (B1.25)"] + _U_VOL + _U_BT,
             strategies=["short index variance", "delta-hedged short straddle", "covered-call overwriting", "put writing", "volatility-targeted short volatility"],
             tutorial="Build firm.synthvol, a synthetic index with stochastic volatility, jumps and an implied-volatility surface carrying a planted variance risk premium; run short-volatility implementations and size them against the planted crash.",
             build="`firm.synthvol` (synthetic index and single-stock option market: stochastic variance with jumps, implied surfaces with a planted premium, deterministic) and `firm.shortvol` (short-volatility implementations with delta hedging and sizing); Python.",
             problem="Picking up nickels — named result: the short-variance book's Sharpe ratio before its worst month and its loss in that month, by leverage.",
             facts=["Carr and Wu 2009 variance risk premiums (RFS)", "Bakshi and Kapadia 2003 delta-hedged gains and the negative market volatility risk premium (RFS)", "Cboe S&P 500 BuyWrite and PutWrite indices (dated)", "February 2018 XIV termination (as B1/B5 where sourced)"]),
        dict(slug="02-dispersion-and-correlation", title="Dispersion and Correlation",
             hook="An index option is priced as if its constituents move together more than they do: selling index volatility and buying the members' collects the gap, until a crash makes everything move as one.",
             sections=["Index volatility from member volatilities", "The correlation risk premium", "Dispersion trades and their weights", "When correlation goes to one"],
             defines=["correlation risk premium", "realised correlation", "dispersion weighting"],
             uses=["dispersion trade (B5.17)", "implied correlation (B5.17)", "correlation swap (B5.17)"] + _U_VOL + _U_BT,
             strategies=["vega-weighted dispersion", "theta-weighted dispersion", "correlation swap short", "sector dispersion"],
             tutorial="On firm.synthvol's index and thirty members with a planted correlation risk premium, measure implied against realised correlation and run dispersion books with different weightings through the planted crash.",
             build="`firm.dispersion`: implied and realised correlation, dispersion trade construction and weighting, P&L decomposition into correlation and volatility parts; Python.",
             problem="When everything moves together — named result: the dispersion book's return from the correlation premium and its loss when correlation jumps.",
             facts=["Driessen, Maenhout, Vilkov 2009 the price of correlation risk (JF)", "Cboe implied correlation index methodology (dated)"]),
        dict(slug="03-skew-and-term-structure-relative-value", title="Skew and Term-Structure Relative Value",
             hook="Two options on the same index, one a month out and one three months out, can disagree about the same future; relative-value traders bet on the disagreement rather than on the level.",
             sections=["Trading the smile", "Trading the term structure", "Across related underlyings", "Risk: what a relative-value vol book is really short"],
             defines=["skew trade", "term-structure trade", "cross-underlying volatility spread"],
             uses=["volatility skew (B1.25)", "term structure of volatility (B1.25)", "volatility surface (B5.7)", "risk reversal (B2.19)", "sticky strike (B5.7)", "sticky delta (B5.7)"] + _U_VOL + _U_BT,
             strategies=["skew flattener", "calendar volatility spread", "index-versus-ETF volatility spread", "cross-market volatility spread"],
             tutorial="Fit firm.synthvol surfaces each day, build skew and calendar trades hedged in vega and delta, and measure how much of their P&L comes from the planted mean reversion of skew and slope and how much from the level.",
             build="`firm.volrv`: surface-feature extraction (level, skew, curvature, slope), vega-neutral relative-value trades and their P&L attribution; Python.",
             problem="Same future, two prices — named result: the skew and calendar trades' Sharpe ratios and the share of their P&L that is really level exposure.",
             facts=["Bakshi, Kapadia, Madan 2003 stock return characteristics, skew laws (RFS)", "Kelly, Pastor, Veronesi 2016 the price of political uncertainty (JF) or equivalent term-structure evidence"]),
        dict(slug="04-gamma-scalping-and-event-volatility", title="Gamma Scalping and Event Volatility",
             hook="Before earnings a stock's options price a move; the stock then moves more or less. Owning the straddle and hedging it pays the difference between the move priced and the move delivered, less the hedging's cost.",
             sections=["Gamma scalping as a bet on realised against implied", "Implied moves around events", "The volatility crush after events", "Hedging frequency and path"],
             defines=["implied move", "event straddle", "volatility crush"],
             uses=["gamma scalping (B5.25)", "event variance (B5.8)", "cash gamma (B5.4)", "theta (B5.4)"] + _U_VOL + _U_BT,
             strategies=["earnings event straddle", "post-event volatility sale", "gamma scalping with hedge bands", "macro-event variance"],
             tutorial="Plant earnings jumps in firm.synthvol's single stocks with an implied event variance that mis-prices them by a controlled amount; trade event straddles and delta-hedged gamma at several hedging frequencies.",
             build="`firm.eventvol`: event-variance extraction from term structures, implied moves, event straddles and discrete delta-hedging P&L with bands; Python.",
             problem="The move priced and the move delivered — named result: the event straddle's return per event against the implied move's error, and the hedging frequency that maximises it after costs.",
             facts=["Dubinsky, Johannes, Kaeck, Seeger 2019 option pricing of earnings announcement risks (RFS)", "Gao, Xing, Zhang 2018 anticipating uncertainty: straddles around earnings announcements (JFQA)"]),
        dict(slug="05-the-volatility-index-complex", title="The Volatility-Index Complex",
             hook="An exchange-traded product that held short-dated VIX futures lost most of its value in years when the index itself ended where it started: the futures curve's roll-down paid its short sellers.",
             sections=["VIX futures and their curve", "Exchange-traded volatility products and their rebalancing", "Futures against options", "February 2018"],
             defines=["exchange-traded volatility product", "ETP rebalancing flow", "VIX term-structure slope"],
             uses=["VIX future (B1.25)", "VIX option (B5.14)", "volatility roll-down (B5.25)", "exchange-traded product (B3.19)", "leveraged ETF (B1.14)"] + _U_BT,
             strategies=["short VIX futures roll-down", "ETP rebalancing front-running", "VIX futures against SPX options", "long volatility on inverted curve"],
             tutorial="Build a VIX-like index and its futures curve on firm.synthvol, simulate long, inverse and leveraged ETPs with daily rebalancing, and measure roll-down returns and the ETPs' rebalancing flow in a volatility spike.",
             build="`firm.vixetp`: volatility-index construction from a surface, a futures curve, ETP daily rebalancing and flow, and roll-down trades; Python.",
             problem="Roll-down — named result: the short-futures book's roll-down return and the inverse ETP's loss in the planted spike.",
             facts=["Cboe VIX methodology white paper (dated)", "Whaley 2013 trading volatility: at what cost? (JPM)", "Augustin, Cheng, Van den Bergen 2021 volmageddon (Management Science)"]),
        dict(slug="06-zero-day-options-and-dealer-gamma-flows", title="Zero-Day Options and Dealer-Gamma Flows",
             hook="Options that expire the day they are bought now trade in volumes comparable to the rest of the S&P 500 option market; the dealers who sell them hedge within the day, and their hedging can pin or push the index.",
             sections=["Zero-day options and who trades them", "Estimating dealer gamma", "Pinning and pushing", "Trading the hedging flow"],
             defines=["gamma exposure estimate", "gamma flip level", "pinning"],
             uses=["zero-day option (B1.26)", "dealer gamma (B1.26)", "end-of-day hedging flow (B8.13)", "pin risk (B1.23)"] + _U_VOL + _U_BT,
             strategies=["long gamma below the flip level", "pin trade near large strikes", "intraday dealer-hedging momentum"],
             tutorial="Simulate an intraday index with dealers short or long gamma from zero-day options, estimate their exposure from open interest by strike with noise in the assumed dealer side, and trade the implied hedging flow.",
             build="`firm.gammaflow`: dealer gamma estimation from open interest by strike under side assumptions, flip-level and pin statistics, and an intraday hedging-feedback simulator; Python.",
             problem="Who is short gamma — named result: the error of the gamma estimate when the dealers' side is guessed, and the hedging-flow trade's return by regime.",
             facts=["Cboe 0DTE volume statistics (dated)", "Baltussen, Da, Lammers, Martens 2021 hedging demand and market intraday momentum (JFE)", "Ni, Pearson, Poteshman, White 2021 does option trading have a pervasive impact on underlying stock prices? (RFS)"]),
        dict(slug="07-tail-hedging-and-long-volatility", title="Tail Hedging and Long Volatility",
             hook="A tail hedge that bleeds a little every month is the most disliked position in a portfolio for years, until the month it pays for all of them; whether it was worth its cost depends on what it lets the rest of the portfolio do.",
             sections=["The cost of convexity", "Put programmes and their monetisation", "Alternatives: trend, long vol, variance", "Judging a hedge by the portfolio"],
             defines=["tail hedge", "hedge monetisation", "hedge bleed"],
             uses=["crisis alpha (B8.19)", "variance risk premium (B5.14)", "collar (B3.12)"] + _U_VOL + _U_BT,
             strategies=["rolling out-of-the-money put programme", "put spread collar", "long variance with monetisation"],
             tutorial="On firm.synthvol run put programmes with different strikes, tenors and monetisation rules, combine them with an equity portfolio, and compare the portfolio's growth rate and drawdown with and without the hedge and with a trend overlay.",
             build="`firm.tailhedge`: rolling option programmes with monetisation rules, their cost and payoff, and portfolio-level evaluation (growth, drawdown, rebalancing benefit); Python.",
             problem="Paying for the month that pays — named result: the hedge's annual bleed and the portfolio growth rate with and without it.",
             facts=["Israelov 2019 pathetic protection: the elusive benefits of protective puts (J. Alternative Investments)", "Harvey et al. 2019 the best of strategies for the worst of times (JPM)"]),
        dict(slug="08-convertible-arbitrage", title="Convertible Arbitrage",
             hook="Buy the convertible, short the stock, and the trade is long volatility and credit, short the borrow; in 2005 and 2008 funds found out how much of each they owned at once.",
             sections=["What a convertible holder owns", "The hedged trade and its Greeks", "Credit and borrow", "2005 and 2008"],
             defines=["busted convertible", "convertible delta hedge", "credit-hedged convertible"],
             uses=["convertible arbitrage (B5.21)", "convertible bond (B5.21)", "borrow fee (B1.6)", "credit default swap (B2.23)"] + _U_VOL + _U_BT,
             strategies=["delta-hedged convertible", "credit-hedged convertible", "busted convertible credit trade", "new-issue convertible"],
             tutorial="Price convertibles on firm.synthvol stocks with a credit spread tied to the stock, hedge them in delta and credit, and run the book through a planted episode of redemptions, widening credit and recalled borrow.",
             build="`firm.convarb`: convertible book on firm.convertible's pricer with delta and credit hedges, borrow costs and a forced-selling scenario; Python.",
             problem="Long everything at once — named result: the hedged book's carry and its loss in the planted forced-selling episode, and the share from credit.",
             facts=["Mitchell, Pedersen, Pulvino 2007 slow moving capital (AER P&P)", "Agarwal, Fung, Loon, Naik 2011 risk and return in convertible arbitrage (J. Empirical Finance)"]),
        dict(slug="09-capital-structure-arbitrage", title="Capital-Structure Arbitrage",
             hook="The same company's shares and its credit default swaps price its default risk; when they disagree, a trader buys one and sells the other and waits for the disagreement to close, or for the model to be wrong.",
             sections=["From equity to credit spread", "The trade and its hedge ratio", "Evidence and losses", "Model risk"],
             defines=["equity-implied spread", "cross-asset hedge ratio"],
             uses=["capital-structure arbitrage (B6.14)", "Merton model (B6.14)", "credit spread (B2.21)", "credit default swap (B2.23)"] + _U_BT,
             strategies=["equity-implied spread convergence", "long CDS short equity on weak equity", "debt-equity dislocation after events"],
             tutorial="Simulate firms whose equity and CDS both reflect a structural default model with planted noise and occasional regime changes; compute equity-implied spreads, trade convergence, and measure losses when the model's parameters shift.",
             build="`firm.capstruct`: equity-implied spreads from a structural model, hedge ratios, convergence trades and a parameter-shift stress; Python.",
             problem="Same default, two prices — named result: the convergence trade's Sharpe ratio and the losses when leverage shifts.",
             facts=["Yu 2006 how profitable is capital structure arbitrage? (FAJ)", "Duarte, Longstaff, Yu 2007 risk and return in fixed-income arbitrage (RFS)"]),
    ]),
    ("part.s2.ratesfx", [
        dict(slug="10-government-bond-relative-value", title="Government-Bond Relative Value",
             hook="Fit a smooth curve to a government's bonds and some sit above it and some below; a relative-value book buys the cheap and sells the rich, hedged, and waits a few weeks for the curve to take them back.",
             sections=["Fitted curves and their residuals", "Butterflies and curve trades", "Rich-cheap signals and their decay", "Leverage and funding"],
             defines=["fitted-curve residual", "rich-cheap signal", "duration-neutral butterfly"],
             uses=["DV01 (B2.3)", "zero-coupon rate (B2.3)", "repo rate (B2.5)", "on-the-run (B2.4)"] + _U_BT,
             strategies=["fitted-curve rich-cheap", "duration-neutral butterfly", "curve steepener or flattener", "off-the-run versus on-the-run", "principal-component-hedged residual"],
             tutorial="Simulate a government curve with three factors and bond-specific pricing errors that revert, fit a smooth curve each day, and trade residuals hedged in duration and in principal components.",
             build="`firm.bondrv`: synthetic government bond market, daily curve fitting (Nelson-Siegel-Svensson or splines), residuals, PCA hedges and a rich-cheap book; Python.",
             problem="Above and below the curve — named result: the rich-cheap book's Sharpe ratio by hedge and the half-life of the residuals.",
             facts=["Gurkaynak, Sack, Wright 2007 the U.S. Treasury yield curve: 1961 to the present (J. Monetary Economics)", "Duarte, Longstaff, Yu 2007 (as ch9)", "Fed H.15 or FRED yields (dated)"]),
        dict(slug="11-the-bond-futures-basis-trade", title="The Bond-Futures Basis Trade",
             hook="Buy a Treasury, sell the future on it, finance the bond in repo at fifty times leverage, and earn a few basis points; in March 2020 the few basis points became losses large enough for the central bank to step in.",
             sections=["Mechanics: cash, future, repo", "Leverage and who does it", "March 2020", "Measuring the crowding"],
             defines=["basis-trade leverage", "repo rollover risk"],
             uses=["basis trade (B2.6)", "cheapest-to-deliver (B2.6)", "implied repo rate (B2.6)", "gross basis (B2.6)", "net basis (B2.6)", "haircut (B1.6)"] + _U_BT,
             strategies=["cash-futures basis long", "delivery option trade", "basis-trade crowding signal"],
             tutorial="Price a bond future's delivery basket on firm.ctd, simulate the basis and repo, run a leveraged basis book, and stress it with a repo-haircut increase and a futures margin call.",
             build="`firm.basistrade`: basis trade accounting (implied repo, carry, margin and haircut funding) and a deleveraging stress; Python.",
             problem="Fifty times — named result: the trade's return on capital by leverage and the loss in the planted funding stress.",
             facts=["Barth and Kahn 2021 hedge funds and the Treasury cash-futures disconnect (OFR)", "Federal Reserve March 2020 Treasury market actions (dated)", "CFTC traders in financial futures (dated)"]),
        dict(slug="12-swap-spread-and-asset-swap-trades", title="Swap-Spread and Asset-Swap Trades",
             hook="For years the swap rate sat below the Treasury yield of the same maturity, which a textbook says cannot last; it lasted because the trade that would close it uses balance sheet that banks no longer had.",
             sections=["Swap spreads and asset swaps", "Negative swap spreads", "Balance sheet as a cost", "Trades and their carry"],
             defines=["swap-spread trade", "balance-sheet cost"],
             uses=["swap spread (B2.9)", "asset-swap spread (B2.21)", "repo rate (B2.5)", "DV01 (B2.3)"] + _U_BT,
             strategies=["long swap spread", "asset-swap carry", "swap-spread curve trade", "year-end balance-sheet trade"],
             tutorial="Simulate Treasury, repo and swap curves with a planted balance-sheet cost that moves swap spreads, run swap-spread trades with their carry and funding, and measure the balance sheet they consume.",
             build="`firm.swapspread`: swap-spread and asset-swap trade accounting, carry, balance-sheet usage and a leverage-ratio cost; Python.",
             problem="Below the Treasury — named result: the swap-spread trade's return with and without a balance-sheet charge.",
             facts=["Du, Tepper, Verdelhan 2018 deviations from covered interest rate parity (JF) (balance-sheet argument)", "Jermann 2020 negative swap spreads and limited arbitrage (RFS)", "FRED swap and Treasury rates (dated)"]),
        dict(slug="13-supply-trades", title="Supply Trades",
             hook="Treasuries cheapen in the days before a large auction and recover after; dealers must absorb the supply, and they are paid for it.",
             sections=["Auction concessions", "New-issue and on-the-run premia", "Corporate supply", "Trading around the calendar"],
             defines=["auction concession", "on-the-run premium", "supply trade"],
             uses=["new-issue concession (B2.21)", "on-the-run (B2.4)", "when-issued trading (B2.4)", "auction tail (B2.4)"] + _U_BT,
             strategies=["pre-auction short, post-auction long", "on-the-run roll", "corporate new-issue concession", "month-end index extension"],
             tutorial="Simulate an auction calendar with planted concessions proportional to size and dealer inventory, and trade the pre- and post-auction pattern and the on-the-run roll.",
             build="`firm.supplytrade`: auction calendar, concession model, supply trades around auctions and on-the-run rolls; Python.",
             problem="Paid to absorb — named result: the auction trade's return per auction and its dependence on auction size.",
             facts=["Lou, Yan, Zhang 2013 anticipated and repeated shocks in liquid markets (RFS)", "Fleming and Rosenberg 2008 how do Treasury dealers manage their positions? (FRBNY staff report)", "TreasuryDirect auction results (dated)"]),
        dict(slug="14-cross-currency-basis-and-fx-carry", title="Cross-Currency Basis and FX Carry",
             hook="Since 2008 borrowing dollars through the FX swap market has cost more than covered interest parity says it should; the gap is small, persistent and largest at quarter-ends, and it is where balance sheets are priced.",
             sections=["FX carry: construction and crash risk", "The cross-currency basis", "Quarter-ends", "Funding-driven trades"],
             defines=["FX carry basket", "basis funding trade", "crash-hedged carry"],
             uses=["cross-currency basis (B2.16)", "covered interest parity (B2.16)", "forward points (B2.16)", "carry crash (B8.20)", "carry strategy (B8.20)"] + _U_BT,
             strategies=["G10 carry basket", "crash-hedged carry with options", "quarter-end basis trade", "basis funding arbitrage", "carry with momentum filter"],
             tutorial="Build G10 carry baskets on firm.synthfut currencies with planted crash risk, hedge the crashes with synthetic options, and simulate a cross-currency basis with quarter-end spikes to trade.",
             build="`firm.fxcarry`: carry baskets, option-hedged carry, basis funding trades and quarter-end effects; Python.",
             problem="Priced at the quarter-end — named result: the carry basket's Sharpe ratio with and without crash hedges, and the basis trade's quarter-end return.",
             facts=["Du, Tepper, Verdelhan 2018 (JF)", "Jurek 2014 crash-neutral currency carry trades (JFE)", "BIS on the cross-currency basis (dated)"]),
        dict(slug="15-fx-flow-strategies", title="FX Flow Strategies",
             hook="At four in the afternoon London time the benchmark rates for currencies are fixed on the trades of a few minutes; funds that must trade at the fix create flows that others can anticipate.",
             sections=["The fix and its flows", "Month-end rebalancing", "Central-bank behaviour", "Trading predictable flows"],
             defines=["fix flow", "rebalancing-flow estimate", "central-bank reaction trade"],
             uses=["benchmark fix (B2.17)", "month-end rebalancing (B2.17)", "fixing window (B2.17)"] + _U_BT,
             strategies=["month-end hedge-rebalancing flow", "fix-window liquidity provision", "central-bank intervention fade", "equity-performance FX hedge flow"],
             tutorial="Estimate month-end FX hedge-rebalancing flows from synthetic equity performance by country and trade ahead of them; simulate fix-window price pressure.",
             build="`firm.fxflows`: month-end flow estimator from asset performance and hedge ratios, fix-window pressure model and flow trades; Python.",
             problem="Four o'clock — named result: the month-end flow trade's return against the estimated flow size.",
             facts=["Melvin and Prins 2015 equity hedging and exchange rates at the London 4 p.m. fix (J. Financial Markets)", "Evans 2018 forex trading and the WMR fix (JBF)", "FCA 2014 FX benchmark enforcement (dated)"]),
        dict(slug="16-systematic-macro", title="Systematic Macro",
             hook="Value, momentum and carry, measured country by country in bonds, currencies and equity indices, make a macro portfolio that no economist designed and that has earned more than most who did.",
             sections=["Signals across countries and assets", "Macro-data signals", "Combining signals", "What the record shows"],
             defines=["macro value signal", "macro momentum", "economic-surprise signal"],
             uses=["time-series momentum (B8.19)", "carry strategy (B8.20)", "diversified carry (B8.20)"] + _U_BT,
             strategies=["cross-country value", "macro momentum", "carry across asset classes", "economic-surprise tilt", "combined macro factor portfolio"],
             tutorial="On firm.synthfut's equity, bond and currency markets, add planted value (mean reversion to fair value) and macro-data effects, build value, momentum, carry and macro-surprise signals and combine them.",
             build="`firm.sysmacro`: cross-asset value, momentum, carry and macro-surprise signals and their combination with risk budgets; Python.",
             problem="Designed by no one — named result: each signal's Sharpe ratio and the combination's, with the correlations that make it work.",
             facts=["Asness, Moskowitz, Pedersen 2013 value and momentum everywhere (JF)", "Brooks 2017 a half century of macro momentum (AQR) or peer-reviewed equivalent"]),
        dict(slug="17-discretionary-macro", title="Discretionary Macro",
             hook="A macro manager with a view that rates will fall has a dozen ways to express it; the view is the easy part, and the instrument, the size and the stop decide whether being right pays.",
             sections=["From view to trade", "Instrument choice and convexity", "Sizing and stops", "Keeping score"],
             defines=["trade expression", "convexity budget", "stop discipline"],
             uses=["risk reversal (B2.19)", "straddle (B5.4)", "drawdown limit (B8.28)"],
             strategies=[],
             tutorial="Simulate a manager with a noisy view on a synthetic rate path and compare expressions (futures, options, spreads) and stop rules on the view's expected payoff and the probability of being stopped out before being right.",
             build="`firm.macrobook`: view-to-trade mapping, expression payoffs under a view distribution, stop rules and their cost; Python.",
             problem="Right and still losing — named result: the expected payoff of each expression of the same view and the share of correct views stopped out early.",
             facts=["no firm named without a public source; public descriptions of macro process (dated) if any"]),
    ]),
    ("part.s2.credit", [
        dict(slug="18-credit-relative-value", title="Credit Relative Value",
             hook="A company's bond and its credit default swap insure the same default; the gap between them, the basis, went deeply negative in 2008 when the trade that should close it needed funding nobody had.",
             sections=["The bond-CDS basis", "Index against constituents", "Credit curve trades", "Funding and the negative basis"],
             defines=["negative basis trade", "credit index arbitrage", "credit curve trade"],
             uses=["credit default swap (B2.23)", "credit spread (B2.21)", "z-spread (B2.21)", "credit event (B2.23)"] + _U_BT,
             strategies=["negative basis trade", "index versus single-name arbitrage", "credit curve flattener", "senior versus subordinated", "cross-currency credit"],
             tutorial="Simulate bonds and CDS on synthetic issuers with a funding cost that drives the basis, trade the basis, index-constituent gaps and curve shapes, and stress funding.",
             build="`firm.creditrv`: bond-CDS basis, index intrinsic value and skew, curve trades and funding stress; Python.",
             problem="Same default, two prices again — named result: the negative-basis trade's carry and its mark-to-market loss when funding costs jump.",
             facts=["Bai and Collin-Dufresne 2019 the CDS-bond basis (Financial Management)", "Mitchell and Pulvino 2012 arbitrage crashes and the speed of capital (JFE)"]),
        dict(slug="19-systematic-credit-and-bond-etf-arbitrage", title="Systematic Credit and Bond-ETF Arbitrage",
             hook="A bond ETF trades every second while most of its bonds do not trade for days; when they disagree, authorised participants create or redeem shares, and the discount says how illiquid the bonds really are.",
             sections=["Factors in credit", "Bond ETFs and create-redeem", "Portfolio trades", "Discounts in stress"],
             defines=["credit factor", "ETF create-redeem arbitrage", "ETF discount"],
             uses=["creation basket (B1.14)", "creation unit (B1.14)", "authorised participant (B1.14)", "portfolio trade (B2.22)"] + _U_BT,
             strategies=["credit value and momentum", "low-risk credit", "ETF premium-discount arbitrage", "portfolio-trade liquidity provision"],
             tutorial="Simulate a bond universe with factor structure and stale prices, a bond ETF with authorised participants, and a stress in which the ETF's discount widens; trade credit factors and the ETF arbitrage.",
             build="`firm.syscredit`: credit factor signals on a synthetic bond panel, ETF net asset value with stale prices, create-redeem arbitrage and portfolio-trade pricing; Python.",
             problem="Which price is right — named result: the credit factors' Sharpe ratios and the ETF arbitrage's return in the planted stress.",
             facts=["Houweling and van Zundert 2017 factor investing in the corporate bond market (FAJ)", "Haddad, Moreira, Muir 2021 when selling becomes viral (RFS)", "Pan and Zeng 2019 or Koont, Ma, Pastor, Zeng on bond ETF arbitrage"]),
        dict(slug="20-mortgage-and-structured-credit-strategies", title="Mortgage and Structured-Credit Strategies",
             hook="A mortgage holder can repay whenever rates fall, so a mortgage bond is short an option the borrower may not use well; traders who model borrowers better than the market are paid for it.",
             sections=["Prepayment views", "Interest-only and principal-only trades", "Tranche relative value"],
             defines=["prepayment trade", "tranche relative value"],
             uses=["prepayment (B2.12)", "conditional prepayment rate (B2.12)", "prepayment model (B6.12)", "interest-only strip (B6.12)", "tranche (B2.24)", "option-adjusted spread (B2.21)"] + _U_BT,
             strategies=["IO long on slow prepayment view", "OAS relative value across coupons", "mezzanine tranche relative value"],
             tutorial="Simulate a mortgage pool with a planted borrower behaviour that differs from the market's prepayment model, value IO, PO and pass-throughs under both, and trade the difference.",
             build="`firm.mbsrv`: prepayment-view trades on firm.prepay and firm.mbsoas, IO/PO valuation and tranche relative value; Python.",
             problem="Better than the market's model — named result: the IO trade's return when the view is right and when the burnout assumption is wrong.",
             facts=["Gabaix, Krishnamurthy, Vigneron 2007 limits of arbitrage: theory and evidence from the mortgage-backed securities market (JF)", "Boyarchenko, Fuster, Lucca 2019 understanding mortgage spreads (RFS)"]),
    ]),
    ("part.s2.commodities", [
        dict(slug="21-commodity-spreads", title="Commodity Spreads",
             hook="A refinery earns the difference between crude and the products made from it; traders who hold that spread rather than oil itself are betting on refining margins, storage and seasons, not on the price of oil.",
             sections=["Calendar spreads again", "Quality and location", "Processing spreads: crack, spark, crush", "Risk in spread books"],
             defines=["processing-spread trade", "quality spread", "location spread"],
             uses=["crack spread (B3.3)", "3-2-1 crack spread (B3.3)", "spark spread (B3.5)", "crush spread (B3.9)", "locational basis (B3.4)", "calendar spread (B1.19)"] + _U_BT,
             strategies=["crack-spread mean reversion", "spark spread with heat-rate view", "soybean crush trade", "Brent-WTI location spread", "sweet-sour quality spread", "seasonal gasoline crack"],
             tutorial="Measure crack and location spreads from EIA product and crude data where available, simulate processing margins with planted seasonal and mean-reverting components, and trade them hedged.",
             build="`firm.commspread`: spread construction by ratio, mean-reversion and seasonal signals on spreads, hedged spread books; Python.",
             problem="Not the price of oil — named result: the crack-spread trade's Sharpe ratio and its correlation with crude.",
             facts=["EIA product and crude prices (as B3)", "Girma and Paulson 1999 risk arbitrage opportunities in petroleum futures spreads (J. Futures Markets)"]),
        dict(slug="22-storage-transport-and-physical-optionality", title="Storage, Transport and Physical Optionality",
             hook="A trader who owns a gas storage cavern owns a string of calendar spread options; one who owns pipeline capacity owns location spread options; the physical asset is valued as the options it contains.",
             sections=["Storage as an option", "Transport as an option", "Monetising the options", "What the asset-backed trader owns"],
             defines=["storage deal", "transport option", "asset-backed trading"],
             uses=["rolling intrinsic (B3.10)", "intrinsic storage value (B6.16)", "calendar-spread option (B3.12)", "locational basis (B3.4)"] + _U_BT,
             strategies=["rolling-intrinsic storage", "spread-option storage hedge", "transport capacity optimisation", "cargo diversion"],
             tutorial="Value a storage facility and a transport contract on synthetic gas curves by intrinsic, rolling intrinsic and spread-option methods, and trade their hedges.",
             build="`firm.physopt`: storage and transport valuation (intrinsic, rolling intrinsic, spread-option bounds) and hedging programmes; Python.",
             problem="The asset as options — named result: storage value by method and the extra value of rolling the hedge.",
             facts=["Eydeland and Wolyniec 2003 energy and power risk management (Wiley)", "Secomandi 2010 optimal commodity trading with a capacitated storage asset (Management Science)"]),
        dict(slug="23-power-and-gas-trading", title="Power and Gas Trading",
             hook="Power bought the day before for delivery tomorrow and power bought an hour before delivery are different products; the spread between them pays traders who forecast the wind better than the market.",
             sections=["Day-ahead against intraday", "Weather-driven positions", "Batteries and flexible assets", "Risk in power books"],
             defines=["day-ahead-intraday spread", "weather-driven position", "battery arbitrage"],
             uses=["day-ahead market (B3.5)", "locational marginal price (B3.5)", "weather derivative (B3.11)", "spark spread (B3.5)"] + _U_BT,
             strategies=["forecast-error intraday trade", "weather-driven gas position", "battery day-ahead arbitrage", "spark-spread plant optimisation", "negative-price hours"],
             tutorial="From Book 3's German hourly power data measure the day-ahead price profile and negative hours, simulate intraday prices with planted wind forecast errors, and optimise a battery against both markets.",
             build="`firm.powergas`: day-ahead and intraday price models, forecast-error trades and battery optimisation by dynamic programming; Python.",
             problem="The wind forecast — named result: the battery's revenue in day-ahead only and with intraday re-optimisation.",
             facts=["German power data (as B3, data/markets-3/de_power_hourly_2024_2025.csv)", "Kiesel and Paraschiv 2017 econometric analysis of 15-minute intraday electricity prices (Energy Economics)"]),
    ]),
    ("part.s2.bank", [
        dict(slug="24-flow-market-making-at-a-bank", title="Flow Market Making at a Bank",
             hook="A bank's flow desk makes money by pricing clients, not by predicting prices: it knows which clients' trades will move against it and charges them accordingly.",
             sections=["The franchise and its P&L", "Axes and skewing", "Client tiering", "Internalisation"],
             defines=["client tiering", "axe-driven skew", "franchise P&L"],
             uses=["axe (B2.22)", "franchise (B1.2)", "internalisation (B1.10)", "quote skewing (B2.15)", "mark-out curve (B7.23)"] + _U_BT,
             strategies=["tiered pricing by client mark-out", "axe skewing", "internalisation before hedging", "RFQ win-rate management"],
             tutorial="Simulate a bank desk facing clients with different information, price them by tier from their mark-outs, skew quotes to axes and internalise opposite flows, and decompose the franchise P&L.",
             build="`firm.flowmm`: client mark-out estimation, tiered pricing, axe skewing and an internalisation engine with P&L decomposition; Python.",
             problem="Pricing the client — named result: the desk's spread capture by tier and the share of risk internalised.",
             facts=["Bjonnes and Rime or Butz and Oomen 2019 internalisation by electronic FX spot dealers (Quantitative Finance)", "Oomen 2017 last look (Quantitative Finance)"]),
        dict(slug="25-the-central-risk-book", title="The Central Risk Book",
             hook="Ten desks each hedging their own risk pay ten spreads for trades that would net to little; a central risk book collects the risk first and hedges only what is left.",
             sections=["Pooling and netting", "Internal crossing", "Optimised hedging", "Governance"],
             defines=["central risk book", "residual risk hedge", "risk pooling"],
             uses=["internal crossing (B7.27)", "fundamental factor model (B7.24)", "transaction cost analysis (B7.23)"],
             strategies=["central netting across desks", "factor-hedged residual risk", "patient hedging of pooled risk"],
             tutorial="Simulate trades arriving at several desks, pool them in a central book, hedge the net with a factor model and a cost model, and compare costs and residual risk with desk-by-desk hedging.",
             build="`firm.crbook`: risk pooling across desks, netting, factor hedges optimised against costs and residual-risk limits; Python.",
             problem="Hedge what is left — named result: the hedging cost saved by pooling and the residual risk accepted.",
             facts=["public descriptions of central risk books (dated), no firm named without a source"]),
        dict(slug="26-delta-one-and-dividends", title="Delta-One and Dividends",
             hook="A bank that sells autocallables is left long dividends it did not want; it sells them in dividend futures and swaps, and the dividend market is priced by that supply.",
             sections=["Index arbitrage at a bank", "Financing trades", "Dividend risk from structured issuance", "Dividend trades"],
             defines=["index arbitrage", "financing trade", "dividend supply pressure"],
             uses=["delta-one (B1.17)", "dividend future (B1.22)", "dividend risk (B5.5)", "fair value (B1.21)", "autocallable (B5.18)"] + _U_BT,
             strategies=["index arbitrage", "total-return swap financing", "long dividends against structured supply", "dividend calendar spread"],
             tutorial="Simulate index futures and their fair value with planted financing spreads, run index arbitrage, and model dividend futures priced below expected dividends because structured-product hedgers sell them.",
             build="`firm.deltaone`: index fair value, arbitrage bands, financing trades and a dividend market with structured supply; Python.",
             problem="Dividends nobody wanted — named result: the dividend trade's return from the supply discount.",
             facts=["Binsbergen, Brandt, Koijen 2012 on the timing and pricing of dividends (AER)", "Eurex dividend futures (dated)"]),
        dict(slug="27-quantitative-investment-strategies", title="Quantitative Investment Strategies",
             hook="A bank can package a carry or momentum strategy as an index, license it, and sell swaps on it; the backtest that sells it is written before the index goes live, and its returns after launch are lower.",
             sections=["Rules-based indices as products", "Wrappers and fees", "Hedging the index", "Live against backtest"],
             defines=["quantitative investment strategy", "index backtest decay", "strategy wrapper"],
             uses=["systematic strategy index (B5.19)", "backtest overfitting (B7.20)", "deflated Sharpe ratio (B4.12)"] + _U_BT,
             strategies=["risk-premia index swap", "volatility-carry index", "multi-asset risk-premia basket", "defensive overlay index"],
             tutorial="Design twenty candidate indices on the synthetic markets, select the best backtests as a bank's product team would, and measure the live decay against the deflated Sharpe ratio's prediction.",
             build="`firm.qis`: index rulebooks, backtest selection, fee and hedging costs, and live-versus-backtest comparison; Python.",
             problem="Written before launch — named result: the gap between the selected indices' backtest and live Sharpe ratios.",
             facts=["Suhonen, Lennkh, Perez 2017 quantifying backtest overfitting in alternative beta strategies (JPM)", "Vatanen and Suhonen or equivalent"]),
        dict(slug="28-hedging-a-structured-products-book", title="Hedging a Structured-Products Book",
             hook="Retail investors buy autocallables in large size; the banks that sell them end up long volatility they must sell, short correlation and long dividends, and their hedging moves those markets.",
             sections=["The autocallable book's exposures", "Vega and skew", "Correlation and dividends", "Recycling trades"],
             defines=["recycling trade", "exotic book exposure"],
             uses=["autocallable (B5.18)", "autocall trigger (B5.18)", "vega bucket (B5.26)", "structured product (B5.19)", "correlation skew (B5.17)"] + _U_BT,
             strategies=["vega recycling to hedge funds", "dividend recycling", "correlation recycling", "skew hedge programme"],
             tutorial="Build a book of autocallables on firm.autocall, compute its vega, skew, dividend and correlation exposures, and simulate the recycling trades it offers and their price impact on the synthetic volatility market.",
             build="`firm.sphedge`: exposure aggregation for an autocallable book, recycling trade construction and a market-impact model of the hedging; Python.",
             problem="Long what nobody wants — named result: the book's net exposures and the implied-volatility move its recycling causes.",
             facts=["Bank of Korea or Korean autocallable market reports (dated)", "Bouzoubaa and Osseiran 2010 exotic options and hybrids (Wiley)"]),
    ]),
    ("part.s2.forbidden", [
        dict(slug="29-manipulative-strategies-and-how-they-are-caught", title="Manipulative Strategies and How They Are Caught",
             hook="A trader placed large orders he never meant to fill, cancelled them within seconds, and traded the other side of the price move they caused; the pattern was clear enough in the order log to convict him.",
             sections=["Spoofing and layering", "Momentum ignition and marking the close", "Wash trades and benchmark manipulation", "Sandwiching and its legal status", "Surveillance: detectors and their errors"],
             defines=["spoofing", "layering", "momentum ignition", "marking the close", "benchmark manipulation"],
             uses=["wash trading (B3.16)", "sandwich attack (B3.22)", "front-running (B3.22)", "cancellation rate (B7.8)", "best execution (B1.11)"],
             strategies=["spoofing", "layering", "momentum ignition", "wash trades", "marking the close", "benchmark manipulation", "sandwiching", "detector: cancellation-pattern surveillance"],
             tutorial="On firm.tape order logs, plant spoofing, layering and marking-the-close episodes among legitimate market-making, build detectors from public enforcement descriptions, and measure their true and false positive rates.",
             build="`firm.surveil`: surveillance detectors (order-to-trade and cancellation patterns around executions, close-window price impact, self-matching) with labelled synthetic episodes and ROC evaluation; Python.",
             problem="In the order log — named result: each detector's true-positive rate at a fixed false-positive rate, and how legitimate market making triggers them.",
             facts=["US v. Sarao (CFTC/DOJ 2015) and Coscia (7th Cir. 2017) spoofing cases (dated)", "Dodd-Frank Act section 747 anti-spoofing provision (dated)", "EU Market Abuse Regulation Annex I indicators (dated)", "FCA and CFTC benchmark (LIBOR/FX) enforcement (dated)", "SEC marking-the-close cases (dated)"]),
    ]),
]
