"""Book 10 (Microstructure and Execution) chapter briefs: data for tools/make_briefs.py --book 10.

`uses` lists terms defined elsewhere that the chapter relies on (not redefined); owners in parentheses:
(B7.18) = One Quant Book 7, chapter 18, checked against the multi-line \\index{} harvest of Books 1-9 on
2026-09-25 (2,103 terms); (ch3) = an earlier chapter of this book; (B11.9, forward) / (B12.17, forward) /
(B13.16, forward) = a term the batch book will define (by the outline; frozen at the Books 10-13 sync).

Ownership: Books 1-9 keep their terms. Book 1 owns the market-structure vocabulary (order, NBBO, protected
quotes' rule, trade-through, intermarket sweep order, maker-taker pricing, inverted venue, access fee cap,
dark pool, the EU waivers and double volume cap, periodic auction, call auction, uncrossing and indicative
price, order imbalance, MOC and LOC orders, volatility interruption, price-time priority, pro-rata and
top-order allocation, market-by-order and -price, levels 1-3, sequence number, exchange timestamp, flash
crash, stub quote, LULD, market-wide circuit breaker, effective and realised spread, price improvement,
internalisation, payment for order flow, best execution); Book 2 owns request for quote, last look, hold
time, reject rate, streaming quote, benchmark fix, all-to-all trading, portfolio trade, winner's curse,
mark-out; Book 3 owns post-only order, rate limit, snapshot-and-delta feed, book checksum, AMM, slippage
tolerance; Book 4 owns the queueing, point-process, control, auction-theory and econometric tools (Roll's
estimator, bid-ask bounce, microstructure noise, Hawkes process, HJB, dynamic programming, Nash and
Bayes-Nash equilibria, common-value and first-price auctions, bid shading, VAR/VECM); Book 7 owns the
research-side execution vocabulary (market impact, counterfactual impact, queue position and the
queue-position model, passive fill probability, latency model and the two latencies, order-book replay,
metaorder, Kyle's lambda, VPIN, order-sign autocorrelation, trade sign, temporary and permanent impact,
square-root impact law, percentage of volume, implementation shortfall, arrival price, transaction cost
analysis, delay and opportunity cost, VWAP and VWAP slippage, mark-out curve, fill rate, hit ratio,
internal crossing, depth profile, cancellation rate, queue imbalance, microprice, stylised fact); Book 8 owns
trading halt, magnet effect, transition management; Book 9 owns central risk book, risk pooling, and the
manipulation patterns. The order types themselves (limit, market, stop, iceberg, pegged, hidden, IOC, FOK,
time in force) and the limit order book are NOT defined in Books 1-9 (only named in prose): this book defines
them (chapters 1-2).

No strategy files (the outline brackets none for Book 10); predictor cards none. Every chapter's numbers come
from the book's simulators (firm.tape of Book 7, and this book's firm.exchsim and firm.agentmkt) or from cited
publications; the only real data planned are public-domain US government series (SEC MIDAS market-structure
metrics) and published exchange documents.

Running project (code/firm/, all new and unique; checked against the 264 existing components):
  lob (ch1, Python + C++20 + Rust)  ordertypes (ch2)  lobstats (ch3)  spreadmodels (ch4)  spreaddecomp (ch5)
  queuevalue (ch6)  venuefees (ch7)  consolidated (ch8)  darkpool (ch9)  auctionsim (ch10)  impactfit (ch11)
  propagator (ch12)  crossimpact (ch13)  acexec (ch14)  execcontrol (ch15)  algos (ch16)  placement (ch17)
  sor (ch18)  tca (ch19)  algowheel (ch20)  xexec (ch21)  riskbid (ch22)  otcsearch (ch23)
  mktquality (ch24)  halts (ch25)  exchsim (ch26, Python reference + C++20 engine, codecs and server + Rust
  engine and codecs)  agentmkt (ch27)  execalgo (ch28)
firm.exchsim is implemented FIRST, right after the sync (BATCH_BOOKS_10-13.md): Books 11, 12 and 13 trade on
it, and chapters 1-25 of this book use it in their tutorials with a forward pointer to chapter 26.
"""
SLUG = "microstructure"
PFX = "mx"
HEAD = "One Quant Book 10 — Microstructure and Execution"

_U_BOOK = ["order (B1.4)", "exchange (B1.4)", "bid--ask spread (B1.1)", "mid price (B1.1)",
           "price-time priority (B1.19)", "market-by-order (B1.19)", "market-by-price (B1.19)"]
_U_SIM = ["stylised fact (B7.5)", "order-book replay (B7.18)", "latency model (B7.18)"]
_U_IMPACT = ["market impact (B7.18)", "temporary impact (B7.27)", "permanent impact (B7.27)",
             "square-root impact law (B7.27)", "metaorder (B7.9)", "percentage of volume (B7.27)"]
_U_EXEC = ["implementation shortfall (B7.19)", "arrival price (B7.19)", "transaction cost analysis (B7.23)"]

PARTS = [
    ("part.mx.orderbook", [
        dict(slug="01-the-limit-order-book", title="The Limit Order Book",
             hook="A trader sends a buy order for 500 shares at 100.02 and the screen shows 3,000 shares already bid there. Her order is not at the best bid: it is behind a line of orders that arrived first, and it trades only if that line is consumed before anyone cancels or the price moves away.",
             sections=["State: price levels and queues", "Events: add, cancel, modify, execute", "Priority and what resets it", "The book as a data structure", "The book as a queueing system"],
             defines=["limit order", "market order", "limit order book", "tick size", "price level", "order-book event", "matching engine", "zero-intelligence model"],
             uses=_U_BOOK + ["level 1 (B1.28)", "level 2 (B1.28)", "level 3 (B1.28)", "sequence number (B1.28)", "market data feed (B1.4)",
                             "queue position (B7.18)", "cancellation rate (B7.8)", "depth profile (B7.8)", "Poisson process (B4.6)",
                             "birth--death process (B4.8)", "continuous-time Markov chain (B4.8)"],
             strategies=[],
             tutorial="Rebuild the book of a firm.tape session message by message with firm.lob; measure the event mix, order lifetimes and the time the best quotes survive; check a price-indexed array book against a tree-keyed book on the same messages (identical level 2 at every step); then run the Smith-Farmer zero-intelligence model on firm.lob and compare its spread and depth with the tape's. Data: firm.tape (simulated).",
             build="`firm.lob`: the reference limit order book (order map, price levels with FIFO queues, add / cancel / reduce / modify with the priority rules of the chapter, execute, level-1/2/3 views, an invariant checker) in Python, with a C++20 and a Rust twin that reproduce the Python book on a shared message fixture; the core that chapter 26's matching engine is built on.",
             problem="The line at 100.02 -- named result: the probability that a resting order at the back of the best bid fills before the price moves, in the zero-intelligence model and in the simulated market, against queue length.",
             facts=["Gould, Porter, Williams, McDonald, Fenn, Howison 2013 limit order books (Quantitative Finance)", "Smith, Farmer, Gillemot, Krishnamurthy 2003 statistical theory of the continuous double auction (QF)", "Cont, Stoikov, Talreja 2010 a stochastic model for order book dynamics (Operations Research)", "Nasdaq TotalView-ITCH 5.0 order replace and cancel semantics (dated)", "CME Globex / Nasdaq rules on priority after a size decrease or increase (dated)"]),
        dict(slug="02-order-types-and-their-uses", title="Order Types and Their Uses",
             hook="US exchanges publish dozens of order types; in 2015 one exchange group paid to settle regulators' charges that some of its order types behaved in ways it had not fully disclosed to all members. An order type is a contract about what the matching engine will do with your order, and its fine print decides who trades first.",
             sections=["Price conditions: limit, market, marketable limit, stop", "Time conditions: day, good-till-cancelled, immediate-or-cancel, fill-or-kill", "Display conditions: hidden, iceberg, pegged", "Who uses which, and why", "A limit order is a free option"],
             defines=["marketable limit order", "stop order", "stop-limit order", "time in force", "immediate-or-cancel order", "fill-or-kill order", "good-till-cancelled order", "hidden order", "iceberg order", "pegged order", "midpoint peg", "free option of a limit order"],
             uses=["limit order (ch1)", "market order (ch1)", "limit order book (ch1)", "matching engine (ch1)", "post-only order (B3.15)",
                   "intermarket sweep order (B1.9)", "market-on-close order (B1.13)", "limit-on-close order (B1.13)", "national best bid and offer (B1.9)",
                   "trade-through (B1.9)", "stub quote (B1.31)", "flash crash (B1.31)", "dark pool (B1.9)", "price improvement (B1.10)",
                   "adverse selection (B1.1)", "maker-taker pricing (B1.9)"],
             strategies=[],
             tutorial="Implement the order types on firm.lob (stops triggered by trades, iceberg refresh with a new time priority, pegs repriced on each change of the best quotes, IOC and FOK, post-only) and replay a scripted morning through them; then detect icebergs in the public feed from same-price refills, and value a resting limit order as a short option against the next price move. Data: firm.tape and scripted scenarios (simulated).",
             build="`firm.ordertypes`: the order-type layer on top of firm.lob (time in force, stop triggers, iceberg display and refresh, primary and midpoint pegs, post-only, IOC / FOK, minimum quantity, self-trade prevention hooks) with a conformance table of scenarios that chapter 26's C++20 and Rust engines must reproduce; Python.",
             problem="The iceberg in the tape -- named result: the detection rate and false-alarm rate of a refill-based iceberg detector against the display size and the randomisation of the refill.",
             facts=["SEC 2015 settlement with Direct Edge exchanges over undisclosed order-type behaviour (order and penalty)", "SEC investor bulletin on stop and stop-limit orders", "Nasdaq and Cboe BZX order-type documentation: midpoint peg, reserve (iceberg), post-only (dated)", "Copeland and Galai 1983 information effects on the bid-ask spread (JF)", "Hautsch and Huang 2012 on the dark side of the market: hidden liquidity (JFM / or equivalent)", "CFTC-SEC 2010 report on 6 May 2010 (stop orders converted to market orders)"]),
        dict(slug="03-empirical-facts-of-order-books", title="Empirical Facts of Order Books",
             hook="Average the depth of a liquid stock's book at each distance from the best price and the curve is not highest at the best quote: it rises for a few ticks and then falls. The book's shape, its flows and the way its spread lives through the day repeat across markets with a regularity no single trader designs.",
             sections=["Depth profiles", "Arrival and cancellation rates by distance", "Spreads and the spread-volatility relation", "Intraday shapes", "Order lifetimes, fleeting orders and resilience"],
             defines=["fleeting order", "order lifetime", "relative limit price", "book resilience", "volatility per trade"],
             uses=["limit order book (ch1)", "tick size (ch1)", "price level (ch1)", "zero-intelligence model (ch1)", "stylised fact (B7.5)",
                   "intraday seasonality (B7.5)", "intraday volume profile (B7.5)", "depth profile (B7.8)", "cancellation rate (B7.8)",
                   "queue depletion rate (B7.8)", "bid--ask spread (B1.1)", "heavy-tailed distribution (B4.15)", "tail index (B4.15)"],
             strategies=[],
             tutorial="Measure on firm.tape, and on the public SEC MIDAS market-structure metrics, the depth profile, arrival and cancellation rates against the relative limit price, the spread distribution, order lifetimes, the intraday profiles of spread and volume, and the book's recovery after large trades; set each beside its published counterpart. Data: firm.tape (simulated); SEC MIDAS metrics by exchange (US government, public domain).",
             build="`firm.lobstats`: the stylised-fact toolkit for any market-by-order stream in the firm.tape format (depth profile, rates by distance, lifetimes and fleeting share, spread histogram and spread-volatility fit, intraday profiles, resilience after large trades), the yardstick chapter 27 calibrates the agent-based market against; Python.",
             problem="Is the simulator a market? -- named result: the table of stylised facts measured on the simulated market against their published values, and the facts it fails.",
             facts=["Bouchaud, Mezard, Potters 2002 statistical properties of stock order books (QF)", "Zovko and Farmer 2002 the power of patience: relative limit prices (QF)", "Hasbrouck and Saar 2009 technology and liquidity provision: fleeting orders (JFM)", "Wyart, Bouchaud, Kockelkoren, Potters, Vettorazzo 2008 relation between bid-ask spread and volatility (QF)", "Biais, Hillion, Spatt 1995 an empirical analysis of the limit order book (JF)", "Large 2007 measuring the resiliency of an electronic limit order book (JFM)", "SEC MIDAS market structure metrics: cancel-to-trade and hidden-volume statistics (dated)"]),
        dict(slug="04-why-there-is-a-spread", title="Why There Is a Spread",
             hook="A market maker quotes 100.00 bid, 100.02 offered. If nobody knew more than she did, the two cents would pay for her time and for the risk of the inventory she carries. A buyer who has read the news first makes the spread pay for something else, and the three explanations lead to different spreads.",
             sections=["Order-processing costs", "Inventory", "Information: the sequential-trade model", "Information: the strategic trader", "Measuring informed trading"],
             defines=["order-processing cost", "inventory-holding cost", "informed trader", "noise trader", "sequential-trade model", "Glosten--Milgrom model", "Kyle model", "probability of informed trading"],
             uses=["adverse selection (B1.1)", "market maker (B1.1)", "bid--ask spread (B1.1)", "inventory (B2.30)", "Bayesian update (B2.30)",
                   "winner's curse (B2.30)", "Kyle's lambda (B7.9)", "VPIN (B7.9)", "flow toxicity (B7.9)", "Roll's estimator (B4.21)",
                   "bid--ask bounce (B4.21)", "Nash equilibrium (B4.29)", "maximum likelihood estimator (B4.11)", "limit order book (ch1)"],
             strategies=[],
             tutorial="Simulate the Glosten-Milgrom dealer and watch its quotes converge to the value; solve Kyle's one-period and N-period models and recover lambda from simulated trades; fit the probability of informed trading by maximum likelihood (scipy) on simulated buy and sell counts, and on firm.tape whose informed flow is known. Data: simulated.",
             build="`firm.spreadmodels`: Glosten-Milgrom quotes and dynamics, Kyle one-period and N-period (backward recursion), Ho-Stoll inventory quotes, the PIN likelihood (numerically stable form) and its fit, all deterministic; Python (scipy).",
             problem="The specialist's two cents -- named result: the share of a Glosten-Milgrom spread that is adverse selection, against the informed share, and the bias of the PIN estimate when arrival rates move during the day.",
             facts=["Roll 1984 a simple implicit measure of the effective bid-ask spread (JF)", "Garman 1976 market microstructure (JFE)", "Stoll 1978 the supply of dealer services (JF)", "Ho and Stoll 1981 optimal dealer pricing (JFE)", "Glosten and Milgrom 1985 (JFE)", "Kyle 1985 continuous auctions and insider trading (Econometrica)", "Easley, Kiefer, O'Hara, Paperman 1996 liquidity, information and infrequently traded stocks (JF)", "Duarte and Young 2009 why is PIN priced? (JFE)"]),
        dict(slug="05-decomposing-the-spread", title="Decomposing the Spread",
             hook="A buy of 1,000 shares pays two cents over the mid. A minute later the mid has moved one and a half cents the way the trade went: the liquidity provider kept half a cent, and the rest was what the trade told the market.",
             sections=["Quoted, effective and realised spreads", "The price impact of a trade", "Structural decompositions", "The vector-autoregression view", "Spreads from daily data"],
             defines=["quoted spread", "trade price impact", "adverse-selection component", "spread decomposition", "Huang--Stoll model", "Madhavan--Richardson--Roomans model", "low-frequency spread estimator"],
             uses=["effective spread (B1.10)", "realised spread (B1.10)", "price improvement (B1.10)", "Rule 605 report (B1.10)", "trade sign (B7.9)",
                   "Lee--Ready algorithm (B7.9)", "vector autoregression (B4.20)", "impulse response function (B4.20)", "generalised method of moments (B4.11)",
                   "Roll's estimator (B4.21)", "order-processing cost (ch4)", "inventory-holding cost (ch4)", "Glosten--Milgrom model (ch4)", "informed trader (ch4)"],
             strategies=[],
             tutorial="On firm.tape, where every trade's informed flag is known, compute quoted, effective and realised spreads and the trade price impact by horizon; estimate the adverse-selection component with Huang-Stoll, MRR (GMM) and a Hasbrouck VAR, and score each against the planted truth; then estimate spreads from daily bars with the low-frequency estimators. Data: firm.tape (simulated).",
             build="`firm.spreaddecomp`: quoted / effective / realised spreads and trade price impact by horizon, Glosten-Harris, Huang-Stoll, MRR by GMM, Hasbrouck VAR impulse responses, Roll, Corwin-Schultz and Abdi-Ranaldo estimators; Python (statsmodels).",
             problem="Who paid the two cents? -- named result: the adverse-selection share estimated by each method against the simulator's truth, and the horizon at which the realised spread settles.",
             facts=["Glosten and Harris 1988 estimating the components of the bid/ask spread (JFE)", "Huang and Stoll 1997 the components of the bid-ask spread: a general approach (RFS)", "Madhavan, Richardson, Roomans 1997 why do security prices change? (RFS)", "Hasbrouck 1991 measuring the information content of stock trades (JF)", "Corwin and Schultz 2012 (JF)", "Abdi and Ranaldo 2017 (RFS)", "SEC 2024 amendments to Rule 605: realized-spread horizons (dated)"]),
        dict(slug="06-tick-size-queues-and-priority", title="Tick Size, Queues and Priority",
             hook="From October 2016 the SEC's tick-size pilot quoted and traded about twelve hundred small stocks in five-cent increments instead of one. Spreads widened, displayed depth grew, and the value of standing first in a queue changed for every market maker in them.",
             sections=["Large-tick and small-tick assets", "The value of queue position", "Queue dynamics and the time to fill", "Tick-size experiments", "Priority rules beyond time"],
             defines=["relative tick size", "large-tick asset", "small-tick asset", "queue value", "uncertainty-zone model", "difference-in-differences"],
             uses=["tick size (ch1)", "limit order book (ch1)", "queue position (B7.18)", "passive fill probability (B7.18)", "price-time priority (B1.19)",
                   "pro-rata allocation (B1.19)", "top-order allocation (B1.19)", "round lot (B1.9)", "odd lot (B1.9)", "queue imbalance (B7.8)",
                   "microprice (B7.8)", "birth--death process (B4.8)", "hitting probability (B4.8)", "clustered standard errors (B4.16)", "adverse selection (B1.1)"],
             strategies=[],
             tutorial="Run firm.exchsim with the tape's background flow at tick sizes of one, two, five and ten cents: spread in ticks, queue lengths, time to fill and the share of time the spread is one tick; value a queue slot by simulation and by the birth-death formulas of firm.queues; estimate a difference-in-differences effect of a tick change on simulated treated and control stocks. Data: simulated; the pilot's published results.",
             build="`firm.queuevalue`: fill probability and expected time to fill from a queue position (birth-death and empirical), value of a queue slot (spread capture less adverse selection conditional on a fill), front- against back-of-queue comparison, uncertainty-zone estimator of the implicit spread; Python.",
             problem="Five cents instead of one -- named result: the change in spread, depth and queue value when the tick is multiplied by five in the simulated market, against the pilot's measured effects.",
             facts=["SEC Tick Size Pilot plan (2014 order, 2016 start, 2018 end; test groups)", "SEC DERA / published assessments of the tick size pilot (e.g. Albuquerque, Song, Yao 2020 JFE; Chung, Lee, Rosch 2020 JFE)", "Dayri and Rosenbaum 2015 large tick assets: implicit spread and optimal tick size (Market Microstructure and Liquidity)", "Robert and Rosenbaum 2011 a new approach for the dynamics of ultra-high-frequency data: the model with uncertainty zones (J. Financial Econometrics)", "Moallemi and Yuan queue position valuation (published version if any)", "SEC 2024 Regulation NMS amendments: minimum pricing increments (half-cent tick) and their effective date (dated)", "EU tick-size regime (as in Book 1 ch. 11)"]),
        dict(slug="07-fees-rebates-and-venue-economics", title="Fees, Rebates and Venue Economics",
             hook="The same stock is bid at the same price on two exchanges. One pays the resting order a rebate and has twenty thousand shares queued ahead; the other charges the resting order a fee and has eight hundred. A trader who wants to be filled should pay to stand in the short line.",
             sections=["Maker-taker, inverted and flat pricing", "Fee-adjusted prices and the effective tick", "Is the fee split neutral?", "Tiers and the venue's business", "Evidence from fee experiments"],
             defines=["fee-adjusted price", "effective tick size", "fee neutrality", "flat pricing"],
             uses=["maker-taker pricing (B1.9)", "inverted venue (B1.9)", "access fee cap (B1.9)", "volume tier (B1.29)", "non-display fee (B1.29)",
                   "market data feed (B1.4)", "payment for order flow (B1.10)", "exchange (B1.4)", "tick size (ch1)", "queue value (ch6)",
                   "passive fill probability (B7.18)", "adverse selection (B1.1)", "mark-out (B2.15)", "difference-in-differences (ch6)"],
             strategies=[],
             tutorial="Run two venues of firm.exchsim with the same flow and different fee schedules (maker-taker and inverted); let the background liquidity providers choose where to post by fee-adjusted price and queue length; measure queue lengths, fill rates, mark-outs of passive fills and the spread net of fees on each venue. Data: simulated; published fee schedules.",
             build="`firm.venuefees`: fee-adjusted prices, effective tick, the passive and aggressive venue choice under tiers (reusing Book 1's firm.feesched), and a fee-neutrality check of any two-venue result; Python.",
             problem="The rebate that bought a queue -- named result: the fill rate and the mark-out of passive orders on the maker-taker and the inverted venue, and the rebate at which a liquidity provider is indifferent.",
             facts=["Colliard and Foucault 2012 trading fees and efficiency in limit order markets (RFS)", "Malinova and Park 2015 subsidizing liquidity: the impact of make/take fees on market quality (JF)", "Battalio, Corwin, Jennings 2016 can brokers have it all? (JF)", "SEC Transaction Fee Pilot 2018 and its vacatur by the DC Circuit 2020", "SEC 2024 amendments to the access fee cap (dated)", "exchange fee schedules: a maker-taker and an inverted venue (dated)", "exchange revenue mix from listed exchange groups' annual reports (dated)"]),
        dict(slug="08-fragmentation-and-routing", title="Fragmentation and Routing",
             hook="An order to buy 5,000 shares at the best offer finds 1,200 on the venue it was sent to. The other 3,800 at that price sit on four other venues, and by the time a second order reaches them some have gone.",
             sections=["Many venues, one stock", "Consolidated and direct views of the market", "Protected quotes, locked and crossed markets", "Latency between venues", "Where is the price discovered?"],
             defines=["market fragmentation", "protected quote", "locked market", "crossed market", "price discovery", "information share", "component share"],
             uses=["national best bid and offer (B1.9)", "securities information processor (B1.9)", "direct feed (B1.9)", "order protection rule (B1.9)",
                   "trade-through (B1.9)", "intermarket sweep order (B1.9)", "consolidated tape provider (B1.11)", "best execution (B1.11)",
                   "alternative trading system (B1.4)", "multilateral trading facility (B1.4)", "cointegration (B4.20)", "vector error-correction model (B4.20)",
                   "Hayashi--Yoshida estimator (B4.21)", "lead--lag relationship (B7.10)", "market-data latency (B7.18)", "latency arbitrage (B11.9, forward)"],
             strategies=[],
             tutorial="Run three venues of firm.exchsim with inter-venue latencies; build the consolidated book from each venue's direct feed and from a delayed consolidated feed; measure how often the two views disagree, the frequency of locked and crossed markets, and the information share of each venue by a VECM with Hasbrouck bounds. Data: simulated; SEC MIDAS metrics.",
             build="`firm.consolidated`: consolidated book across venues with per-venue latency (reusing Book 1's firm.nbbo), locked and crossed detection, direct-against-consolidated comparison, information shares (Hasbrouck bounds) and component shares; Python.",
             problem="Where is the price found? -- named result: the information shares of three simulated venues, and the share of time the direct-feed and consolidated best prices differ, against the consolidated feed's delay.",
             facts=["O'Hara and Ye 2011 is market fragmentation harming market quality? (JFE)", "Degryse, de Jong, van Kervel 2015 the impact of dark trading and visible fragmentation on market quality (Review of Finance)", "Hasbrouck 1995 one security, many markets (JF)", "Gonzalo and Granger 1995 (JBES) component share", "Bartlett and McCrary 2019 how rigged are stock markets? (JFM) or Ding, Hanna, Hendershott 2014 (RFS)", "SEC 2020 market data infrastructure rule and its status (dated)", "SEC 2026 proposal to rescind the order protection rule and its status (dated; see Book 1 ch. 9 trap)", "number of US equity exchanges and ATSs (dated)"]),
        dict(slug="09-dark-pools-and-blocks", title="Dark Pools and Blocks",
             hook="A pension fund wants to buy two million shares of a stock that trades five million a day. Shown on a lit book, the order would move the price before a tenth of it traded; sent to a dark pool, it waits for a seller, and every venue it touches learns a little of what it wants.",
             sections=["Midpoint crossing and minimum quantities", "Conditional orders and block venues", "Who trades in the dark, and the evidence", "Information leakage", "Dark pools in enforcement records"],
             defines=["minimum execution quantity", "conditional order", "firm-up rate", "information leakage", "pinging order", "indication of interest", "crossing network"],
             uses=["dark pool (B1.9)", "large-in-scale waiver (B1.11)", "reference price waiver (B1.11)", "double volume cap (B1.11)", "periodic auction (B1.11)",
                   "block trade (B1.2)", "alternative trading system (B1.4)", "systematic internaliser (B1.11)", "internalisation (B1.10)",
                   "midpoint peg (ch2)", "hidden order (ch2)", "immediate-or-cancel order (ch2)", "adverse selection (B1.1)", "mark-out (B2.15)",
                   "mark-out curve (B7.23)", "informed trader (ch4)"],
             strategies=[],
             tutorial="Add a midpoint dark venue to the multi-venue firm.exchsim; let informed and uninformed flow choose between lit and dark (Zhu 2014); measure dark fill rates, the mark-outs of dark against lit fills, and how much a parent order's footprint (pings, conditionals that do not firm up) moves the price before it completes. Data: simulated; SEC and FINRA published statistics.",
             build="`firm.darkpool`: a midpoint crossing venue with minimum quantities and conditional orders (invitation, firm-up timer, firm-up rate per participant), leakage metrics (pre-completion drift, counterparty mark-outs), plugged into firm.exchsim as a venue type; Python.",
             problem="The block that leaked -- named result: the price drift before completion of a parent order worked in the dark against in the lit market, and the leakage cost in basis points.",
             facts=["Zhu 2014 do dark pools harm price discovery? (RFS)", "Comerton-Forde and Putnins 2015 dark trading and price discovery (JFE)", "SEC orders: ITG POSIT 2015; Barclays LX 2016; Credit Suisse Crossfinder 2016 (amounts and findings)", "FINRA ATS transparency data: dark share of US volume (dated)", "ESMA double volume cap and its 2024 MiFIR review changes (dated)", "Kavajecz and Keim / block-venue evidence if cited"]),
        dict(slug="10-auction-mechanics-and-theory", title="Auction Mechanics and Theory",
             hook="In the minutes before a closing auction the exchange publishes an indicative price and imbalance every few seconds, and much of the auction's volume arrives in its last seconds. Every participant watches the same numbers and decides when to show its hand.",
             sections=["Uncrossing rules revisited", "Indicative prices and imbalance publication", "Cut-offs, collars and random ends", "Strategic behaviour near the uncross", "Frequent batch auctions"],
             defines=["auction cut-off time", "auction collar", "random end", "frequent batch auction"],
             uses=["call auction (B1.13)", "uncrossing price (B1.13)", "indicative price (B1.13)", "order imbalance (B1.13)", "market-on-close order (B1.13)",
                   "limit-on-close order (B1.13)", "closing price (B1.13)", "volatility interruption (B1.13)", "periodic auction (B1.11)",
                   "uniform-price auction (B2.4)", "Bayes--Nash equilibrium (B4.29)", "bid shading (B4.29)", "Kyle model (ch4)", "informed trader (ch4)",
                   "latency arbitrage (B11.9, forward)"],
             strategies=[],
             tutorial="Run closing auctions in firm.exchsim (Book 1's firm.auction does the uncross) with a market-on-close imbalance, liquidity providers who respond to the published imbalance, and one strategic participant; draw the indicative price's path and the arrival of volume; compare a fixed end with a random end, and a continuous market with frequent batch auctions for a sniping race. Data: simulated; published auction rules.",
             build="`firm.auctionsim`: the auction phase that firm.exchsim runs (order acceptance by phase, indicative price and imbalance publication, cut-off rules, collars, random end, the uncross through Book 1's firm.auction) and a frequent-batch-auction mode; Python.",
             problem="The last ten seconds -- named result: the gap between the indicative and the final price against the time to the uncross, and the gain from late submission under a fixed and a random end.",
             facts=["Nasdaq closing cross rules (dated)", "NYSE closing auction rules and imbalance publication (dated)", "LSE / Euronext random end of auction periods (dated)", "Budish, Cramton, Shim 2015 the high-frequency trading arms race: frequent batch auctions (QJE)", "Madhavan 1992 trading mechanisms in securities markets (JF)", "Bogousslavsky and Muravyev 2023 who trades at the close? (JFE or current venue)", "share of US volume in closing auctions (dated)"]),
    ]),
    ("part.mx.impact", [
        dict(slug="11-the-empirics-of-price-impact", title="The Empirics of Price Impact",
             hook="Buy one per cent of a day's volume and the price moves, on average, by some amount; buy four per cent and it moves about twice as much, not four times. That the impact of an order grows like the square root of its size is one of the most robust regularities in finance, and nobody designed it.",
             sections=["The impact of a single trade", "Aggregate impact of order flow", "The impact of a metaorder: during and after", "The square-root law", "Measurement pitfalls"],
             defines=["aggregate impact", "impact curve", "peak impact", "impact reversion", "impact prefactor", "alpha contamination"],
             uses=_U_IMPACT + ["Kyle's lambda (B7.9)", "trade sign (B7.9)", "order-sign autocorrelation (B7.9)", "counterfactual impact (B7.18)",
                               "trade price impact (ch5)", "implementation shortfall (B7.19)", "arrival price (B7.19)",
                               "HAC estimator (B4.11)", "bootstrap (B4.13)"],
             strategies=[],
             tutorial="Trade metaorders of random sizes and durations into firm.exchsim with the tape's background flow; measure single-trade, aggregate and metaorder impact; fit the square-root law's exponent and prefactor with robust errors; show the concave single-trade curve, the decay after completion, and the bias when the orders were sent because of a forecast. Data: simulated; published estimates.",
             build="`firm.impactfit`: impact estimation from fills and a market-data stream (single-trade response, aggregate impact on intervals, metaorder impact paths and their decay, exponent and prefactor fits with robust errors, a correction for alpha contamination); Python, reusing Book 7's firm.tcost fit where it applies.",
             problem="The square root in our own data -- named result: the exponent and prefactor of the square-root law fitted on the firm's simulated metaorders with confidence intervals, and their bias when order timing carries a forecast.",
             facts=["Almgren, Thum, Hauptmann, Li 2005 direct estimation of equity market impact (Risk)", "Toth et al. 2011 anomalous price impact and the critical nature of liquidity in financial markets (PRX)", "Bacry, Iuga, Lasnier, Lehalle 2015 market impacts and the life cycle of investors orders (Market Microstructure and Liquidity)", "Frazzini, Israel, Moskowitz 2018 trading costs (working paper, AQR)", "Moro et al. 2009 market impact and trading profile of hidden orders in stock markets (PRE)", "Zarinelli, Treccani, Farmer, Lillo 2015 beyond the square root (Market Microstructure and Liquidity)", "Loeb 1983 trading cost: the critical link between investment information and results (FAJ)"]),
        dict(slug="12-transient-impact-and-propagator-models", title="Transient Impact and Propagator Models",
             hook="The signs of trades are predictable for hours: a buy is followed by buys long after any one trader's order has finished. Yet prices do not trend. Something must undo the impact of each trade, and how fast it does decides what an execution costs.",
             sections=["The long memory of order flow", "The propagator model", "Transient impact in continuous time", "No-manipulation conditions", "Estimating the kernel"],
             defines=["propagator model", "decay kernel", "transient impact model", "Obizhaeva--Wang model", "no-dynamic-arbitrage condition", "transaction-triggered price manipulation"],
             uses=["long memory (B4.17)", "Hurst exponent (B4.17)", "autocorrelation function (B4.17)", "order-sign autocorrelation (B7.9)", "trade sign (B7.9)",
                   "metaorder (B7.9)", "market impact (B7.18)", "temporary impact (B7.27)", "permanent impact (B7.27)", "impact curve (ch11)",
                   "impact reversion (ch11)", "book resilience (ch3)", "Hawkes process (B4.7)"],
             strategies=[],
             tutorial="Fit a propagator kernel to firm.exchsim trades by inverting the sign-correlation Toeplitz system (Bouchaud et al. 2004); check that the fitted kernel makes prices diffusive; simulate round trips under exponential and power-law kernels and exhibit a profitable round trip when the kernel's decay violates the no-arbitrage conditions. Data: simulated.",
             build="`firm.propagator`: response functions, kernel estimation (correlation inversion by Levinson recursion), transient-impact simulation for exponential and power-law kernels, round-trip cost and the positive-definiteness check, the Obizhaeva-Wang limit-order-book model; Python.",
             problem="The kernel that paid you to trade -- named result: the round-trip profit under a kernel that decays too fast after large trades, and the decay rate at which it vanishes.",
             facts=["Bouchaud, Gefen, Potters, Wyart 2004 fluctuations and response in financial markets (QF)", "Lillo and Farmer 2004 the long memory of the efficient market (SNDE)", "Obizhaeva and Wang 2013 optimal trading strategy and supply/demand dynamics (JFM)", "Gatheral 2010 no-dynamic-arbitrage and market impact (QF)", "Alfonsi, Schied, Slynko 2012 order book resilience, price manipulation and the positive portfolio problem (SIFIN)", "Huberman and Stanzl 2004 price manipulation and quasi-arbitrage (Econometrica)", "Bouchaud, Bonart, Donier, Gould 2018 Trades, Quotes and Prices (CUP)"]),
        dict(slug="13-metaorders-latent-liquidity-and-cross-impact", title="Metaorders, Latent Liquidity and Cross-Impact",
             hook="Why should impact grow like the square root of size, whatever the stock, the decade or the market? The answer most models now give is that the book a trader sees is a small part of the liquidity that exists: the rest is latent, waiting to be revealed at prices a large order has not yet reached.",
             sections=["Why impact is concave", "Latent liquidity and the locally linear book", "Fair pricing and the end of a metaorder", "Cross-impact", "Arbitrage-free cross-impact"],
             defines=["latent liquidity", "latent order book", "locally linear order book", "fair pricing condition", "cross-impact", "cross-impact matrix"],
             uses=["metaorder (B7.9)", "square-root impact law (B7.27)", "permanent impact (B7.27)", "propagator model (ch12)", "no-dynamic-arbitrage condition (ch12)",
                   "impact curve (ch11)", "Kyle model (ch4)", "covariance matrix (B4.22)", "principal component analysis (B4.22)", "factor model (B4.22)",
                   "order-flow imbalance (B7.8)"],
             strategies=[],
             tutorial="Simulate a latent-order-book market (reaction-diffusion of latent orders) and recover a square-root impact from its linear book; check the fair-pricing condition on metaorders of random length; estimate cross-impact on two correlated simulated assets and project it onto the arbitrage-free set. Data: simulated.",
             build="`firm.crossimpact`: latent-order-book simulator, fair-pricing check, cross-impact estimation (returns on order-flow imbalances, eigenliquidity decomposition), symmetrisation and positive-definite projection; Python.",
             problem="Selling the stock, moving its neighbour -- named result: the share of each asset's price move explained by the other asset's order flow, and the cost saved by a cross-impact-aware liquidation.",
             facts=["Donier, Bonart, Mastromatteo, Bouchaud 2015 a fully consistent, minimal model for non-linear market impact (QF)", "Farmer, Gerig, Lillo, Waelbroeck 2013 how efficiency shapes market impact (QF)", "Benzaquen, Mastromatteo, Eisler, Bouchaud 2017 dissecting cross-impact on stock markets (J. Stat. Mech.)", "Schneider and Lillo 2019 cross-impact and no-dynamic-arbitrage (QF)", "Pasquariello and Vega 2015 strategic cross-trading in the US stock market (Review of Finance)", "Bucci et al. 2019 crossover from linear to square-root market impact (PRL)"]),
    ]),
    ("part.mx.execution", [
        dict(slug="14-the-almgren-chriss-framework", title="The Almgren--Chriss Framework",
             hook="A trader must sell a million shares by the close. Selling them all now pays the impact; selling them evenly carries the price risk all day. Between the two lies a curve of schedules, and choosing a point on it is choosing a risk aversion.",
             sections=["Parent orders, child orders and a trajectory", "Costs: impact and risk", "The optimal trajectory in closed form", "The efficient trading frontier", "Calibration and limits"],
             defines=["parent order", "child order", "trading trajectory", "Almgren--Chriss model", "execution risk", "efficient trading frontier", "urgency"],
             uses=_U_IMPACT + _U_EXEC + ["mean--variance optimisation (B7.25)", "risk-aversion parameter (B7.25)", "certainty equivalent (B4.9)",
                                         "Hamilton--Jacobi--Bellman equation (B4.9)", "value function (B4.9)", "dynamic programming (B4.9)",
                                         "volume-weighted average price (B7.2)", "impact prefactor (ch11)"],
             strategies=[],
             tutorial="Implement the discrete and continuous Almgren-Chriss solutions; draw trajectories for several risk aversions and the efficient trading frontier; execute the schedules in firm.exchsim with an execution agent and compare the realised mean and variance of the shortfall with the model's. Data: simulated.",
             build="`firm.acexec`: discrete and continuous Almgren-Chriss trajectories, cost and variance, frontier, calibration of the impact parameters from firm.impactfit, and the common scheduler interface (target holdings per interval) that chapters 15, 16 and 28 plug their schedules into; Python.",
             problem="Liquidating a block by the close -- named result: the optimal trading horizon, expected cost and standard deviation for a given risk aversion, and the extra cost of a schedule that is twice too patient or twice too hurried.",
             facts=["Almgren and Chriss 2000 optimal execution of portfolio transactions (J. Risk)", "Bertsimas and Lo 1998 optimal control of execution costs (JFM)", "Almgren 2003 optimal execution with nonlinear impact functions and trading-enhanced risk (Applied Mathematical Finance)", "Kissell and Glantz 2003 Optimal Trading Strategies"]),
        dict(slug="15-beyond-almgren-chriss", title="Beyond Almgren--Chriss",
             hook="The Almgren-Chriss schedule does not look at the market while it trades. A trader who expects the price to fall in the next half-hour should sell faster; one whose impact decays should pause after a large trade; one whose market dries up at lunch should trade before it does.",
             sections=["Execution with a signal", "Adaptive schedules", "Transient impact and the optimal block", "Stochastic liquidity", "A control-theory template"],
             defines=["signal-adaptive schedule", "adaptive execution", "aggressive-in-the-money strategy", "bucket-shaped trajectory", "stochastic liquidity"],
             uses=["Almgren--Chriss model (ch14)", "trading trajectory (ch14)", "urgency (ch14)", "transient impact model (ch12)", "Obizhaeva--Wang model (ch12)",
                   "Hamilton--Jacobi--Bellman equation (B4.9)", "stochastic control problem (B4.9)", "value function (B4.9)", "dynamic programming (B4.9)",
                   "impulse control (B4.10)", "Ornstein--Uhlenbeck process (B4.4)", "Kalman filter (B4.19)", "execution coupling (B8.14)",
                   "implementation shortfall (B7.19)"],
             strategies=[],
             tutorial="Solve execution with an Ornstein-Uhlenbeck alpha signal in closed form (linear-quadratic), the Obizhaeva-Wang optimum with its blocks at both ends, and a stochastic-liquidity schedule by dynamic programming with Book 4's firm.dpsolve; run all three in firm.exchsim against Almgren-Chriss on common random numbers. Data: simulated.",
             build="`firm.execcontrol`: linear-quadratic execution with signals (Riccati), the Obizhaeva-Wang optimal schedule, adaptive (aggressive-in-the-money) rules, and a dynamic-programming wrapper for stochastic liquidity, all returning schedules in firm.acexec's scheduler interface; Python.",
             problem="Trading on a forecast -- named result: the basis points an alpha signal saves an execution schedule, against the signal's half-life and strength.",
             facts=["Obizhaeva and Wang 2013 (JFM)", "Almgren 2012 optimal trading with stochastic liquidity and volatility (SIFIN)", "Cartea and Jaimungal 2016 incorporating order-flow into optimal execution (Mathematics and Financial Economics)", "Cartea, Jaimungal, Penalva 2015 Algorithmic and High-Frequency Trading (CUP)", "Lorenz and Almgren 2011 mean-variance optimal adaptive execution (Applied Mathematical Finance)", "Gatheral and Schied 2011 optimal trade execution under geometric Brownian motion in the Almgren and Chriss framework (IJTAF)"]),
        dict(slug="16-benchmark-algorithms", title="Benchmark Algorithms",
             hook="Most institutional equity orders are handed to algorithms that promise a benchmark: the day's volume-weighted price, the arrival price, the close. Each promise is a schedule, and each schedule is only as good as its forecast of the day's volume.",
             sections=["The algorithms and their benchmarks", "Forecasting intraday volume", "VWAP: static and dynamic", "Participation and its feedback", "Implementation-shortfall and close algorithms"],
             defines=["execution algorithm", "VWAP algorithm", "TWAP algorithm", "participation algorithm", "implementation-shortfall algorithm", "target-close algorithm", "intraday volume forecast", "dynamic VWAP"],
             uses=["volume-weighted average price (B7.2)", "intraday volume profile (B7.5)", "percentage of volume (B7.27)", "VWAP slippage (B7.23)",
                   "implementation shortfall (B7.19)", "arrival price (B7.19)", "closing price (B1.13)", "market-on-close order (B1.13)",
                   "parent order (ch14)", "child order (ch14)", "Almgren--Chriss model (ch14)", "ARMA process (B4.17)", "principal component analysis (B4.22)"],
             strategies=[],
             tutorial="Forecast intraday volume on simulated days (static curve, rolling average, a PCA-plus-ARMA decomposition); run VWAP, TWAP, participation, shortfall and close algorithms in firm.exchsim; measure VWAP slippage from forecast error, and the feedback of a participation algorithm on a thin day. Data: simulated.",
             build="`firm.algos`: the benchmark algorithms as schedulers on firm.acexec's interface (static and dynamic VWAP, TWAP, participation with caps, shortfall via Almgren-Chriss, close with a market-on-close split) and the intraday volume forecaster; Python.",
             problem="VWAP on a day that was not average -- named result: the VWAP slippage explained by volume-forecast error, for static and dynamic VWAP, on the simulator's high-volume days.",
             facts=["Konishi 2002 optimal slice of a VWAP trade (JFM)", "Bialkowski, Darolles, Le Fol 2008 improving VWAP strategies: a dynamic volume approach (JBF)", "Humphery-Jenner 2011 optimal VWAP trading under noisy conditions (JBF)", "Madhavan 2002 VWAP strategies (Transaction Performance / Trading)", "Kissell 2013 The Science of Algorithmic Trading and Portfolio Management", "a broker's public algorithm guide (dated; only with a citable document)"]),
        dict(slug="17-child-order-placement", title="Child-Order Placement",
             hook="An algorithm must buy 800 shares in the next minute. It can join the queue at the bid and hope, or pay the spread now. Waiting saves half a spread if it fills and costs more than that if the price walks away while it waits.",
             sections=["The placement problem", "Passive against aggressive", "Queue management and repricing", "Placement as a Markov decision problem", "Learning a placement policy"],
             defines=["order placement problem", "non-execution risk", "clean-up trade", "repricing rule", "queue-aware placement"],
             uses=["limit order (ch1)", "market order (ch1)", "queue value (ch6)", "queue position (B7.18)", "passive fill probability (B7.18)",
                   "queue imbalance (B7.8)", "microprice (B7.8)", "child order (ch14)", "adverse selection (B1.1)", "dynamic programming (B4.9)",
                   "birth--death process (B4.8)", "reinforcement learning (B12.17, forward)"],
             strategies=[],
             tutorial="On firm.exchsim, compare placement policies for a one-minute slice (join the bid, step one tick behind, cross at once, imbalance-conditioned) by cost per share and its spread; solve the placement problem by dynamic programming on a birth-death book model; train a tabular Q-learning policy and compare it with the dynamic-programming one (forward pointer to Book 12). Data: simulated.",
             build="`firm.placement`: placement policies (static offsets, imbalance-conditioned, dynamic programming on a Markov book, a tabular Q-learning baseline), fill-probability models, repricing rules and a slice executor that plugs into firm.algos; Python.",
             problem="Join, step ahead or cross? -- named result: the expected cost per share of each placement policy, and the queue-imbalance threshold above which crossing at once is cheaper.",
             facts=["Cont and Kukanov 2017 optimal order placement in limit order markets (QF)", "Nevmyvaka, Feng, Kearns 2006 reinforcement learning for optimized trade execution (ICML)", "Harris and Hasbrouck 1996 market vs limit orders (JFQA)", "Lehalle and Mounjid 2017 (Market Microstructure and Liquidity)", "Huang, Lehalle, Rosenbaum 2015 simulating and analyzing order book data: the queue-reactive model (JASA)"]),
        dict(slug="18-smart-order-routing", title="Smart Order Routing",
             hook="A router splits an order across five venues. Sent at once, the pieces arrive microseconds apart, and quotes on the later venues vanish in between: the first fill told fast traders what was coming.",
             sections=["What a router decides", "Venue ranking and fill probabilities", "Aggressive routing and quote fade", "Passive allocation across venues", "Fee-aware routing and anti-gaming"],
             defines=["smart order router", "venue ranking", "spray order", "quote fade", "synchronised routing", "anti-gaming logic"],
             uses=["national best bid and offer (B1.9)", "intermarket sweep order (B1.9)", "order protection rule (B1.9)", "fee-adjusted price (ch7)",
                   "market fragmentation (ch8)", "protected quote (ch8)", "dark pool (B1.9)", "pinging order (ch9)", "information leakage (ch9)",
                   "passive fill probability (B7.18)", "market-data latency (B7.18)", "order-entry latency (B7.18)", "latency arbitrage (B11.9, forward)",
                   "convex optimisation problem (B4.23)"],
             strategies=[],
             tutorial="On the multi-venue firm.exchsim with fast liquidity providers who cancel on seeing a fill elsewhere, route an aggressive order by spray and by synchronised routing (sends timed to arrive together) and measure the fill ratio; allocate a passive order across venues by the Cont-Kukanov convex programme; add fees and a dark venue. Data: simulated.",
             build="`firm.sor`: a router with a venue model (fees, latency, fill probability, fade), aggressive sweep with arrival-time alignment, passive allocation (Cont-Kukanov), dark-first logic and anti-gaming rules; Python on the multi-venue simulator.",
             problem="The order that arrived after the quotes had gone -- named result: the fill ratio of a sweep with and without arrival-time alignment, and its fee-adjusted cost.",
             facts=["Cont and Kukanov 2017 (QF)", "Foucault and Menkveld 2008 competition for order flow and smart order routing systems (JF)", "Maglaras, Moallemi, Zheng 2021 optimal execution in a limit order book and an associated microstructure market impact model / or queueing model of routing (if cited)", "a public description of arrival-synchronised routing (patent or court record)", "Battalio, Corwin, Jennings 2016 (JF)"]),
        dict(slug="19-transaction-cost-analysis", title="Transaction-Cost Analysis",
             hook="A portfolio manager's order cost 25 basis points against the arrival price; the broker's report says it beat VWAP by three. Both numbers are right, and only one of them says what the order cost the fund.",
             sections=["Benchmarks and what each hides", "Pre-trade estimates", "Post-trade attribution", "Comparing across orders, brokers and peers", "Closing the loop"],
             defines=["pre-trade cost estimate", "execution benchmark", "slippage attribution", "post-trade reversion", "peer-universe comparison"],
             uses=_U_EXEC + ["delay cost (B7.23)", "opportunity cost (B7.23)", "VWAP slippage (B7.23)", "mark-out curve (B7.23)", "square-root impact law (B7.27)",
                             "VWAP algorithm (ch16)", "execution algorithm (ch16)", "impact prefactor (ch11)", "clustered standard errors (B4.16)",
                             "A/B test (B7.21)", "CUPED (B7.21)", "information leakage (ch9)"],
             strategies=[],
             tutorial="Generate a parent-order log in firm.exchsim with the algorithms of chapter 16 under varied parameters and market conditions; run TCA against every benchmark, attribute slippage to spread, impact, timing and opportunity, regress costs on size, volatility and participation with clustered errors, and read post-trade reversion as a leakage signal; compare with the pre-trade model. Data: simulated.",
             build="`firm.tca`: pre-trade model (on Book 7's firm.tcost), post-trade reports by benchmark, slippage attribution, reversion, difficulty-adjusted peer comparison with robust errors, and the feedback step that refits an algorithm's parameters; Python, on Book 7's firm.markout.",
             problem="Bad broker or hard day? -- named result: the difficulty-adjusted cost difference between two algorithms with its confidence interval, against the raw difference.",
             facts=["Perold 1988 the implementation shortfall: paper versus reality (JPM)", "Kissell 2013", "Frazzini, Israel, Moskowitz 2018", "Anand, Irvine, Puckett, Venkataraman 2012 performance of institutional trading desks (RFS)", "MiFID II RTS 27/28 and their suspension or deletion in the 2024 review (dated)", "FCA best execution thematic reviews (2014, 2017)"]),
        dict(slug="20-the-buy-side-trading-desk-and-its-brokers", title="The Buy-Side Trading Desk and Its Brokers",
             hook="A fund's trading desk sends its orders to six brokers' algorithms and pays each in commissions. Which broker is best cannot be seen in a quarter's data, so the desk lets a wheel choose, and measures.",
             sections=["What the desk does", "High touch and low touch", "Algo wheels", "Evaluating brokers", "Paying for research and execution"],
             defines=["high-touch trading", "low-touch trading", "algo wheel", "broker scorecard", "order management system", "execution management system", "commission sharing agreement", "research unbundling"],
             uses=["best execution (B1.11)", "broker (B1.4)", "sales-trader (B1.2)", "block trade (B1.2)", "indication of interest (ch9)", "execution algorithm (ch16)",
                   "transaction cost analysis (B7.23)", "peer-universe comparison (ch19)", "A/B test (B7.21)", "randomisation unit (B7.21)",
                   "minimum detectable effect (B7.21)", "power of a test (B4.12)"],
             strategies=[],
             tutorial="Simulate an algo wheel over six brokers with different true costs and order mixes; compare random allocation with performance-weighted allocation (Thompson sampling); estimate broker differences with the chapter 19 toolkit and compute how many months the desk needs to rank them. Data: simulated.",
             build="`firm.algowheel`: randomised and stratified allocation, difficulty-adjusted broker evaluation (on firm.tca), Thompson-sampling allocation, a broker scorecard; Python.",
             problem="Six brokers, one wheel -- named result: the months of flow needed to tell the best broker from the second with 80% power, with and without difficulty adjustment.",
             facts=["MiFID II research unbundling (2018) and the UK (FCA PS24/9) and EU (Listing Act 2024) re-bundling options (dated)", "SEC no-action relief on research payments and its expiry (dated)", "FCA thematic reviews of best execution", "Anand et al. 2012 (RFS)", "a public description of algo wheels (buy-side publication; dated, only if citable)"]),
        dict(slug="21-execution-beyond-equities", title="Execution Beyond Equities",
             hook="Buying the same amount of risk takes an order in an index future, a request for quote in bonds, a stream of last-look prices in currencies and a venue that never closes in crypto. The objective is the same shortfall; the market's rules change what the algorithm can do.",
             sections=["Futures: one book, implied liquidity, rolls", "FX: streams, last look and aggregation", "Bonds: requests for quote and portfolio lists", "Crypto: round the clock, rate limits and on-chain legs", "One order, four markets"],
             defines=["request for stream", "risk transfer price", "liquidity aggregator", "firm liquidity"],
             uses=["request for quote (B2.22)", "last look (B2.15)", "hold time (B2.15)", "reject rate (B2.15)", "streaming quote (B2.15)",
                   "benchmark fix (B2.17)", "fixing window (B2.17)", "all-to-all trading (B2.22)", "electronic communication network (B2.14)",
                   "calendar spread (B1.19)", "implied-in (B1.19)", "roll (B1.21)", "rate limit (B3.15)", "centralised exchange (B3.15)",
                   "automated market maker (B3.20)", "slippage tolerance (B3.22)", "funding rate (B3.17)", "implementation-shortfall algorithm (ch16)",
                   "mark-out (B2.15)"],
             strategies=[],
             tutorial="Execute the same parent order through execution adapters: an FX order on an aggregator of last-look liquidity providers (Book 2's firm.lastlook) against firm liquidity; a futures roll through outright and calendar-spread books with implied prices (firm.exchsim with Book 1's firm.match); a bond by request for quote to n dealers (Book 2's firm.rfq); a crypto order across a rate-limited venue and an AMM leg (Book 3's firm.amm). Data: simulated.",
             build="`firm.xexec`: execution adapters per market type (RFQ, streaming last-look aggregator, futures with implied books, rate-limited crypto venue, AMM routing) behind firm.acexec's scheduler interface; Python.",
             problem="One order, four markets -- named result: the all-in cost of the same risk transfer in futures, FX, bonds and crypto in the simulator, and the part of it each market's rule explains.",
             facts=["FX Global Code principle 17 (last look) as in Book 2", "BIS Triennial Survey 2025: FX execution methods (dated)", "Hendershott and Madhavan 2015 click or call? auction versus search in the over-the-counter market (JF)", "Oomen 2017 last look (QF)", "public statistics of electronic bond trading platforms from filings (dated)", "CME implied-price functionality (as in Book 1 ch. 19)"]),
        dict(slug="22-portfolio-trades-and-risk-bids", title="Portfolio Trades and Risk Bids",
             hook="A pension fund asks three brokers for a price at which they will take on a basket of five hundred stocks at tonight's close, knowing only its size, its sectors and its liquidity. The broker who wins learns the names afterwards, and learns whether it bid too much.",
             sections=["Agency and principal portfolio trades", "The cost of liquidating a basket", "Pricing a risk bid", "Blind bids and the winner's curse", "Transitions"],
             defines=["agency portfolio trade", "risk bid", "blind risk bid", "basket liquidity profile"],
             uses=["portfolio trade (B2.22)", "transition management (B8.29)", "central risk book (B9.25)", "risk pooling (B9.25)", "internal crossing (B7.27)",
                   "principal (B1.1)", "winner's curse (B2.30)", "factor model (B4.22)", "Almgren--Chriss model (ch14)", "cross-impact matrix (ch13)",
                   "square-root impact law (B7.27)", "closing price (B1.13)"],
             strategies=[],
             tutorial="Price a risk bid on a synthetic basket: its expected liquidation cost (multi-asset Almgren-Chriss with cross-impact and Book 7's firm.riskmodel), the price of the risk carried, and the winner's-curse adjustment against competing brokers; compare a disclosed and a blind bid. Data: simulated (firm.synthmkt names).",
             build="`firm.riskbid`: basket liquidity profile, multi-asset liquidation cost and risk, bid pricing with competition and information (winner's curse), a transition plan with internal crossing; Python.",
             problem="Pricing the basket blind -- named result: the bid in basis points for the disclosed and the blind basket, and the winner's-curse adjustment against three competitors.",
             facts=["Kavajecz and Keim 2005 packaging liquidity: blind auctions and transaction efficiencies (JFQA)", "Almgren and Chriss 2000 (multi-asset section)", "public descriptions of principal portfolio trading in equities or bonds (dated, only if citable)", "Bernstein / other transition-management references only if citable"]),
    ]),
    ("part.mx.dealer", [
        dict(slug="23-request-for-quote-and-dealer-markets-in-theory", title="Request-for-Quote and Dealer Markets in Theory",
             hook="A client who asks five dealers for a price on a corporate bond gets a better price than one who asks two, up to a point: every dealer asked learns that someone is selling, and the ones who lose the request can trade on it.",
             sections=["Search and bargaining", "Dealer networks", "The request for quote as an auction", "How many dealers to ask", "Relationships and information chasing"],
             defines=["over-the-counter search model", "search friction", "bargaining power", "core--periphery network", "information chasing"],
             uses=["request for quote (B2.22)", "winner's curse (B2.30)", "dealer-to-client platform (B2.4)", "inter-dealer broker (B2.4)", "all-to-all trading (B2.22)",
                   "common-value auction (B4.29)", "first-price auction (B4.29)", "Bayes--Nash equilibrium (B4.29)", "bid shading (B4.29)",
                   "information leakage (ch9)", "Poisson process (B4.6)", "continuous-time Markov chain (B4.8)"],
             strategies=[],
             tutorial="Solve the Duffie-Garleanu-Pedersen search model's steady state and prices; simulate request-for-quote competition with leakage (extending Book 2's firm.rfq) and find the client's cost-minimising number of dealers; let dealers chase informed flow and watch spreads by client type. Data: simulated.",
             build="`firm.otcsearch`: search-and-bargaining steady state and prices, RFQ auctions with private and common values, leakage and winner's curse, the optimal number of dealers, a core-periphery network simulator; Python (extends Book 2's firm.rfq by composition).",
             problem="How many dealers to ask -- named result: the cost-minimising number of dealers and its dependence on the leakage cost per losing dealer.",
             facts=["Duffie, Garleanu, Pedersen 2005 over-the-counter markets (Econometrica)", "Hendershott and Madhavan 2015 (JF)", "Riggs, Onur, Reiffen, Zhu 2020 swap trading after Dodd-Frank: evidence from index CDS (JFE)", "Li and Schurhoff 2019 dealer networks (JF)", "Di Maggio, Kermani, Song 2017 the value of trading relations in turbulent times (JFE)", "Hendershott, Li, Livdan, Schurhoff 2020 relationship trading in over-the-counter markets (JF)"]),
        dict(slug="24-market-quality-and-regulation", title="Market Quality and Regulation",
             hook="Twenty years of automation have narrowed spreads and multiplied messages, and regulators still disagree about whether markets are better for it. The evidence is abundant; what it measures, and what it cannot, is the subject of this chapter.",
             sections=["Measuring liquidity and market quality", "Algorithmic and high-frequency trading in the evidence", "The flash-crash literature", "Latency races and speed bumps in the evidence", "Rules on algorithms and order-to-trade ratios"],
             defines=["market quality", "algorithmic trading", "high-frequency trading", "order-to-trade ratio", "hot-potato trading"],
             uses=["flash crash (B1.31)", "stub quote (B1.31)", "limit up--limit down (B1.31)", "effective spread (B1.10)", "realised spread (B1.10)",
                   "Rule 605 report (B1.10)", "Amihud illiquidity (B7.7)", "Kyle's lambda (B7.9)", "VPIN (B7.9)", "market maker (B1.1)",
                   "book resilience (ch3)", "quoted spread (ch5)", "difference-in-differences (ch6)", "frequent batch auction (ch10)",
                   "latency arbitrage (B11.9, forward)", "speed bump (B11.9, forward)", "clustered standard errors (B4.16)", "spoofing (B9.29)"],
             strategies=[],
             tutorial="Build a panel of market-quality measures on simulated stock-days with and without fast liquidity providers (firm.exchsim with the tape's background flow); plant a regulatory change on half the stocks and estimate it by difference-in-differences with clustered errors; show the wrong answer without a control group. Data: simulated; SEC MIDAS metrics.",
             build="`firm.mktquality`: liquidity and market-quality measures on a stock-day panel (quoted, effective and realised spreads, depth, price impact, Amihud, variance ratios, resilience, order-to-trade ratio), event studies and difference-in-differences with clustered errors; Python (statsmodels).",
             problem="Did the rule make the market better? -- named result: the difference-in-differences estimate of a planted change in spreads with its standard error, against the before-after estimate that ignores the control group.",
             facts=["CFTC-SEC 2010 findings regarding the market events of May 6, 2010", "Kirilenko, Kyle, Samadi, Tuzun 2017 the flash crash: HFT in an electronic market (JF)", "Hendershott, Jones, Menkveld 2011 does algorithmic trading improve liquidity? (JF)", "Brogaard, Hendershott, Riordan 2014 high-frequency trading and price discovery (RFS)", "Menkveld 2013 high frequency trading and the new market makers (JFM)", "Aquilina, Budish, O'Neill 2022 quantifying the high-frequency trading arms race (QJE)", "MiFID II article 4(1)(39)-(40) definitions of algorithmic and high-frequency algorithmic trading; RTS 6; RTS 9 order-to-trade ratio (dated)", "SEC 2010 concept release on equity market structure"]),
        dict(slug="25-circuit-breakers-and-halts", title="Circuit Breakers and Halts",
             hook="On 9 March 2020 the S&P 500 fell seven per cent minutes after the open and all US equity trading stopped for fifteen minutes; it happened three more times that month. Whether stopping a falling market calms it or makes it fall faster toward the stop is an old argument with new data.",
             sections=["Designs: bands, pauses, halts, limits", "Single-stock and market-wide mechanisms", "Futures: velocity logic and stop logic", "Magnet effects in the evidence", "Reopening"],
             defines=["static price band", "dynamic price band", "trading pause", "reopening auction", "velocity logic"],
             uses=["limit up--limit down (B1.31)", "market-wide circuit breaker (B1.31)", "volatility interruption (B1.13)", "price limit (B1.12)",
                   "trading halt (B8.17)", "magnet effect (B8.18)", "limit-locked market (B3.9)", "clearly erroneous trade (B1.31)", "call auction (B1.13)",
                   "flash crash (B1.31)", "auction collar (ch10)", "stop order (ch2)"],
             strategies=[],
             tutorial="Add bands, pauses and a market-wide halt to firm.exchsim through firm.halts; run a crash scenario with agents who accelerate their selling near a band, and measure the magnet effect: the probability of reaching the limit against the distance to it, with and without the mechanism; replay the pause with Book 1's firm.replay monitors. Data: simulated; published trigger events.",
             build="`firm.halts`: static and dynamic bands, LULD-style limit states and pauses, market-wide levels, velocity logic, and the reopening through firm.auctionsim, as the module firm.exchsim loads; Python.",
             problem="Fifteen minutes of silence -- named result: the probability of reaching the band conditional on the distance to it, with and without the band, and the size of the simulated magnet effect.",
             facts=["NYSE / SEC market-wide circuit breaker triggers of March 2020 (dates, times, levels)", "LULD plan and its amendments (dated)", "CME Globex velocity logic and stop spike logic documentation (dated)", "Subrahmanyam 1994 circuit breakers and market volatility: a theoretical perspective (JF)", "Cho, Russell, Tiao, Tsay 2003 the magnet effect of price limits (J. Empirical Finance)", "Brugler, Linton, Noss, Pedace 2018 or a published study of single-stock halts", "Eurex / Xetra volatility interruption and static/dynamic bands (dated)"]),
    ]),
    ("part.mx.builds", [
        dict(slug="26-build-a-matching-engine-and-exchange-simulator", title="Build: a Matching Engine and Exchange Simulator",
             hook="Every tutorial in the books that follow needs a venue: something that accepts orders, matches them, publishes what happened in a feed that can drop packets, and does exactly the same thing every time it is run with the same inputs.",
             sections=["What an exchange does, in messages", "The matching engine", "The market-data feed: sequencing, redundancy, recovery", "The order-entry protocol and its sessions", "Clock, latency and determinism"],
             defines=["exchange simulator", "order-entry protocol", "order-entry session", "execution report", "self-trade prevention", "cancel on disconnect", "redundant feed lines", "snapshot recovery", "retransmission request"],
             uses=["matching engine (ch1)", "limit order book (ch1)", "order-book event (ch1)", "time in force (ch2)", "iceberg order (ch2)", "pegged order (ch2)",
                   "price-time priority (B1.19)", "pro-rata allocation (B1.19)", "top-order allocation (B1.19)", "market-by-order (B1.19)",
                   "sequence number (B1.28)", "exchange timestamp (B1.28)", "receive timestamp (B1.28)", "market data feed (B1.4)",
                   "order lifecycle (B7.17)", "simulated clock (B7.17)", "latency model (B7.18)", "order-entry latency (B7.18)",
                   "market-data latency (B7.18)", "order-book replay (B7.18)", "call auction (B1.13)", "uncrossing price (B1.13)", "trading pause (ch25)",
                   "rate limit (B3.15)", "snapshot-and-delta feed (B3.26)", "book checksum (B3.26)", "counter-based generator (B4.26)",
                   "feed handler (B13.18, forward)", "line arbitration (B13.16, forward)"],
             strategies=[],
             tutorial="Start firm.exchsim in process, connect a Python client through the byte-stream transport, send orders and read the execution reports; drop packets on line A and recover from line B, then from a snapshot; run the same inputs through the C++20 and Rust engines and check byte-identical feeds; start the C++20 server on localhost and trade on it from Python; measure throughput on this laptop. Data: none (deterministic scenarios and the tape's background flow).",
             build="`firm.exchsim`: the exchange simulator -- matching engine (on firm.lob and firm.ordertypes, allocation by Book 1's firm.match), trading phases and auctions (firm.auctionsim), halts (firm.halts), fees, sequenced binary market-data feed (superset of Book 1's firm.feed layout) on two redundant lines with snapshot and retransmission channels, binary order-entry protocol with sessions, throttles, self-trade prevention and cancel-on-disconnect, deterministic clock and latency model, multi-venue harness, tape export for Book 7's tools; Python reference, C++20 engine, codecs and localhost server, Rust engine and codecs; acceptance tests: conformance scenarios, three-language byte-identity on a fixture, determinism by hash, recovery under packet loss.",
             problem="Certification day -- named result: the conformance suite passed by each engine, the byte-identity of the three engines' feeds on the fixture, and the engines' messages per second measured on this laptop.",
             facts=["Nasdaq TotalView-ITCH 5.0 specification (message layouts, sequencing via MoldUDP64)", "Nasdaq OUCH order-entry specification (dated)", "Nasdaq MoldUDP64 and SoupBinTCP specifications", "CME MDP 3.0: A and B feeds, snapshot recovery, packet sequence numbers (dated; via the client-systems wiki)", "CME iLink 3 / self-match prevention and cancel on disconnect functionality (dated)", "FIX Trading Community Simple Binary Encoding standard", "LSEG / Cboe binary order-entry specifications for comparison (dated)"]),
        dict(slug="27-build-an-agent-based-market", title="Build: an Agent-Based Market",
             hook="An exchange simulator with nobody on it is an empty room. Populated with a few kinds of simple traders -- some who know nothing, some who know the value, some who follow trends and some who make markets -- it starts to look like a market, and which of them it needs to look like one is itself a finding.",
             sections=["Agents and their information", "Liquidity providers and their inventory", "Execution agents and metaorders", "Calibrating to stylised facts", "What agent-based markets can and cannot tell you"],
             defines=["agent-based model", "fundamentalist agent", "chartist agent", "market-making agent", "method of simulated moments"],
             uses=["exchange simulator (ch26)", "zero-intelligence model (ch1)", "informed trader (ch4)", "noise trader (ch4)", "stylised fact (B7.5)",
                   "fleeting order (ch3)", "book resilience (ch3)", "metaorder (B7.9)", "square-root impact law (B7.27)", "Hawkes process (B4.7)",
                   "calibration (B4.24)", "method of moments (B4.11)", "depth profile (B7.8)", "order-sign autocorrelation (B7.9)",
                   "Glosten--Milgrom model (ch4)", "inventory (B2.30)"],
             strategies=[],
             tutorial="Populate firm.exchsim with agents (zero-intelligence noise, informed on a hidden value, fundamentalists and chartists, inventory-skewing market makers, execution agents with metaorders); run a day; check the stylised facts with firm.lobstats; calibrate the population by the method of simulated moments; switch each agent type off in turn to see which fact it carries. Data: simulated.",
             build="`firm.agentmkt`: the agent library and population runner on firm.exchsim (deterministic, seeded per agent), with a calibration routine and output in the firm.tape format, so that Book 7's tools and the tutorials of Books 11 and 12 run on it; Python.",
             problem="A market that looks like a market -- named result: the distance between simulated and target stylised facts after calibration, and the fact each agent type is responsible for (ablation).",
             facts=["Chiarella and Iori 2002 a simulation analysis of the microstructure of double auction markets (QF)", "Farmer, Patelli, Zovko 2005 the predictive power of zero intelligence in financial markets (PNAS)", "Lux and Marchesi 1999 scaling and criticality in a stochastic multi-agent model of a financial market (Nature)", "Franke and Westerhoff 2012 structural stochastic volatility in asset pricing dynamics: estimation and model contest (JEDC)", "Byrd, Hybinette, Balch 2020 ABIDES (ACM SIGSIM PADS)", "Vyetrenko et al. 2020 get real: realism metrics for robust limit order book market simulations (ICAIF)"]),
        dict(slug="28-build-an-execution-algorithm", title="Build: an Execution Algorithm",
             hook="A trader hands the algorithm an order to buy 200,000 shares by three o'clock with a limit price. Everything the book has built -- the schedule, the placement, the routing, the measurement -- has to run at once, and to keep running when the market does something the design did not expect.",
             sections=["The algorithm as a state machine", "Schedule, placement and routing together", "Limits, pauses and exceptions", "Measuring it", "Rolling it out"],
             defines=["I-would price", "participation band"],
             uses=["implementation-shortfall algorithm (ch16)", "execution algorithm (ch16)", "Almgren--Chriss model (ch14)", "urgency (ch14)",
                   "order placement problem (ch17)", "smart order router (ch18)", "pre-trade cost estimate (ch19)", "slippage attribution (ch19)",
                   "exchange simulator (ch26)", "agent-based model (ch27)", "transaction cost analysis (B7.23)", "A/B test (B7.21)",
                   "canary deployment (B7.21)", "kill criterion (B7.1)", "trading pause (ch25)"],
             strategies=[],
             tutorial="Assemble firm.execalgo from chapter 14's schedule, chapter 17's placement and chapter 18's router; run 200 parent orders in firm.exchsim populated by firm.agentmkt; measure them with firm.tca; test the algorithm against a TWAP baseline in a simulated A/B test, and through a halt and a volatility spike. Data: simulated.",
             build="`firm.execalgo`: a complete implementation-shortfall algorithm (scheduler, placement, router, limit and I-would prices, participation band, pause and resume on halts, cancel on kill, parameter interface, audit log) trading through firm.exchsim's order-entry client, measured with firm.tca; Python.",
             problem="Beat TWAP by how much? -- named result: the shortfall saved against TWAP in basis points with its confidence interval, and its dependence on urgency and order size.",
             facts=["Almgren and Chriss 2000", "Perold 1988", "Kissell 2013", "SEC Market Access Rule 15c3-5 pre-trade controls (as a design requirement; dated)"]),
    ]),
]
