"""Book 11 (Market Making and High-Frequency Trading) chapter briefs: data for tools/make_briefs.py --book 11.

`uses` lists terms defined elsewhere that the chapter relies on (not redefined); owners in parentheses:
(B7.23) = One Quant Book 7, chapter 23, checked against the multi-line \\index{} harvest of Books 1-9 on
2026-09-25 (2,103 terms); (B10.26) = a batch book, by its outline (to be confirmed at the sync); (ch3) = an earlier
chapter of this book.

Ownership. Books 1-9 keep their terms. Book 1 owns the market-structure vocabulary a market maker lives in (market
maker, bid-ask spread, adverse selection, maker-taker pricing, inverted venue, volume tier, designated and lead market
maker, quoting obligation, quote protection, payment for order flow, wholesaler, internalisation, price improvement,
the auction terms, depositary receipt, dual listing, the ETF primary-market terms, pro-rata allocation, implied-in and
implied-out, fair value of a future); Book 2 owns last look, hold time, quote skewing, streaming quote, liquidity
tier, mark-out, request for quote, all-to-all trading, axe, portfolio trade, winner's curse, width, inventory; Book 3
owns the crypto and on-chain terms (funding rate, perpetual future, liquidation terms, rate limit, cross-venue
arbitrage, CEX-DEX arbitrage, searcher, block builder, transaction bundle, just-in-time liquidity, loss-versus-
rebalancing, sandwich attack, the betting-market terms); Book 4 owns the control, point-process, queue and
high-frequency econometrics terms; Book 5 owns the options market-making terms (theoretical value, vega bucket,
hedging band, dividend play, box spread); Book 7 owns microprice, the order-book and trade-flow features, lead-lag,
queue position, the latency model and the market-making P&L decomposition; Book 8 owns intraday alpha, machine-
readable news, daily P&L attribution; Book 9 owns index arbitrage, client tiering, axe-driven skew, franchise P&L,
the manipulation patterns (spoofing, layering, momentum ignition, marking the close) and the sandwiching strategy
file. Within the batch (sources/BATCH_BOOKS_10-13.md): Book 10 owns the microstructure, price-impact, execution, fee
and venue mechanisms as the market sees them and the exchange simulator (large-tick asset, effective tick, imbalance
publication, the sequential-trade model); Book 12 owns reinforcement learning; Book 13 owns the software side of the
quoting engine, gateway and pre-trade risk. This book owns the market-making and high-frequency strategy terms and
the risk-control policy of an algorithmic firm; the contested terms are listed in sources/hft/PROGRESS.md.

Strategy files (section 6.3 of WRITING_A_QUANT_BOOK.md): 75, the outline's bracketed counts in chapters 7-9 and
12-26. Overlaps with written books are resolved by angle, not repeated: Book 9 ch. 26's minute-level index arbitrage
against this book's partial-basket and cross-listed arbitrage at the tick (ch. 13); Book 9 ch. 24's bank flow desk
against this book's non-bank electronic FX liquidity provision (ch. 21); Book 9 ch. 19's portfolio-trade liquidity
provision and Book 9 ch. 29's sandwiching file are pointed to, not rewritten (ch. 22, ch. 25); Book 8 ch. 10, 13 and
17's close and news strategies at the day and minute scale against this book's sub-second versions (ch. 16, ch. 18).

Running project (code/firm/, all new and unique; checked against the 265 existing): mmharness (the strategy harness
every tutorial runs through: firm_tape's agent API now, Book 10's exchange simulator when it lands) and mmecon (ch1),
fairprice (ch2), invmm (ch3), multimm (ch4), qreactive (ch5), toxicity (ch6), hfalpha (ch7), xvenue (ch8), latrace
(ch9), quoteengine (ch10), mmhedge (ch11), etfmm (ch12), basketarb (ch13), drarb (ch14), futmm (ch15), auctionmm
(ch16), rebatemm (ch17), newsrace (ch18), optquoter (ch19), optarb (ch20), fxlp (ch21), rfqmm (ch22), wholesale (ch23),
cryptohft (ch24), searcher (ch25), sportsmm (ch26), riskctl (ch27), mmattrib (ch28), venueprofile (ch29). Python;
fairprice's streaming core and quoteengine also in C++20 and Rust.
"""
SLUG = "hft"
PFX = "hf"
HEAD = "One Quant Book 11 — Market Making and High-Frequency Trading"

_U_MM = ["market maker (B1.1)", "bid--ask spread (B1.1)", "adverse selection (B1.1)", "mid price (B1.1)",
         "inventory (B2.30)"]
_U_MEAS = ["mark-out curve (B7.23)", "spread capture (B7.23)", "adverse-selection cost (B7.23)",
           "inventory P\\&L (B7.23)", "fill rate (B7.23)"]
_U_SIM = ["queue position (B7.18)", "latency model (B7.18)", "order-book replay (B7.18)",
          "exchange simulator (B10.26)"]
_U_ARB = ["law of one price (B5.1)", "transaction cost analysis (B7.23)", "implementation shortfall (B7.19)"]

PARTS = [
    ("part.hf.core", [
        dict(slug="01-the-business-of-market-making", title="The Business of Market Making",
             hook="A listed electronic market maker reports its trading income per day to the cent, and the same filing shows what the machines, the data and the exchange memberships that earn it cost; divided by the volume it trades, the revenue per share is a fraction of a cent.",
             sections=["What a market maker sells", "Revenue: capture per unit traded, volume, volatility", "Costs: inventory, adverse selection, fees, technology, people", "What the public statements reveal", "The shape of the business: fixed costs and scale"],
             defines=["electronic market maker", "revenue capture"],
             uses=_U_MM + ["high-frequency trading (B10.24)", "algorithmic trading (B10.24)", "proprietary trading firm (B1.1)", "maker-taker pricing (B1.9)", "designated market maker (B1.29)", "net capture (B1.1)", "P\\&L attribution (B1.7)"] + _U_MEAS,
             tutorial="Build firm.mmecon and read two public market makers' annual figures (trading income per day, volume, cost lines) into a unit-economics table; then run a first market maker through firm.mmharness on firm_tape and decompose its day into capture, adverse selection, fees and inventory.",
             build="`firm.mmharness` (the strategy harness: a `Quoter` protocol with on_market / on_fill / on_timer, run on firm_tape's agent API now and on Book 10's exchange simulator later, with a common fill log) and `firm.mmecon` (unit economics: capture per share, break-even volume, fixed-cost leverage); Python.",
             problem="A fraction of a cent — named result: the break-even daily volume of a small market maker at a given capture and cost base, and its operating leverage.",
             facts=["Virtu Financial 10-K FY2025: trading income, adjusted net trading income per day, segment data, costs (dated)", "Flow Traders annual report 2025: net trading income, value traded (dated)", "Menkveld 2013 High frequency trading and the new market makers (JFM)", "Baron, Brogaard, Hagstromer, Kirilenko 2019 Risk and return in high-frequency trading (JFQA)", "Brogaard, Hendershott, Riordan 2014 High-frequency trading and price discovery (RFS)"]),
        dict(slug="02-fair-value", title="Fair Value",
             hook="The same stock quotes on a dozen venues, its future trades in Chicago and its ETF in New Jersey; the market maker's price is none of these quotes but its own estimate, updated on every message from any of them.",
             sections=["Mid, weighted mid and microprice as estimators", "Fair price across venues", "Fair price across instruments", "Filtering: the fair price as a state", "Evaluating a fair price"],
             defines=["fair price", "consolidated fair price", "cross-instrument fair price", "fair-price filter"],
             uses=["microprice (B7.8)", "weighted mid price (B7.8)", "queue imbalance (B7.8)", "Kalman filter (B4.19)", "microstructure noise (B4.21)", "national best bid and offer (B1.9)", "fair value (B1.21)", "lead--lag relationship (B7.10)"] + _U_MM,
             tutorial="On firm_tape's paired instruments (simulate_pair) and a synthetic multi-venue book, build weighted-mid, microprice, venue-weighted and Kalman fair prices and score each as a forecast of the efficient price and of the mid a few seconds later.",
             build="`firm.fairprice`: streaming fair-price estimators (weighted mid, microprice table, consolidated across venues with staleness weights, cross-instrument Kalman filter) with a common `update(event) -> price` interface; Python, streaming core in C++20 and Rust checked on one fixture.",
             problem="Whose price is it — named result: the forecast error of each estimator against the efficient price, and the share of the improvement that comes from the second instrument.",
             facts=["Stoikov 2018 The micro-price (QF)", "Cartea, Jaimungal, Penalva 2015 Algorithmic and High-Frequency Trading (CUP)", "Gatheral and Oomen 2010 zero-intelligence realized variance estimation (F&S) or equivalent on noise"]),
        dict(slug="03-inventory-models", title="Inventory Models",
             hook="A market maker who has just bought three times in a row owns stock nobody has yet asked for; lowering both quotes a little makes the next trade more likely to be a sale, and the question is by how much.",
             sections=["The market maker's control problem", "The Avellaneda--Stoikov model", "Reservation price and optimal spread", "Closed forms, their limits, and a numerical solution", "Simulating the policy"],
             defines=["Avellaneda--Stoikov model", "reservation price", "fill intensity", "inventory penalty"],
             uses=["Hamilton--Jacobi--Bellman equation (B4.9)", "value function (B4.9)", "stochastic control problem (B4.9)", "CRRA utility (B4.9)", "certainty equivalent (B4.9)", "Poisson process (B4.6)", "quote skewing (B2.15)"] + _U_MM + _U_MEAS,
             tutorial="Solve the Avellaneda--Stoikov control problem on a grid with firm.dpsolve, compare it with the closed-form approximations, then run the policy as a Quoter in firm.mmharness on firm_tape and measure inventory, capture and P&L against a symmetric quoter.",
             build="`firm.invmm`: the Avellaneda--Stoikov and Cartea--Jaimungal quoting policies (closed form and numerical HJB), fill-intensity estimation from a quoter's own fills, a Poisson-fill simulator for fast policy studies; Python.",
             problem="Three buys in a row — named result: the P&L and inventory variance of the optimal quoter against the symmetric one, and the risk aversion at which they diverge.",
             facts=["Avellaneda and Stoikov 2008 High-frequency trading in a limit order book (QF)", "Ho and Stoll 1981 Optimal dealer pricing under transactions and return uncertainty (JFE)", "Cartea, Jaimungal, Ricci 2014 Buy low, sell high (SIAM JFM)", "Gueant 2016 The Financial Mathematics of Market Liquidity (CRC)"]),
        dict(slug="04-extensions-of-the-inventory-framework", title="Extensions of the Inventory Framework",
             hook="The closed form tells a quoter to quote a negative spread when it is long enough; real market makers stop buying instead, hold several correlated books at once, and know that the next trade is more likely to come from someone who knows more than they do.",
             sections=["Inventory bounds and the asymptotic solution", "Many assets and correlated inventory", "Signals and drift inside the control problem", "Adverse selection inside the fill intensity"],
             defines=["inventory bound", "multi-asset market making", "drift-adjusted quoting"],
             uses=["Avellaneda--Stoikov model (ch3)", "reservation price (ch3)", "fill intensity (ch3)", "covariance matrix (B4.22)", "Hamilton--Jacobi--Bellman equation (B4.9)"] + _U_MM,
             tutorial="Implement the Gueant--Lehalle--Fernandez-Tapia asymptotic quotes with an inventory bound, extend to two correlated assets, add a drift signal, and compare all policies on common random numbers in firm.invmm's fast simulator and in firm.mmharness.",
             build="`firm.multimm`: bounded-inventory asymptotic quotes, the multi-asset reservation price and quotes, drift-adjusted and adverse-selection-adjusted policies; Python.",
             problem="Two books, one risk — named result: the reduction in inventory risk from quoting two correlated assets jointly, at equal expected capture.",
             facts=["Gueant, Lehalle, Fernandez-Tapia 2013 Dealing with the inventory risk (MFE)", "Gueant 2017 Optimal market making (Applied Mathematical Finance)", "Cartea and Wang 2020 Market making with alpha signals (IJTAF)", "Cartea, Donnelly, Jaimungal 2017 Algorithmic trading with model uncertainty (SIAM JFM)"]),
        dict(slug="05-queue-reactive-models-and-large-tick-assets", title="Queue-Reactive Models and Large-Tick Assets",
             hook="On a stock whose spread is one tick nearly all day, every market maker quotes the same prices; what separates them is where they stand in the queue, and an order at the front of a long queue is worth money before it trades.",
             sections=["The large-tick regime", "Queue-reactive intensities", "The value of a place in the queue", "When to join and when to leave", "Queue-reactive simulation"],
             defines=["queue-reactive model", "queue-join rule", "queue-exit rule"],
             uses=["queue value (B10.6)", "large-tick asset (B10.6)", "small-tick asset (B10.6)", "queue imbalance (B7.8)", "queue depletion rate (B7.8)", "queue-position model (B7.18)", "birth--death process (B4.8)", "price-time priority (B1.19)"] + _U_SIM,
             tutorial="Estimate state-dependent add, cancel and trade intensities on firm_tape (large-tick configuration), simulate the queue-reactive model, and value a queue slot by its expected spread capture less adverse selection as a function of position and queue sizes.",
             build="`firm.qreactive`: queue-reactive intensity estimation and simulation (Huang--Lehalle--Rosenbaum), queue value by position, a join/leave rule tested in firm.mmharness; Python.",
             problem="Front of the line — named result: the value of the first place in a queue against the tenth, in ticks, and the imbalance at which leaving beats staying.",
             facts=["Huang, Lehalle, Rosenbaum 2015 Simulating and analyzing order book data: the queue-reactive model (JASA)", "Moallemi and Yuan 2017 A model for queue position valuation in a limit order book (working paper / MS)", "Cont, Stoikov, Talreja 2010 A stochastic model for order book dynamics (OR)", "Dayri and Rosenbaum 2015 Large tick assets: implicit spread and optimal tick size (MMF)"]),
        dict(slug="06-adverse-selection-and-toxicity", title="Adverse Selection and Toxicity",
             hook="A market maker's fills from one counterparty class lose half a tick five seconds later on average, and from another they gain; the quotes are the same for both until the desk decides they should not be.",
             sections=["Mark-outs by counterparty, venue and order type", "Detecting informed flow", "Toxicity scores", "Responses: widen, fade, skew, refuse", "Toxicity is not permanent"],
             defines=["toxicity score", "defensive widening"],
             uses=["quote fade (B10.18)", "flow toxicity (B7.9)", "VPIN (B7.9)", "mark-out (B2.15)", "client tiering (B9.24)", "order-flow imbalance (B7.8)", "trade sign (B7.9)"] + _U_MM + _U_MEAS,
             tutorial="Run a quoter in firm.mmharness against firm_tape flow with informed and noise traders, compute mark-out curves by counterparty class, venue-like order type and time of day, build a toxicity score and test widening and fading against a flat policy on common random numbers.",
             build="`firm.toxicity`: grouped mark-outs with standard errors, a sequential toxicity score (Bayesian update of the informed share), fade and widen responses as Quoter wrappers; Python, on firm.markout.",
             problem="Who is on the other side — named result: the change in capture and in adverse-selection cost when quotes are faded on a high toxicity score, and the fills given up.",
             facts=["Easley, Lopez de Prado, O'Hara 2012 Flow toxicity and liquidity in a high-frequency world (RFS)", "Battalio, Corwin, Jennings 2016 Can brokers have it all? (JF)", "O'Hara 2015 High frequency market microstructure (JFE)", "Andersen and Bondarenko 2014 VPIN and the flash crash (JFM)"]),
        dict(slug="07-short-horizon-alpha", title="Short-Horizon Alpha",
             hook="The bid queue is three times the ask queue and the futures ticked up two milliseconds ago; a market maker who ignores both will sell at the ask to someone who did not.",
             sections=["What predicts the next second", "Building the forecast: book, flow, cross-asset", "Horizon, decay and evaluation at high frequency", "Coupling the forecast to quotes: skew", "When to take instead of make"],
             defines=["short-horizon alpha", "forecast skew", "take threshold"],
             uses=["order-flow imbalance (B7.8)", "queue imbalance (B7.8)", "microprice (B7.8)", "futures-to-cash lead (B7.10)", "information coefficient (B7.6)", "signal half-life (B7.13)", "intraday alpha (B8.14)", "prediction horizon (B8.14)"] + _U_MM + _U_MEAS,
             strategies=["book-imbalance quote skew", "order-flow-imbalance taking", "trade-sign continuation", "futures-led quoting", "post-sweep reversion"],
             tutorial="Build a seconds-horizon forecast from firm.lobfeat features and the paired instrument's returns on firm_tape, evaluate it out of sample, and couple it to a quoter as a skew and a take threshold; measure the P&L of each coupling rerun a tick later.",
             build="`firm.hfalpha`: event-time forecast targets, feature assembly from firm.lobfeat and firm.tradeflow, ridge forecasts with decay by horizon, skew and take-threshold couplings as Quoter wrappers; Python.",
             problem="Three to one on the bid — named result: the capture per share of the forecast-skewed quoter against the unskewed one, and the fraction lost when the forecast arrives one message late.",
             facts=["Cont, Kukanov, Stoikov 2014 The price impact of order book events (JFEc)", "Kolm, Turiel, Westray 2023 Deep order flow imbalance (Math Finance)", "Cartea, Donnelly, Jaimungal 2018 Enhancing trading strategies with order book signals (AMF)", "Lehalle and Mounjid 2017 Limit order strategic placement with adverse selection risk and the role of latency (MMF)"]),
        dict(slug="08-lead-lag-and-cross-venue-trading", title="Lead--Lag and Cross-Venue Trading",
             hook="When the index future moves, the ETF follows within milliseconds and the constituent stocks within a little more; who leads depends on the hour, the venue and the size of the move, and it has changed as the fastest firms have caught up.",
             sections=["Price discovery across markets", "Information shares", "Estimating lag on asynchronous ticks", "Trading the lead: quoting and taking", "When the leader changes"],
             defines=["cross-venue lead"],
             uses=["information share (B10.8)", "component share (B10.8)", "lead--lag relationship (B7.10)", "lead--lag estimator (B7.10)", "Hayashi--Yoshida estimator (B4.21)", "Epps effect (B4.21)", "cointegration (B4.20)", "vector error-correction model (B4.20)", "futures-to-cash lead (B7.10)", "primary venue (B2.14)"] + _U_MM,
             strategies=["index future to ETF", "ETF to constituents", "cash Treasury to Treasury futures", "leading crypto venue to lagging venue", "primary FX venue to secondary platforms"],
             tutorial="Measure Hayashi--Yoshida lead-lag and Hasbrouck information shares on firm_tape pairs with known latency, recover the planted lag, then trade the lead as a quoter and as a taker with execution latency in firm.mmharness.",
             build="`firm.xvenue`: information and component shares from a vector error-correction fit, lag estimation on firm.leadlag, a lead-follower simulator with per-venue latency; Python.",
             problem="Who moves first — named result: the planted and estimated lead, the leader's information share, and the P&L of trading the lead at the latency where it disappears.",
             facts=["Hasbrouck 1995 One security, many markets (JF)", "Gonzalo and Granger 1995 Estimation of common long-memory components in cointegrated systems (JBES)", "Hasbrouck 2003 Intraday price formation in US equity index markets (JF)", "Huth and Abergel 2014 High frequency lead/lag relationships -- empirical facts (JEF)", "Makarov and Schoar 2020 Trading and arbitrage in cryptocurrency markets (JFE)"]),
        dict(slug="09-latency-arbitrage-and-its-defence", title="Latency Arbitrage and Its Defence",
             hook="A quote that was right a millisecond ago is still resting on one venue after the price has moved on another; the first firm to reach it wins a riskless tick, and the loser of the race is the market maker who left it there.",
             sections=["Stale quotes and races", "The evidence: races, their size and who wins", "Defence by the market maker", "Defence by the venue: speed bumps, asymmetric delays, batch auctions", "Last look as a defence"],
             defines=["latency arbitrage", "latency race", "stale-quote sniping", "speed bump", "asymmetric speed bump"],
             uses=["frequent batch auction (B10.10)", "last look (B2.15)", "hold time (B2.15)", "national best bid and offer (B1.9)", "order protection rule (B1.9)", "market-data latency (B7.18)", "order-entry latency (B7.18)", "cross-venue lead (ch8)"] + _U_MM,
             strategies=["cross-venue stale-quote sniping", "futures-led sniping of equity quotes", "liquidity provision behind an asymmetric speed bump", "defensive quote cancellation on a lead signal"],
             tutorial="Simulate races between a liquidity provider and snipers with latency distributions on a two-venue market (firm_tape pair now, Book 10's simulator later); measure the provider's loss to sniping, then add a speed bump, an asymmetric delay and a batch auction and measure again.",
             build="`firm.latrace`: race simulation with per-agent latency distributions, venue delays (symmetric, asymmetric for takers) and a periodic batch-auction venue; the sniping tax on liquidity providers; Python.",
             problem="The race nobody sees — named result: the latency-arbitrage tax as a share of the provider's spread, with and without each venue defence.",
             facts=["Budish, Cramton, Shim 2015 The high-frequency trading arms race (QJE)", "Aquilina, Budish, O'Neill 2022 Quantifying the high-frequency trading arms race (QJE)", "Baldauf and Mollner 2020 High-frequency trading and market performance (JF)", "SEC approval of IEX exchange registration and its speed bump 2016 (dated)", "Asymmetric speed bumps: SEC orders on Cboe EDGA and others; TSX Alpha; ICE/Eurex passive protection (dated)", "Shkilko and Sokolov 2020 Every cloud has a silver lining (JF)"]),
        dict(slug="10-the-quoting-engine", title="The Quoting Engine",
             hook="A market maker changes its mind about its price tens of thousands of times a day on one instrument; every change is a cancel and a new order or a modification, each can cross a fill already on its way, and the venue counts them all.",
             sections=["From target quotes to orders", "Cancel-replace, priority and in-flight states", "Throttles, message limits and order-to-trade ratios", "Self-match prevention and multiple strategies", "Quote ladders and the line not to cross"],
             defines=["cancel-replace", "quote ladder", "message throttle"],
             uses=["self-trade prevention (B10.26)", "order-to-trade ratio (B10.24)", "token bucket (B13.21)", "rate limit (B3.15)", "post-only order (B3.15)", "price-time priority (B1.19)", "layering (B9.29)", "spoofing (B9.29)", "cancellation rate (B7.8)", "order lifecycle (B7.17)"] + _U_SIM,
             tutorial="Drive quoteengine from target quotes produced by the chapter 3 policy on firm_tape; count messages, measure the priority lost by modifications, and replay fills that cross cancels to test the in-flight state machine.",
             build="`firm.quoteengine`: target quotes to order actions (diffing, minimum price and size change, modify versus cancel-replace by the venue's priority rules), in-flight state machine per order, token-bucket throttle and order-to-trade budget, self-trade prevention across strategies; Python reference, C++20 and Rust twins on one fixture.",
             problem="Ten thousand changes of mind — named result: the message count and priority lost per hour under three quoting thresholds, against the capture each earns.",
             facts=["Commission Delegated Regulation (EU) 2017/566 (RTS 9) order-to-trade ratio (dated)", "CME Group messaging efficiency programme and self-match prevention (dated)", "Eurex excessive system usage and order-to-trade limits (dated)", "Nasdaq or Cboe anti-internalisation / self-trade prevention options (dated)", "US v. Coscia 7th Cir. 2017 (the line: from Book 9 ch. 29)"]),
        dict(slug="11-hedging-and-inventory-in-practice", title="Hedging and Inventory in Practice",
             hook="At ten to four a stock market maker is long a basket of forty names it never chose; it can sell them, sell the index future against them, or keep them overnight and start tomorrow long.",
             sections=["Choosing the hedge instrument", "Partial hedging and hedge triggers", "Inventory across correlated books", "End of day and overnight"],
             defines=["hedge instrument", "delta-equivalent inventory", "end-of-day flattening"],
             uses=["hedging band (B5.26)", "internalisation (B1.10)", "cross-asset hedge ratio (B9.9)", "impulse control (B4.10)", "no-trade region (B4.10)", "closing price (B1.13)", "multi-asset market making (ch4)"] + _U_MM,
             tutorial="On a simulated day of fills across forty names (firm.mmharness on firm_tape paths with a common factor), hedge with the future, with single stocks, or not at all, under band and trigger rules; compare hedging cost, residual risk and overnight gap exposure.",
             build="`firm.mmhedge`: delta-equivalent inventory across instruments by factor loadings, hedge-instrument choice by cost and residual risk, band and trigger policies on firm.impulse, end-of-day flattening schedules; Python.",
             problem="Forty names at ten to four — named result: the cost and residual risk of the three hedging choices, and the overnight loss distribution of keeping the book.",
             facts=["Hendershott and Menkveld 2014 Price pressures (JFE)", "Menkveld 2013 inventory mean reversion of a high-frequency market maker (JFM)", "Comerton-Forde, Hendershott, Jones, Moulton, Seasholes 2010 Time variation in liquidity: the role of market-maker inventories and revenues (JF)"]),
    ]),
    ("part.hf.strategies", [
        dict(slug="12-etf-market-making", title="ETF Market Making",
             hook="An ETF on emerging-market bonds trades all day in New York while half of its bonds have not traded for a week; the market maker who quotes it is the price, and on a bad day its quote and the fund's net asset value can be several percent apart.",
             sections=["Pricing an ETF from its basket", "The primary market: creation and redemption", "Hedging an ETF book", "When the underlying is closed or illiquid", "Stress: discounts, stale NAVs and who absorbs them"],
             defines=["pricing basket", "custom basket", "creation fee"],
             uses=["exchange-traded fund (B1.14)", "authorised participant (B1.14)", "creation unit (B1.14)", "creation basket (B1.14)", "indicative NAV (B1.14)", "net asset value (B1.14)", "ETF create-redeem arbitrage (B9.19)", "ETF discount (B9.19)", "fair price (ch2)"] + _U_MM,
             strategies=["basket-hedged equity ETF quoting", "creation-redemption arbitrage", "fixed-income ETF quoting on a stale NAV", "international ETF quoting while the underlying is closed", "futures-hedged ETF quoting"],
             tutorial="Price a synthetic ETF from a pricing basket with stale components, quote it with firm.mmharness hedged in the basket or in a future, and run the create-redeem decision at the close; stress with a planted bond-market freeze.",
             build="`firm.etfmm`: pricing-basket fair price with staleness and futures proxies, hedge choice, creation-redemption decision with fees and settlement lag; Python, on firm.etfmonitor.",
             problem="Quoting a closed market — named result: the ETF market maker's P&L and the premium it quotes through the planted freeze, and how much of the discount was the NAV's staleness.",
             facts=["SEC Rule 6c-11 (2019) custom baskets and ETF disclosure (dated)", "Flow Traders annual report: ETF value traded (dated)", "Petajisto 2017 Inefficiencies in the pricing of exchange-traded funds (FAJ)", "Pan and Zeng 2019 or Koont et al. on ETF arbitrage under liquidity mismatch", "Haddad, Moreira, Muir 2021 When selling becomes viral (RFS): March 2020 bond ETF discounts"]),
        dict(slug="13-index-and-basket-arbitrage", title="Index and Basket Arbitrage",
             hook="The index future ticks up and five hundred stocks have not moved yet; buying all five hundred takes longer than the gap lasts, so the arbitrageur buys the thirty that matter and accepts the risk of the rest.",
             sections=["The futures--cash basis at high frequency", "Partial baskets and tracking risk", "Legging and execution risk", "Financing and dividend risk", "The same index on several futures"],
             defines=["partial basket", "legging risk", "cross-listed futures"],
             uses=["index arbitrage (B9.26)", "fair value (B1.21)", "implied financing rate (B1.21)", "basis (B1.21)", "mini contract (B1.22)", "micro contract (B1.22)", "dividend risk (B5.5)"] + _U_ARB,
             strategies=["futures against an optimised partial basket", "cross-listed index futures arbitrage", "mini against full-size contract arbitrage"],
             tutorial="On a synthetic index of fifty names driven by a factor, with the future leading the stocks by a planted lag, choose partial baskets of five to fifty names, trade the basis with execution lags, and measure tracking error, legging losses and net capture.",
             build="`firm.basketarb`: partial-basket selection by tracking-error minimisation, basis bands with financing and dividends, legging simulation with per-leg latency, cross-listed contract spreads with currency and hours; Python.",
             problem="Thirty names out of five hundred — named result: the net edge per trade as a function of the basket size, and the size that maximises it.",
             facts=["MacKinlay and Ramaswamy 1988 Index-futures arbitrage and the behavior of stock index futures prices (RFS)", "Roll, Schwartz, Subrahmanyam 2007 Liquidity and the law of one price: the futures-cash basis (JF)", "Nikkei 225 futures listings on OSE, SGX and CME (dated)", "CME Micro E-mini launch and contract specification (dated)"]),
        dict(slug="14-depositary-receipts-and-dual-listings", title="Depositary Receipts and Dual Listings",
             hook="A company's shares trade in London and its receipts in New York; for three hours both are open and one is a currency conversion of the other, and for the rest of the day one of them is priced by a market maker who can only guess.",
             sections=["Receipts, ratios and the depositary", "Arbitrage in overlapping hours", "Pricing across non-overlapping hours", "Conversion: issuance, cancellation and its frictions"],
             defines=["depositary receipt ratio", "depositary receipt issuance", "pre-release"],
             uses=["depositary receipt (B1.17)", "dual listing (B1.17)", "cross rate (B2.14)", "spot value date (B2.14)", "settlement cycle (B1.5)", "cross-instrument fair price (ch2)"] + _U_ARB,
             strategies=["receipt against ordinary shares in overlapping hours", "pricing the receipt when the home market is closed", "conversion arbitrage through the depositary"],
             tutorial="Simulate a home listing, its receipt and the currency with independent liquidity; quote the receipt from the home market and the currency when both are open and from a futures proxy when not, and decide when converting receipts is worth the fees and the settlement lag.",
             build="`firm.drarb`: receipt fair price across hours (home price, ratio, currency, futures proxy), overlapping-hours arbitrage band, conversion decision with fees and settlement; Python.",
             problem="Two prices, one company — named result: the receipt market maker's quoting error in closed hours against open hours, and the conversion threshold after fees.",
             facts=["Gagnon and Karolyi 2010 Multi-market trading and arbitrage (JFE)", "SEC enforcement against depositary banks over ADR pre-release 2018-2019 (dated)", "Froot and Dabora 1999 How are stock prices affected by the location of trade? (JFE)", "A depositary's published fee schedule (dated)"]),
        dict(slug="15-futures-market-making", title="Futures Market Making",
             hook="In a short-rate futures contract the queue at the best price holds tens of thousands of lots and fills are shared pro rata; a market maker who wants a hundred lots shows thousands, and every other maker knows it.",
             sections=["Pro-rata books and size", "Calendar spreads and implied prices", "Arbitrage between spread and outright books", "Rates futures strips", "Inter-commodity spreads"],
             defines=["over-quoting", "implied-price arbitrage"],
             uses=["pro-rata allocation (B1.19)", "top-order allocation (B1.19)", "implied-in (B1.19)", "implied-out (B1.19)", "calendar spread (B1.19)", "pack (B2.8)", "bundle (B2.8)", "futures strip (B2.8)", "overnight-rate future (B2.8)", "lead market maker (B1.19)", "inter-commodity spread credit (B1.20)"] + _U_MM,
             strategies=["pro-rata outright quoting", "calendar-spread quoting with implied legs", "implied-price arbitrage between spread and outright books", "short-rate futures strip making", "inter-commodity spread trading"],
             tutorial="Match a pro-rata book with firm.match, show the over-quoting equilibrium when every maker scales its size to its share, then quote a strip of short-rate futures and its calendar spreads with implied prices and find the arbitrage when an implied price lags.",
             build="`firm.futmm`: pro-rata fill model with top-order and minimum-allocation rules, over-quoting best response, implied-price computation across a strip, spread-outright arbitrage scanner; Python, on firm.match.",
             problem="Showing ten times what you want — named result: the equilibrium over-quoting factor in a pro-rata book, and the inventory risk it creates when an unexpectedly large order fills everyone at once.",
             facts=["CME Globex matching algorithms (pro-rata, allocation, split FIFO) (dated)", "CME implied functionality description (dated)", "Field and Large 2008 Pro-rata matching and one-tick futures markets (working paper)", "Eurex or ICE pro-rata products (dated)"]),
        dict(slug="16-auctions-and-the-close", title="Auctions and the Close",
             hook="At ten to four the exchange publishes a buy imbalance of two hundred thousand shares in a stock; in the next ten minutes someone will sell them into the auction, and the price at which they do is set by whoever shows the best offer.",
             sections=["The closing auction as a liquidity event", "Reading the imbalance publication", "Offsetting imbalances: pricing the order", "The auction and the continuous book before it", "Opening auctions and reopenings"],
             defines=["imbalance-offsetting order", "auction impact curve"],
             uses=["call auction (B1.13)", "closing price (B1.13)", "indicative price (B1.13)", "order imbalance (B1.13)", "uncrossing price (B1.13)", "market-on-close order (B1.13)", "limit-on-close order (B1.13)", "basis trade at index close (B1.21)", "trade at settlement (B1.21)"] + _U_MM,
             strategies=["closing-auction imbalance liquidity provision", "opening-auction liquidity provision", "close hedged with trade-at-settlement futures"],
             tutorial="Uncross synthetic closing books with firm.auction, publish imbalances on a schedule, and price imbalance-offsetting orders from the auction impact curve and the post-close reversal; measure the provider's P&L and its sensitivity to the reversal assumption.",
             build="`firm.auctionmm`: indicative price and imbalance publications on a schedule, the auction impact curve, offsetting-order sizing and pricing, post-close mark-outs; Python, on firm.auction.",
             problem="Two hundred thousand to sell — named result: the offsetting provider's expected P&L per share against the imbalance size, and the share of the closing move that reverts overnight.",
             facts=["Nasdaq Net Order Imbalance Indicator and closing cross rules (dated)", "NYSE closing auction imbalance publication times (dated)", "Closing auction share of US and European volume, exchange statistics (dated)", "Bogousslavsky and Muravyev 2023 Who trades at the close? (JFE)", "Jegadeesh and Wu 2022 Closing auctions: nasdaq versus NYSE (JFE) or equivalent"]),
        dict(slug="17-rebates-inverted-venues-and-tiers", title="Rebates, Inverted Venues and Tiers",
             hook="Two venues show the same bid; one pays a passive fill about thirty cents per hundred shares and the other charges for it, so the queue on the first is long, the queue on the second is short, and a market maker has to decide which one to stand in.",
             sections=["Fees as part of the spread", "Queues on maker-taker and inverted venues", "Tiers and their cliffs", "Marginal fees and the volume decision"],
             defines=["rebate capture", "tier cliff", "marginal fee"],
             uses=["maker-taker pricing (B1.9)", "inverted venue (B1.9)", "access fee cap (B1.9)", "volume tier (B1.29)", "member rate (B1.30)", "effective tick size (B10.7)", "queue value (B10.6)", "wash trading (B3.16)"] + _U_MM,
             strategies=["rebate-capture passive making", "inverted-venue queue placement", "tier-aware volume management"],
             tutorial="On firm.feesched's schedules and a two-venue queue model, compute where a passive order should rest (fee, queue length, adverse selection), then the month's volume plan around a tier cliff and the marginal fee of each extra share.",
             build="`firm.rebatemm`: fee-adjusted queue value by venue, tier-cliff marginal-fee curve, volume allocation across venues under a tier schedule; Python, on firm.feesched.",
             problem="Paid to wait, charged to wait — named result: the fee-adjusted edge of resting on each venue, and the month-end volume at which chasing the next tier stops paying.",
             facts=["SEC Rule 610 access fee cap amendments 2024 and their compliance status (dated)", "Battalio, Corwin, Jennings 2016 make-take fees and limit order execution quality (JF)", "A published maker-taker and an inverted venue fee schedule (Nasdaq, Cboe BYX/EDGA) (dated)", "SEC Transaction Fee Pilot and its vacatur, D.C. Circuit 2020 (dated)"]),
        dict(slug="18-news-and-event-trading", title="News and Event Trading",
             hook="At half past eight on the first Friday of the month a number is released; within the next millisecond futures trade in Chicago and the arbitrage to New York is under way, and the market makers who did not want to be part of it pulled their quotes a second before.",
             sections=["Scheduled numbers and the release race", "Machine-readable headlines", "Social media and unscheduled events", "The market maker's event protocol", "Risk controls for event trading"],
             defines=["release lock-up", "release race", "event protocol"],
             uses=["machine-readable news (B8.17)", "news reaction window (B8.17)", "economic release (B2.31)", "data surprise (B2.31)", "consensus forecast (B2.31)", "trading halt (B8.17)", "latency race (ch9)"] + _U_MM,
             strategies=["macro-release race in futures", "machine-readable earnings headline race", "social-media headline reaction", "market-maker event protocol: pull, widen, re-enter"],
             tutorial="Simulate a scheduled release with a surprise distribution, traders reacting at several latencies and a market maker who pulls, widens and re-enters on a schedule; measure who captures the move and what the market maker saves.",
             build="`firm.newsrace`: scheduled releases with surprises, reaction by latency, headline misparsing risk, a market maker's event protocol as a Quoter wrapper; Python, on firm.newsevent.",
             problem="Half past eight — named result: the share of the release's move captured by each latency tier, and the market maker's loss with and without its event protocol.",
             facts=["Hu, Pan, Wang 2017 Early peek advantage? (JFE)", "New York Attorney General settlements on early data access (Thomson Reuters 2014; Business Wire 2014) (dated)", "BLS or DOL media lock-up rules and changes (dated)", "AP Twitter account hack of 23 April 2013 and the market's move (dated)", "SEC v. Musk 2018 settlement (the funding-secured tweet) (dated)"]),
        dict(slug="19-automated-options-market-making", title="Automated Options Market Making",
             hook="An options market maker quotes every strike and expiry of a stock at once, several thousand prices on a dozen exchanges, and a sweep can hit forty of them in the same millisecond; the exchange's quote protection is what stops the forty-first.",
             sections=["The live surface", "Mass quoting and quote protection", "Delta hedging at speed", "Per-strike and per-expiry risk", "What the major firms have published"],
             defines=["mass quote", "live surface fit", "strike risk limit"],
             uses=["theoretical value (B5.26)", "vega bucket (B5.26)", "hedging band (B5.26)", "quote protection (B1.24)", "options market maker (B1.24)", "quoting obligation (B1.24)", "SVI parametrisation (B5.8)", "sticky strike (B5.7)", "OPRA (B1.24)"] + _U_MM,
             strategies=["surface-fitted quoting across a listed chain", "mass-quote making with quote protection", "delta-hedged options book", "event-aware options quoting", "vega-limited skew quoting"],
             tutorial="Refit an SVI surface on every underlying move with firm.optmm, generate mass quotes, run a sweep across strikes against quote-protection settings, delta-hedge in the underlying, and enforce per-strike and per-expiry vega limits.",
             build="`firm.optquoter`: incremental surface refit, mass-quote generation with widths from the surface's uncertainty, quote-protection triggers (fill count, delta, vega per interval), delta hedger and bucketed limits; Python, on Book 5's firm.optmm and firm.svi.",
             problem="Forty strikes in a millisecond — named result: the loss on a planted informed sweep as a function of the quote-protection threshold, and the fills given up by a tight threshold on normal days.",
             facts=["Cboe market-maker risk parameters (quote protection) rules (dated)", "OPRA message rates and capacity (dated)", "Muravyev 2016 Order flow and expected option returns (JF)", "Muravyev and Pearson 2020 Options trading costs are lower than you think (RFS)", "Public talks or papers by options market makers on automated quoting (dated; only with a citable source)"]),
        dict(slug="20-options-cross-venue-and-volatility-arbitrage-at-speed", title="Options: Cross-Venue and Volatility Arbitrage at Speed",
             hook="The day before a stock goes ex-dividend, thousands of deep in-the-money calls should be exercised and some are not; the holders who forget pay the ones who remember, and the trade that collects it has been in the exchanges' rulebooks for years.",
             sections=["Parity at speed: conversions and reversals", "Box spreads and the rate they imply", "Early exercise, dividends and the dividend play", "The same volatility on several listings"],
             defines=["conversion arbitrage", "reversal arbitrage", "jelly roll"],
             uses=["put--call parity (B1.25)", "box spread (B5.1)", "dividend play (B5.26)", "early-exercise premium (B5.6)", "American exercise (B1.23)", "assignment (B1.23)", "implied borrow rate (B5.5)", "live surface fit (ch19)"] + _U_ARB,
             strategies=["conversion and reversal arbitrage", "box-spread financing arbitrage", "dividend play on unexercised calls", "index against ETF options volatility arbitrage"],
             tutorial="Scan synthetic option chains on several listings for parity, box and early-exercise violations with firm.parity and firm.american, net them of fees, borrow and assignment risk, and measure how many survive a one-tick execution lag.",
             build="`firm.optarb`: parity, box and jelly-roll scanners with borrow and rates, the dividend-play assignment model, cross-listing volatility spreads; Python, on firm.parity and firm.american.",
             problem="The calls nobody exercised — named result: the dividend play's expected profit per contract as a function of the share of holders who fail to exercise.",
             facts=["Pool, Stoll, Whaley 2008 Failure to exercise call options (JFM)", "Hao, Kalay, Mayhew 2010 Ex-dividend arbitrage in option markets (RFS)", "van Binsbergen, Diamond, Grotteria 2022 Risk-free interest rates (JFE)", "Ofek, Richardson, Whitelaw 2004 Limited arbitrage and short sales restrictions (JFE)", "Exchange fee caps or rules on dividend strategies (dated)"]),
        dict(slug="21-fx-market-making", title="FX Market Making",
             hook="A non-bank liquidity provider streams euro-dollar prices to a hundred banks, brokers and platforms at once, each with its own price; a trade on one of them is hedged, or not, within microseconds on another.",
             sections=["Principal electronic liquidity provision", "Pricing from many venues", "Streams, tiers and last look", "Internalise or hedge", "Crosses and emerging markets"],
             defines=["synthetic cross"],
             uses=["liquidity aggregator (B10.21)", "firm liquidity (B10.21)", "last look (B2.15)", "hold time (B2.15)", "reject rate (B2.15)", "quote skewing (B2.15)", "streaming quote (B2.15)", "liquidity tier (B2.15)", "primary venue (B2.14)", "electronic communication network (B2.14)", "internalisation (B1.10)", "client tiering (B9.24)", "cross rate (B2.14)", "non-deliverable forward (B2.18)", "FX Global Code (B2.15)"] + _U_MM,
             strategies=["primary-venue FX market making", "disclosed streaming to aggregators with last look", "cross-rate synthesis quoting", "non-deliverable forward electronic making"],
             tutorial="Build a consolidated fair price from three simulated FX venues, stream tiered prices to simulated aggregators with and without last look, and choose between internalising and hedging each trade; measure capture, rejects and hedging cost.",
             build="`firm.fxlp`: multi-venue FX fair price, per-stream pricing with skew and tier, last-look check, internalise-or-hedge policy, synthetic crosses; Python, on firm.lastlook and firm.flowmm.",
             problem="A hundred prices at once — named result: the liquidity provider's capture and reject rate with and without last look, and the hedge share at which internalising stops paying.",
             facts=["BIS Triennial Central Bank Survey 2025 FX turnover by counterparty and execution method (dated)", "Chaboud, Chiquoine, Hjalmarsson, Vega 2014 Rise of the machines (JF)", "Oomen 2017 Last look (QF)", "FX Global Code principle 17 on last look (dated)", "Euromoney FX survey or a firm's published market share (dated; only with a citable source)"]),
        dict(slug="22-bond-and-etf-request-for-quote-market-making", title="Bond and ETF Request-for-Quote Market Making",
             hook="A corporate bond that last traded three weeks ago is on the screen in a request from an asset manager to five dealers; one of them answers in under a second, without a human, because its model has already priced the bond from its neighbours.",
             sections=["Pricing bonds that do not trade", "Auto-quoting request for quote", "Win probability and the winner's curse", "ETF request for quote and block liquidity", "Portfolio trades and all-to-all"],
             defines=["auto-quoting", "win-probability model", "cover price"],
             uses=["request for quote (B2.22)", "all-to-all trading (B2.22)", "composite price (B2.22)", "axe (B2.22)", "portfolio trade (B2.22)", "winner's curse (B2.30)", "hit ratio (B7.23)", "dealer-to-client platform (B2.4)", "trade reporting (B2.22)"] + _U_MM,
             strategies=["algorithmic corporate-bond request-for-quote responder", "ETF request-for-quote market making", "Treasury streaming and request for quote", "all-to-all anonymous liquidity provision"],
             tutorial="Price synthetic bonds from issuer curves and reported trades, answer simulated requests from clients with private values against competing dealers with firm.rfq, fit a win-probability model and choose the quote that maximises expected profit net of the winner's curse.",
             build="`firm.rfqmm`: bond fair price from comparables and stale prints, win-probability model with cover feedback, optimal RFQ response, ETF RFQ pricing from the creation basket; Python, on firm.rfq.",
             problem="Five dealers and a bond nobody traded — named result: the auto-quoter's profit per request and win rate at its optimal markup, and how both change with the number of dealers asked.",
             facts=["MarketAxess and Tradeweb annual reports: automated and portfolio trading volumes (dated)", "Hendershott and Madhavan 2015 Click or call? (JF)", "O'Hara and Zhou 2021 The electronic evolution of corporate bond dealers (JFE)", "FINRA TRACE dissemination rules (dated)", "Bessembinder, Spatt, Venkataraman 2020 A survey of the microstructure of fixed-income markets (JFQA)"]),
        dict(slug="23-retail-wholesaling", title="Retail Wholesaling",
             hook="A retail order to buy fifty shares is routed from a phone to a wholesaler, which fills it at a price slightly better than the best offer on any exchange, keeps the trade, and pays the broker for the privilege.",
             sections=["The economics of retail flow", "Segmentation and pricing", "Price improvement and its measurement", "Inventory from one-sided flow", "Rules and the debate"],
             defines=["flow segmentation", "retail liquidity programme", "internalisation rate"],
             uses=["wholesaler (B1.10)", "payment for order flow (B1.10)", "price improvement (B1.10)", "internalisation (B1.10)", "Rule 605 report (B1.10)", "Rule 606 report (B1.10)", "best execution (B1.11)", "odd lot (B1.9)", "price-improvement auction (B1.24)"] + _U_MM + _U_MEAS,
             strategies=["equity retail internalisation", "retail options flow through price-improvement auctions", "exchange retail liquidity programmes"],
             tutorial="Simulate retail flow segmented from institutional flow on firm_tape, internalise it with price improvement against the national best bid and offer, hedge the one-sided residual, and decompose the wholesaler's P&L into capture, payment for flow and hedging.",
             build="`firm.wholesale`: segmented flow simulation, price-improvement policy, internalisation and hedging of residual inventory, Rule 605-style statistics; Python.",
             problem="Fifty shares from a phone — named result: the wholesaler's capture per share net of payment for order flow and hedging, and the retail trader's price improvement against the displayed spread.",
             facts=["Virtu and a second wholesaler's filings on retail market making (dated)", "SEC Rule 605 amendments 2024 and the status of the 2022 order-competition and best-execution proposals (dated)", "Ernst and Spatt 2022 Payment for order flow and asset choice (working paper)", "Schwarz, Barber, Huang, Jorion, Odean 2025 The actual retail price of equity trades (JF or working paper)", "SEC approval of the NYSE Retail Liquidity Program 2012 (dated)"]),
        dict(slug="24-crypto-high-frequency-trading-on-centralised-venues", title="Crypto High-Frequency Trading on Centralised Venues",
             hook="Bitcoin trades on dozens of exchanges around the clock with no consolidated tape; a market maker quotes on one, hedges on another, pays funding every few hours on a third, and has to fit it all inside each venue's request budget.",
             sections=["Cross-exchange making and taking", "Funding and basis at speed", "Liquidation flows", "Rate-limit-aware quoting", "Market-maker programmes and their obligations"],
             defines=["cross-exchange market making", "hedge venue", "liquidation absorption"],
             uses=["funding rate (B3.17)", "funding interval (B3.17)", "perpetual future (B3.17)", "mark price (B3.17)", "liquidation cascade (B3.18)", "liquidation engine (B3.18)", "auto-deleveraging (B3.18)", "rate limit (B3.15)", "request weight (B3.15)", "post-only order (B3.15)", "cross-venue arbitrage (B3.16)", "prepositioned inventory (B3.16)", "uptime requirement (B3.25)", "token market-making agreement (B3.24)"] + _U_MM,
             strategies=["cross-exchange market making", "cross-exchange latency taking", "funding-timestamp trading", "liquidation-flow absorption", "rate-limit-aware quoting under a programme", "spot-perpetual basis market making"],
             tutorial="Quote a synthetic perpetual on one venue while hedging on another's spot book, with funding intervals, a planted liquidation cascade and each venue's rate limits from firm.ratelimit; measure capture, hedge slippage, funding P&L and uptime.",
             build="`firm.cryptohft`: two-venue making and hedging with transfer and inventory limits, funding accrual at timestamps, liquidation-cascade flow, a rate-limit budget allocator; Python, on firm.perp, firm.liquidation, firm.ratelimit and firm.mmprogram.",
             problem="Around the clock — named result: the cross-exchange maker's P&L by component over a week with one cascade, and the capture it gives up to stay inside its request budget.",
             facts=["Makarov and Schoar 2020 Trading and arbitrage in cryptocurrency markets (JFE)", "A major venue's API rate limits and market-maker programme terms (dated)", "Funding intervals of major perpetual venues (dated)", "The 10 October 2025 liquidation event: size and venues (dated; as Book 3 where sourced)", "Kaiko or venue research on cross-exchange spreads (dated)"]),
        dict(slug="25-on-chain-trading", title="On-Chain Trading",
             hook="A large swap on a decentralised exchange moves its pool price away from the centralised exchanges; within the same block, searchers compete to arbitrage it back, and most of what they earn is bid away to the builder that includes their bundle.",
             sections=["Exchange-to-chain arbitrage", "Atomic arbitrage and searching", "Liquidations on lending protocols", "Just-in-time and hedged liquidity provision", "Bundles, builders and bidding; sandwiching and the law"],
             defines=["atomic arbitrage", "bundle bid", "hedged liquidity provision"],
             uses=["CEX--DEX arbitrage (B3.22)", "maximal extractable value (B3.22)", "searcher (B3.22)", "block builder (B3.22)", "transaction bundle (B3.22)", "back-running (B3.22)", "sandwich attack (B3.22)", "proposer--builder separation (B3.22)", "order-flow auction (B3.22)", "just-in-time liquidity (B3.20)", "loss-versus-rebalancing (B3.20)", "concentrated liquidity (B3.20)", "liquidation bonus (B3.23)", "health factor (B3.23)", "flash loan (B3.23)", "priority fee (B3.14)"],
             strategies=["CEX-DEX arbitrage", "atomic DEX-DEX arbitrage", "lending-protocol liquidation searching", "just-in-time liquidity provision", "bundle bidding in builder auctions", "hedged concentrated-liquidity market making"],
             tutorial="On firm.amm pools priced against a simulated centralised exchange, find the arbitrage after each block, simulate competing searchers bidding for inclusion, and measure the share of the opportunity paid to the builder; then run a hedged liquidity position and measure its loss-versus-rebalancing.",
             build="`firm.searcher`: CEX-DEX and atomic cycle detection, liquidation opportunity scanner, a first-price bundle auction among searchers, hedged liquidity-provision P&L; Python, on firm.amm, firm.sandwich and firm.gasfee.",
             problem="Bid away to the builder — named result: the share of arbitrage profit paid to builders as the number of competing searchers grows, and the hedged liquidity provider's net return after loss-versus-rebalancing.",
             facts=["Daian et al. 2020 Flash Boys 2.0 (IEEE S&P)", "Milionis, Moallemi, Roughgarden, Zhang 2022 Automated market making and loss-versus-rebalancing (arXiv)", "Heimbach, Pahari, Schertenleib 2024 Non-atomic arbitrage in decentralized finance (IEEE S&P or arXiv)", "Flashbots MEV-Boost documentation (dated)", "US v. Peraire-Bueno (SDNY 2024) and its outcome (dated)"]),
        dict(slug="26-prediction-and-sports-market-making", title="Prediction and Sports Market Making",
             hook="A goal is scored and the television picture arrives several seconds after the stadium's; the betting exchange holds every in-play order for a few seconds before it matches, so that the fans in the stands do not win every race.",
             sections=["Pricing models for events and matches", "Making markets on exchanges and prediction venues", "In-play latency and the bet delay", "Limits and counterparty selection"],
             defines=["bet delay", "courtsiding", "stake limiting"],
             uses=["betting exchange (B3.27)", "bookmaker (B3.27)", "overround (B3.27)", "in-play betting (B3.27)", "implied probability (B3.27)", "favourite--longshot bias (B3.27)", "event contract (B3.27)", "back bet (B3.27)", "lay bet (B3.27)", "Poisson process (B4.6)"] + _U_MM,
             strategies=["prediction-market making on a central limit order book", "in-play exchange trading with the bet delay", "cross-venue event arbitrage"],
             tutorial="Price a football match with a Poisson goals model, make a market on a simulated betting exchange, and trade in play with a bet delay against faster and slower counterparties; measure the market maker's loss to the fastest and its gain from the slowest.",
             build="`firm.sportsmm`: Poisson match model with in-play updating, exchange market making with a bet delay, counterparty limits by mark-out; Python, on firm.odds.",
             problem="Faster than the television — named result: the market maker's loss per goal to courtsiders as a function of the bet delay, and the delay that makes it negligible.",
             facts=["Croxson and Reade 2014 Information and efficiency: goal arrival in soccer betting (EJ)", "Betfair exchange in-play delay rules (dated)", "Kalshi CFTC designation and the 2024 D.C. court ruling on event contracts (dated)", "Polymarket CFTC settlement 2022 and later status (dated)", "A court or regulator record on courtsiding (dated)"]),
    ]),
    ("part.hf.running", [
        dict(slug="27-risk-controls", title="Risk Controls",
             hook="On 1 August 2012 a market maker's new code sent millions of unintended orders in the first three quarters of an hour of trading; the loss was about four hundred and sixty million dollars, and the regulator's order afterwards reads as a checklist of the controls it did not have.",
             sections=["Pre-trade limits", "Position, loss and message limits", "Price collars and fat-finger checks", "Kill switches: who pulls them and when", "The regulatory requirements for algorithmic firms"],
             defines=["kill switch", "price collar", "pre-trade risk check", "market access rule", "loss limit"],
             uses=["risk limit (B6.29)", "position limit (B1.27)", "drawdown limit (B8.28)", "limit up--limit down (B1.31)", "clearly erroneous trade (B1.31)", "sponsored access (B1.4)", "direct market access (B1.4)", "rogue trading (B6.28)", "message throttle (ch10)", "order-to-trade ratio (B10.24)"],
             tutorial="Replay a synthetic runaway algorithm through firm.riskctl with each control switched on in turn (order-rate limit, position limit, loss limit, collar, kill switch) and measure the loss each one would have capped and the false alarms each raises on normal days.",
             build="`firm.riskctl`: a limits hierarchy (firm, desk, strategy, instrument) in a declarative schema, pre-trade checks, post-trade loss and position monitors, kill-switch semantics and an audit log; Python reference with fixtures that Book 13's nanosecond gate replays.",
             problem="Forty-five minutes — named result: the loss the runaway algorithm would have made under each control and the earliest control that stops it.",
             facts=["SEC order In the Matter of Knight Capital Americas 2013 (Release 34-70694) (dated)", "SEC Rule 15c3-5 market access rule (dated)", "Commission Delegated Regulation (EU) 2017/589 (RTS 6) (dated)", "CFTC electronic trading risk principles 2021 (dated)", "FIA best practices for automated trading risk controls (dated)", "FCA and PRA fines on a bank's May 2022 erroneous basket order, 2024 (dated)"]),
        dict(slug="28-pnl-analytics-and-the-strategy-lifecycle", title="P\\&L Analytics and the Strategy Lifecycle",
             hook="A market-making strategy earned less this month than last; the spread was narrower, volume was higher, a competitor arrived on one venue, and someone changed a parameter on the twelfth, and the morning report has to say which of these did it.",
             sections=["Daily attribution of a market-making book", "Parameter changes as experiments", "Capture decay and competition", "When to retire a strategy"],
             defines=["strategy lifecycle", "parameter change control", "capture decay"],
             uses=["daily P\\&L attribution (B8.1)", "A/B test (B7.21)", "staged rollout (B7.21)", "post-publication decay (B7.13)", "kill criterion (B7.1)", "CUSUM test (B7.13)", "crowding (B7.28)"] + _U_MEAS,
             tutorial="Attribute a synthetic market maker's daily P&L over a simulated year with firm.markout's decomposition, detect a planted competitor's arrival and a parameter change, run the parameter change as a randomised experiment, and apply a retirement rule.",
             build="`firm.mmattrib`: daily attribution (capture, adverse selection, inventory, fees, rebates) by instrument and venue, change-point detection on capture, parameter experiments by randomised days, a retirement rule; Python, on firm.markout and firm.abtest.",
             problem="Which of these did it — named result: the attribution of the month-on-month P&L change to spread, volume, competition and the parameter change, against the planted truth.",
             facts=["Menkveld 2013 (the one HFT's P&L decomposition) (JFM)", "Virtu 10-K: capture and volume by segment over time (dated)", "Budish, Lee, Shim 2019 Will the market fix the market? (working paper) or equivalent on competition and capture"]),
        dict(slug="29-a-venue-playbook", title="A Venue Playbook",
             hook="The same quoting code behaves differently on a price-time equities exchange, a pro-rata futures book, a venue with a speed bump and a crypto exchange with a request budget; a desk keeps one page per venue so that nobody learns the differences in production.",
             sections=["What a venue profile holds", "Equities and options venues", "Futures and FX venues", "Crypto, on-chain and event venues", "Onboarding a new venue"],
             defines=["venue profile"],
             uses=["price-time priority (B1.19)", "pro-rata allocation (B1.19)", "maker-taker pricing (B1.9)", "speed bump (ch9)", "frequent batch auction (B10.10)", "rate limit (B3.15)", "market-by-order (B1.19)", "market-by-price (B1.19)", "last look (B2.15)", "on-chain order book (B3.21)"],
             tutorial="Encode venue profiles for eight venue types (matching rule, fees, feed, order types, limits, quirks) and run one quoting strategy through firm.mmharness on each configuration to show which parameters must change.",
             build="`firm.venueprofile`: a venue-profile schema and registry with validation, and the harness configuration it produces for each venue type; Python, on firm.venues and firm.feesched.",
             problem="One code, eight venues — named result: the quoting strategy's capture and message count on each venue type with and without the venue-specific parameters.",
             facts=["Matching rules, fees and feed types of one venue per type (CME, Nasdaq, Cboe, IEX, Eurex, EBS or LSEG FX, a major crypto venue, a betting exchange or Kalshi) (dated)"]),
    ]),
]
