"""Book 1 (Markets I) chapter briefs: data for tools/make_briefs.py --book 1."""
SLUG = "markets-1"
PFX = "m1"
HEAD = "One Quant Book 1 — Markets I"

# (part key, [chapters]); chapter = dict(slug, title, hook, sections, defines,
# tutorial, build, problem, facts)
PARTS = [
    ("part.m1.ecosystem", [
        dict(slug="01-what-a-trading-firm-does", title="What a Trading Firm Does",
             hook="One share of one stock changes hands at 10:31:04; five firms earn something from that single print.",
             sections=["Five business models", "Where the money comes from: spread, risk premium, fee, carry, alpha", "Principal versus agent", "A map of one trade"],
             defines=["market maker", "proprietary trading firm", "hedge fund", "multi-manager platform", "asset manager", "principal", "agent", "bid--ask spread", "alpha", "assets under management"],
             tutorial="Decompose a day of simulated trades into who earned what (spread, fees, rebate, P&L).",
             build="`firm.ledger`: a fee-and-revenue ledger that every later component posts to.",
             problem="A week at a small market maker — named result: the break-even daily volume.",
             facts=["public revenue figures of listed market makers (annual reports)", "fee model 2-and-20 history", "size of global AUM (industry report)"]),
        dict(slug="02-the-sell-side", title="The Sell Side",
             hook="A pension fund wants to sell 2 million shares before lunch and phones a bank.",
             sections=["The markets division: sales, trading, structuring, research", "Flow versus franchise", "Prime services", "Primary markets", "What regulation did to the dealer"],
             defines=["sell side", "broker-dealer", "flow trading", "franchise", "prime services", "underwriting", "risk-weighted assets", "sales-trader", "block trade"],
             tutorial="Price a risk bid for a block from spread, volatility and participation.",
             build="Block-pricing calculator (Python).",
             problem="The risk bid — named result: the discount at which the desk breaks even with 95% confidence.",
             facts=["Volcker rule citation", "Basel III / FRTB references", "bank markets revenue split (public filings)"]),
        dict(slug="03-the-buy-side", title="The Buy Side",
             hook="Twelve thousand index funds must all buy the same stock at the same closing auction.",
             sections=["Asset owners and asset managers", "Mandates, benchmarks and tracking error", "Hedge funds and their structures", "Why each of them trades", "Retail"],
             defines=["buy side", "mandate", "benchmark", "tracking error", "passive management", "active management", "commodity trading advisor", "management fee", "performance fee", "high-water mark"],
             tutorial="Compute tracking error and fee drag for three funds on simulated returns.",
             build="Fund fee engine with high-water mark.",
             problem="Two and twenty — named result: the manager's share of gross alpha over ten years.",
             facts=["share of passive in US equity funds (ICI)", "hedge fund industry AUM (HFR/SEC)", "UCITS / 40 Act citations"]),
        dict(slug="04-exchanges-brokers-venues", title="Exchanges, Brokers and Venues",
             hook="The New York Stock Exchange is a listed company's subsidiary that sells data, ports and cabinets as well as matching.",
             sections=["What an exchange sells", "Members, brokers and access", "Direct and sponsored access", "Alternative venues", "The consolidated view"],
             defines=["exchange", "exchange member", "broker", "direct market access", "sponsored access", "alternative trading system", "multilateral trading facility", "market data feed", "order"],
             tutorial="Read an exchange group's segment revenue and compute the share from data and connectivity.",
             build="Venue registry (static reference data for the firm).",
             problem="Building an exchange — named result: the break-even traded value per day.",
             facts=["exchange groups' revenue segments (10-K)", "SEC Rule 15c3-5 market access", "Reg ATS", "MiFID II MTF/OTF definitions"]),
        dict(slug="05-clearing-and-settlement", title="Clearing and Settlement",
             hook="On 28 January 2021 a retail broker received a multi-billion-dollar collateral call before dawn.",
             sections=["From trade to settlement", "The central counterparty and novation", "Margin and the default waterfall", "Settlement cycles, DVP and fails", "When a member defaults"],
             defines=["clearing", "settlement", "central counterparty", "novation", "initial margin", "variation margin", "default fund", "default waterfall", "delivery versus payment", "central securities depository", "settlement fail"],
             tutorial="Net a day of trades multilaterally and compute settlement obligations.",
             build="`firm.clearing`: multilateral netting engine.",
             problem="The default of member C — named result: the loss reaching the mutualised default fund.",
             facts=["US T+1 date (SEC rule)", "NSCC January 2021 call (congressional testimony / report)", "CPMI-IOSCO PFMI waterfall", "Lehman default at LCH (public account)"]),
        dict(slug="06-financing", title="Financing: Repo, Securities Lending and Prime Brokerage",
             hook="A fund holds 5 billion dollars of stock with 1 billion of its own money; the rest is borrowed every night.",
             sections=["Leverage and who provides it", "Repo", "Securities lending and the short sale", "Prime brokerage and margin", "Synthetic financing", "When financing runs"],
             defines=["leverage", "repurchase agreement", "haircut", "securities lending", "short sale", "locate", "rebate rate", "prime broker", "rehypothecation", "total return swap", "margin call"],
             tutorial="Cost of carry of a long--short book under cash and synthetic financing.",
             build="Financing-cost calculator feeding the P&L keeper.",
             problem="Archegos in miniature — named result: the price drop that wipes out the equity.",
             facts=["Reg T 50%", "SEC Rule 15c3-3 rehypothecation 140%", "Archegos losses (Credit Suisse report, SEC complaint)", "Reg SHO locate"]),
        dict(slug="07-pnl-and-positions", title=r"P\&L and the Accounting of a Position",
             hook="The trader says she made 40 thousand; the risk report says 31; finance says 27. All three are right.",
             sections=["Positions and average cost", "Mark-to-market: realised and unrealised", "Carry, financing, fees and dividends", "Currency translation", "P&L explain: a first look"],
             defines=["position", "mark-to-market", "realised P&L", "unrealised P&L", "average cost", "carry", "P&L attribution", "notional", "gross exposure", "net exposure"],
             tutorial="Replay a fill stream into positions and P&L; reconcile three P&L numbers.",
             build="`firm.pnl`: position and P&L keeper (Python, C++, Rust).",
             problem="Three numbers, one day — named result: the reconciled P&L and each difference.",
             facts=["FIFO vs average cost accounting reference"]),
    ]),
    ("part.m1.equities", [
        dict(slug="08-shares-corporate-actions-indices", title="Shares, Corporate Actions and Indices",
             hook="A stock closes at 480 and opens at 120; nobody lost a cent.",
             sections=["What a share is", "Dividends and the ex-date", "Splits, rights, spin-offs and mergers", "Adjustment factors", "Indices: weighting and the divisor"],
             defines=["share", "free float", "dividend", "ex-dividend date", "record date", "stock split", "rights issue", "spin-off", "adjustment factor", "index divisor", "total return index", "market capitalisation"],
             tutorial="Build back-adjusted price series and a divisor-maintained index.",
             build="Corporate-action adjuster.",
             problem="Maintaining an index through a bad week — named result: the new divisor.",
             facts=["ex-date rule under T+1", "S&P/MSCI/FTSE methodology documents", "Dow price-weighting"]),
        dict(slug="09-us-equity-market-structure", title="US Equity Market Structure",
             hook="The same 100 shares can be bought on sixteen exchanges and thirty dark pools; the law says which price is the best.",
             sections=["Regulation NMS", "The national best bid and offer", "The tape and the direct feeds", "Exchange families and fee models", "Off-exchange trading", "Speed bumps and tick rules"],
             defines=["national best bid and offer", "order protection rule", "securities information processor", "direct feed", "maker-taker pricing", "inverted venue", "intermarket sweep order", "dark pool", "round lot", "odd lot", "access fee cap", "trade-through"],
             tutorial="Build an NBBO from per-venue quotes and detect trade-throughs and locked markets.",
             build="`firm.nbbo`: consolidated best-quote builder.",
             problem="A stale tape — named result: the latency-arbitrage profit per share.",
             facts=["Rule 611, 610, 612 text", "number of exchanges (SEC list)", "off-exchange share (Cboe/FINRA)", "IEX 350 microsecond speed bump", "2024 tick-size and access-fee amendments"]),
        dict(slug="10-retail-flow-and-wholesaling", title="Retail Flow and Wholesaling",
             hook="Your market order for ten shares never reaches an exchange.",
             sections=["The path of a retail order", "Payment for order flow", "Price improvement and how it is measured", "Why uninformed flow is valuable", "January 2021"],
             defines=["wholesaler", "payment for order flow", "price improvement", "internalisation", "effective spread", "realised spread", "Rule 605 report", "Rule 606 report"],
             tutorial="Compute effective spread, realised spread and price improvement from simulated fills.",
             build="Execution-quality report generator.",
             problem="Pricing retail flow — named result: the maximum payment per share the wholesaler can afford.",
             facts=["Rule 605/606 text and 2024 amendments", "SEC staff report on Jan 2021", "PFOF totals (606 aggregations)", "Robinhood SEC settlement 2020"]),
        dict(slug="11-european-equity-market-structure", title="European Equity Market Structure",
             hook="A French stock trades in Paris, in London, in a bank's own book and in an auction that lasts a tenth of a second.",
             sections=["MiFID II and its venue types", "Fragmentation without a tape", "Systematic internalisers", "Dark caps and periodic auctions", "The closing auction", "Tick-size regime"],
             defines=["regulated market", "systematic internaliser", "organised trading facility", "double volume cap", "periodic auction", "large-in-scale waiver", "reference price waiver", "consolidated tape provider", "best execution"],
             tutorial="Build a European best bid and offer across venues and measure fragmentation (Herfindahl).",
             build="Fragmentation monitor.",
             problem="Where did the volume go? — named result: market share shift after a dark cap.",
             facts=["MiFID II/MiFIR articles", "ESMA DVC", "MiFIR review 2024 (CTP, DVC to single cap)", "tick-size RTS 11", "closing auction share statistics"]),
        dict(slug="12-asian-and-emerging-equity-markets", title="Asian and Emerging Equity Markets",
             hook="In Shanghai a stock that rises ten percent simply stops; in Tokyo the tick depends on the price; in Mumbai the tax is charged per trade.",
             sections=["Japan", "Hong Kong and the Connect programmes", "Mainland China", "Korea and Taiwan", "India", "What changes for a trading firm"],
             defines=["price limit", "board lot", "T+0 restriction", "Stock Connect", "qualified foreign investor", "securities transaction tax", "uptick rule", "foreign ownership limit", "stamp duty"],
             tutorial="Simulate returns truncated by price limits and measure the spill-over to the next day.",
             build="Market-rules table (limits, lots, ticks, taxes) as reference data.",
             problem="Limit-up — named result: expected days locked at the limit.",
             facts=["SSE/SZSE 10% and 20% limits", "TSE tick tables", "HK stamp duty rate", "India STT rates", "Korea short-selling bans dates", "Stock Connect quotas"]),
        dict(slug="13-auctions", title="Auctions",
             hook="At 15:59:50 a tenth of the day's volume is waiting for a single price.",
             sections=["Call auctions and the uncrossing rule", "Opening and closing auctions", "Imbalance information", "Volatility auctions and IPOs", "Why the close keeps growing"],
             defines=["call auction", "uncrossing price", "indicative price", "order imbalance", "market-on-close order", "limit-on-close order", "volatility interruption", "closing price"],
             tutorial="Implement the uncrossing algorithm with tie-break rules.",
             build="`firm.auction`: auction uncrosser (used by the Book 10 simulator).",
             problem="The index rebalance close — named result: the uncrossing price and paired volume.",
             facts=["NYSE/Nasdaq closing-cross rules and cutoff times", "Xetra/Euronext uncrossing rules", "closing auction volume share"]),
        dict(slug="14-exchange-traded-funds", title="Exchange-Traded Funds",
             hook="A fund's shares trade at 50.10 while the basket inside is worth 50.00; within seconds someone fixes that.",
             sections=["Structure: fund, sponsor, authorised participant", "Creation and redemption", "NAV, intraday value, premium and discount", "When the underlying is closed or illiquid", "Leveraged and inverse ETFs"],
             defines=["exchange-traded fund", "authorised participant", "creation unit", "creation basket", "net asset value", "indicative NAV", "premium", "in-kind transfer", "leveraged ETF", "volatility decay"],
             tutorial="Arbitrage bands from basket spread, creation fee and financing.",
             build="ETF premium monitor.",
             problem="The daily rebalance of a 3x fund — named result: notional to trade at the close after a 5% move.",
             facts=["Rule 6c-11", "ETF AUM totals (ICI/ETFGI)", "March 2020 bond ETF discounts (BIS/Fed papers)", "leveraged ETF rebalance formula sources"]),
        dict(slug="15-index-construction-and-rebalancing", title="Index Construction and Rebalancing",
             hook="A committee in New York adds a company to an index and forty billion dollars must buy it by Friday's close.",
             sections=["Methodologies", "The rebalance calendar", "Announcement and effective dates", "The index effect and its decay", "The footprint of passive"],
             defines=["index methodology", "float adjustment", "index reconstitution", "buffer rule", "index effect", "demand shock", "pro-forma index"],
             tutorial="Predict index adds and deletes from a ranked universe with buffers.",
             build="Reconstitution predictor.",
             problem="Russell day — named result: the expected trade size as a multiple of average daily volume.",
             facts=["Russell reconstitution schedule and move to semi-annual", "S&P inclusion criteria", "Tesla S&P inclusion Dec 2020 numbers", "index effect literature figures"]),
        dict(slug="16-stock-loan-and-short-selling", title="Stock Loan and Short Selling in Practice",
             hook="The borrow fee on one stock goes from 1% to 80% a year in a week.",
             sections=["The lending chain", "Fees, rebates and specials", "Recalls and buy-ins", "Short-sale regulation", "Squeezes", "Dividends and tax: the cum-ex affair"],
             defines=["lendable supply", "utilisation", "general collateral", "special", "recall", "buy-in", "short interest", "days to cover", "short squeeze", "naked short sale"],
             tutorial="Cost of a short over time with a fee that follows utilisation.",
             build="Borrow-cost model feeding the financing calculator.",
             problem="The squeeze — named result: the break-even holding period of the short.",
             facts=["Reg SHO Rule 203/204", "EU SSR thresholds", "GameStop short interest >100% (SEC report)", "Volkswagen 2008", "cum-ex court rulings"]),
        dict(slug="17-delta-one-instruments", title="Delta-One Instruments",
             hook="Five ways to own the same index for a year, and five different costs.",
             sections=["What delta-one means", "Total return swaps", "Futures as delta-one", "Depositary receipts and dual listings", "Comparing wrappers"],
             defines=["delta-one", "equity swap", "funding spread", "depositary receipt", "dual listing", "contract for difference", "withholding tax", "dividend enhancement"],
             tutorial="All-in annual cost of five wrappers for the same exposure.",
             build="Wrapper-cost comparator.",
             problem="The ADR and the ordinary — named result: the arbitrage band in basis points.",
             facts=["ADR ratio and fees (depositary docs)", "871(m)", "UK stamp duty and CFD exemption", "futures roll cost statistics (CME)"]),
    ]),
    ("part.m1.futures", [
        dict(slug="18-futures-contracts-and-exchanges", title="Futures Contracts and Their Exchanges",
             hook="One E-mini contract controls a quarter of a million dollars of stock for a few thousand dollars of margin.",
             sections=["The contract", "The exchange groups", "Specifications: multiplier, tick, months", "Sessions, settlement and limits", "Who trades futures"],
             defines=["futures contract", "contract multiplier", "tick value", "expiry month code", "daily settlement price", "open interest", "price limit (futures)", "front month", "hedger", "speculator"],
             tutorial="A contract-spec table and notional, tick value and leverage for ten contracts.",
             build="Contract master (reference data).",
             problem="Sizing a hedge — named result: the number of contracts and the residual exposure.",
             facts=["CME ES, NQ, ZN, CL specs", "Eurex FESX, FGBL specs", "ICE Brent spec", "CME price limit/circuit breaker rules", "volumes by exchange (FIA)"]),
        dict(slug="19-matching-algorithms-and-implied-spreads", title="Matching Algorithms and Implied Spreads",
             hook="Two traders join the bid at the same price; in one product the first gets everything, in another they share.",
             sections=["Price-time priority", "Pro-rata and its variants", "Market-maker privileges", "Calendar spreads and implied prices", "What the feed shows"],
             defines=["price-time priority", "pro-rata allocation", "top-order allocation", "lead market maker", "calendar spread", "implied-in", "implied-out", "market-by-order", "market-by-price"],
             tutorial="Implement FIFO and pro-rata allocation and compare fills.",
             build="`firm.match`: allocation algorithms (used by the Book 10 matching engine).",
             problem="The implied book — named result: the implied best bid in the spread.",
             facts=["CME matching algorithm list (F, K, A, etc.)", "Eurex allocation methods", "CME implied functionality docs", "CME MBO availability"]),
        dict(slug="20-margin", title="Margin",
             hook="The position did not change overnight; the money required to hold it rose by half.",
             sections=["Variation margin", "Initial margin: scenario methods", "Initial margin: value-at-risk methods", "Portfolio offsets", "Procyclicality and intraday calls"],
             defines=["performance bond", "maintenance margin", "scanning range", "inter-commodity spread credit", "margin period of risk", "portfolio margining", "procyclicality", "intraday margin call"],
             tutorial="A SPAN-style scenario margin for a futures-and-options portfolio.",
             build="`firm.margin`: scenario margin engine.",
             problem="March 2020 — named result: the additional margin called on a fixed portfolio.",
             facts=["SPAN 16 scenarios description", "CME SPAN 2", "Eurex Prisma", "margin increases March 2020 (BIS/CFTC)", "LME nickel 2022 margin facts"]),
        dict(slug="21-basis-roll-and-delivery", title="Basis, Roll and Delivery",
             hook="The future trades eleven points above the index, and that is exactly right.",
             sections=["Cost of carry", "Fair value and index arbitrage", "The roll", "Delivery and final settlement", "Off-book mechanisms"],
             defines=["basis", "cost of carry", "fair value", "implied financing rate", "roll", "contango", "backwardation", "cash settlement", "physical delivery", "special opening quotation", "exchange for physical", "basis trade at index close", "trade at settlement"],
             tutorial="Fair value of an index future with discrete dividends; implied financing rate.",
             build="Fair-value calculator.",
             problem="Rolling a billion — named result: the cost of the roll in basis points per year.",
             facts=["CME SOQ procedure", "BTIC, TAS, EFP rule references", "WTI April 2020 settlement price and TAS role (CFTC report)", "quarterly roll dates"]),
        dict(slug="22-index-and-single-stock-futures-worldwide", title="Equity Index and Single-Stock Futures Worldwide",
             hook="The most traded equity index contract in the world is not American.",
             sections=["The main index contracts by region", "Dividend futures", "Total return futures", "Single-stock futures", "Trading hours and the global relay"],
             defines=["dividend future", "total return future", "single-stock future", "index point", "mini contract", "micro contract"],
             tutorial="Implied dividends from index futures and dividend futures.",
             build="Global contract calendar.",
             problem="The dividend curve — named result: the implied dividend growth.",
             facts=["FIA volume rankings (Nifty, Bank Nifty, Kospi)", "Eurex dividend futures, TRF specs", "SGX/HKEX contract specs", "single-stock futures venues"]),
    ]),
    ("part.m1.options", [
        dict(slug="23-option-contracts-and-exchanges", title="Option Contracts and the Options Exchanges",
             hook="One stock, two thousand option series, seventeen exchanges.",
             sections=["The contract", "Clearing of options", "The US options exchanges", "European venues", "Exercise, assignment and expiry"],
             defines=["call option", "put option", "strike price", "expiry", "option premium", "option series", "American exercise", "European exercise", "assignment", "option multiplier", "in the money"],
             tutorial="Parse option symbols (OSI) and build a chain; payoff diagrams.",
             build="Option-chain container.",
             problem="Expiry Friday — named result: the net share position after exercise and assignment.",
             facts=["OCC role and cleared volume", "number of US options exchanges", "OSI symbology", "exercise-by-exception threshold 0.01", "AM/PM settlement of SPX"]),
        dict(slug="24-options-market-structure", title="Options Market Structure",
             hook="A customer's ten-lot starts a 100-millisecond auction among the largest firms in the world.",
             sections=["Quote-driven markets and obligations", "Allocation: customer priority and pro-rata", "Price-improvement auctions", "Complex orders", "Penny increments, fees and order-flow payment"],
             defines=["options market maker", "quoting obligation", "customer priority", "price-improvement auction", "complex order book", "penny program", "marketing fee", "OPRA", "quote protection"],
             tutorial="Allocate an incoming order under customer-priority pro-rata with a market-maker entitlement.",
             build="Options allocation rules in `firm.match`.",
             problem="The auction — named result: the expected allocation to the initiating firm.",
             facts=["Cboe/ISE/PHLX allocation rules", "PIM/AIM timers", "Penny interval program permanent 2020", "OPRA message rates"]),
        dict(slug="25-volatility-first-contact", title="Volatility as a Traded Quantity: First Contact",
             hook="The option's price is 4.20; the trader says it is ``18 vol''.",
             sections=["Put-call parity with dividends and borrow", "Implied volatility", "Skew and term structure", "The volatility index", "Futures on volatility"],
             defines=["put--call parity", "implied volatility", "volatility skew", "term structure of volatility", "at-the-money", "volatility index", "variance", "realised volatility", "VIX future"],
             tutorial="Implied volatility by root finding; implied forward and borrow from parity.",
             build="Parity checker and implied-volatility solver.",
             problem="Reading a chain — named result: the implied dividend and the skew.",
             facts=["Cboe VIX methodology white paper", "VIX futures spec", "Feb 2018 VIX spike numbers"]),
        dict(slug="26-zero-day-options-and-retail-flow", title="Zero-Day Options, Weeklies and Retail Options Flow",
             hook="By mid-afternoon the most traded option in the world expires in two hours.",
             sections=["From monthlies to dailies", "Who trades short-dated options", "Gamma near expiry", "Dealer hedging and the underlying", "Retail options flow"],
             defines=["zero-day option", "weekly option", "gamma", "delta hedging", "dealer gamma", "pin risk"],
             tutorial="Gamma of an at-the-money option as expiry approaches; hedging flow for a price move.",
             build="Gamma-exposure estimator.",
             problem="The last hour — named result: shares to trade per 1% move.",
             facts=["0DTE share of SPX volume (Cboe)", "SPX daily expiries since 2022", "retail share of options volume (Cboe/OCC)"]),
        dict(slug="27-options-markets-europe-asia", title="Options Markets in Europe and Asia",
             hook="In 2024 more index option contracts traded in Mumbai than everywhere else combined.",
             sections=["Europe", "Korea", "India", "Other Asian markets", "The expiry-day case"],
             defines=["lot size (derivatives)", "notional turnover", "premium turnover", "weekly expiry", "position limit"],
             tutorial="Contract counts versus notional versus premium: three rankings of the same markets.",
             build="Turnover normaliser.",
             problem="Counting contracts — named result: premium turnover ratio between two markets.",
             facts=["FIA 2023/2024 volume by exchange", "NSE index option lot sizes and changes", "SEBI interim order July 2025 (Jane Street) facts", "SEBI F&O retail loss study", "Kospi 200 multiplier history"]),
    ]),
    ("part.m1.working", [
        dict(slug="28-reading-market-data", title="Reading Market Data",
             hook="Forty million messages before lunch, and one of them is wrong.",
             sections=["Levels of data", "Trades, quotes and condition codes", "Timestamps", "Symbology and reference data", "From raw feed to research table"],
             defines=["level 1", "level 2", "level 3", "trade condition", "exchange timestamp", "receive timestamp", "sequence number", "symbology", "reference data", "normalisation"],
             tutorial="Parse a binary order-by-order feed sample into a book and a trades table.",
             build="`firm.feed`: feed normaliser (C++/Rust decoder, Python reader).",
             problem="The bad tick — named result: the number of trades to exclude and the corrected VWAP.",
             facts=["Nasdaq ITCH 5.0 message spec", "CTA/UTP sale condition codes", "MiFID II RTS 25 clock sync", "CAT clock sync"]),
        dict(slug="29-getting-access-equities", title="Getting Access: Equity Markets",
             hook="A new firm has a strategy, ten million dollars and no way to send an order.",
             sections=["Member or client?", "Clearing arrangements", "Fee schedules and tiers", "Liquidity-provider programmes", "Data licences", "The negotiation"],
             defines=["clearing broker", "executing broker", "volume tier", "designated market maker", "supplemental liquidity provider", "non-display fee", "give-up (equities)"],
             tutorial="Net cost per share across three venues under tiered fees.",
             build="Fee-schedule engine.",
             problem="Reaching the tier — named result: the volume at which the better tier pays for itself.",
             facts=["NYSE/Nasdaq/Cboe fee schedule structure", "NYSE DMM/SLP programme rules", "non-display fee policies", "FINRA/SEC broker-dealer registration, net capital 15c3-1"]),
        dict(slug="30-getting-access-futures-options", title="Getting Access: Futures and Listed Options",
             hook="The same contract costs one firm 1.38 dollars a side and another 0.35.",
             sections=["The clearing broker", "Membership: buy, lease or stay outside", "Incentive and market-maker programmes", "Options market-maker appointments", "Data licences"],
             defines=["futures commission merchant", "clearing member", "exchange membership", "member rate", "incentive programme", "give-up", "market-maker appointment"],
             tutorial="Break-even volume for leasing a membership.",
             build="Futures fee engine.",
             problem="Lease or pay? — named result: break-even contracts per month.",
             facts=["CME fee schedule structure and membership types", "CME membership lease/seat prices (public)", "Eurex MM programmes", "Cboe MM appointment costs", "CFTC FCM list"]),
        dict(slug="31-stress-case-studies", title="Stress Case Studies",
             hook="At 14:45:28 on 6 May 2010 trading in the E-mini paused for five seconds.",
             sections=["6 May 2010", "24 August 2015", "5 February 2018", "January 2021", "What the four have in common"],
             defines=["flash crash", "stub quote", "limit up--limit down", "market-wide circuit breaker", "liquidity spiral", "clearly erroneous trade"],
             tutorial="Reconstruct a liquidity withdrawal in a simulated book.",
             build="Incident replay harness.",
             problem="Five seconds — named result: the depth that would have absorbed the sell programme.",
             facts=["CFTC-SEC 2010 report numbers", "SEC Aug 24 2015 research note", "XIV termination Feb 2018 (prospectus, press)", "SEC GameStop staff report", "LULD plan bands"]),
    ]),
]
