"""Book 2 (Markets II: Rates, FX and Credit) chapter briefs: data for
tools/make_briefs.py --book 2.

`uses` lists terms defined in One Quant Book 1 (or earlier in this book) that
the chapter relies on: they are NOT redefined (a term is defined once in the
series); the text points to the defining chapter in prose.
"""
SLUG = "markets-2"
PFX = "m2"
HEAD = "One Quant Book 2 — Markets II"

# (part key, [chapters]); chapter = dict(slug, title, hook, sections, defines,
# uses, tutorial, build, problem, facts)
PARTS = [
    ("part.m2.money", [
        dict(slug="01-central-banks-and-the-short-rate", title="Central Banks and the Short Rate",
             hook="At 14:00 New York time a one-paragraph statement moves every interest rate in the world; the overnight rate printed the next morning moved by exactly the amount announced.",
             sections=["Reserves and the central-bank balance sheet", "Corridor and floor systems", "Open-market operations and balance-sheet policy", "Overnight benchmarks and the end of the interbank offered rates"],
             defines=["reserves", "policy rate", "corridor system", "floor system", "standing facility", "open-market operation", "quantitative easing", "overnight benchmark rate", "interbank offered rate", "compounding in arrears", "fallback spread"],
             uses=["repurchase agreement", "general collateral", "settlement"],
             tutorial="Compound a month of overnight fixings in arrears with and without a five-day lookback; compare with a simple-interest average.",
             build="`firm.rfr`: overnight-rate compounding engine (in arrears, lookback, lockout, observation shift).",
             problem="The month the corridor moved — named result: the interest a reserve-rich bank earns versus a reserve-poor one over one maintenance period.",
             facts=["Fed administered rates (IORB, ON RRP) and target range now", "ECB deposit facility / MRO / MLF and the 2024 corridor narrowing", "BoE Bank Rate and its reserves remuneration", "SOFR, €STR, SONIA, TONA definitions and administrators, publication times", "LIBOR cessation dates (FCA 2021 announcement; synthetic end 2024)", "ISDA fallback spreads (5-year median, fixed March 2021)", "Fed balance-sheet size and QT programme"]),
        dict(slug="02-money-markets", title="Money Markets",
             hook="On the last business day of a quarter, the rate at which a bank will lend cash overnight jumps, and on the next morning it falls back.",
             sections=["Bills and their quoting conventions", "Commercial paper and certificates of deposit", "Money-market funds", "Turns: quarter-end and year-end"],
             defines=["Treasury bill", "discount yield", "money-market yield", "bond-equivalent yield", "commercial paper", "certificate of deposit", "money-market fund", "turn", "reverse repo facility"],
             uses=["repurchase agreement", "general collateral", "overnight benchmark rate", "policy rate"],
             tutorial="Convert a strip of bill quotes between discount, money-market and bond-equivalent yields and plot the resulting bill curve.",
             build="`firm.mmyield`: money-market quote converter.",
             problem="Parking cash over year-end — named result: the implied year-end turn from three quoted rates.",
             facts=["US bill conventions (discount basis, ACT/360, 4/8/13/17/26/52-week)", "ACT/365 vs ACT/360 by currency", "MMF size (ICI weekly data)", "ON RRP usage peak and recent level", "SEC 2023 MMF reforms", "2008 Reserve Primary Fund broke the buck"]),
        dict(slug="03-government-bonds", title="Government Bonds",
             hook="Two traders agree on a bond's yield to the fourth decimal and disagree on the price by 1{,}800 dollars per million: one quoted clean, the other dirty.",
             sections=["Cash flows, day counts and accrued interest", "Price and yield", "Duration, DV01 and convexity", "Zero-coupon rates, par yields and strips"],
             defines=["coupon", "par", "clean price", "dirty price", "accrued interest", "day-count convention", "yield to maturity", "Macaulay duration", "modified duration", "DV01", "convexity", "zero-coupon rate", "par yield", "STRIPS"],
             uses=["settlement", "notional"],
             tutorial="Price a bond from its yield on a real calendar, get accrued interest right across a coupon date, and check DV01 against a bumped reprice.",
             build="`firm.bond`: day counts, schedules, accrued interest, price/yield, DV01 (Python, C++20, Rust).",
             problem="The 32nds desk — named result: the hedge ratio that neutralises a two-bond position and the P&L it leaves after a 25 bp parallel move.",
             facts=["US Treasury note/bond conventions (semiannual, ACT/ACT, 32nds)", "Bund/gilt/JGB coupon frequencies and day counts", "STRIPS programme start (1985)", "US Treasury marketable debt outstanding"]),
        dict(slug="04-the-treasury-market", title="The Treasury Market",
             hook="At 13:00:00 the result of a ten-year auction appears on every screen; within a second the futures have moved half a point.",
             sections=["Auctions and primary dealers", "When-issued, on-the-run and off-the-run", "Inter-dealer and dealer-to-client", "Principal trading firms and the electronic market", "15 October 2014 and March 2020"],
             defines=["primary dealer", "uniform-price auction", "bid-to-cover ratio", "auction tail", "when-issued trading", "on-the-run", "off-the-run", "inter-dealer broker", "dealer-to-client platform", "flash rally", "dash for cash"],
             uses=["proprietary trading firm", "central counterparty", "clearing"],
             tutorial="Reconstruct an auction's stop-out yield, tail and bid-to-cover from a synthetic bid book.",
             build="`firm.tsyauction`: auction analyser (stop-out, tail versus when-issued, allotment).",
             problem="Tailing — named result: the tail at which a dealer's auction bid loses money against the when-issued close.",
             facts=["Treasury auction process (uniform price since 1998), results timing", "number of primary dealers (NY Fed list)", "Joint Staff Report on 15 Oct 2014 (yield range, timing)", "March 2020 dash-for-cash (FSB/Fed reports; Fed purchases)", "SEC Treasury clearing rule and compliance dates", "on/off-the-run spread evidence", "BrokerTec/eSpeed/Tradeweb as venues (public)"]),
        dict(slug="05-repo-and-specials", title="Repo and Specials",
             hook="On 17 September 2019 the overnight general-collateral repo rate printed near ten percent while the policy range stood near two.",
             sections=["The repo trade from both sides", "Tri-party, bilateral and sponsored", "Specials and specialness", "Fails and the fails charge", "September 2019"],
             defines=["repo rate", "reverse repo", "tri-party repo", "bilateral repo", "term repo", "special repo rate", "specialness", "sponsored repo", "fails charge"],
             uses=["repurchase agreement", "haircut", "general collateral", "special", "rehypothecation", "on-the-run"],
             tutorial="Value the specialness of an on-the-run note: the financing advantage over its expected special life.",
             build="`firm.repo`: repo book (trades, accrual, margin calls, specialness).",
             problem="The special — named result: the break-even price premium an on-the-run can carry given its expected specialness.",
             facts=["Sept 2019 repo spike (SOFR 5.25%, GC highs; Fed/BIS reports)", "TMPG fails charge formula (3% minus fed funds, floor 0)", "FICC sponsored service description", "tri-party repo mechanics (BNY)", "US repo market size (OFR data)"]),
        dict(slug="06-bond-futures", title="Bond Futures",
             hook="A futures contract on a ten-year note that does not exist: the short chooses which of a dozen real bonds to deliver, and the market prices the choice.",
             sections=["The contract and its basket", "Conversion factors and invoice price", "Cheapest-to-deliver", "Gross basis, net basis and implied repo", "The delivery options"],
             defines=["deliverable basket", "conversion factor", "invoice price", "cheapest-to-deliver", "gross basis", "net basis", "implied repo rate", "quality option", "wildcard option", "basis trade"],
             uses=["futures contract", "cost of carry", "physical delivery", "implied financing rate", "repo rate", "dirty price", "accrued interest"],
             tutorial="Compute conversion factors, gross and net basis and implied repo across a synthetic basket, and identify the CTD.",
             build="`firm.ctd`: CTD and basis analyser.",
             problem="The switch — named result: the yield level at which the cheapest-to-deliver switches, and the value of the switch option.",
             facts=["CBOT TY / ZN contract spec (6% notional coupon, deliverable maturities, tick 1/2 of 1/32)", "Eurex Bund future spec (6% coupon, 8.5-10.5y)", "delivery process timeline (CBOT)", "hedge-fund Treasury basis trade size (Fed notes / OFR)"]),
        dict(slug="07-european-and-japanese-government-bonds", title="European and Japanese Government Bonds",
             hook="On 28 September 2022 the Bank of England announced it would buy long gilts; the thirty-year yield fell more than a percentage point in a day.",
             sections=["The euro area: one currency, many issuers", "Spreads, backstops and the electronic dealer market", "Japan: yield-curve control and its exit", "The United Kingdom and the 2022 gilt crisis"],
             defines=["sovereign spread", "redenomination risk", "syndication", "Bund", "gilt", "yield-curve control", "liability-driven investment", "central-bank backstop"],
             uses=["primary dealer", "margin call", "leverage", "dealer-to-client platform"],
             tutorial="Build a spread monitor across euro-area ten-year yields and decompose one widening episode.",
             build="`firm.sovspread`: sovereign spread monitor.",
             problem="The collateral spiral — named result: the yield rise at which an LDI fund's collateral buffer is exhausted.",
             facts=["BoE 28 Sept 2022 intervention size and yield moves (BoE reports)", "BoE FPC LDI buffer guidance (250 bp)", "BoJ YCC start (Sept 2016), band changes, end (March 2024)", "ECB TPI (July 2022), OMT (2012)", "MTS as EGB interdealer venue", "euro-area issuance by syndication"]),
        dict(slug="08-short-term-interest-rate-futures", title="Short-Term Interest-Rate Futures",
             hook="Twelve days before a central-bank meeting the futures price implies a 62 percent chance of a cut; the desk has to decide whether that is too high.",
             sections=["Overnight-rate futures", "IMM dates, packs, bundles and strips", "Pricing a meeting", "The convexity adjustment"],
             defines=["overnight-rate future", "IMM date", "reference quarter", "futures strip", "pack", "bundle", "implied policy path", "convexity adjustment"],
             uses=["futures contract", "overnight benchmark rate", "compounding in arrears", "daily settlement price", "variation margin", "policy rate"],
             tutorial="Extract meeting-by-meeting policy expectations from a strip of one-month and three-month futures.",
             build="`firm.meetings`: policy-path extractor.",
             problem="Cut or hold — named result: the meeting probability implied by the futures and its sensitivity to the turn.",
             facts=["CME SOFR futures specs (1M average, 3M compounded)", "ICE SONIA / Euribor futures specs", "IMM dates definition", "FOMC meeting schedule current year", "Euribor still published (EMMI)"]),
    ]),
    ("part.m2.swaps", [
        dict(slug="09-interest-rate-swaps", title="Interest-Rate Swaps",
             hook="A company borrows at a floating rate and wants to sleep at night; a bank quotes it a fixed rate for ten years on a phone line, and hedges within the minute.",
             sections=["The swap and its legs", "Overnight index swaps and conventions", "Pricing, par rates and risk", "Swap spreads", "Execution facilities and compression"],
             defines=["interest-rate swap", "fixed leg", "floating leg", "payer swap", "receiver swap", "overnight index swap", "par swap rate", "annuity", "swap spread", "swap execution facility", "trade compression"],
             uses=["notional", "discount yield", "DV01", "compounding in arrears", "overnight benchmark rate"],
             tutorial="Bootstrap a single OIS curve from par rates, reprice the inputs, and compute bucketed DV01 of a ten-year swap.",
             build="`firm.curve`: OIS curve bootstrap and swap pricer.",
             problem="The corporate hedge — named result: the fixed rate and the DV01 of the ten-year hedge, and its P&L under a steepening.",
             facts=["swap conventions USD SOFR OIS (annual, ACT/360)", "BIS OTC derivatives statistics (IRS notional outstanding)", "negative 30y swap spreads (US, since 2008)", "CFTC SEF rule / made-available-to-trade", "compression volume (TriOptima/LCH public)"]),
        dict(slug="10-swap-clearing-and-the-ccp-basis", title="Swap Clearing and the Clearing-House Basis",
             hook="The same ten-year swap, with the same dates and the same rate, is worth two basis points more at one clearing house than at the other.",
             sections=["The clearing mandate", "The competing clearing houses", "Initial margin, cleared and uncleared", "Why the same swap has two prices"],
             defines=["clearing mandate", "client clearing", "porting", "uncleared margin rules", "credit support annex", "CCP basis"],
             uses=["central counterparty", "initial margin", "variation margin", "default fund", "futures commission merchant", "interest-rate swap", "margin period of risk"],
             tutorial="Price the CCP basis from margin funding: simulate the initial-margin profile of a directional book at two clearing houses.",
             build="`firm.ccpbasis`: margin-funding cost of a book at two CCPs.",
             problem="The one-way book — named result: the basis at which moving the book is break-even.",
             facts=["G20 2009 Pittsburgh commitment", "CFTC/EMIR clearing mandates", "LCH SwapClear / CME cleared volumes (public)", "LCH–CME basis evidence (public articles)", "UMR phases and thresholds (BCBS-IOSCO)", "EMIR 3 active-account requirement"]),
        dict(slug="11-inflation-markets", title="Inflation Markets",
             hook="A thirty-year bond whose coupons are adjusted for prices gained 37 percent less than it promised to protect, because its real yield had been minus two.",
             sections=["Index-linked bonds", "Real yields and breakevens", "Zero-coupon inflation swaps", "Indexation lag and seasonality"],
             defines=["index-linked bond", "reference index", "real yield", "breakeven inflation rate", "indexation lag", "zero-coupon inflation swap", "inflation seasonality", "deflation floor"],
             uses=["yield to maturity", "par swap rate", "coupon"],
             tutorial="Compute breakevens from a nominal and a linker curve and estimate monthly CPI seasonality from index data.",
             build="`firm.breakeven`: breakeven and inflation-carry calculator with seasonality.",
             problem="The linker's carry — named result: the monthly carry of a linker position in a high-inflation print.",
             facts=["TIPS conventions (3-month lag, CPI-U NSA, deflation floor at par)", "UK index-linked gilts (8-month then 3-month lag)", "OATi/€i and HICPxT", "US CPI release data (BLS; free)", "real-yield 2020–2022 moves"]),
        dict(slug="12-mortgages-and-agencies", title="Mortgages and Agencies",
             hook="When rates fall half a point, a thirty-year mortgage bond gains less than a Treasury, and its holders sell Treasuries to catch up.",
             sections=["The agency pass-through", "Prepayment", "The to-be-announced market and dollar rolls", "Negative convexity and its hedging flows"],
             defines=["agency mortgage-backed security", "pass-through", "prepayment", "conditional prepayment rate", "PSA benchmark", "to-be-announced trade", "specified pool", "dollar roll", "effective duration", "negative convexity"],
             uses=["convexity", "DV01", "repurchase agreement", "cost of carry"],
             tutorial="Project the cash flows of a pass-through under several prepayment speeds and compute its effective duration.",
             build="`firm.prepay`: pass-through cash-flow engine.",
             problem="The refinancing wave — named result: the effective duration at the money and the hedge a servicer must buy after a 50 bp rally.",
             facts=["Agency MBS market size (SIFMA)", "TBA good-delivery rules (SIFMA guidelines)", "PSA benchmark definition", "Fed MBS holdings", "1994 and 2003 convexity events (public accounts)"]),
        dict(slug="13-the-rates-options-market", title="The Rates Options Market",
             hook="A broker reads out a column of numbers in basis points a day; they are volatilities, and nobody on the line uses a percentage.",
             sections=["Caps and floors", "Swaptions", "Normal volatility", "The volatility cube and who trades it"],
             defines=["caplet", "cap", "floor", "callable bond", "swaption", "payer swaption", "receiver swaption", "normal volatility", "Bachelier model", "volatility cube"],
             uses=["implied volatility", "annuity", "par swap rate", "negative convexity"],
             tutorial="Convert between normal and lognormal quotes and price a swaption straddle from a cube slice.",
             build="`firm.normalvol`: Bachelier pricer and quote converter.",
             problem="The callable issuer — named result: the vega a bank acquires from swapping one callable issue, and the swaption it sells to lay it off.",
             facts=["market quoting in normal vol (bp/day, bp/year)", "negative rates made Black unusable (EUR 2015+)", "callable issuance and structural vega flows (public BIS/ECB)"]),
    ]),
    ("part.m2.fx", [
        dict(slug="14-the-fx-market", title="The FX Market",
             hook="Nine trillion dollars' worth of currency changes hands on an average day, and there is no exchange.",
             sections=["Currencies, pairs and conventions", "Dealers, tiers and the over-the-counter structure", "Primary venues and electronic networks", "Single-dealer platforms and prime brokerage", "What the turnover surveys say"],
             defines=["currency pair", "base currency", "quote currency", "pip", "spot value date", "cross rate", "primary venue", "electronic communication network", "single-dealer platform", "FX prime brokerage"],
             uses=["market maker", "prime broker", "broker"],
             tutorial="Compute spot dates across holiday calendars and triangulate crosses with bid and ask.",
             build="`firm.fxpairs`: pair conventions, spot dates and cross rates.",
             problem="The cross — named result: the widest arbitrage-free bid-ask of a cross given two legs.",
             facts=["BIS Triennial Survey 2025 turnover numbers", "EBS and Refinitiv Matching as primary venues", "CLS volumes", "T+2 spot, USDCAD T+1", "market convention ranking EUR>GBP>AUD>NZD>USD>..."]),
        dict(slug="15-fx-spot-microstructure", title="FX Spot Microstructure",
             hook="A price streamed at 10:00:00.000 is hit at 10:00:00.003 and rejected at 10:00:00.090: the client asks why.",
             sections=["Streaming prices and tiered liquidity", "Adverse selection", "Last look and hold times", "Skewing and internalisation", "The global code of conduct"],
             defines=["streaming quote", "liquidity tier", "mark-out", "last look", "hold time", "reject rate", "quote skewing", "FX Global Code"],
             uses=["internalisation", "market maker", "adverse selection", "single-dealer platform"],
             tutorial="Measure a liquidity provider's reject rate and post-trade mark-outs as a function of hold time on a simulated stream.",
             build="`firm.lastlook`: last-look TCA (fill ratio, mark-outs, hold times).",
             problem="The asymmetric window — named result: the value a symmetric versus asymmetric last-look policy transfers from the client.",
             facts=["FX Global Code principle 17 (last look)", "EBS minimum quote life / latency floor", "FCA/NY DFS last-look enforcement (Barclays 2015)", "GFXC disclosure templates"]),
        dict(slug="16-fx-swaps-forwards-and-the-cross-currency-basis", title="FX Swaps, Forwards and the Cross-Currency Basis",
             hook="A Japanese insurer buys US Treasuries and hedges the dollars back to yen; the hedge costs more than the extra yield.",
             sections=["Outright forwards and forward points", "FX swaps and short-dated rolls", "Covered interest parity", "The cross-currency basis", "Dollar funding stress"],
             defines=["outright forward", "forward points", "FX swap", "tom-next", "covered interest parity", "cross-currency basis swap", "cross-currency basis"],
             uses=["currency pair", "spot value date", "interest-rate swap", "overnight benchmark rate"],
             tutorial="Compute forward points from two curves, then back out the implied basis from market points.",
             build="`firm.fxfwd`: forward-points and basis calculator.",
             problem="The hedged yield — named result: the currency-hedged yield of a ten-year Treasury for a yen investor.",
             facts=["BIS on CIP deviations post-2008 (Borio et al.)", "FX swaps as most traded instrument (Triennial)", "Fed central-bank swap lines (2008, 2020)", "quarter-end basis spikes"]),
        dict(slug="17-fixings-and-flows", title="Fixings and Flows",
             hook="At 15:59:30 London time the chat rooms go quiet; at 16:00:00 the fix is struck; at 16:02 the price is back where it started.",
             sections=["The benchmark fix", "Month-end and index rebalancing flows", "Option expiries and the cuts", "The fixing scandal and what changed"],
             defines=["benchmark fix", "fixing window", "fixing order", "month-end rebalancing", "option cut", "banging the close"],
             uses=["benchmark", "currency pair", "FX Global Code", "tracking error"],
             tutorial="Estimate a month-end hedge-rebalancing flow from equity returns and a hedge ratio.",
             build="`firm.fixflow`: month-end flow estimator.",
             problem="Guaranteed at the fix — named result: the dealer's expected P&L on a fixing order with and without pre-hedging.",
             facts=["WM/Reuters 4pm fix, window lengthened to 5 min in 2015", "FCA Nov 2014 fines (amounts, banks)", "CFTC/DOJ FX actions 2014-2015 (outcomes)", "10am NY cut, 3pm Tokyo cut", "ECB reference rate 14:15 CET"]),
        dict(slug="18-emerging-market-fx-and-ndfs", title="Emerging-Market FX and Non-Deliverable Forwards",
             hook="On 15 January 2015 at 09:30 Zurich time the euro fell from 1.20 francs to below 0.90 within minutes.",
             sections=["Convertibility and capital controls", "Onshore and offshore markets", "Non-deliverable forwards", "Pegs, bands and interventions", "The franc unpeg"],
             defines=["convertibility", "capital control", "non-deliverable forward", "fixing source", "onshore market", "offshore market", "currency peg", "currency band", "FX intervention"],
             uses=["outright forward", "forward points", "benchmark fix", "cash settlement"],
             tutorial="Settle an NDF against its fixing and compute the onshore–offshore basis from two forward curves.",
             build="`firm.ndf`: NDF settlement and onshore/offshore basis.",
             problem="The floor that broke — named result: the loss on a 20:1 leveraged EURCHF long at the first quoted price after the unpeg.",
             facts=["SNB 15 Jan 2015 announcement (floor 1.20 since Sept 2011)", "EURCHF low on the day", "broker losses (FXCM, public filings/press)", "CNY vs CNH, PBoC fixing band", "EMTA NDF fixing sources", "HKD band 7.75-7.85"]),
        dict(slug="19-the-fx-options-market", title="The FX Options Market",
             hook="Asked for the twenty-five delta risk reversal, the broker answers 1.2 puts over; a new trader writes it down without knowing which side pays.",
             sections=["Delta and at-the-money conventions", "Risk reversals, butterflies and the smile", "Premium currency and premium-adjusted delta", "Broker markets and barrier-driven flows"],
             defines=["spot delta", "forward delta", "premium-adjusted delta", "delta-neutral straddle", "risk reversal", "strangle", "butterfly", "barrier option", "knock-out option", "knock-in option"],
             uses=["implied volatility", "volatility skew", "at-the-money", "delta hedging", "option cut", "forward points"],
             tutorial="Recover the 25-delta call and put strikes and vols from ATM, RR and BF quotes with each delta convention.",
             build="`firm.fxsmile`: quote-to-smile converter.",
             problem="The barrier defence — named result: the notional of spot the option desk must trade at the barrier.",
             facts=["market conventions (Clark / Wystup) for delta and ATM", "OTC FX options turnover (Triennial)", "USDJPY or EURCHF barrier episodes (public)"]),
        dict(slug="20-settlement-risk", title="Settlement Risk",
             hook="On 26 June 1974 German regulators closed a bank at 15:30 Frankfurt time; its counterparties in New York had already paid their marks and never received their dollars.",
             sections=["Herstatt", "Payment versus payment", "Netting", "What remains unprotected"],
             defines=["settlement risk", "Herstatt risk", "payment versus payment", "payment netting", "unilateral irrevocable payment time"],
             uses=["delivery versus payment", "currency pair", "spot value date", "central counterparty"],
             tutorial="Build the settlement-exposure timeline of a day's FX trades across time zones, gross and under PvP.",
             build="`firm.settlerisk`: settlement-exposure calculator.",
             problem="The unsettled trillion — named result: the peak exposure of a gross-settled book and the reduction from netting and PvP.",
             facts=["Herstatt 1974 timeline (BIS)", "CLS settlement window, currencies, share of market (BIS 2022/2025)", "BIS settlement-risk estimates (2022 Triennial: $2.2tn unsettled)", "Basel Committee FX settlement guidance (2013)"]),
    ]),
    ("part.m2.credit", [
        dict(slug="21-corporate-bonds", title="Corporate Bonds",
             hook="A company rated one notch above junk is downgraded; by Monday its bonds are owned by different people.",
             sections=["Issuance and the new-issue concession", "Ratings and the investment-grade line", "The family of spread measures", "Covenants, seniority and recovery"],
             defines=["investment grade", "high yield", "credit rating", "fallen angel", "new-issue concession", "credit spread", "G-spread", "I-spread", "Z-spread", "asset-swap spread", "option-adjusted spread", "covenant", "seniority", "recovery rate"],
             uses=["yield to maturity", "par swap rate", "underwriting", "benchmark", "callable bond"],
             tutorial="Compute G-, I-, Z- and asset-swap spreads of one bond and show why they differ.",
             build="`firm.spreads`: spread-measure library.",
             problem="The fallen angel — named result: the forced-selling discount given index exit and the recovery of the spread afterwards.",
             facts=["rating scales (S&P/Moody's) and IG cut-off", "US corporate bond market size (SIFMA)", "Moody's recovery statistics by seniority", "fallen-angel price effect literature"]),
        dict(slug="22-how-bonds-trade", title="How Bonds Trade",
             hook="A portfolio manager sends one request for quote covering 400 bonds; four dealers answer in eleven minutes with a single price.",
             sections=["Request for quote", "Trade reporting and transparency", "All-to-all and portfolio trading", "Bond ETFs as a liquidity layer", "Algorithmic dealer pricing"],
             defines=["request for quote", "trade reporting", "dissemination cap", "all-to-all trading", "portfolio trade", "axe", "composite price"],
             uses=["exchange-traded fund", "authorised participant", "creation basket", "dealer-to-client platform", "net asset value"],
             tutorial="Simulate RFQ competition among dealers and measure winning-spread distribution versus number of dealers queried.",
             build="`firm.rfq`: RFQ auction simulator with composite pricing.",
             problem="How many dealers? — named result: the number of dealers to query that minimises expected cost including information leakage.",
             facts=["TRACE start (2002) and dissemination caps ($5mm IG, $1mm HY)", "MarketAxess/Tradeweb e-trading share (public filings)", "portfolio trading growth (public)", "EU bond transparency / consolidated tape"]),
        dict(slug="23-credit-default-swaps", title="Credit Default Swaps",
             hook="In 2009 a bank had to pay 91.5 cents on the dollar after an auction that lasted two rounds.",
             sections=["The standard contract", "Upfront and running", "Credit events and determinations committees", "Settlement auctions", "The cheapest-to-deliver option"],
             defines=["credit default swap", "protection buyer", "protection seller", "reference entity", "credit event", "determinations committee", "auction final price", "standard coupon", "upfront payment", "hazard rate", "survival probability"],
             uses=["recovery rate", "cheapest-to-deliver", "credit spread", "annuity", "central counterparty"],
             tutorial="Convert running spread to upfront with a flat hazard curve and verify against the par spread.",
             build="`firm.cds`: CDS pricer, flat hazard (Python, C++20, Rust).",
             problem="The auction — named result: the final price from a two-stage auction and each participant's settlement.",
             facts=["2009 Big Bang (standard coupons 100/500, auction hardwiring)", "ISDA DC composition and role", "CDS auction results (e.g. Lehman 8.625, GM) from Creditex/ISDA", "2014 Definitions", "CDS notional (BIS)"]),
        dict(slug="24-credit-indices-and-tranches", title="Credit Indices and Tranches",
             hook="In spring 2012 a single desk's index position grew so large that other funds traded against its skew; the bank lost more than six billion dollars.",
             sections=["The index families and their rolls", "Index versus constituents", "Tranches", "Index options"],
             defines=["credit index", "index series", "intrinsic spread", "index skew", "tranche", "attachment point", "detachment point", "base correlation", "credit index option"],
             uses=["credit default swap", "on-the-run", "roll", "survival probability", "standard coupon"],
             tutorial="Compute an index's intrinsic spread from its constituents and the skew; value tranche expected losses with a one-factor Gaussian model.",
             build="`firm.tranche`: index intrinsic and large-pool tranche loss.",
             problem="The skew trade — named result: the P&L of an index-versus-intrinsic position when the skew closes.",
             facts=["CDX/iTraxx roll dates (March/Sept), 125 names", "JPMorgan 2012 losses (Senate report, SEC order)", "S&P/IHS Markit ownership of indices", "tranche market post-2008"]),
        dict(slug="25-loans-clos-and-securitisation", title="Loans, CLOs and Securitisation",
             hook="A private-equity firm borrows two billion dollars to buy a company; within a month the loan sits in forty separate vehicles.",
             sections=["The leveraged-loan market", "Securitisation", "The CLO waterfall and its tests", "Who holds which tranche"],
             defines=["leveraged loan", "term loan B", "covenant-lite", "securitisation", "special-purpose vehicle", "collateralised loan obligation", "payment waterfall", "overcollateralisation test", "interest-coverage test", "equity tranche"],
             uses=["tranche", "attachment point", "seniority", "credit rating"],
             tutorial="Run a CLO waterfall through a default wave and watch the OC test divert cash.",
             build="`firm.waterfall`: CLO waterfall engine.",
             problem="The test that trips — named result: the default rate at which the equity tranche stops receiving cash.",
             facts=["US leveraged loan market size", "CLO market size", "CLO tranche structure typical", "covenant-lite share", "risk-retention rules"]),
        dict(slug="26-distressed-sovereign-and-bank-capital-credit", title="Distressed, Sovereign and Bank-Capital Credit",
             hook="On 19 March 2023 a regulator's statement wiped out sixteen billion Swiss francs of bonds while the same bank's shareholders were paid.",
             sections=["Restructuring and exchange offers", "Sovereign debt: collective-action clauses and holdouts", "Bank capital: contingent convertibles", "The 2023 write-down"],
             defines=["distressed debt", "exchange offer", "collective action clause", "holdout creditor", "pari passu clause", "contingent convertible bond", "additional tier 1", "point of non-viability", "bail-in"],
             uses=["recovery rate", "seniority", "credit event"],
             tutorial="Value a distressed exchange offer against holding out, with a probability tree over outcomes.",
             build="`firm.recovery`: restructuring-offer valuation.",
             problem="Hold out or tender — named result: the tender participation above which holding out stops paying.",
             facts=["Credit Suisse AT1 write-down CHF 16bn (FINMA)", "Greece 2012 PSI and CAC use", "Argentina pari passu litigation (NML v Argentina)", "AT1 market size", "EU single-limb aggregated CACs 2022"]),
    ]),
    ("part.m2.access", [
        dict(slug="27-getting-access-fx", title="Getting Access: FX",
             hook="A new systematic fund has a strategy that trades a billion euros a day and no bank that will let it.",
             sections=["Prime-broker credit and give-up lines", "Limits: net open position and settlement", "Becoming a liquidity provider on venues and single-dealer platforms", "Brokerage, disclosures and reviews"],
             defines=["give-up line", "net open position limit", "settlement limit", "prime-of-prime", "designation notice", "liquidity-provider review"],
             uses=["FX prime brokerage", "give-up", "last look", "reject rate", "settlement risk"],
             tutorial="Implement a pre-trade check that enforces NOP and settlement limits per prime broker.",
             build="`firm.pblimits`: pre-trade credit-limit gate (C++20, Rust; Python reader).",
             problem="Three prime brokers — named result: the allocation of flow that keeps every limit and minimises cost.",
             facts=["FX PB market structure after 2015 SNB (public)", "PB fee ranges (EXCLUDED unless public)", "venue LP onboarding requirements (EBS/LSEG rulebooks)", "GFXC disclosure cover sheets"]),
        dict(slug="28-getting-access-rates-credit", title="Getting Access: Rates and Credit",
             hook="Before the first swap, the lawyers: a master agreement, a schedule, a credit support annex and an identifier, weeks of work for a trade that takes a second.",
             sections=["Documentation before the first trade", "Dealer and client status on the platforms", "Inter-dealer access for non-banks", "Sponsored repo and clearing membership", "Swap clearing brokers"],
             defines=["ISDA master agreement", "Global Master Repurchase Agreement", "legal entity identifier", "sponsored member", "clearing broker (swaps)"],
             uses=["credit support annex", "sponsored repo", "futures commission merchant", "inter-dealer broker", "dealer-to-client platform", "clearing member"],
             tutorial="Cost out three ways to access Treasury repo and swaps for a mid-size fund.",
             build="`firm.clearcost`: access-cost model.",
             problem="Build or rent — named result: the balance-sheet size at which direct clearing membership beats a clearing broker.",
             facts=["ISDA 1992/2002 master agreements", "GMRA (ICMA) 2011", "LEI (GLEIF), cost", "FICC sponsored membership rules", "BrokerTec/ICAP non-bank access (public)", "CME/LCH FCM client clearing"]),
    ]),
    ("part.m2.craft", [
        dict(slug="29-thinking-in-expected-value", title="Thinking in Expected Value",
             hook="A coin lands heads with probability 0.6 and you may bet any fraction of your wealth, again and again; most people who try it on a screen go broke.",
             sections=["Edge and odds", "The Kelly criterion", "Fractional Kelly and risk of ruin", "When the edge itself is uncertain"],
             defines=["edge", "odds", "Kelly criterion", "fractional Kelly", "growth rate", "risk of ruin", "drawdown"],
             uses=["leverage"],
             tutorial="Simulate repeated bets at several Kelly fractions and plot the distribution of terminal wealth.",
             build="`firm.sizing`: sizing module (Kelly, fractional, drawdown-constrained).",
             problem="The uncertain edge — named result: the optimal Kelly fraction when the edge is estimated from 200 trades.",
             facts=["Kelly 1956 paper", "Thorp", "Haghani & Dewey 2016 coin-flip experiment"]),
        dict(slug="30-market-making-games", title="Market-Making Games",
             hook="An interviewer says: make me a market on the number of windows in this building. You answer 200 at 400. She says: I buy.",
             sections=["Make me a market", "Updating on trades", "Adverse selection around a table", "The training games firms describe"],
             defines=["make-me-a-market", "width", "inventory", "Bayesian update", "winner's curse"],
             uses=["market maker", "bid--ask spread", "adverse selection", "edge"],
             tutorial="Play a simulated card-sum market against informed and uninformed bots and plot P&L by width.",
             build="`firm.mmgame`: market-making game engine.",
             problem="The card-sum market — named result: the width that maximises expected P&L against the table's mix of traders.",
             facts=["public descriptions of trading games (firm blogs/careers pages)", "Glosten-Milgrom 1985"]),
        dict(slug="31-reading-a-macro-calendar-and-a-rates-screen", title="Reading a Macro Calendar and a Rates Screen",
             hook="At 08:29:59 on the first Friday of the month the Treasury market is silent; at 08:30:00 it trades more in one second than in the previous hour.",
             sections=["The calendar", "Consensus and surprise", "Positioning into events", "Reading curve shapes", "A rates screen at a glance"],
             defines=["economic release", "consensus forecast", "data surprise", "blackout period", "steepener", "flattener", "curve fly", "bull steepening", "bear flattening"],
             uses=["policy rate", "DV01", "par swap rate", "swap spread", "cross-currency basis", "implied policy path"],
             tutorial="Build a release calendar, measure surprise-to-yield-move sensitivities on synthetic data, and summarise a curve screen.",
             build="`firm.macrocal`: event calendar and curve-shape summary.",
             problem="Payrolls Friday — named result: the DV01-neutral 2s10s position size and its P&L under the surprise.",
             facts=["BLS employment situation timing (08:30 ET, first Friday)", "FOMC blackout rules", "US CPI release time", "ECB meeting schedule"]),
    ]),
]
