"""Book 6 (Rates, Credit, XVA and Risk) chapter briefs: data for
tools/make_briefs.py --book 6.

`uses` lists terms defined elsewhere that the chapter relies on: they are NOT
redefined (a term is defined once in the series); the text points to the
defining chapter in prose. Each use carries its owner in parentheses:
(B1.7) = One Quant Book 1, chapter 7 (checked against the harvested \\index{}
entries of Books 1-2); (B4.5) = a batch book's chapter by the outline, to be
confirmed at the sync; (ch3) = an earlier chapter of this book.

Ownership (sources/BATCH_BOOKS_3-6.md): Book 2 owns the rates, FX and credit
market and product terms; Book 4 the mathematics (numeraire, forward and
annuity measures, Girsanov, Monte Carlo, regression methods, PCA, splines);
Book 5 option pricing, the Greeks and SABR; Book 3 the commodity products.
This book owns the rates and credit models, XVA, and risk measures and
processes. Chapter 29 (the risk engine on Book 5's pricing library) is
written last, against code/firm/INTERFACES.md.
"""
SLUG = "rates-credit-risk"
PFX = "rc"
HEAD = "One Quant Book 6 — Rates, Credit, XVA and Risk"

# (part key, [chapters]); chapter = dict(slug, title, hook, sections, defines,
# uses, tutorial, build, problem, facts)
PARTS = [
    ("part.rc.rates", [
        dict(slug="01-curve-construction", title="Curve Construction",
             hook="A rates desk changes its curve interpolation over a weekend; on Monday no market price has moved, yet the book shows a profit of 180 thousand dollars and every hedge ratio has shifted.",
             sections=["Choosing the instruments", "Calibration: bootstrap and global fit", "Interpolation and the forward curve", "The front end: futures, turns and meeting dates", "Hedging consequences of an interpolation"],
             defines=["pillar", "instantaneous forward rate", "curve calibration", "flat-forward interpolation", "monotone convex interpolation", "interpolation locality", "Nelson--Siegel curve"],
             uses=["par swap rate (B2.9)", "overnight index swap (B2.9)", "annuity (B2.9)", "zero-coupon rate (B2.3)", "DV01 (B2.3)", "overnight-rate future (B2.8)", "convexity adjustment (B2.8)", "IMM date (B2.8)", "turn (B2.2)", "implied policy path (B2.8)", "cubic spline (B4.28)"],
             tutorial="Build the same SOFR curve from deposits, futures and swaps with four interpolations (linear zero, flat forward, natural cubic on zeros, monotone convex); plot the forward curves and the bucketed DV01 of an off-pillar swap under each.",
             build="`firm.curvebuild`: multi-instrument curve builder with pluggable interpolators, global Newton calibration and its Jacobian; imports `firm.curve` (Book 2), never edits it.",
             problem="The Monday profit — named result: the P&L and the change in hedge notionals produced on a USD 5 billion swap book by switching from linear-zero to monotone-convex interpolation.",
             facts=["Hagan and West 2006, monotone convex method (paper)", "Nelson-Siegel 1987 and Svensson 1994 (papers)", "Fed (Gürkaynak-Sack-Wright 2007) and ECB published curve-fitting methods", "SOFR futures and swaps as the dollar curve's instruments (CME volume, dated)", "year-end turn size evidence (public)"]),
        dict(slug="02-multi-curve-and-collateral-discounting", title="Multi-Curve and Collateral Discounting",
             hook="In August 2007 the spread between three-month Euribor and the overnight swap rate for the same three months jumped from under ten basis points to over sixty, and every single-curve pricer on the Street became wrong overnight.",
             sections=["The 2007 break and the tenor basis", "Discount curves and projection curves", "Collateral discounting and the credit support annex", "Collateral choice and cross-currency collateral", "After the interbank rates: the 2020 discounting switches"],
             defines=["projection curve", "discount curve", "multi-curve framework", "tenor basis", "tenor basis swap", "collateral rate", "CSA discounting", "collateral choice option", "price alignment interest", "discounting switch"],
             uses=["interbank offered rate (B2.1)", "overnight index swap (B2.9)", "credit support annex (B2.10)", "cross-currency basis (B2.16)", "cross-currency basis swap (B2.16)", "variation margin (B1.5)", "central counterparty (B1.5)", "fallback spread (B2.1)", "cheapest-to-deliver (B2.6)", "numeraire (B4.5)", "forward measure (B4.5)", "pillar (ch1)", "curve calibration (ch1)"],
             tutorial="Build a six-month Euribor projection curve on an euro short-term rate discount curve; price the same swap under Euribor-flat, OIS and dollar-collateral discounting and explain each difference.",
             build="`firm.multicurve`: discount curve per collateral currency and projection curve per index, dual-curve swap pricer; imports `firm.curvebuild`.",
             problem="The discounting-switch weekend — named result: the value transfer on a 30-year receiver swap at the October 2020 SOFR switch and the basis-swap hedge that neutralised it.",
             facts=["Euribor-EONIA basis in 2007-08 (ECB/BIS papers)", "LCH and CME euro switch to €STR discounting and PAI (July 2020)", "SOFR discounting switch of 16-17 October 2020, cash compensation and basis-swap auction", "EONIA cessation 3 January 2022", "Piterbarg 2010 'Funding beyond discounting' (paper)"]),
        dict(slug="03-rates-risk", title="Rates Risk",
             hook="A swap book with zero parallel DV01 loses three million dollars on a day when two-year rates fell eight basis points and thirty-year rates rose six.",
             sections=["Bucketed sensitivities and risk ladders", "From par risk to zero risk: the Jacobian", "Principal components of the curve", "Hedging a swap book", "Gamma and cross-gamma"],
             defines=["bucketed sensitivity", "risk ladder", "key-rate duration", "curve Jacobian", "level factor", "slope factor", "curvature factor", "cross-gamma"],
             uses=["DV01 (B2.3)", "convexity (B2.3)", "par swap rate (B2.9)", "steepener (B2.31)", "flattener (B2.31)", "curve fly (B2.31)", "principal component analysis (B4.22)", "shrinkage (B4.22)", "bump-and-reprice (B5.4)", "pillar (ch1)", "curve calibration (ch1)"],
             tutorial="Compute the par-rate risk ladder of a 200-swap book, map it to zero-rate risk through the Jacobian, run a PCA on daily US Treasury par-yield changes, and find the three-swap hedge that minimises residual variance.",
             build="`firm.ratesrisk`: risk ladders, Jacobian transforms, PCA of curve moves, minimum-variance hedge solver.",
             problem="The twisted Tuesday — named result: the loss of a DV01-flat book explained by the first three components, and the three-swap hedge that removes 95 per cent of its variance.",
             facts=["US Treasury daily par yield curve (treasury.gov, public domain)", "Litterman and Scheinkman 1991: share of variance of level, slope, curvature", "day of the hook: a real twist day from the Treasury data"]),
        dict(slug="04-vanilla-rates-options", title="Vanilla Rates Options",
             hook="In 2014 euro rates went below zero and the broker screens that had quoted caps and swaptions in lognormal volatility for twenty years began printing blanks.",
             sections=["Black and Bachelier for rates", "Caps, floors and caplet stripping", "Swaptions: physical and cash settlement", "Vega, the smile at a glance, and the choice of model"],
             defines=["lognormal volatility", "flat volatility", "caplet volatility", "caplet stripping", "cash-settled swaption", "cash annuity"],
             uses=["caplet (B2.13)", "cap (B2.13)", "floor (B2.13)", "swaption (B2.13)", "payer swaption (B2.13)", "receiver swaption (B2.13)", "Bachelier model (B2.13)", "normal volatility (B2.13)", "volatility cube (B2.13)", "annuity (B2.9)", "implied volatility (B1.25)", "Black model (B5.3)", "vega (B5.4)", "forward measure (B4.5)", "annuity measure (B4.5)", "projection curve (ch2)", "discount curve (ch2)"],
             tutorial="Strip caplet volatilities from a ladder of flat cap volatilities; price swaptions under Black and Bachelier; compare a cash-settled swaption on the cash annuity with its physical twin.",
             build="`firm.capfloor`: cap, floor and swaption pricer on the multi-curve, flat-to-caplet stripping, cash annuity; reuses `firm.normalvol`.",
             problem="The treasurer's cap — named result: the premium, vega and break-even rate of a five-year cap bought to protect a floating-rate loan.",
             facts=["ECB deposit facility rate negative from June 2014 to July 2022 (ECB)", "the move of rates-option quoting to normal volatility (public)", "ISDA collateralised cash price settlement for EUR swaptions (2018)", "rates options market size (BIS OTC statistics, dated)"]),
        dict(slug="05-sabr-in-rates-and-the-volatility-cube", title="SABR in Rates and the Volatility Cube",
             hook="In 2015 a desk asked its SABR calibrator for the volatility of a receiver swaption struck at minus twenty basis points; the formula returned a complex number.",
             sections=["SABR in rates: normal SABR and the backbone", "Negative rates and shifted models", "Building the cube smile by smile", "Interpolating in expiry, tenor and strike", "Arbitrage in the wings"],
             defines=["swaption matrix", "shifted lognormal model", "shifted SABR", "normal SABR", "effective lower bound"],
             uses=["SABR model (B5.11)", "backbone (B5.11)", "static arbitrage (B5.7)", "butterfly arbitrage (B5.7)", "risk-neutral density (B5.7)", "Hagan formula (B5.11)", "volatility cube (B2.13)", "normal volatility (B2.13)", "Bachelier model (B2.13)", "swaption (B2.13)", "lognormal volatility (ch4)", "caplet volatility (ch4)"],
             tutorial="Calibrate shifted SABR smile by smile to a synthetic euro cube on a 5x5 expiry-tenor grid, interpolate a missing section, and check the implied density for negativity in the low-strike wing.",
             build="`firm.sabrcube`: the cube as expiry x tenor x strike sections with shifted-SABR parameters, interpolation and a density check; calls Book 5's SABR formula through the frozen interface if it exposes one.",
             problem="The minus-fifty strike — named result: the price of a deep receiver under shifts of 1 and 3 per cent, and the smallest shift for which the density stays positive.",
             facts=["ECB deposit facility rate low of -0.50% (2019-2022)", "broker shift conventions for EUR swaption quotes (dated)", "Hagan et al. 2002 'Managing smile risk'", "Antonov, Konikov, Spector 2015 free-boundary SABR", "ICE Swap Rate as the settlement rate (administrator)"]),
        dict(slug="06-convexity-adjustments-and-constant-maturity-products", title="Convexity Adjustments and Constant-Maturity Products",
             hook="A note pays each year the ten-year swap rate observed that day; the forward swap rate is 4 per cent, and the dealer's fair value of the coupon is 4.3.",
             sections=["Paying a rate at the wrong time: timing adjustments", "Constant-maturity swaps and their replication by swaptions", "The linear terminal swap-rate model", "Quanto adjustments in rates", "CMS spread options"],
             defines=["timing adjustment", "constant-maturity swap", "CMS convexity adjustment", "linear terminal swap-rate model", "CMS spread option"],
             uses=["convexity adjustment (B2.8)", "swaption (B2.13)", "volatility cube (B2.13)", "steepener (B2.31)", "annuity measure (B4.5)", "forward measure (B4.5)", "quanto adjustment (B5.17)", "shifted SABR (ch5)", "swaption matrix (ch5)"],
             tutorial="Replicate a CMS swaplet and a CMS caplet with a strip of swaptions priced on the cube, and compare with the Hagan closed-form approximation across strikes.",
             build="`firm.cms`: CMS replication pricer on `firm.sabrcube`; timing and quanto adjustments.",
             problem="The steepener note — named result: the fair participation of a ten-year-minus-two-year CMS spread note and its sensitivity to the correlation between the two rates.",
             facts=["Hagan 2003 'Convexity conundrums' (paper)", "CMS steepener note issuance and 2008 losses (public sources only)", "Andersen and Piterbarg 2010 (textbook)"]),
        dict(slug="07-short-rate-models", title="Short-Rate Models",
             hook="Every night a bank must value ten thousand callable bonds and mortgage pools; a one-factor tree does it in minutes, and its weaknesses are known by name.",
             sections=["The short rate and affine bond prices", "Vasicek and Hull--White", "Calibration to the curve and to swaptions", "Trees", "Two factors, and what one factor cannot do"],
             defines=["short-rate model", "affine term-structure model", "Vasicek model", "Hull--White model", "Black--Karasinski model", "Jamshidian decomposition", "two-factor Gaussian model"],
             uses=["Ornstein--Uhlenbeck process (B4.4)", "square-root process (B4.4)", "Feynman--Kac formula (B4.4)", "numeraire (B4.5)", "forward measure (B4.5)", "Monte Carlo (B4.26)", "finite-difference method (B4.27)", "recombining tree (B5.2)", "trinomial tree (B5.22)", "zero-coupon rate (B2.3)", "swaption (B2.13)", "normal volatility (B2.13)", "instantaneous forward rate (ch1)", "curve calibration (ch1)"],
             tutorial="Fit Hull--White to the curve, calibrate its mean reversion and volatility to co-terminal swaptions through the Jamshidian decomposition, build the trinomial tree and check that it reprices bonds and swaptions.",
             build="`firm.shortrate`: Hull--White closed forms, trinomial tree and calibration; two-factor Gaussian bond prices.",
             problem="One sigma is not enough — named result: the co-terminal swaption pricing errors with a constant volatility and with a piecewise-constant one, and the calibrated volatility term structure.",
             facts=["Vasicek 1977, Hull-White 1990, Black-Karasinski 1991, Jamshidian 1989 (papers)", "Brigo and Mercurio 2006 (textbook)"]),
        dict(slug="08-forward-rate-and-market-models", title="Forward-Rate and Market Models",
             hook="In 1997 three papers showed that the formula traders had used for caps for twenty years was the exact price in a consistent model of the whole curve.",
             sections=["The Heath--Jarrow--Morton framework and its drift", "The market model", "Drifts under the spot and terminal measures", "Calibrating to caps and swaptions: Rebonato's formula", "Correlation and factor reduction"],
             defines=["Heath--Jarrow--Morton framework", "HJM drift condition", "LIBOR market model", "swap market model", "spot measure", "terminal measure", "Rebonato's formula", "forward-rate correlation"],
             uses=["Girsanov theorem (B4.5)", "numeraire (B4.5)", "forward measure (B4.5)", "annuity measure (B4.5)", "Monte Carlo (B4.26)", "principal component analysis (B4.22)", "instantaneous forward rate (ch1)", "caplet volatility (ch4)", "swaption matrix (ch5)", "level factor (ch3)"],
             tutorial="Simulate a lognormal market model under the spot measure with a predictor-corrector drift, check that caplets reprice, and compare Rebonato's approximation with Monte Carlo swaption prices.",
             build="`firm.lmm`: market-model Monte Carlo (spot and terminal measures), volatility and correlation parametrisations, swaption calibration.",
             problem="The correlation you cannot see — named result: two correlation parametrisations that fit the same swaption matrix and the price gap they leave on a CMS spread option.",
             facts=["Heath, Jarrow, Morton 1992 Econometrica", "Brace, Gatarek, Musiela 1997; Jamshidian 1997; Miltersen, Sandmann, Sondermann 1997", "Rebonato 2002 (textbook)"]),
        dict(slug="09-bermudans-and-callables", title="Bermudans and Callables",
             hook="A Taiwanese life insurer buys a thirty-year zero-coupon bond the issuer may call every year; the issuing bank's hedge of that call is part of why long-dated dollar volatility falls when such issuance is heavy.",
             sections=["Bermudan swaptions and their co-terminal Europeans", "Exercise by backward induction on a tree", "Exercise by regression in Monte Carlo", "Upper bounds and the switch option", "The callable-bond issuance business"],
             defines=["Bermudan swaption", "co-terminal swaption", "switch option", "Formosa bond", "callable range accrual"],
             uses=["callable bond (B2.13)", "swaption (B2.13)", "option-adjusted spread (B2.21)", "exercise boundary (B5.6)", "Bermudan exercise (B5.6)", "Longstaff--Schwartz method (B5.23)", "dual upper bound (B5.23)", "trinomial tree (B5.22)", "Hull--White model (ch7)", "LIBOR market model (ch8)"],
             tutorial="Price a ten-year-non-call-one Bermudan receiver on the Hull--White tree and by least-squares regression on the same model; compare with the most expensive co-terminal European and bound it from above.",
             build="`firm.bermudan`: tree and regression pricers for Bermudan swaptions and callable bonds on `firm.shortrate`.",
             problem="The Formosa hedge — named result: the Bermudan premium over the most expensive European and the vega the issuing bank's hedge sells into the market.",
             facts=["Formosa bond market size and history (TPEx/BIS)", "BIS or central-bank analysis of callable issuance and long-dated volatility", "Longstaff and Schwartz 2001; Andersen and Broadie 2004 (papers)"]),
        dict(slug="10-modelling-overnight-rate-products", title="Modelling Overnight-Rate Products",
             hook="A caplet on compounded SOFR keeps accruing risk after its period has started: the rate is not known until the last day, and neither is the payoff.",
             sections=["Backward-looking rates and their options", "The generalised forward market model", "Low-dimensional Markov models", "Meeting dates and jumps in the short rate", "Forward-looking term rates"],
             defines=["backward-looking rate", "forward-looking term rate", "backward-looking caplet", "generalised forward market model", "Cheyette model"],
             uses=["compounding in arrears (B2.1)", "overnight benchmark rate (B2.1)", "implied policy path (B2.8)", "caplet (B2.13)", "interbank offered rate (B2.1)", "LIBOR market model (ch8)", "Heath--Jarrow--Morton framework (ch8)", "Hull--White model (ch7)", "caplet volatility (ch4)"],
             tutorial="Price backward-looking caplets under Hull--White and under the generalised forward market model; plot how the variance accrues through the accrual period and compare with a forward-looking caplet.",
             build="`firm.rfrcaplet`: backward-looking caplet and cap pricer with in-period volatility decay; meeting-date step option.",
             problem="The SOFR cap on a leveraged loan — named result: the premium gap between a backward-looking cap and a term-rate cap, and the part due to scheduled meeting dates.",
             facts=["Lyashenko and Mercurio 2019 (paper)", "ARRC term SOFR recommendation (July 2021) and its scope of use", "CME Term SOFR administration (dated)"]),
        dict(slug="11-inflation-derivatives", title="Inflation Derivatives",
             hook="In October 2022 UK retail price inflation reached 14.2 per cent; pension funds that had bought caps on their inflation-linked liabilities found out what the caps were worth.",
             sections=["The foreign-currency analogy", "Zero-coupon versus year-on-year", "The year-on-year convexity adjustment", "Seasonality in the model", "Inflation options and limited price indexation"],
             defines=["Jarrow--Yildirim model", "year-on-year inflation swap", "year-on-year convexity adjustment", "inflation cap", "limited price indexation"],
             uses=["zero-coupon inflation swap (B2.11)", "index-linked bond (B2.11)", "real yield (B2.11)", "breakeven inflation rate (B2.11)", "indexation lag (B2.11)", "inflation seasonality (B2.11)", "deflation floor (B2.11)", "reference index (B2.11)", "liability-driven investment (B2.7)", "quanto adjustment (B5.17)", "Hull--White model (ch7)", "timing adjustment (ch6)"],
             tutorial="Estimate monthly seasonal factors from US CPI (public data), then price a year-on-year swap and caplets under Jarrow--Yildirim and show the effect of the nominal-real correlation.",
             build="`firm.inflopt`: year-on-year swaps, inflation caps and floors, limited-price-indexation legs; reuses `firm.breakeven`.",
             problem="The pension fund's LPI swap — named result: the value of a 0-5 per cent limited-price-indexation leg against the uncapped leg, and its volatility sensitivity.",
             facts=["UK RPI 14.2% October 2022 (ONS)", "RPI reform to CPIH methods from 2030 (UKSA/HM Treasury 2020)", "Jarrow and Yildirim 2003 (paper)", "US CPI NSA series (BLS/FRED, public domain)", "LPI market (public)"]),
        dict(slug="12-mortgage-modelling", title="Mortgage Modelling",
             hook="In the summer of 2003 ten-year Treasury yields rose by more than a percentage point in six weeks, and much of the move was mortgage investors selling duration to hedge the negative convexity of their own portfolios.",
             sections=["Anatomy of a prepayment model", "Rate paths and path dependence", "The option-adjusted spread in practice", "Hedging negative convexity", "Model risk in prepayment"],
             defines=["prepayment model", "refinancing incentive", "prepayment S-curve", "burnout", "housing turnover", "option cost", "current coupon", "primary--secondary spread", "interest-only strip", "principal-only strip"],
             uses=["prepayment (B2.12)", "conditional prepayment rate (B2.12)", "PSA benchmark (B2.12)", "agency mortgage-backed security (B2.12)", "pass-through (B2.12)", "to-be-announced trade (B2.12)", "effective duration (B2.12)", "negative convexity (B2.12)", "option-adjusted spread (B2.21)", "Z-spread (B2.21)", "Monte Carlo (B4.26)", "Hull--White model (ch7)"],
             tutorial="Compute the option-adjusted spread, effective duration and convexity of a pass-through on Hull--White paths with a refinancing S-curve and burnout; split its value into interest-only and principal-only strips.",
             build="`firm.mbsoas`: path-wise prepayment model and OAS engine on `firm.prepay` and `firm.shortrate`.",
             problem="The convexity event of 2003 — named result: the notional of ten-year swaps a mortgage portfolio must pay to stay duration-neutral after a 100 basis-point rise, and the feedback it creates.",
             facts=["summer 2003 Treasury sell-off (FRED data)", "Fed research on mortgage convexity hedging (Perli-Sack 2003; Hanson 2014)", "agency MBS outstanding (SIFMA, dated)", "primary-secondary spread in 2020 (NY Fed staff report)"]),
    ]),
    ("part.rc.credit", [
        dict(slug="13-reduced-form-credit", title="Reduced-Form Credit",
             hook="On 8 April 2009 the whole North American CDS market switched overnight to fixed coupons of 100 and 500 basis points and to one open-source model to convert quoted spreads into upfront cash.",
             sections=["Default as the first jump of an intensity", "Pricing the legs of a default swap", "Bootstrapping a hazard curve", "The standard model and its conventions", "Credit risk measures: CS01 and jump to default"],
             defines=["reduced-form model", "probability of default", "loss given default", "risky discount factor", "risky annuity", "credit triangle", "ISDA standard model", "CS01", "jump-to-default risk", "default risk premium"],
             uses=["hazard rate (B2.23)", "survival probability (B2.23)", "credit default swap (B2.23)", "standard coupon (B2.23)", "upfront payment (B2.23)", "credit event (B2.23)", "recovery rate (B2.21)", "credit spread (B2.21)", "credit rating (B2.21)", "Poisson process (B4.6)", "Cox process (B4.7)", "discount curve (ch2)"],
             tutorial="Bootstrap a piecewise-constant hazard curve from a CDS term structure, convert spreads to upfronts and back, and compute bucketed CS01 and jump to default.",
             build="`firm.cdscurve`: hazard-curve bootstrap with standard-model conventions, CS01 and jump to default; imports `firm.cds` (flat hazard, Book 2).",
             problem="The negative basis package — named result: the CS01 and jump-to-default of a long bond plus bought protection, and the recovery at which the package breaks even.",
             facts=["CDS Big Bang 8 April 2009, standard coupons (ISDA)", "European Small Bang June 2009 coupons", "ISDA CDS Standard Model (open source, administrator)", "physical versus risk-neutral default probabilities (Hull, Predescu, White 2005)", "rating-agency default studies (public)"]),
        dict(slug="14-structural-credit-models", title="Structural Credit Models",
             hook="In May 2005 General Motors' shares rose on a takeover bid while its bonds fell on a downgrade; hedge funds long the debt and short the stock lost on both legs.",
             sections=["Equity as a call on the firm", "Distance to default", "First-passage models", "Capital-structure signals and arbitrage"],
             defines=["structural model", "Merton model", "distance to default", "first-passage model", "default barrier", "capital-structure arbitrage"],
             uses=["Black--Scholes model (B5.3)", "equity-to-credit model (B5.21)", "convertible bond (B5.21)", "reflection principle (B4.2)", "hitting time (B4.2)", "seniority (B2.21)", "credit spread (B2.21)", "hazard rate (B2.23)", "credit default swap (B2.23)", "implied volatility (B1.25)", "probability of default (ch13)"],
             tutorial="Back out asset value and asset volatility from equity price and equity volatility, compute the distance to default and the model spread, and compare with a first-passage model on the same firm.",
             build="`firm.structural`: Merton and first-passage models, asset-value inversion, model CDS spread.",
             problem="May 2005 — named result: the P&L of a CDS-versus-equity hedge sized by the Merton model when the equity rallies and the spread widens together.",
             facts=["Merton 1974; Black and Cox 1976 (papers)", "CreditGrades technical document 2002", "GM and Ford downgrades of 5 May 2005 (rating agency releases/press)", "Kerkorian tender offer for GM shares May 2005 (SEC filing/press)", "Yu 2006 capital-structure arbitrage (paper)"]),
        dict(slug="15-portfolio-credit", title="Portfolio Credit",
             hook="In May 2005 traders long the equity tranche and short the mezzanine, hedged by every model they had, lost on both legs in the same week.",
             sections=["Default correlation and copulas", "The one-factor Gaussian copula and the large pool", "Pricing tranches: recursion, compound and base correlation", "Beyond the Gaussian: fat tails and tail dependence", "May 2005 and 2008"],
             defines=["default correlation", "Gaussian copula", "Student-t copula", "large homogeneous pool", "compound correlation", "tranche delta", "super senior tranche"],
             uses=["tranche (B2.24)", "attachment point (B2.24)", "detachment point (B2.24)", "base correlation (B2.24)", "credit index (B2.24)", "index series (B2.24)", "equity tranche (B2.25)", "collateralised loan obligation (B2.25)", "hazard rate (B2.23)", "survival probability (B2.23)", "copula (B4.15)", "tail dependence (B4.15)", "Monte Carlo (B4.26)", "loss given default (ch13)"],
             tutorial="Price index tranches by the large-pool formula and by exact recursion, imply compound and base correlations from synthetic quotes, and show where compound correlation has no or two solutions.",
             build="`firm.portcredit`: copula default simulation, loss recursion, tranche pricer and correlation implier; imports `firm.tranche` (Book 2).",
             problem="Long equity, short mezzanine — named result: the P&L of the delta-hedged equity tranche when idiosyncratic spreads blow out and correlation falls.",
             facts=["Li 2000 'On default correlation' (paper)", "Vasicek 2002 loan-portfolio value (paper)", "May 2005 correlation dislocation (BIS Quarterly Review June 2005 or similar)", "2008 super-senior write-downs (bank shareholder reports, public)", "Andersen, Sidenius, Basu 2003 recursion (paper)"]),
        dict(slug="16-commodity-and-energy-derivatives", title="Commodity and Energy Derivatives",
             hook="In February 2021 a winter storm froze Texas and day-ahead gas at some hubs traded above 200 dollars per million British thermal units; the owners of gas storage and swing rights earned in a week what they normally earn in years.",
             sections=["Factor models of the forward curve", "The Samuelson effect and forward volatility", "Spread options", "Storage valuation", "Swing contracts"],
             defines=["Schwartz--Smith model", "spread option", "Kirk's approximation", "intrinsic storage value", "extrinsic value", "rolling intrinsic"],
             uses=["forward curve (B3.10)", "convenience yield (B3.10)", "theory of storage (B3.10)", "Samuelson effect (B3.10)", "swing contract (B3.12)", "take-or-pay clause (B3.12)", "calendar-spread option (B3.12)", "average-price option (B3.12)", "crack spread (B3.3)", "spark spread (B3.5)", "contango (B1.21)", "backwardation (B1.21)", "Ornstein--Uhlenbeck process (B4.4)", "Longstaff--Schwartz method (B5.23)", "Monte Carlo (B4.26)"],
             tutorial="Calibrate a two-factor model to a synthetic gas forward curve and its option volatilities, then value a storage facility by rolling intrinsic and by regression Monte Carlo and split intrinsic from extrinsic value.",
             build="`firm.energymodel`: two-factor forward-curve model, Kirk spread options, storage and swing valuation by regression.",
             problem="The salt cavern in February 2021 — named result: intrinsic and extrinsic value of a storage facility and the value the storm week added to it.",
             facts=["Winter Storm Uri gas and power prices (EIA)", "Schwartz 1997; Schwartz and Smith 2000 (papers)", "Kirk 1995 (paper)", "Boogert and de Jong 2008 storage by LSM (paper)"]),
    ]),
    ("part.rc.xva", [
        dict(slug="17-counterparty-exposure", title="Counterparty Exposure",
             hook="When Lehman Brothers filed on 15 September 2008 its counterparties had to replace hundreds of thousands of derivatives in a market moving against all of them at once.",
             sections=["Exposure and its profiles", "Netting and collateral", "Simulating exposure", "The margin period of risk and the collateralised profile", "Wrong-way risk"],
             defines=["counterparty credit risk", "counterparty exposure", "expected exposure", "expected positive exposure", "expected negative exposure", "potential future exposure", "netting set", "close-out netting", "collateral threshold", "minimum transfer amount", "independent amount", "wrong-way risk"],
             uses=["margin period of risk (B1.20)", "variation margin (B1.5)", "initial margin (B1.5)", "mark-to-market (B1.7)", "credit support annex (B2.10)", "ISDA master agreement (B2.28)", "payment netting (B2.20)", "settlement risk (B2.20)", "Monte Carlo (B4.26)", "Longstaff--Schwartz method (B5.23)", "Hull--White model (ch7)", "multi-curve framework (ch2)"],
             tutorial="Simulate the exposure profiles of a ten-year swap, a cross-currency swap and their netting set, with and without variation margin under a ten-day margin period of risk.",
             build="`firm.exposure`: exposure simulation engine (scenario paths, trade revaluation, netting, collateral); Python driver with a C++20 kernel and a Rust twin.",
             problem="The uncollateralised corporate — named result: the peak PFE and EPE of a swap-plus-FX-forward netting set, before and after the client signs a CSA.",
             facts=["Lehman derivative counterparties and trade count (bankruptcy filings)", "ISDA netting opinions coverage (ISDA)", "Basel margin period of risk floors (10 days, 20 for large netting sets)", "Gregory, The xVA Challenge (textbook)"]),
        dict(slug="18-credit-and-debit-valuation-adjustments", title="Credit and Debit Valuation Adjustments",
             hook="The Basel Committee found that roughly two-thirds of the counterparty losses of the 2007-09 crisis came from marking the credit of living counterparties, not from defaults.",
             sections=["CVA as the price of counterparty default", "DVA and the bilateral view", "Computing CVA", "Sensitivities and hedging", "Accounting and regulation"],
             defines=["credit valuation adjustment", "debit valuation adjustment", "bilateral CVA", "XVA", "close-out amount"],
             uses=["expected exposure (ch17)", "expected negative exposure (ch17)", "netting set (ch17)", "wrong-way risk (ch17)", "probability of default (ch13)", "loss given default (ch13)", "CS01 (ch13)", "hazard rate (B2.23)", "survival probability (B2.23)", "credit default swap (B2.23)", "credit spread (B2.21)", "additional tier 1 (B2.26)"],
             tutorial="Compute CVA and DVA of chapter 17's netting set on a CDS-implied hazard curve, with bucketed CS01, and show the effect of wrong-way correlation.",
             build="`firm.cva`: CVA and DVA from exposure profiles and hazard curves, bucketed credit sensitivities; reads `firm.exposure` and `firm.cdscurve`.",
             problem="The gain from getting riskier — named result: the DVA profit a bank books when its own spread widens by 50 basis points, and why regulators deduct it from capital.",
             facts=["BCBS statement on CVA losses in 2007-09 (two-thirds)", "IFRS 13 (2011, effective 2013) non-performance risk", "Basel III deduction of DVA from CET1", "bank DVA gains in 2011 (annual reports)"]),
        dict(slug="19-funding-margin-and-capital-adjustments", title="Funding, Margin and Capital Adjustments",
             hook="In January 2014 a large US bank took a charge of about one and a half billion dollars in a single quarter for the cost of funding its uncollateralised derivatives.",
             sections=["Funding a derivative: the debate", "Funding cost and benefit adjustments", "Initial margin and MVA", "Capital: counterparty and CVA capital, and KVA", "The whole stack"],
             defines=["funding valuation adjustment", "funding cost adjustment", "funding benefit adjustment", "margin valuation adjustment", "capital valuation adjustment", "standardised approach for counterparty credit risk", "exposure at default", "CVA risk capital", "hurdle rate"],
             uses=["funding spread (B1.17)", "initial margin (B1.5)", "risk-weighted assets (B1.2)", "uncleared margin rules (B2.10)", "CCP basis (B2.10)", "credit valuation adjustment (ch18)", "debit valuation adjustment (ch18)", "XVA (ch18)", "expected exposure (ch17)", "expected positive exposure (ch17)", "CSA discounting (ch2)"],
             tutorial="Compute FCA, FBA, MVA and KVA for the chapter 17 swap with initial margin from a simple sensitivity model, and decompose the full adjustment stack.",
             build="`firm.xvafund`: funding, margin and capital adjustments from exposure and margin profiles; reuses `firm.ccpbasis` (MVA) and `firm.exposure`.",
             problem="The fourth-quarter charge — named result: the FVA of an uncollateralised ten-year swap for a bank funding at 80 basis points over the overnight rate, and how much a CSA removes.",
             facts=["JPMorgan FVA charge Q4 2013 (earnings release, January 2014)", "Hull and White 2012 'The FVA debate' (paper)", "Burgard and Kjaer 2011 (paper)", "BCBS SA-CCR standard (March 2014)", "BCBS revised CVA framework (July 2020)", "implementation dates of SA-CCR and CVA capital by jurisdiction (dated)"]),
        dict(slug="20-the-valuation-adjustment-desk", title="The Valuation-Adjustment Desk",
             hook="A salesperson prices a twenty-year swap for an unrated corporate client; the valuation-adjustment desk adds thirty basis points a year, and the client walks to another bank.",
             sections=["Why one central desk", "Incremental pricing and allocation", "What it hedges and what it cannot", "Charging, transfer pricing and the desk's P&L", "Organisation"],
             defines=["XVA desk", "incremental XVA", "Euler allocation", "XVA charge", "proxy credit spread", "contingent credit default swap"],
             uses=["credit valuation adjustment (ch18)", "debit valuation adjustment (ch18)", "funding valuation adjustment (ch19)", "margin valuation adjustment (ch19)", "capital valuation adjustment (ch19)", "netting set (ch17)", "expected exposure (ch17)", "CS01 (ch13)", "credit default swap (B2.23)", "novation (B1.5)", "trade compression (B2.9)"],
             tutorial="Compute the incremental CVA of a new trade in an existing netting set, compare it with the standalone figure, and allocate the netting set's CVA to its trades by Euler allocation.",
             build="`firm.xvaquote`: incremental XVA quote service over `firm.cva` and `firm.xvafund`; running-charge conversion.",
             problem="The unrated corporate — named result: the all-in XVA add-on in running basis points for a twenty-year swap, and the part of it the desk can hedge in the market.",
             facts=["public descriptions of XVA desks (bank annual reports, published papers)", "EBA RTS on proxy spreads for CVA (EU Regulation 526/2014)", "Basel eligible CVA hedges (BCBS CVA framework)", "contingent CDS (public description)"]),
    ]),
    ("part.rc.risk", [
        dict(slug="21-market-risk-measures", title="Market-Risk Measures",
             hook="In the early 1990s a bank's chairman asked for one number, delivered at a quarter past four each afternoon, that said how much the firm could lose tomorrow; in 1994 the method was published for everyone.",
             sections=["Loss distributions and value at risk", "Value at risk three ways", "Expected shortfall and coherence", "Backtesting the measure", "Risk contributions"],
             defines=["risk factor", "value at risk", "expected shortfall", "historical simulation", "filtered historical simulation", "parametric value at risk", "Monte Carlo value at risk", "delta--gamma approximation", "coherent risk measure", "square-root-of-time rule", "VaR exception", "Kupiec test", "Christoffersen test", "traffic-light test"],
             uses=["realised volatility (B1.25)", "P\\&L attribution (B1.7)", "GARCH model (B4.18)", "extreme-value theory (B4.15)", "bootstrap (B4.13)", "Monte Carlo (B4.26)", "hypothesis test (B4.12)", "gamma (B1.26)", "bucketed sensitivity (ch3)", "Euler allocation (ch20)"],
             tutorial="Compute historical, parametric and Monte Carlo VaR and expected shortfall of a small multi-asset book on public rates and FX data, backtest them over four years and place them in the traffic-light zones.",
             build="`firm.varmodel`: VaR and ES by three methods, delta--gamma approximation, backtests (Kupiec, Christoffersen, traffic light), Euler contributions.",
             problem="The quarter-past-four report — named result: the 99 per cent VaR and 97.5 per cent ES of a desk, its exceptions over 250 days, and the capital multiplier they imply.",
             facts=["RiskMetrics Technical Document 1994/1996 (decay 0.94)", "Basel 1996 market-risk amendment (99%, 10 days, multiplier 3, traffic light)", "BCBS FRTB expected shortfall at 97.5%", "Artzner, Delbaen, Eber, Heath 1999 (paper)", "Kupiec 1995; Christoffersen 1998 (papers)", "FRED H.10 FX and Treasury yields (public domain)"]),
        dict(slug="22-stress-testing-and-scenarios", title="Stress Testing and Scenarios",
             hook="In March 2021 a family office defaulted on its swap margin calls and its prime brokers lost more than ten billion dollars between them; one lost five and a half billion on positions no value-at-risk model had flagged.",
             sections=["What value at risk cannot see", "Historical scenarios", "Hypothetical scenarios and their consistency", "Reverse stress tests", "Supervisory stress tests"],
             defines=["stress test", "historical scenario", "hypothetical scenario", "scenario conditioning", "reverse stress test", "supervisory stress test"],
             uses=["value at risk (ch21)", "expected shortfall (ch21)", "risk factor (ch21)", "historical simulation (ch21)", "total return swap (B1.6)", "prime broker (B1.6)", "liquidity spiral (B1.31)", "margin spiral (B3.28)", "dash for cash (B2.4)", "liability-driven investment (B2.7)", "procyclicality (B1.20)", "covariance matrix (B4.22)"],
             tutorial="Apply the 1987, 2008, March 2020 and September 2022 scenarios to a multi-asset book; fill the unshocked factors of a hypothetical scenario by conditioning; find the most plausible scenario that costs a given loss.",
             build="`firm.stresstest`: scenario library, conditional scenario expansion, reverse stress by constrained optimisation.",
             problem="The family office from the broker's side — named result: the market move at which a concentrated swap book exhausts its margin, found by reverse stress.",
             facts=["Archegos: Credit Suisse special committee report (Paul Weiss, July 2021)", "2022 UK LDI gilt episode (Bank of England)", "Fed supervisory stress test scenarios (latest year, dated)", "EBA EU-wide stress test (latest, dated)", "October 1987 crash size (public)"]),
        dict(slug="23-regulatory-capital-for-trading-books", title="Regulatory Capital for Trading Books",
             hook="Each quarter a bank's trading desk must show that its risk model explains its own P&L; if the test fails, the desk falls back to the standardised approach and its capital can double.",
             sections=["The trading book and its boundary", "The standardised approach: sensitivities, curvature, default and residual risks", "The internal models approach: expected shortfall with liquidity horizons", "Backtesting and the P&L attribution test", "Non-modellable risk factors"],
             defines=["Fundamental Review of the Trading Book", "trading book", "banking book", "sensitivities-based method", "curvature risk charge", "default risk charge", "residual risk add-on", "internal models approach", "liquidity horizon", "stressed expected shortfall", "P\\&L attribution test", "hypothetical P\\&L", "risk-theoretical P\\&L", "non-modellable risk factor", "risk-factor eligibility test"],
             uses=["risk-weighted assets (B1.2)", "P\\&L attribution (B1.7)", "value at risk (ch21)", "expected shortfall (ch21)", "risk factor (ch21)", "VaR exception (ch21)", "traffic-light test (ch21)", "bucketed sensitivity (ch3)", "Kolmogorov--Smirnov test (B4.12)", "Spearman correlation (B4.15 or B4.16)"],
             tutorial="Compute sensitivities-based delta, vega and curvature charges for a small rates and FX book under the three correlation scenarios, then run the P&L attribution test on simulated hypothetical and risk-theoretical P&L.",
             build="`firm.frtb`: standardised-approach engine (weighted sensitivities, buckets, correlation scenarios), liquidity-horizon ES, PLA and NMRF eligibility tests.",
             problem="The desk that failed attribution — named result: the desk's capital under internal models and under the standardised approach, and the Spearman and Kolmogorov--Smirnov values that put it in the amber zone.",
             facts=["BCBS minimum capital requirements for market risk (d457, January 2019): liquidity horizons, PLA thresholds, NMRF 24 observations", "BCBS implementation date and each jurisdiction's latest date: EU CRR3 postponements, UK PRA, US proposal status (dated; search latest release)", "trading-book boundary rules (BCBS)", "Basel 2.5 stressed VaR (2009)"]),
        dict(slug="24-liquidity-and-funding-risk-bank-treasury", title="Liquidity and Funding Risk; Bank Treasury",
             hook="On 9 March 2023 depositors withdrew 42 billion dollars from Silicon Valley Bank in one day, and asked for about a hundred billion more the next morning.",
             sections=["Liquidity ratios", "Funds-transfer pricing", "Asset-liability management and rate risk in the banking book", "Deposits: the behavioural model", "The 2023 regional-bank failures"],
             defines=["liquidity coverage ratio", "high-quality liquid assets", "net stable funding ratio", "funds-transfer pricing", "asset--liability management", "interest-rate risk in the banking book", "economic value of equity", "net interest income sensitivity", "non-maturity deposit", "deposit beta", "held-to-maturity portfolio", "bank run"],
             uses=["reserves (B2.1)", "standing facility (B2.1)", "repurchase agreement (B1.6)", "haircut (B1.6)", "modified duration (B2.3)", "bail-in (B2.26)", "liquidity spiral (B1.31)", "banking book (ch23)", "trading book (ch23)", "key-rate duration (ch3)"],
             tutorial="Compute the economic-value and net-interest-income sensitivities of a stylised bank balance sheet under the supervisory shocks, its LCR, and the deposit outflow that exhausts its liquid assets.",
             build="`firm.alm`: balance-sheet cash-flow ladder, EVE and NII under shock scenarios, LCR and NSFR calculators, FTP curve.",
             problem="March 2023 — named result: the held-to-maturity unrealised loss as a share of capital and the one-day outflow at which the stylised bank runs out of liquid assets.",
             facts=["SVB outflows 9-10 March 2023 (Fed Barr review, April 2023)", "SVB HTM unrealised losses end-2022 (10-K)", "Signature Bank and First Republic failures (FDIC)", "BTFP announced 12 March 2023 (Fed)", "BCBS LCR (2013) and NSFR (2014) standards", "BCBS IRRBB standard 2016 and the supervisory outlier test (latest, dated)"]),
        dict(slug="25-margin-models", title="Margin Models",
             hook="In March 2020 initial margin at the world's clearing houses rose by roughly three hundred billion dollars in a few weeks, just when every firm needed its cash elsewhere.",
             sections=["What an initial-margin model must do", "Clearing-house models: scenarios, historical and filtered simulation", "The standard bilateral model", "Procyclicality and its tools", "Backtesting margin"],
             defines=["initial-margin model", "standard initial margin model", "schedule-based initial margin", "initial-margin threshold", "anti-procyclicality tool", "concentration add-on"],
             uses=["initial margin (B1.5)", "variation margin (B1.5)", "margin period of risk (B1.20)", "procyclicality (B1.20)", "portfolio margining (B1.20)", "scanning range (B1.20)", "default fund (B1.5)", "central counterparty (B1.5)", "uncleared margin rules (B2.10)", "credit support annex (B2.10)", "historical simulation (ch21)", "filtered historical simulation (ch21)", "VaR exception (ch21)", "bucketed sensitivity (ch3)", "margin valuation adjustment (ch19)"],
             tutorial="Compute the initial margin of a swap portfolio by historical simulation, by a sensitivity-based model with illustrative parameters and by the regulatory schedule; replay a March-2020-type shock with and without anti-procyclicality tools.",
             build="`firm.initmargin`: historical and filtered-simulation IM, a sensitivity-based bilateral IM with illustrative weights and correlations, schedule IM, APC buffers.",
             problem="The margin calls of March 2020 — named result: the IM increase with and without a 25 per cent buffer and a stressed-period weight, and the cash the member had to find.",
             facts=["BCBS-CPMI-IOSCO review of margining practices (September 2022): March 2020 IM increase", "ISDA SIMM methodology (current version and calibration cycle, dated)", "UMR phase-in to phase 6 (1 September 2022) and EUR 50m IM threshold", "EMIR RTS anti-procyclicality options (25% buffer, 25% stressed weight, 10-year lookback)", "PFMI coverage 99% (CPMI-IOSCO 2012)"]),
        dict(slug="26-model-risk-and-validation", title="Model Risk and Validation",
             hook="In 2012 a bank's new value-at-risk model halved the measured risk of a synthetic-credit portfolio; one of its spreadsheets divided by a sum where it should have divided by an average.",
             sections=["What model risk is and how it enters", "Supervisory expectations", "The validation report", "Inventories, tiering and limitations", "Benchmarking and outcomes analysis"],
             defines=["model risk", "model risk management", "model validation", "effective challenge", "model inventory", "model tiering", "benchmark model", "outcomes analysis", "post-model adjustment", "three lines of defence"],
             uses=["value at risk (ch21)", "VaR exception (ch21)", "P\\&L attribution (B1.7)", "Hull--White model (ch7)", "trinomial tree (B5.22)", "Monte Carlo (B4.26)", "model reserve (B5.27)"],
             tutorial="Validate chapter 7's tree pricer against an independent Monte Carlo and the closed form over a grid of parameters, record tolerances and failures, and write the findings in the structure of a validation report.",
             build="`firm.modelval`: model inventory records, tiering rules, benchmarking harness with tolerance grids and outcome tests.",
             problem="The averaging error — named result: the VaR reduction produced on a synthetic tranche book by dividing a rate change by the sum of two rates instead of their average.",
             facts=["Fed/OCC SR 11-7 (April 2011)", "PRA SS1/23 (May 2023, effective 17 May 2024)", "JPMorgan Management Task Force report on CIO losses (January 2013)", "ECB guide to internal models (latest revision, dated)", "any later revision or rescission of US model-risk guidance (search latest)"]),
        dict(slug="27-pnl-explain-and-independent-price-verification", title="P\\&L Explain and Independent Price Verification",
             hook="Every evening a product controller must explain each dollar a desk made or lost; on the day a swaption book shows 400 thousand dollars nobody can account for, the search begins.",
             sections=["Attribution: risk-based and revaluation-based", "Unexplained P&L and what it reveals", "Independent price verification", "Reserves and the fair-value hierarchy", "Prudent valuation"],
             defines=["risk-based attribution", "revaluation-based attribution", "unexplained P\\&L", "product control", "independent price verification", "fair-value hierarchy", "prudent valuation", "additional valuation adjustment"],
             uses=["P\\&L attribution (B1.7)", "realised P\\&L (B1.7)", "unrealised P\\&L (B1.7)", "mark-to-market (B1.7)", "carry (B1.7)", "composite price (B2.22)", "gamma (B1.26)", "vega (B5.4)", "theta (B5.4)", "day-one P\\&L (B5.27)", "valuation reserve (B5.27)", "bid--offer reserve (B5.27)", "model reserve (B5.27)", "parameter bid--offer (B5.27)", "hypothetical P\\&L (ch23)", "cross-gamma (ch3)", "delta--gamma approximation (ch21)"],
             tutorial="Explain a day of a swaption book's P&L by Greeks and by step-by-step revaluation, measure the unexplained part, verify the marks against consensus data and compute the prudent-valuation adjustment.",
             build="`firm.pnlexplain`: risk-based and revaluation-based attribution, unexplained-P&L alerts, IPV tolerance checks, AVA calculator; reads `firm.pnl` (Book 1).",
             problem="The unexplained 400 thousand — named result: the missing cross term that accounts for the unexplained P&L on a big-move day, and the attribution after it is added.",
             facts=["EU prudent valuation RTS (Delegated Regulation 2016/101): 90% confidence, core and fallback approaches, EUR 15bn threshold", "IFRS 13 / ASC 820 fair-value levels", "JPMorgan CIO valuation-control findings (Task Force report 2013)", "consensus-pricing services (public description)"]),
        dict(slug="28-operational-risk-and-rogue-trading", title="Operational Risk and Rogue Trading",
             hook="On 26 February 1995 Barings, a bank more than two centuries old, failed because the losses one trader had hidden in an account numbered 88888 had grown larger than its capital.",
             sections=["Operational risk and its measurement", "The documented cases", "The control failures they share", "Detecting fictitious and hidden trades"],
             defines=["operational risk", "operational loss event", "rogue trading", "segregation of duties", "fictitious trade", "block leave"],
             uses=["three lines of defence (ch26)", "unexplained P\\&L (ch27)", "product control (ch27)", "independent price verification (ch27)", "position limit (B1.27)", "margin call (B1.6)", "settlement (B1.5)", "P\\&L attribution (B1.7)"],
             tutorial="Run detection rules on a synthetic trade blotter (late bookings, cancel-and-amend around reporting dates, off-market prices, internal counterparties, forward-dated trades that never settle) and measure hit and false-alarm rates.",
             build="`firm.tradecontrol`: blotter surveillance rules, alert scoring, audit log.",
             problem="January 2008 — named result: the position size implied by the reported unwinding loss and market move, and the first control in the chain that would have caught it.",
             facts=["Barings: Board of Banking Supervision report 1995 (loss GBP 827m)", "Daiwa 1995 (USD 1.1bn), Sumitomo 1996 (USD 2.6bn) (court/regulatory records)", "Allfirst: Promontory (Ludwig) report 2002 (USD 691m)", "Société Générale: Mission Green report and Commission Bancaire 2008 (EUR 4.9bn, EUR 50bn position)", "UBS 2011 (USD 2.3bn): FINMA and FSA 2012 decisions", "Basel operational-risk definition and standardised approach (2017; implementation dated)"]),
        dict(slug="29-build-a-risk-engine", title="Build: A Risk Engine",
             hook="At six in the morning the overnight run must have repriced fifty thousand trades under five hundred scenarios, aggregated them by desk, and flagged every limit breach before the traders arrive.",
             sections=["Architecture: market data, scenarios, revaluation, aggregation", "Scenario generation", "Revaluation: full, grid and sensitivity-based", "Aggregation, hierarchies and limits", "Testing a risk engine"],
             defines=["risk engine", "full revaluation", "revaluation grid", "risk hierarchy", "risk limit", "risk data aggregation"],
             uses=["pricing engine (B5.28)", "market-data snapshot (B5.28)", "reference pricer (B5.28)", "bump-and-reprice (B5.4)", "value at risk (ch21)", "expected shortfall (ch21)", "historical simulation (ch21)", "delta--gamma approximation (ch21)", "Euler allocation (ch20)", "stress test (ch22)", "sensitivities-based method (ch23)", "bucketed sensitivity (ch3)", "position limit (B1.27)"],
             tutorial="Run the engine on a thousand-trade book over historical scenarios, produce VaR and ES by node of the hierarchy, and compare full, grid and delta--gamma revaluation for speed and error.",
             build="`firm.riskengine`: scenario generation, revaluation through Book 5's pricing library (adapter on the frozen interface), aggregation by hierarchy, limits; Python driver with a C++20 aggregation kernel and a Rust twin.",
             problem="The six o'clock deadline — named result: wall-clock time and VaR error of full, grid and delta--gamma revaluation on the test book, and the cheapest method within a 2 per cent error budget.",
             facts=["BCBS 239 principles for risk data aggregation (January 2013) and adoption status (dated)", "Book 5 pricing-library interface (code/firm/INTERFACES.md)"]),
    ]),
]
