"""Book 13 (Low-Latency Software) chapter briefs: data for tools/make_briefs.py --book 13.

`uses` lists terms defined elsewhere that the chapter relies on (not redefined); owners in parentheses:
(B7.18) = One Quant Book 7, chapter 18, checked against the multi-line \\index{} harvest of Books 1-9 on
2026-09-25 (2,103 definitions); (B10.26) = a batch book, by its outline (to be confirmed at the sync);
(ch5) = an earlier chapter of this book.

Ownership. Books 1-9 keep their terms: Book 1 owns the market-data vocabulary (sequence number, exchange
and receive timestamps, levels 1-3, normalisation, market-by-order/-by-price, direct feed, sponsored access),
Book 3 the crypto-venue API vocabulary (rate limit, request weight, API key, snapshot-and-delta feed, book
checksum, cloud region, dedicated endpoint) and `sequencer` in its blockchain sense, Book 4 floating point
and bitwise reproducibility, the M/M/1 queue and the bootstrap, Book 6 risk limit and risk hierarchy, Book 7
the simulation vocabulary (latency model, order-entry and market-data latency, order lifecycle, partial fill,
simulated clock, order-book replay, replay parity test, canary deployment, staged rollout, paper trading).
In the batch, Book 10 owns the order book and order types as the market sees them, tick size and the
exchange simulator; Book 11 owns the quoting engine, latency arbitrage and the risk-control *policy*
(kill switch, pre-trade risk check, price collar); Book 12 owns low-latency inference. This book owns the
software, hardware-seen-from-the-program, systems and protocol-engineering terms, and the implementation of
the risk controls.

No strategy files (the outline gives Book 13 none). C++20 is the printed systems language; every systems
build has a Rust twin in the companion tree, and the chapters print both where the contrast teaches something
(chapters 9, 11, 12, 14 and 16-19 at least). Measured timings follow the batch ruling: measured on this
laptop (Intel Core Ultra 7 155H, WSL2, no isolated cores), caption says so, tests assert only
machine-independent properties; tuned-server figures come from cited sources.

Running project (code/firm/, all new and unique; checked against the 264 existing components):
  latbudget (ch1)  ubench (ch2)  memkit (ch3)  coreplan (ch4)  lathist (ch5)  arena (ch6)  pipeline (ch7)
  flagbench (ch8)  affinity (ch9)  gcwatch (ch10)  mpmcq (ch11)  ring (ch12)  tuneaudit (ch13)
  simdscan (ch14)  fixengine (ch15)  wirecodec (ch16)  wsclient (ch17)  feedhandler (ch18)
  bookbuilder (ch19)  stratengine (ch20)  ordergw (ch21)  riskgate (ch22)  binlog (ch23)  sequencer (ch24)
  perfgate (ch25)  ticktotrade (ch26)
Part IV (ch. 18-26) runs against One Quant Book 10's exchange simulator (Book 10, ch. 26; interface frozen
in code/firm/INTERFACES.md section 7 at the sync). Until it lands, only its recorded fixtures are needed.
"""
SLUG = "low-latency"
PFX = "ll"
HEAD = "One Quant Book 13 — Low-Latency Software"

_U_TS = ["exchange timestamp (B1.28)", "receive timestamp (B1.28)"]
_U_LAT = ["latency model (B7.18)", "order-entry latency (B7.18)", "market-data latency (B7.18)"]
_U_FEED = ["market data feed (B1.4)", "sequence number (B1.28)", "normalisation (B1.28)",
           "market-by-order (B1.19)", "market-by-price (B1.19)", "level 1 (B1.28)", "level 2 (B1.28)",
           "level 3 (B1.28)"]
_U_BOOK = ["limit order book (B10.1)", "limit order (B10.1)", "market order (B10.1)",
           "price-time priority (B1.19)", "tick size (B10.1)", "price level (B10.1)"]
_U_SIM = ["exchange simulator (B10.26)", "matching engine (B10.1)"]

PARTS = [
    ("part.ll.machine", [
        dict(slug="01-where-latency-comes-from", title="Where Latency Comes From",
             hook="In a study of a large exchange's own message data, the winner of a race to trade on a stale quote beat the loser by a few millionths of a second, and such races were a sizeable share of the day's volume: a microsecond is a unit of competition, not of engineering pride.",
             sections=["The tick-to-trade path, stage by stage", "Latency is a distribution: medians, tails, jitter", "Budgets from wire to wire", "Which strategies pay for which microseconds"],
             defines=["latency", "tick-to-trade latency", "wire-to-wire latency", "latency budget", "hot path", "tail latency", "jitter"],
             uses=_U_TS + _U_LAT + ["direct feed (B1.9)", "adverse selection (B1.1)", "latency arbitrage (B11.9)", "heavy-tailed distribution (B4.15)"],
             tutorial="Time each stage of a toy tick-to-trade path (Book 1's C++ decoder, a book update, a decision, an order encode) with a steady clock, then compose per-stage distributions in Python: the sum of the stage medians against the median of the sum, the sum of the stage 99th percentiles against the 99th percentile of the sum. End state: a stacked budget chart and a table of percentiles, measured on this laptop.",
             build="`firm.latbudget`: a latency budget as data (stages, targets per percentile), composition of per-stage histograms by convolution or by joint samples, a budget-against-measurement report; Python. Consumed by chapter 26.",
             problem="The microsecond that lost the race -- named result: a firm's probability of winning a race against one competitor, from both latency distributions, and the gain from halving its 99th percentile compared with halving its median.",
             facts=["Aquilina, Budish and O'Neill 2022, Quantifying the high-frequency trading arms race (QJE): race duration and share of volume", "speed of light in optical fibre (refractive index about 1.47)", "a published matching-engine round-trip latency of a major venue (dated)", "tuned-server tick-to-trade figures from a public talk (dated)"],
             data="Book 1's firm.feed sample; measured stage timings on this laptop (bench script, machine named in the caption)."),
        dict(slug="02-cpu-microarchitecture", title="CPU Microarchitecture",
             hook="The same twelve lines of C++ ran six times faster on sorted input than on shuffled input: nothing in the source changed, only how often the processor guessed a branch right.",
             sections=["Pipelines and superscalar execution", "Out-of-order execution and the reorder buffer", "Branch prediction and its misses", "Frequency scaling, turbo and idle states", "Simultaneous multithreading and heterogeneous cores"],
             defines=["microbenchmark", "compiler barrier", "time-stamp counter", "instruction pipeline", "out-of-order execution", "reorder buffer", "branch prediction", "branch misprediction", "instructions per cycle", "dynamic frequency scaling", "idle state", "simultaneous multithreading", "heterogeneous cores"],
             uses=["hot path (ch1)", "jitter (ch1)"],
             tutorial="C++ microbenchmarks with a cycle counter: a branchy filter on sorted and shuffled data and its branchless rewrite; one dependency chain against four independent accumulators; the same loop pinned with taskset to a performance core and to an efficiency core of this hybrid laptop. End state: a chart of cycles per element by variant and core type.",
             build="`firm.ubench`: the microbenchmark harness every later chapter uses -- warm-up, repetitions, an optimisation barrier, rdtscp and steady-clock timers, raw samples to CSV; C++20 header and Rust twin.",
             problem="The branch that cost a quote -- named result: the expected cycles per message lost to one data-dependent branch at a given misprediction rate, and the rate above which the branchless version wins.",
             facts=["Stack Overflow question 11227809 (2012), why is processing a sorted array faster", "Intel 64 and IA-32 Architectures Optimization Reference Manual: misprediction penalty, reorder-buffer size of the performance core (dated)", "Intel product page of the Core Ultra 7 155H: 6 P + 8 E + 2 LP-E cores, turbo frequency (dated)", "Agner Fog, The microarchitecture of Intel, AMD and VIA CPUs"],
             data="Measured on this laptop only."),
        dict(slug="03-memory-hierarchy-and-caches", title="Memory Hierarchy and Caches",
             hook="An order-book update costs a few nanoseconds when its price level is in the first-level cache and about a hundred when it is not: most of the difference between a fast book and a slow one is where its bytes live.",
             sections=["Cache levels, lines and associativity", "Coherence and false sharing", "Translation buffers and huge pages", "Prefetching and access patterns"],
             defines=["cache line", "set-associative cache", "cache miss", "cache coherence", "false sharing", "translation lookaside buffer", "huge page", "hardware prefetching", "working set"],
             uses=["hot path (ch1)", "microbenchmark (ch2)"],
             tutorial="Measure the memory staircase with a pointer chase through a random cyclic permutation of growing size; measure two threads incrementing counters on one cache line and on padded lines; repeat a random-access loop over 1 GiB with and without transparent huge pages (madvise). End state: the staircase chart with this laptop's cache sizes marked, and a false-sharing bar chart.",
             build="`firm.memkit`: cache-line padding (CachePadded), aligned allocation, huge-page-backed buffers with fallback, a pointer-chase probe; C++20 and Rust.",
             problem="The staircase -- named result: the latency of each level read off the pointer-chase curve and the number of instruments whose book fits in the second-level cache.",
             facts=["Drepper 2007, What every programmer should know about memory", "Papamarcos and Patel 1984, MESI protocol (ISCA)", "Linux transparent hugepage documentation (admin-guide/mm/transhuge)", "cache sizes of the laptop from lscpu and Intel documentation (dated)"],
             data="Measured on this laptop only."),
        dict(slug="04-multi-socket-machines-and-interconnects", title="Multi-Socket Machines and Interconnects",
             hook="On a two-socket server the network card is wired to one socket and the strategy thread was pinned to the other: every packet and every order crossed the interconnect, twice, and nobody had looked at the topology.",
             sections=["Non-uniform memory access", "The socket interconnect and remote caches", "The peripheral bus and direct memory access", "Where the network card sits", "Reading a machine's topology"],
             defines=["non-uniform memory access", "NUMA node", "first-touch allocation", "socket interconnect", "PCI Express", "direct memory access", "direct cache access", "device locality"],
             uses=["cache coherence (ch3)", "cache line (ch3)", "heterogeneous cores (ch2)"],
             tutorial="Read the topology from sysfs (CPUs, caches, NUMA nodes, PCI devices and their numa_node and local CPU lists) on this laptop and on a recorded two-socket fixture; measure core-to-core cache-line ping-pong latency between every pair of this laptop's CPUs. End state: a core-to-core latency heat map (it shows the hybrid core clusters) and a placement plan for the fixture server.",
             build="`firm.coreplan`: topology from sysfs or a fixture tree, a placement plan by role (feed, strategy, gateway, logger, housekeeping) that keeps the hot path on the network card's node, and validation rules; Python. Consumed by chapters 13 and 26.",
             problem="Wrong socket -- named result: the latency added per packet and per order by a remote placement, from a budget of interconnect crossings and remote-memory accesses.",
             facts=["Linux numa(7) and sysfs ABI documentation", "PCI-SIG: PCIe generation bandwidth per lane (dated)", "Intel Data Direct I/O technology overview (dated)", "a published measurement of cross-socket latency (paper or vendor document)"],
             data="Sysfs of this laptop; a synthetic two-socket sysfs fixture written by a script (not a copy of a real machine)."),
        dict(slug="05-measuring-latency", title="Measuring Latency",
             hook="A service's 99th percentile improved after a change that made it slower: the load generator waited for each reply before sending the next request, so during every stall it simply stopped measuring.",
             sections=["Clocks: cycle counters and the kernel's clocks", "Timestamping at the wire", "Histograms and percentiles", "Coordinated omission", "Profilers and hardware counters"],
             defines=["invariant time-stamp counter", "hardware timestamp", "latency histogram", "coordinated omission", "measurement overhead", "sampling profiler", "hardware performance counter"],
             uses=_U_TS + ["tail latency (ch1)", "jitter (ch1)", "time-stamp counter (ch2)", "microbenchmark (ch2)", "bootstrap percentile interval (B4.13)"],
             tutorial="Calibrate the time-stamp counter against the steady clock and measure the cost of each clock call; fill a log-linear histogram; drive a service with periodic stalls by a closed-loop and by an open-loop load generator, with and without the correction. End state: two percentile curves that disagree above the 90th percentile, measured on this laptop.",
             build="`firm.lathist`: a log-linear latency histogram (bounded relative error, constant-time record, merge, percentiles, serialisation) with coordinated-omission correction and a TSC clock calibrated against the steady clock; C++20, Rust and Python on one shared fixture.",
             problem="The benchmark that lied -- named result: the 99.9th percentile reported with and without the correction for a service that stalls 10 ms once a second.",
             facts=["Tene, How NOT to measure latency (talk, 2015) and the HdrHistogram documentation", "Intel SDM: RDTSC/RDTSCP semantics and the invariant TSC", "Linux clock_gettime(2) and the vDSO", "Linux perf_event_open(2), perf_event_paranoid", "MiFID II RTS 25 clock accuracy (pointer to B1.28)"],
             data="Measured on this laptop; a histogram fixture shared by the three languages."),
    ]),
    ("part.ll.languages", [
        dict(slug="06-cpp-for-latency-i-memory", title="C++ for Latency I: Memory",
             hook="A strategy ran at a steady two microseconds a message, except once or twice a minute when it took several hundred: the tail was the allocator, taking its slow path and faulting in a fresh page.",
             sections=["Object layout, padding and alignment", "What an allocation costs, and when", "Arenas, pools and free lists", "Small buffers and fixed-capacity containers", "Page faults and pre-faulting"],
             defines=["structure padding", "arena allocator", "object pool", "free list", "small-buffer optimisation", "fixed-capacity container", "page fault", "pre-faulting"],
             uses=["cache line (ch3)", "working set (ch3)", "latency histogram (ch5)", "hot path (ch1)"],
             tutorial="Count heap allocations with a replaced global operator new; measure the latency distribution of new/delete against a pool and a monotonic arena (std::pmr and hand-written); reorder a message struct's fields and watch its size and its line count change; count page faults with getrusage before and after pre-faulting. End state: allocation counts per message and the tail of each allocator, measured on this laptop.",
             build="`firm.arena`: arena, fixed-size object pool with an intrusive free list, fixed-capacity vector and string, and an allocation counter used by every later acceptance test to assert zero allocations on the hot path; C++20 and Rust.",
             problem="Four hundred microseconds, once a minute -- named result: allocations and page faults per message before and after the rewrite (from seven and a fault every few thousand messages to zero), and the tail they removed.",
             facts=["glibc malloc tunables: mmap threshold and trim threshold defaults (manual, dated)", "libstdc++ std::string small-string capacity (15 characters)", "C++17 polymorphic memory resources (standard, [mem.res])"],
             data="Measured on this laptop only."),
        dict(slug="07-cpp-for-latency-ii-compile-time", title="C++ for Latency II: Compile Time",
             hook="The handler called one virtual function per message; making the strategy a template parameter removed the indirect call, and the compiler then inlined the whole path from the decoder to the order.",
             sections=["Virtual dispatch and what it costs", "Static polymorphism: templates, CRTP and concepts", "Compile-time evaluation", "Inlining and its limits", "Branch layout and cold paths"],
             defines=["dynamic dispatch", "static polymorphism", "curiously recurring template pattern", "compile-time evaluation", "inlining", "devirtualisation", "cold path"],
             uses=["branch prediction (ch2)", "branch misprediction (ch2)", "microbenchmark (ch2)", "hot path (ch1)"],
             tutorial="Three dispatchers for the same message stream -- virtual calls, std::variant with std::visit, and a template pipeline -- benchmarked on predictable and on mixed message types; a lookup table computed at compile time with consteval; an error path marked cold and moved out of line, checked in the disassembly. End state: a chart of cycles per message by design and message mix.",
             build="`firm.pipeline`: compile-time composition of hot-path stages (decode, book, strategy, gateway) constrained by concepts, with a runtime-polymorphic adapter for tests; C++20, and a Rust twin with generics and traits. Used by chapters 20 and 26.",
             problem="The indirect branch -- named result: the cost per message of virtual against static dispatch when the target is predictable and when it is not (a ratio, measured; the tests assert only the ordering).",
             facts=["ISO C++20: concepts, consteval, [[likely]] (standard or cppreference)", "GCC manual: -fdevirtualize, function attributes cold and noinline", "Driesen and Holzle 1996, The direct cost of virtual function calls in C++ (OOPSLA)"],
             data="Measured on this laptop only."),
        dict(slug="08-cpp-for-latency-iii-the-compiler", title="C++ for Latency III: The Compiler",
             hook="In 2009 a null-pointer check vanished from a Linux kernel driver: the pointer had been dereferenced one line earlier, so the compiler concluded it could not be null. Undefined behaviour is a contract, and the optimiser reads it literally.",
             sections=["Undefined behaviour as an optimisation contract", "Aliasing", "Flags and target selection", "Profile-guided and link-time optimisation", "Reading assembly"],
             defines=["undefined behaviour", "strict aliasing", "profile-guided optimisation", "link-time optimisation", "function multiversioning"],
             uses=["inlining (ch7)", "compiler barrier (ch2)", "microbenchmark (ch2)", "fused multiply-add (B4.25)", "bitwise reproducibility (B4.25)"],
             tutorial="Build the feed decoder at -O0, -O2, -O3, -O3 -march=native, with profile-guided and with link-time optimisation under g++ 11; check that every build decodes the sample to the same bytes; read the hot loop in the disassembly; show a signed-overflow assumption removing a check, and the undefined-behaviour sanitiser catching it; show -ffast-math changing a result. End state: a table of speed-ups over -O2 and the one flag that changed an answer.",
             build="`firm.flagbench`: a driver that compiles a benchmark under a matrix of flag sets, verifies identical outputs, measures, and ranks; Python driving g++ and cargo. The firm's release flags are chosen with it.",
             problem="The fast build that was wrong -- named result: the speed-up of profile-guided plus link-time plus target-specific optimisation over -O2 on the decoder, and the output difference -ffast-math introduced.",
             facts=["Linux kernel tun driver null-check removal, CVE-2009-1897 (LWN coverage, 2009)", "ISO C++ definition of undefined behaviour ([defns.undefined])", "GCC 11 manual: -O levels, -fprofile-generate/-fprofile-use, -flto, -march, -ffast-math, target_clones", "Lattner 2011, What every C programmer should know about undefined behavior (LLVM blog)"],
             data="Measured on this laptop only; generated assembly committed with the compiler version named."),
        dict(slug="09-rust-for-low-latency", title="Rust for Low Latency",
             hook="A team porting its feed handler to Rust found the median unchanged and one allocation per message hidden in a convenient iterator adapter; the compiler had stopped them sharing the book across threads, but not from allocating.",
             sections=["Zero-cost abstractions, checked", "Unsafe code and its boundaries", "Controlling allocation", "Threads, pinning and what the type system guarantees", "Where async does and does not belong"],
             defines=["data race", "zero-cost abstraction", "bounds-check elimination", "sound abstraction", "global allocator", "async runtime"],
             uses=["arena allocator (ch6)", "static polymorphism (ch7)", "cache line (ch3)", "microbenchmark (ch2)"],
             tutorial="In one Rust crate: an iterator chain against an indexed loop and the bounds checks each leaves in the assembly; a counting global allocator asserting zero allocations per message; a thread pinned through sched_setaffinity by a small FFI declaration; the Rust twin of chapter 6's pool against the C++ one. End state: the C++ and Rust decoders side by side, cycles and allocations per message.",
             build="`firm.affinity`: thread placement by role -- pin, verify with sched_getcpu, name threads, read back the placement from firm.coreplan's plan; Rust and C++20.",
             problem="The port -- named result: the Rust-to-C++ ratio of median cycles per message for the decoder and the book, and allocations per message in each (zero in both after the fix).",
             facts=["Stroustrup, the zero-overhead principle (Foundations of C++, 2012)", "The Rust Reference and the Rustonomicon: unsafe, Send and Sync, GlobalAlloc", "Linux sched_setaffinity(2)"],
             data="Measured on this laptop only."),
        dict(slug="10-managed-and-functional-languages-on-the-desk", title="Managed and Functional Languages on the Desk",
             hook="An exchange built in Java processed millions of orders a second on a single thread; its authors pre-allocated everything, kept the business logic free of locks, and wrote about it in public.",
             sections=["Garbage collection and its pauses", "The low-latency managed style: pre-allocation, off-heap memory, warm-up", "Just-in-time compilation and deoptimisation", "The functional-language shops", "Choosing a language for a desk"],
             defines=["garbage collector", "stop-the-world pause", "off-heap memory", "just-in-time compilation", "warm-up period", "deoptimisation"],
             uses=["object pool (ch6)", "latency histogram (ch5)", "tail latency (ch1)"],
             tutorial="Python is the managed language at hand: record every garbage-collector pause through gc.callbacks while a message loop allocates, then pre-allocate NumPy record buffers and freeze the heap, and compare the pause distributions and the loop's tail. End state: two pause histograms and the loop's percentiles, measured on this laptop.",
             build="`firm.gcwatch`: a pause and allocation-rate monitor for the firm's Python services (gc callbacks into firm.lathist's Python histogram), with a pre-allocated message pool; acceptance: no full collection during the steady-state loop; Python.",
             problem="The garbage budget -- named result: the bytes a managed-language engine may allocate per order so that the young generation fills less than once in a trading session, for a given heap and message rate.",
             facts=["Fowler 2011, The LMAX Architecture (orders per second on one thread)", "Thompson, Farley, Barker, Gee and Stewart 2011, Disruptor technical paper", "Minsky and Weeks 2008, Caml trading (Journal of Functional Programming) and Minsky 2011, OCaml for the masses (ACM Queue)", "OpenJDK JEP 333 / JEP 377 ZGC pause-time goals (dated)", "Python gc module documentation (gc.freeze, gc.callbacks)"],
             data="Measured on this laptop only."),
        dict(slug="11-lock-free-programming", title="Lock-Free Programming",
             hook="In 1997 a spacecraft on Mars kept resetting itself: a low-priority task held a lock that a high-priority task needed while a medium-priority task ran. A trading thread waiting on a logger's lock has the same problem, only faster.",
             sections=["Atomics and the memory model", "Memory ordering: acquire, release, sequential consistency", "Compare-and-swap loops and the ABA problem", "Safe memory reclamation", "Progress guarantees"],
             defines=["atomic operation", "memory ordering", "acquire--release ordering", "sequential consistency", "compare-and-swap", "ABA problem", "hazard pointer", "epoch-based reclamation", "lock-free", "wait-free", "priority inversion"],
             uses=["data race (ch9)", "cache coherence (ch3)", "false sharing (ch3)", "out-of-order execution (ch2)"],
             tutorial="A Treiber stack in C++ with a tagged pointer against the ABA problem, stress-tested under the thread sanitiser; a counter under a mutex, a compare-and-swap loop, a fetch-add and per-thread counters, scaled from one to eight threads; the same stack in Rust, where the borrow checker forces the reclamation question into the open. End state: a scaling chart of operations per second by design and thread count, measured on this laptop.",
             build="`firm.mpmcq`: a bounded multi-producer multi-consumer queue (per-slot sequence numbers) with stress tests that check every item is delivered exactly once; C++20 and Rust.",
             problem="The descheduled lock holder -- named result: the expected time per second the trading thread spends blocked behind a logger's mutex, given the logger's hold time and the chance it is descheduled while holding it, against zero for the lock-free queue.",
             facts=["Jones 1997, What really happened on Mars (Pathfinder priority inversion, Reeves account)", "Boehm and Adve 2008, Foundations of the C++ concurrency memory model (PLDI)", "Herlihy 1991, Wait-free synchronization (TOPLAS)", "Treiber 1986, Systems programming: coping with parallelism (IBM RJ 5118)", "Michael 2004, Hazard pointers (IEEE TPDS)", "Fraser 2004, Practical lock-freedom (Cambridge PhD thesis)"],
             data="Measured on this laptop only."),
        dict(slug="12-queues-ring-buffers-and-shared-memory", title="Queues, Ring Buffers and Shared Memory",
             hook="A team measured a three-stage pipeline built on a standard blocking queue and found that the queues, not the work, dominated its latency; the ring buffer they replaced them with became a pattern with its own name.",
             sections=["The single-producer single-consumer ring", "Many readers: the disruptor pattern", "Sequence locks for last-value data", "Shared memory between processes", "Back-pressure, slow consumers and conflation"],
             defines=["ring buffer", "single-producer single-consumer queue", "disruptor pattern", "sequence lock", "shared-memory transport", "back-pressure", "slow consumer", "conflation"],
             uses=["acquire--release ordering (ch11)", "false sharing (ch3)", "lock-free (ch11)", "wait-free (ch11)", "M/M/1 queue (B4.8)"],
             tutorial="An SPSC ring in C++ with cached indices; its round-trip latency between two pinned threads on the same core cluster and across clusters; a seqlock publishing the top of the book; a ring in /dev/shm written by a Rust process and read by a C++ process. End state: round-trip histograms by placement, measured on this laptop, and a cross-language test that passes.",
             build="`firm.ring`: SPSC ring, broadcast ring with per-reader sequences (disruptor style), seqlock slot, shared-memory segment with a versioned header; C++20 and Rust sharing one memory layout. The transport of every Part IV component.",
             problem="Three strategies, one feed -- named result: the time before a slow consumer is overrun in a broadcast ring of given size during a burst, and the share of updates a conflating reader skips.",
             facts=["Thompson et al. 2011, Disruptor technical paper (queue against ring latency figures)", "Lamport 1983, Specifying concurrent program modules (TOPLAS) -- the single-producer single-consumer queue", "Linux seqlock documentation (kernel locking docs)", "Boehm 2012, Can seqlocks get along with programming language memory models? (MSPC)", "POSIX shm_open(3)"],
             data="Measured on this laptop only."),
        dict(slug="13-linux-tuning", title="Linux Tuning",
             hook="A thread that should have run without interruption was stopped for a few microseconds every few milliseconds, like a clock; it was the kernel's own timer tick, and the fix was a boot parameter.",
             sections=["Core isolation and CPU affinity", "Interrupts and their affinity", "Tickless kernels and housekeeping", "Busy polling and kernel bypass", "Real-time priorities and memory locking"],
             defines=["CPU affinity", "core isolation", "housekeeping core", "interrupt affinity", "tickless kernel", "context switch", "busy polling", "kernel bypass", "real-time scheduling policy", "memory locking"],
             uses=["jitter (ch1)", "page fault (ch6)", "time-stamp counter (ch2)", "device locality (ch4)", "NUMA node (ch4)"],
             tutorial="Measure what this machine allows: a spinning thread that records every gap in its own time-stamp readings (a hiccup meter), alone, pinned, and next to a competing load; busy polling against a blocking receive on a loopback UDP socket; mlockall and the page-fault count. The isolation, interrupt and real-time steps are shown as the commands a tuned host runs, with what a reader would see there. End state: the gap histograms and the loopback receive latencies, measured on this laptop, no isolated cores.",
             build="`firm.tuneaudit`: audits a host against firm.coreplan's plan -- kernel command line, isolated and tickless CPU lists, interrupt affinities, frequency governors, idle-state limits, transparent huge pages, locked memory limits -- and reports each deviation; tested on fixture sysfs and procfs trees; Python.",
             problem="The hiccup -- named result: the fraction of wall time a spinning thread is not running and its worst gap on this laptop, against a tuned host modelled from cited figures.",
             facts=["Linux kernel documentation: kernel-parameters (isolcpus, nohz_full, irqaffinity, rcu_nocbs), timers/no_hz", "Red Hat Enterprise Linux for Real Time tuning guide (dated)", "socket(7): SO_BUSY_POLL; sched(7); mlockall(2)", "a public description of kernel-bypass stacks (vendor or open-source documentation)"],
             data="Measured on this laptop; synthetic sysfs/procfs fixtures for a tuned and a mis-tuned host."),
        dict(slug="14-vector-instructions-and-data-parallel-code", title="Vector Instructions and Data-Parallel Code",
             hook="A parser that reads one byte at a time looks at a JSON message the way a person reads a page letter by letter; a published parser that reads thirty-two bytes per instruction processes gigabytes a second on one core.",
             sections=["SIMD registers and instruction sets", "Auto-vectorisation and what blocks it", "Intrinsics and CPU feature dispatch", "Where vectorisation pays in a trading system", "Structure of arrays"],
             defines=["SIMD", "vector instruction", "auto-vectorisation", "compiler intrinsic", "CPU feature dispatch", "structure of arrays"],
             uses=["instructions per cycle (ch2)", "compiler barrier (ch2)", "function multiversioning (ch8)", "fused multiply-add (B4.25)"],
             tutorial="Find a delimiter and parse eight ASCII digits with AVX2 intrinsics behind a runtime feature check, with a scalar reference that the tests compare byte for byte; price a batch of options stored as a structure of arrays and read the compiler's vectorisation report at -O2 and -O3 under g++ 11; the same scan in Rust with std::arch. End state: bytes per cycle of the scalar, SSE and AVX2 scans by message length, measured on this laptop.",
             build="`firm.simdscan`: byte-class scanning (delimiters, structural characters) and integer and fixed-point parsing, with scalar fallbacks and dispatch; C++20 and Rust. Consumed by firm.fixengine and firm.wsclient.",
             problem="Thirty-two bytes at a time -- named result: the message length below which the vector scan does not repay its setup, from the measured cost per byte and per call.",
             facts=["Langdale and Lemire 2019, Parsing gigabytes of JSON per second (VLDB Journal)", "Lemire 2021, Number parsing at a gigabyte per second (Software: Practice and Experience)", "Intel Intrinsics Guide (AVX2)", "GCC 12 release notes: vectorisation enabled at -O2 (so not in g++ 11)"],
             data="Measured on this laptop only."),
    ]),
    ("part.ll.protocols", [
        dict(slug="15-protocols-i-fix", title="Protocols I: FIX",
             hook="An order sent from a fund to its broker this morning most likely travelled as a line of tag=value pairs whose format two firms agreed in 1992; the protocol is old, slow to parse naively, and everywhere.",
             sections=["Tag-value encoding and the message", "The session layer: logon, heartbeats, sequence numbers, resend and gap fill", "The application layer: orders and execution reports", "Parsing fast", "Where FIX is still used"],
             defines=["FIX protocol", "tag-value encoding", "FIX session", "heartbeat", "resend request", "gap fill", "FIX engine"],
             uses=["sequence number (B1.28)", "execution report (B10.26)", "order lifecycle (B7.17)", "partial fill (B7.17)", "SIMD (ch14)", "direct market access (B1.4)"],
             tutorial="Parse and build FIX 4.4 messages in C++ with zero-copy field views over the buffer, body length and checksum included; replay a recorded conversation with a gap through the session state machine and watch the resend request and the gap fill; compare parse throughput with a map-based parser. End state: a table of messages per second by parser, measured on this laptop, and the session trace.",
             build="`firm.fixengine`: tag-value codec (zero-copy views, checksum, body length), session state machine (logon, heartbeat, test request, resend request, sequence reset and gap fill, logout) and a message store for resends; C++20, Rust and a Python reference; golden conversations as fixtures.",
             problem="The weekend gap -- named result: messages resent and time to resynchronise after a disconnect of a given length at a given message rate, with and without gap fill of administrative messages.",
             facts=["FIX Trading Community: history (1992, Fidelity and Salomon Brothers)", "FIX 4.4 and FIXT 1.1 / FIX 5.0 SP2 specifications: tags 8, 9, 35, 34, 49, 56, 52, 10, checksum and body length rules", "FIX Performance Session Layer (FIXP) and FIX over SBE (dated)", "venues and brokers that offer FIX order entry today (dated)"],
             data="Golden FIX conversations written by the chapter's script (synthetic)."),
        dict(slug="16-protocols-ii-binary-exchange-protocols", title="Protocols II: Binary Exchange Protocols",
             hook="A futures exchange sends every market-data packet twice, over two separate networks, as fixed-layout binary messages a handler can read without parsing; the handler's first job is to keep whichever copy arrives first and forget the other.",
             sections=["Order-by-order feeds and their messages", "Packets, sequence numbers and multicast", "Incremental and snapshot channels, retransmission and recovery", "Arbitration of redundant lines", "Binary order entry and simple binary encoding"],
             defines=["multicast", "line arbitration", "message gap", "incremental channel", "snapshot channel", "simple binary encoding", "flyweight codec"],
             uses=_U_FEED + _U_SIM + ["redundant feed lines (B10.26)", "retransmission request (B10.26)", "snapshot recovery (B10.26)", "order-entry protocol (B10.26)", "order-entry session (B10.26)", "mass quote (B11.19)", "FIX session (ch15)", "direct feed (B1.9)", "snapshot-and-delta feed (B3.26)"],
             tutorial="Decode the exchange simulator's recorded A and B lines with C++ and Rust flyweights, zero-copy; generate a little-endian SBE-style codec for the same messages from an XML schema with a Python generator and compare it with Book 1's big-endian decoder; count gaps on each line and on the arbitrated stream. End state: gap counts per line and arbitrated, and decode throughput by codec, measured on this laptop.",
             build="`firm.wirecodec`: flyweight codecs for the simulator's feed (packet header, order-by-order messages, snapshot) and order-entry messages, generated from one schema into C++20 and Rust (generated files committed and checked for no diff), validated against Book 10's golden fixtures; Python generator.",
             problem="Two copies of everything -- named result: the probability that a message is lost on both lines at a per-packet loss rate, independent and with correlated bursts, and the recovery time from the snapshot channel at its publication interval.",
             facts=["Nasdaq TotalView-ITCH 5.0, MoldUDP64 and SoupBinTCP specifications", "Nasdaq OUCH 5.0 specification", "CME MDP 3.0: SBE encoding, A/B feeds, market recovery (client systems wiki, dated)", "FIX Simple Binary Encoding standard (version and date)", "Eurex EOBI/ETI documentation (dated)"],
             data="Book 10 simulator's recorded lines and golden fixtures; until it lands, Book 1's firm.feed sample packetised by the chapter's script."),
        dict(slug="17-websocket-rest-tls-and-json-at-speed", title="WebSocket, REST, TLS and JSON at Speed",
             hook="A crypto market maker's server sits in the same cloud region as the venue, a fraction of a millisecond away; decoding the venue's JSON depth updates and signing its own requests took longer than the network, until both moved off the hot path.",
             sections=["HTTP, REST and connection reuse", "TLS: the handshake and the record layer", "WebSocket framing", "JSON at speed", "Signing requests off the hot path"],
             defines=["REST interface", "persistent connection", "connection pool", "TLS handshake", "session resumption", "WebSocket", "WebSocket frame", "structural index", "request signature"],
             uses=["API key (B3.15)", "rate limit (B3.15)", "request weight (B3.15)", "snapshot-and-delta feed (B3.26)", "book checksum (B3.26)", "cloud region (B3.26)", "SIMD (ch14)"],
             tutorial="On loopback, measure a full TLS handshake against a resumed one (Python ssl, self-signed certificate made by the openssl command) and the record layer's cost per kilobyte; parse WebSocket frames (masking, fragmentation, control frames) in C++; decode a depth-update message with a structural index against a naive parser; precompute the HMAC state of a request signature. End state: a stacked budget for one websocket order -- network, TLS, framing, JSON, signing -- measured on this laptop.",
             build="`firm.wsclient`: WebSocket frame codec, a structural-index JSON decoder for depth updates feeding Book 3's firm.wsbook, an HMAC-SHA256 request signer checked against the RFC 4231 vectors, and a connection pool governed by Book 3's firm.ratelimit; C++20, Rust and a Python reference.",
             problem="Cloud to venue -- named result: the share of a websocket strategy's tick-to-trade spent in decryption, JSON and signing against the network hop, and what connection reuse saves per order.",
             facts=["RFC 6455 (WebSocket)", "RFC 8446 (TLS 1.3: one round trip, 0-RTT)", "RFC 2104 and RFC 4231 (HMAC, test vectors)", "RFC 9110 and RFC 9112 (HTTP semantics, persistent connections)", "a major crypto venue's websocket and request-signing documentation (dated; see B3.15)"],
             data="Synthetic depth updates in a venue-like JSON shape written by a script; measured on this laptop."),
    ]),
    ("part.ll.system", [
        dict(slug="18-the-feed-handler", title="The Feed Handler",
             hook="At the open the message rate jumped a hundredfold; the handler fell behind, the socket buffer overflowed, line A lost a packet that line B lost too, and the firm's book was stale for tens of milliseconds while it recovered from a snapshot.",
             sections=["Decode and arbitrate", "Detect gaps and recover", "Normalise and publish", "Bursts, buffers and slow consumers", "Monitoring a feed"],
             defines=["feed handler", "message burst", "stale-book flag", "receive buffer overrun", "recovery latency"],
             uses=_U_FEED + _U_SIM + ["line arbitration (ch16)", "message gap (ch16)", "snapshot channel (ch16)", "retransmission request (B10.26)", "ring buffer (ch12)", "slow consumer (ch12)", "M/M/1 queue (B4.8)"],
             tutorial="Run the C++ handler on the simulator's recorded A and B lines with injected loss, reordering and a burst; watch arbitration, gap detection, the retransmission request, snapshot recovery and the stale-book flag; compare the normalised output with the clean run's. End state: a timeline of staleness intervals and the per-packet handling-time histogram, measured on this laptop.",
             build="`firm.feedhandler`: A/B arbitration by packet sequence, gap detection with a timeout, recovery by retransmission then snapshot, normalisation to the firm's event record, publication on firm.ring, counters for monitoring; C++20 and Rust with a Python reference; acceptance: identical normalised output on clean and impaired lines once recovered, in all three languages.",
             problem="The opening burst -- named result: the receive-buffer size a handler with a given service time needs to absorb a burst of a given size and rate without loss, and the staleness a snapshot interval implies when it does lose.",
             facts=["socket(7) and the net.core.rmem_max / SO_RCVBUF behaviour (the kernel doubles the value)", "a published peak message rate of a major feed (for example OPRA capacity figures, dated)", "CME MDP 3.0 market-recovery procedure (dated)"],
             data="Book 10 simulator's recorded lines with seeded impairments."),
        dict(slug="19-the-order-book-builder", title="The Order-Book Builder",
             hook="A book keyed by a balanced tree took hundreds of nanoseconds per update at the open; an array of price levels around the touch took a few tens, and then broke on the first stock that moved thirty percent in a day.",
             sections=["What the book must answer, and how fast", "Structures by feed type and tick regime", "Order lookup: hash tables and open addressing", "Correctness under gaps, crosses and recovery", "Testing a book"],
             defines=["book builder", "dense price ladder", "open addressing", "book invariant"],
             uses=_U_FEED + _U_BOOK + _U_SIM + ["feed handler (ch18)", "stale-book flag (ch18)", "cache miss (ch3)", "working set (ch3)", "microprice (B7.8)"],
             tutorial="Three builders -- tree map, sorted vector and a recentring dense ladder with an open-addressing order map -- driven by the simulator's day for a large-tick and a small-tick instrument; a differential test against Book 1's firm.feed book and Book 7's firm.lobfeat on shared fixtures. End state: update-time histograms by structure and tick regime, measured on this laptop.",
             build="`firm.bookbuilder`: order-by-order book with constant-time order lookup, a dense ladder with recentring and a sparse fallback, level 1 and level 2 queries, invariants checked in debug builds, invalidation on gaps and rebuild from a snapshot; C++20 and Rust with a Python reference; acceptance: identical level 2 to firm.feed and firm.lobfeat on the fixtures and zero allocations per update after warm-up.",
             problem="The stock that moved thirty percent -- named result: the ladder width against the expected number of recentrings a day for a given daily volatility and tick, and the width that minimises the day's total cost.",
             facts=["Nasdaq ITCH 5.0: order replace semantics (priority lost)", "cppreference: std::map node allocation and complexity"],
             data="Book 10 simulator's recorded day (large-tick and small-tick instruments); Book 1 and Book 7 fixtures."),
        dict(slug="20-the-strategy-engine", title="The Strategy Engine",
             hook="Two runs of the same strategy on the same day's data ended with different profits: one component iterated a hash map, another read the wall clock. After both were removed the runs agreed to the last bit, and every later bug could be replayed.",
             sections=["The event loop", "Single-threaded determinism", "Timers and the injected clock", "Configuration and parameters at run time", "Hot-path discipline"],
             defines=["event loop", "run-to-completion processing", "timer wheel", "injected clock", "parameter snapshot"],
             uses=_U_SIM + ["simulated clock (B7.17)", "bitwise reproducibility (B4.25)", "quoting engine (B11.10)", "cancel-replace (B11.10)", "microprice (B7.8)", "ring buffer (ch12)", "hot path (ch1)"],
             tutorial="Build the C++ engine: ring inputs, an event loop, a timer wheel and a simple quoting strategy on Book 7's microprice; run it twice on the same recorded input and compare output hashes; inject a wall-clock read and a hash-map iteration and watch the hashes diverge. End state: identical hashes over repeated runs, and the divergence table with each source of nondeterminism switched on.",
             build="`firm.stratengine`: event loop over market, order and timer events with fixed ordering rules, an injected clock (simulated or real), a timer wheel, versioned parameter snapshots applied between events; C++20 and Rust; acceptance: bit-identical output on replay and zero allocations in steady state.",
             problem="Two runs, two profits -- named result: the number of distinct outcomes in a hundred reruns with each source of nondeterminism switched on, and one after the fixes.",
             facts=["Varghese and Lauck 1987, Hashed and hierarchical timing wheels (SOSP)", "Fowler 2011, The LMAX Architecture (single-threaded business logic)"],
             data="Book 10 simulator's recorded day."),
        dict(slug="21-order-gateway-and-order-management", title="Order Gateway and Order Management",
             hook="A strategy cancelled an order and, a few microseconds later, sent its replacement; the cancel crossed a fill on the way, the exchange rejected it as too late, and for a moment the firm held twice the position it believed it held.",
             sections=["The order state machine", "Acknowledgements, in-flight orders and races", "Throttles and message budgets", "Sessions: login, sequence numbers, cancel on disconnect", "Drop copies and reconciliation"],
             defines=["order gateway", "order state machine", "in-flight order", "cancel--fill race", "token bucket", "drop copy"],
             uses=_U_SIM + ["order lifecycle (B7.17)", "partial fill (B7.17)", "rate limit (B3.15)", "execution report (B10.26)", "order-entry protocol (B10.26)", "order-entry session (B10.26)", "cancel on disconnect (B10.26)", "self-trade prevention (B10.26)", "order management system (B10.20)", "message throttle (B11.10)", "position (B1.7)"],
             tutorial="Connect the C++ gateway to the simulator's order-entry session: a table-driven state machine, conservative position accounting for in-flight orders, a token-bucket throttle; inject cancel-fill races through the simulator's latency model; reconcile the gateway's view against the drop-copy session. End state: a race-frequency chart against cancel latency, and a reconciliation report with zero breaks.",
             build="`firm.ordergw`: order-entry session (login, sequencing, heartbeats, replay on reconnect), order state machine with pending states, worst-case position accounting on Book 1's firm.pnl (its C++20 and Rust twins), token-bucket throttle, drop-copy reconciler; C++20 and Rust with a Python reference; acceptance: property tests over random interleavings (filled never exceeds ordered, no negative leaves, exposure bound respected) and conformance against the simulator.",
             problem="The cancel that crossed a fill -- named result: the probability of a cancel-fill race per cancel as a function of the cancel's latency and the fill intensity, and the worst over-position without in-flight accounting.",
             facts=["FIX OrdStatus and ExecType values (FIX specification)", "Nasdaq OUCH 5.0 order states and cancel reasons", "exchange cancel-on-disconnect functionality (for example CME iLink, dated)", "drop-copy services of a major exchange (dated)"],
             data="Book 10 simulator's order-entry and drop-copy sessions."),
        dict(slug="22-pre-trade-risk-and-kill-switches", title="Pre-Trade Risk and Kill Switches",
             hook="On 1 August 2012 a broker-dealer's order router sent millions of unintended orders in forty-five minutes (One Quant Book 7, chapter 21, tells the story). Read as a requirements document, the regulator's order lists the checks, limits and kill switch this chapter implements.",
             sections=["The requirements document: the 2012 incident and the rules it produced", "Checks in nanoseconds", "Limits in a hierarchy, updated live", "Kill switches: block, cancel, flatten", "Where the checks sit: gateway, separate process, broker, exchange"],
             defines=["risk gate", "worst-case exposure", "mass cancel", "fail-closed design"],
             uses=["kill switch (B11.27)", "pre-trade risk check (B11.27)", "price collar (B11.27)", "risk limit (B6.29)", "risk hierarchy (B6.29)", "sponsored access (B1.4)", "canary deployment (B7.21)", "in-flight order (ch21)", "order gateway (ch21)"],
             tutorial="Implement the checks in C++ with precomputed per-instrument limits in a dense table and branch-light code; measure the cost per check; replay a runaway child-order generator of the 2012 shape against the simulator with and without each check. End state: the position and order count reached before each check trips, and the per-check cost, measured on this laptop.",
             build="`firm.riskgate`: price collar, order size and notional, position limits including in-flight orders, order and message rates, duplicate detection, a limit hierarchy updated atomically between events, kill switch (block, mass cancel, optional flatten), audit records; C++20 and Rust with a Python reference; acceptance: every check at its boundaries, the runaway stopped within a stated number of orders, zero allocations, fail closed on stale limits.",
             problem="Forty-five minutes -- named result: orders sent and position reached before each check trips for a runaway generator at the 2012 incident's rates, against the incident's actual totals.",
             facts=["SEC Release 34-70694 (2013), In the Matter of Knight Capital Americas LLC: orders, executions, shares, positions, loss", "SEC Rule 15c3-5 (17 CFR 240.15c3-5), market access controls", "Commission Delegated Regulation (EU) 2017/589 (RTS 6): pre-trade controls and kill functionality (articles 12 and 15)", "FIA best practices for automated trading risk controls (dated)", "exchange-provided kill switches (dated)"],
             data="Book 10 simulator; runaway rates from the SEC order."),
        dict(slug="23-logging-capture-and-replay", title="Logging, Capture and Replay",
             hook="A regulator asked why one order was sent at a given nanosecond. The firm answered by replaying the day's captured inputs through the same binary and showing the decision, the book and the parameters that produced it, to the bit.",
             sections=["Why formatted logging is not for the hot path", "Binary logging and deferred formatting", "Capture: inputs, outputs and time", "Deterministic replay of a production day", "What must be kept, and for how long"],
             defines=["binary log", "deferred formatting", "input journal", "deterministic replay"],
             uses=_U_TS + ["event loop (ch20)", "injected clock (ch20)", "ring buffer (ch12)", "replay parity test (B7.19)", "order-book replay (B7.18)", "bitwise reproducibility (B4.25)"],
             tutorial="Log from the hot path as fixed-size records (a format identifier and raw arguments) into a ring drained by a writer thread; decode and format offline in Python; compare the hot-path cost with fprintf and std::format; journal the strategy engine's inputs, replay them and find a planted nondeterminism by bisecting the first diverging record. End state: cost per log call by method, measured on this laptop, and a replay that matches to the bit.",
             build="`firm.binlog`: log statements registered at compile time, a lock-free record ring, a writer thread, a file format with a schema header, a Python decoder, an input journal and a replay driver for firm.stratengine; C++20 and Rust with the Python decoder; acceptance: bit-identical replay and zero allocations on the logging path.",
             problem="To the nanosecond -- named result: journal storage per day at given message rates and compression ratio, and the replay speed against real time.",
             facts=["Yang et al. 2018, NanoLog: a nanosecond scale logging system (USENIX ATC)", "Commission Delegated Regulation (EU) 2017/589 (RTS 6) record-keeping of algorithmic trading (article 28)", "Commission Delegated Regulation (EU) 2017/574 (RTS 25) timestamp granularity (pointer to B1.28)", "CAT NMS Plan record requirements (dated)"],
             data="Recorded inputs of chapter 20's engine."),
        dict(slug="24-resilience", title="Resilience",
             hook="On 1 October 2020 a stock exchange halted trading for a full day: a storage device failed and the automatic switch to its backup did not happen as designed. Failover is a feature that is exercised rarely, and so fails when it is needed.",
             sections=["Failure modes of a trading system", "Sequencer architectures", "Replicated state machines and failover", "Exchange disconnects and recovery", "Testing failover"],
             defines=["sequencer architecture", "replicated state machine", "primary--backup replication", "failover", "split brain", "idempotent processing"],
             uses=_U_SIM + ["input journal (ch23)", "deterministic replay (ch23)", "cancel on disconnect (B10.26)", "drop copy (ch21)", "heartbeat (ch15)", "operational risk (B6.28)"],
             tutorial="Model the architecture in Python, then run it in C++: a sequencer that numbers every input, two replicas of the engine and order state applying the journal, the primary killed at every cut point of a short scenario, the backup taking over with a fencing epoch; then the simulator drops the order-entry session and the gateway reconnects, replays from its sequence number and reconciles its open orders. End state: a table of failure points against recovery outcome (state equal, orders duplicated or not) with and without idempotency keys.",
             build="`firm.sequencer`: sequencer, journal, replica apply, failover with fencing epochs, and the gateway's reconnect-and-reconcile procedure; Python reference, C++20 and Rust; acceptance: state equality after failover at every cut point of the scenario, no duplicate orders after reconnect.",
             problem="The failover that doubled the orders -- named result: duplicate orders sent after a failover without idempotency keys, over the distribution of failure points, and zero with them, with the recovery time achieved.",
             facts=["Japan Exchange Group / Tokyo Stock Exchange report on the 1 October 2020 system failure", "Schneider 1990, Implementing fault-tolerant services using the state machine approach (ACM Computing Surveys)", "Ongaro and Ousterhout 2014, In search of an understandable consensus algorithm (Raft, USENIX ATC)", "Fowler 2011, The LMAX Architecture (replicated business logic)"],
             data="Book 10 simulator with scheduled session drops."),
        dict(slug="25-testing-and-deploying-low-latency-systems", title="Testing and Deploying Low-Latency Systems",
             hook="A release passed every functional test and added a few hundred nanoseconds to the 99th percentile, because one log statement had moved inside the hot loop; the performance gate caught it, after two false alarms the week before had taught the team how to run it.",
             sections=["The test pyramid for a trading system", "Tests backed by the exchange simulator", "Exchange certification and conformance", "Performance regression gates", "Staged rollouts and rollback"],
             defines=["property-based test", "differential test", "fuzz testing", "exchange certification", "performance regression gate"],
             uses=_U_SIM + ["canary deployment (B7.21)", "staged rollout (B7.21)", "paper trading (B7.21)", "permutation test (B4.13)", "bootstrap (B4.13)", "power of a test (B4.12)", "microbenchmark (ch2)"],
             tutorial="Fuzz the FIX parser with a mutational loop and the sanitisers; property-test the order gateway over random interleavings; run a certification script against the simulator; then gate a planted regression with interleaved A/B benchmark runs and a bootstrap on the percentile ratio, on this noisy shared laptop. End state: the gate's false-alarm rate and detection rate against the number of interleaved runs.",
             build="`firm.perfgate`: interleaved A/B benchmark runner, bootstrap and permutation comparison of latency percentiles, thresholds and a report, plus a certification-script runner against the simulator; Python.",
             problem="A few hundred nanoseconds -- named result: the number of interleaved runs the gate needs to detect a 5% rise in the 99th percentile with 90% power at this machine's measured noise.",
             facts=["Claessen and Hughes 2000, QuickCheck (ICFP)", "Commission Delegated Regulation (EU) 2017/589 (RTS 6): testing of algorithms and conformance testing (articles 5-7)", "a major exchange's certification requirements before production access (dated)", "Beyer et al., Site Reliability Engineering (canarying releases)"],
             data="Measured on this laptop; Book 10 simulator for the certification script."),
        dict(slug="26-build-tick-to-trade-measured", title="Build: Tick-to-Trade, Measured",
             hook="A packet leaves the simulated exchange, and some microseconds later an order comes back: the whole path of this book is assembled, and every stage stamps the time it took.",
             sections=["Assembling the path", "Instrumentation points and stage timestamps", "The budget against the measurement", "What a tuned server would change"],
             defines=["instrumentation point", "latency attribution"],
             uses=_U_SIM + ["tick-to-trade latency (ch1)", "latency budget (ch1)", "latency histogram (ch5)", "feed handler (ch18)", "book builder (ch19)", "event loop (ch20)", "order gateway (ch21)", "risk gate (ch22)", "binary log (ch23)", "kernel bypass (ch13)"],
             tutorial="Replay the simulator's recorded A and B lines over loopback UDP at their recorded pace into the assembled C++ path (feed handler, ring, book builder, strategy engine, risk gate, gateway over TCP to the simulator), time every stage with the time-stamp counter into the binary log, and produce per-stage histograms and the budget report of chapter 1; run the Rust twin on the same input. End state: the end-to-end and per-stage histograms, measured on this laptop with no isolated cores, and the budget table.",
             build="`firm.ticktotrade`: the assembled path and its harness -- configuration, instrumentation points, per-stage histograms, budget report through firm.latbudget; C++20 and Rust; acceptance: orders identical to the Python reference strategy on the same input, zero allocations after warm-up, every stage timestamp ordered.",
             problem="The budget, proven -- named result: the measured median, 99th and 99.9th percentiles per stage and end to end on this laptop, and the projected figures for a tuned server built from cited per-stage factors.",
             facts=["STAC tick-to-trade benchmark reports (dated)", "a public talk giving a production tick-to-trade figure (dated)", "a kernel-bypass stack's published loopback or wire latency (dated)"],
             data="Book 10 simulator's recorded lines and order-entry server; measured on this laptop."),
    ]),
]
