"""Book 5 (Derivatives and Volatility) chapter briefs: data for
tools/make_briefs.py --book 5.

`uses` lists terms defined in One Quant Books 1-2, in a batch book (by its
outline numbering: Book 4 = Quantitative Methods, Book 6 = Rates, Credit, XVA
and Risk, Book 3 = Markets III), or earlier in this book. They are NOT
redefined (a term is defined once in the series); the text points to the
defining chapter in prose ("One Quant Book 4, chapter 3") or with \\cref
inside this book. The owner is given in parentheses.
"""
SLUG = "derivatives"
PFX = "dv"
HEAD = "One Quant Book 5 — Derivatives and Volatility"

# (part key, [chapters]); chapter = dict(slug, title, hook, sections, defines,
# uses, tutorial, build, problem, facts)
PARTS = [
    ("part.dv.foundations", [
        dict(slug="01-no-arbitrage-and-the-fundamental-theorems", title="No Arbitrage and the Fundamental Theorems",
             hook="Four S&P 500 index options, two calls and two puts, bought and sold together, pay exactly the distance between two strikes at expiry whatever the index does; their price on the screen is a zero-coupon bond, and a desk reads an interest rate off it.",
             sections=["Arbitrage and the law of one price", "State prices in one period", "Martingale measures and the first fundamental theorem", "Completeness, replication and the second theorem", "Price bounds when the market is incomplete"],
             defines=["arbitrage", "law of one price", "contingent claim", "replicating portfolio", "self-financing strategy", "Arrow--Debreu security", "state price", "state-price density", "fundamental theorem of asset pricing", "complete market", "super-replication price", "box spread"],
             uses=["call option, put option, strike price, expiry, European exercise (Book 1 ch. 23)", "put--call parity (Book 1 ch. 25)", "martingale, filtration, change of measure (Book 4 ch. 1)", "equivalent martingale measure, risk-neutral measure (Book 4 ch. 5)", "numeraire (Book 4 ch. 5)", "zero-coupon rate (Book 2 ch. 3)", "overnight benchmark rate (Book 2 ch. 1)", "repo rate (Book 2 ch. 5)"],
             tutorial="From a table of traded payoffs on a finite state grid, solve for the state prices; when no positive solution exists, find the arbitrage portfolio (a small hand-written simplex in numpy, no solver library); read the financing rate off a box spread.",
             build="`firm.arbcheck`: static-arbitrage checker for a chain of European quotes (bounds, monotonicity and convexity in strike, parity, box bounds); returns the violated inequality and the portfolio that exploits it.",
             problem="The box-spread rate — named result: the annualised financing rate implied by an index box spread and its spread over the overnight benchmark rate.",
             facts=["Cboe SPX options: European, cash-settled, multiplier (reuse Book 1 ledger)", "box spreads used as a financing instrument (Cboe materials)", "box-spread implied rates versus Treasury rates (van Binsbergen, Diamond, Grotteria 2022, JFE)", "Harrison-Kreps 1979, Harrison-Pliska 1981, Delbaen-Schachermayer 1994 publication details", "Arrow 1953/1964 and Debreu 1959 state-contingent claims"]),
        dict(slug="02-the-binomial-model", title="The Binomial Model",
             hook="A three-step tree on a whiteboard, eight end nodes, and a question: the price of a call, with no volatility number, no formula, only the two moves and the rate.",
             sections=["One period: replication and the risk-neutral probability", "Many periods: the recombining tree", "Calibrating the tree to a volatility", "Convergence and its oscillations", "American exercise on a tree"],
             defines=["binomial model", "recombining tree", "Cox--Ross--Rubinstein tree", "Jarrow--Rudd tree", "Leisen--Reimer tree"],
             uses=["replicating portfolio, self-financing strategy, risk-neutral measure (Book 4 ch. 5)", "American exercise (Book 1 ch. 23)", "dynamic programming (Book 4 ch. 9)", "central limit theorem (Book 4 ch. 1)"],
             tutorial="Price a European and an American put on CRR, JR and Leisen-Reimer trees from 10 to 1,000 steps and plot the error against the number of steps.",
             build="`firm.binomial`: recombining-tree pricer (CRR, JR, LR; European and American; the discrete-dividend hook is filled in chapter 5).",
             problem="The whiteboard tree — named result: the early-exercise premium of the American put on the three-step tree, and the number of CRR steps after which the price stays within one cent of its limit.",
             facts=["Cox, Ross, Rubinstein 1979 JFE", "Rendleman-Bartter 1979 JF", "Jarrow-Rudd 1983 book", "Leisen-Reimer 1996 Applied Mathematical Finance"]),
        dict(slug="03-black-scholes-three-ways", title="Black--Scholes Three Ways",
             hook="On 26 April 1973 the Chicago Board Options Exchange listed its first calls; the paper that priced them appeared in the Journal of Political Economy that same spring.",
             sections=["The model and the replication argument", "The pricing equation", "The martingale route", "The binomial limit", "Black's formula on forwards, and what each derivation teaches"],
             defines=["Black--Scholes model", "Black--Scholes equation", "Black--Scholes formula", "Black model"],
             uses=["geometric Brownian motion, Feynman--Kac formula (Book 4 ch. 4)", "Itô's formula (Book 4 ch. 3)", "Girsanov's theorem, numeraire (Book 4 ch. 5)", "implied volatility, put--call parity (Book 1 ch. 25)", "delta, delta hedging (Book 1 ch. 26)", "replicating portfolio, self-financing strategy, risk-neutral measure (Book 4 ch. 5)", "Cox--Ross--Rubinstein tree (ch. 2)", "futures option (Book 3 ch. 12)"],
             tutorial="Implement the Black-Scholes and Black formulas and a robust implied-volatility solver (rational initial guess, Newton safeguarded by bisection); check them against the tree of chapter 2 and against put-call parity to machine precision.",
             build="`firm.bs`: Black-Scholes / Black kernels: price, analytic Greeks, implied volatility (Python, C++20, Rust) — the inner loop every later engine and Book 6's risk engine call.",
             problem="One price, three derivations — named result: the price of a one-year at-the-money call by the formula, by a 1,000-step tree and by 10^6 Monte Carlo paths, with the error of each.",
             facts=["CBOE first trading day 26 April 1973, calls on 16 stocks", "Black & Scholes 1973 JPE 81(3) 637-654", "Merton 1973 Bell Journal", "1997 Nobel prize (Scholes, Merton; Black died 1995)", "Black 1976 JFE 'The pricing of commodity contracts'", "Jäckel 2015 'Let's be rational' (implied-volatility solver)"]),
        dict(slug="04-greeks-and-the-hedging-pnl", title="Greeks and the Hedging P\\&L",
             hook="An options trader is short one-month at-the-money straddles at 20 volatility; the share realises 25; at the end of the month the hedged book has lost almost exactly what the gamma-theta identity predicted on the first morning.",
             sections=["The Greeks and their shapes", "The gamma-theta identity and the hedging P&L", "Discrete hedging error", "Break-even volatility", "Which volatility to hedge at"],
             defines=["Greeks", "vega", "theta", "rho", "vanna", "volga", "cash gamma", "straddle", "hedging P\\&L", "discrete hedging error", "break-even volatility", "bump-and-reprice"],
             uses=["delta, delta hedging, gamma (Book 1 ch. 26)", "realised volatility, implied volatility (Book 1 ch. 25)", "P\\&L attribution (Book 1 ch. 7)", "delta-neutral straddle (Book 2 ch. 19)", "Itô's formula (Book 4 ch. 3)", "quadratic variation (Book 4 ch. 2)", "finite differences (Book 4 ch. 27)", "Black--Scholes formula (ch. 3)"],
             tutorial="Simulate delta hedging of a short call sold at 20% implied when realised is 25%, daily and hourly, hedged at the implied and at the realised volatility; plot the distribution of the hedging P&L and the path of cumulative gamma P&L.",
             build="`firm.greeks`: Greek calculator: analytic Greeks from `firm.bs`, central bump-and-reprice for any pricer, Greeks in money units (cash gamma, theta per day, vega per point), and the next-day P&L predictor.",
             problem="The short-straddle month — named result: the hedged P&L of a short one-month straddle when realised volatility exceeds implied by five points: its expectation from the gamma-theta identity and its standard deviation under daily hedging.",
             facts=["Boyle-Emanuel 1980 discrete hedging error", "Leland 1985 transaction costs", "Ahmad-Wilmott 2005 'Which free lunch would you like today, sir?' (hedging at implied versus realised)", "Carr's and Bergomi's P&L-of-hedging derivations (book references)"]),
        dict(slug="05-dividends-borrow-and-forwards", title="Dividends, Borrow and Forwards",
             hook="A share is on every broker's hard-to-borrow list; its one-month puts trade well above the calls at the strike nearest spot, and put-call parity turns the difference into a borrow rate of 35% a year.",
             sections=["Forwards with discrete dividends and borrow", "Dividends in the option model: escrowed, proportional, mixed", "Implying forwards, dividends and borrow from parity", "Dividend risk and dividend swaps"],
             defines=["escrowed dividend model", "proportional dividend", "mixed dividend model", "implied dividend", "implied borrow rate", "dividend risk", "dividend swap"],
             uses=["dividend, ex-dividend date (Book 1 ch. 8)", "put--call parity (Book 1 ch. 25)", "securities lending, rebate rate, borrow fee, short sale, locate (Book 1 ch. 6)", "dividend future (Book 1 ch. 22)", "cost of carry (Book 1 ch. 21)", "repo rate (Book 2 ch. 5)", "binomial model (ch. 2)", "Black model (ch. 3)"],
             tutorial="Build an equity forward curve from a synthetic multi-expiry chain: implied dividends and borrow per expiry; then price one option under the three dividend models and plot the differences by strike.",
             build="`firm.divfwd`: equity forward-curve builder (discrete cash and proportional dividends, borrow curve, implied from parity); it becomes `MarketData.forward` in chapter 28.",
             problem="The hard-to-borrow share — named result: the borrow rate implied by the one-month chain, and the mispricing of a call priced with the forward that ignores it.",
             facts=["Eurex Euro Stoxx 50 index dividend futures listing date and spec", "index dividend swap market practice (exchange or practitioner documents)", "ECB recommendation of 27 March 2020 on bank dividends and the 2020 dividend-futures fall", "Haug, Haug, Lewis 2003 on discrete dividends", "hard-to-borrow fee levels (reuse Book 1 ledger)"]),
        dict(slug="06-american-options-and-early-exercise", title="American Options and Early Exercise",
             hook="The share pays a dividend of 1.00 tomorrow and trades at 100.30; the 80 call is bid 20.40. Holders who exercise tonight keep the dividend; holders who forget leave it to the writers.",
             sections=["Why and when to exercise early", "The exercise boundary", "Dividends and rates as triggers", "Approximations and bounds", "The practical exercise decision"],
             defines=["early-exercise premium", "exercise boundary", "Bermudan exercise", "quadratic approximation"],
             uses=["American exercise, European exercise, assignment (Book 1 ch. 23)", "dividend, ex-dividend date (Book 1 ch. 8)", "optimal stopping, free boundary, smooth pasting, variational inequality (Book 4 ch. 10)", "binomial model (ch. 2)", "escrowed dividend model (ch. 5)"],
             tutorial="Compute the exercise boundary of an American put on a 2,000-step tree and compare it with the quadratic approximation; then find, for a call before an ex-dividend date, the dividend above which exercise is optimal.",
             build="`firm.american`: American pricer (tree with discrete dividends, Barone-Adesi-Whaley approximation) and an exercise-decision helper (exercise now or hold, with the threshold dividend).",
             problem="The night before the ex-date — named result: the smallest dividend at which exercising the 80 call the night before is optimal, and the value transferred to writers when a given share of holders fails to exercise.",
             facts=["Merton 1973: no early exercise of a call without dividends", "Barone-Adesi & Whaley 1987 JF", "Bjerksund-Stensland 1993/2002", "Pool, Stoll, Whaley 2008 'Failure to exercise call options' (J. Financial Markets)", "OCC exercise-by-exception threshold (reuse Book 1 ledger)"]),
    ]),
    ("part.dv.surface", [
        dict(slug="07-implied-volatility-and-its-surface", title="Implied Volatility and Its Surface",
             hook="Before October 1987 the implied volatilities of index options were nearly flat in strike; after it, low strikes have traded above high strikes every day since.",
             sections=["The surface as the market's price list", "Smile phenomenology by asset class", "Sticky strike, sticky delta and what the desk assumes", "Static no-arbitrage conditions", "The risk-neutral density"],
             defines=["volatility surface", "log-moneyness", "total implied variance", "sticky strike", "sticky delta", "static arbitrage", "butterfly arbitrage", "calendar arbitrage", "risk-neutral density", "Breeden--Litzenberger formula"],
             uses=["implied volatility, at-the-money, volatility skew, term structure of volatility (Book 1 ch. 25)", "risk reversal, butterfly (Book 2 ch. 19)", "normal volatility (Book 2 ch. 13)", "state price, state-price density (ch. 1)", "Black model (ch. 3)", "vega (ch. 4)"],
             tutorial="From a synthetic multi-expiry chain compute implied volatilities and total variance in log-moneyness, test the butterfly and calendar conditions, extract the risk-neutral density by finite differences and plot it.",
             build="`firm.volsurface`: implied-volatility surface object (expiry x log-moneyness grid, interpolation in total variance, arbitrage report) — the `VolSurface` of the pricing library.",
             problem="The crash premium — named result: the risk-neutral probability of a fall of more than 20% in three months under a flat and under a skewed surface with the same at-the-money volatility, and their ratio.",
             facts=["Rubinstein 1994 JF 'Implied binomial trees' (smile emergence after 1987)", "Jackwerth-Rubinstein 1996 JF", "Derman 1999 'Regimes of volatility' (sticky strike, sticky delta)", "Breeden-Litzenberger 1978 J. Business", "Carr-Madan 2005 static-arbitrage conditions", "smile shapes by asset class (FX, commodities, rates; references)"]),
        dict(slug="08-parametrising-the-surface", title="Parametrising the Surface",
             hook="A market maker's screen refreshes 400 strikes on 20 expiries several times a second; the model behind it has five numbers per expiry.",
             sections=["Why parametrise", "SVI and its surface version", "Splines and non-parametric fits", "Fitting to bid and ask", "Events, and business time against calendar time"],
             defines=["SVI parametrisation", "surface SVI", "Lee moment formula", "event variance", "business time"],
             uses=["total implied variance, log-moneyness, butterfly arbitrage, calendar arbitrage (ch. 7)", "vega (ch. 4)", "least squares, Levenberg--Marquardt (Book 4 ch. 16, 24)", "spline (Book 4 ch. 28)", "bid--ask spread (Book 1 ch. 1)"],
             tutorial="Fit raw SVI slice by slice to bid and ask quotes of a synthetic chain with vega weights, check it is free of butterfly arbitrage, fit SSVI to the whole surface and compare the errors; strip an earnings event out of the term structure.",
             build="`firm.svi`: SVI/SSVI fitter (quasi-explicit slice fit, bid-ask-aware objective, arbitrage checks) plugged into `volsurface`.",
             problem="Earnings week — named result: the implied move of an earnings announcement from the jump in total variance between the expiries before and after it.",
             facts=["Gatheral 2004 SVI presentation (Merrill Lynch origin, 1999)", "Gatheral-Jacquier 2014 Quant. Finance, arbitrage-free SVI", "Lee 2004 Math. Finance moment formula", "Zeliade 2009 quasi-explicit SVI calibration white paper", "Dubinsky-Johannes 2006 earnings announcements and option prices"]),
        dict(slug="09-local-volatility", title="Local Volatility",
             hook="Two desks price the same one-year cliquet with two models that both fit every listed vanilla to the tick; their prices differ by a third.",
             sections=["Dupire's formula", "Local volatility from implied volatility", "Calibration in practice", "What local volatility predicts: dynamics and the forward smile"],
             defines=["local volatility", "local volatility model", "Dupire formula", "Markovian projection", "forward smile"],
             uses=["volatility surface, total implied variance, log-moneyness, sticky strike (ch. 7)", "SVI parametrisation, surface SVI (ch. 8)", "Kolmogorov forward equation (Book 4 ch. 4)", "Monte Carlo (Book 4 ch. 26)"],
             tutorial="Compute local volatility from an SSVI surface with the total-variance form of Dupire's formula, reprice vanillas by Monte Carlo under it to check the fit, then compute the forward smile it implies and compare it with today's smile.",
             build="`firm.localvol`: Dupire local-volatility surface from a `volsurface` (total-variance formula, guarded derivatives) and a local-volatility path generator.",
             problem="The flattening forward smile — named result: the at-the-money skew of the six-month smile six months forward under local volatility, as a fraction of today's six-month skew.",
             facts=["Dupire 1994 Risk 'Pricing with a smile'", "Derman-Kani 1994", "Gyöngy 1986 mimicking theorem", "Hagan et al. 2002 on local volatility's smile dynamics"]),
        dict(slug="10-stochastic-volatility", title="Stochastic Volatility",
             hook="Asked why the calibrated correlation of the Heston model is minus 0.7, an index-options trader answers without a formula: because when the index falls, volatility rises.",
             sections=["Stochastic volatility models", "The Heston model", "The characteristic function and pricing", "Calibration", "What the parameters mean to a trader"],
             defines=["stochastic volatility model", "Heston model", "volatility of volatility", "spot--volatility correlation", "mixing formula"],
             uses=["square-root process, Feller condition (Book 4 ch. 4)", "characteristic function (Book 4 ch. 1)", "Fourier inversion (Book 4 ch. 28)", "complete market (ch. 1)", "calibration (Book 4 ch. 24)", "local volatility (ch. 9)"],
             tutorial="Price with the Heston characteristic function in its stable form, calibrate the five parameters to a synthetic surface, and show how each parameter moves the smile.",
             build="`firm.heston`: Heston characteristic function, semi-analytic pricer, calibration (numpy Levenberg-Marquardt), and the path generator used in chapter 23.",
             problem="Reading the parameters — named result: the change in the one-year 90-110 skew for a change of 0.2 in correlation, and the volatility of volatility that matches a quoted butterfly.",
             facts=["Heston 1993 RFS", "Albrecher et al. 2007 'The little Heston trap'", "Hull-White 1987 JF", "Romano-Touzi 1997 mixing", "leverage effect evidence (Black 1976; Bouchaud, Matacz, Potters 2001)"]),
        dict(slug="11-sabr-and-smile-dynamics", title="SABR and Smile Dynamics",
             hook="In 2002 four authors showed that the model many desks used to fit smiles predicted the smile would move the wrong way when the forward moved, so that its hedges were worse than none.",
             sections=["The SABR model", "The asymptotic formula", "Backbone and smile dynamics", "Hedging under a smile model", "Limits: wings and long expiries"],
             defines=["SABR model", "Hagan formula", "backbone", "minimum-variance delta"],
             uses=["stochastic volatility model, volatility of volatility, spot--volatility correlation (ch. 10)", "local volatility (ch. 9)", "sticky strike, sticky delta (ch. 7)", "Black model (ch. 3)", "vanna, volga (ch. 4)", "Bachelier model, normal volatility (Book 2 ch. 13)"],
             tutorial="Implement Hagan's lognormal and normal formulas, fit SABR at one expiry, plot the backbone for beta 0, one half and 1, and compare the Black delta, the minimum-variance delta and the realised hedge ratio on simulated paths.",
             build="`firm.sabr`: Hagan implied-volatility formulas (lognormal and normal), calibration with fixed beta, minimum-variance delta (Book 6 ch. 5 builds the cube and shifted SABR on it).",
             problem="Which delta — named result: the reduction in the variance of the hedging error from the minimum-variance delta over the Black delta on simulated SABR paths.",
             facts=["Hagan, Kumar, Lesniewski, Woodward 2002 Wilmott 'Managing smile risk'", "Bartlett 2006 Wilmott 'Hedging under SABR model'", "Obłój 2008 correction", "Hagan et al. 2014 arbitrage-free SABR (negative density in the wings)"]),
        dict(slug="12-rough-volatility-and-forward-variance-models", title="Rough Volatility and Forward-Variance Models",
             hook="Plot the logarithm of realised volatility's increments against the lag on log-log axes and the slope comes out near 0.1: volatility is rougher than any diffusion model allows.",
             sections=["Forward variance curves", "Bergomi's variance-curve models", "Rough volatility", "Path-dependent volatility", "Joint calibration to index and volatility-index options"],
             defines=["forward variance", "forward-variance model", "Bergomi model", "rough volatility", "rough Bergomi model", "path-dependent volatility model"],
             uses=["fractional Brownian motion, Hurst exponent (Book 4 ch. 17)", "volatility index, VIX future (Book 1 ch. 25)", "stochastic volatility model (ch. 10)", "Monte Carlo (Book 4 ch. 26)"],
             tutorial="Estimate the roughness of volatility from simulated and published realised-variance data, simulate the rough Bergomi model with the hybrid scheme, and show the at-the-money skew term structure against a power law.",
             build="`firm.fwdvar`: forward-variance curve object (from variance-swap strikes or the log-contract strip) and a rough-Bergomi simulator (hybrid scheme).",
             problem="The skew that will not flatten — named result: the power-law exponent of the at-the-money skew term structure fitted on the chapter's surface, and the Hurst exponent it implies.",
             facts=["Gatheral, Jaisson, Rosenbaum 2018 Quant. Finance 'Volatility is rough' (H near 0.1)", "Bayer, Friz, Gatheral 2016 rough Bergomi", "Bergomi 2005/2008 Risk 'Smile dynamics II, III'", "Guyon 2020 Risk, joint SPX/VIX smile calibration", "Guyon-Lekeufack 2023 'Volatility is (mostly) path-dependent'", "Bennedsen, Lunde, Pakkanen 2017 hybrid scheme", "availability and licence of a public realised-variance dataset"]),
        dict(slug="13-jumps-and-levy-models", title="Jumps and Lévy Models",
             hook="A one-week option on a biotechnology share that reports trial results on Thursday: a diffusion needs 150% volatility to price it, a jump model one number, the size of the move.",
             sections=["Why diffusions fail at short expiries", "Jump-diffusions: Merton, Kou, Bates", "Pure-jump Lévy models", "What cannot be hedged", "When jumps matter"],
             defines=["Merton jump-diffusion model", "Kou model", "Bates model", "variance gamma model"],
             uses=["Poisson process, compound Poisson process, Lévy process, Lévy--Khintchine formula, subordinator (Book 4 ch. 6)", "characteristic function (Book 4 ch. 1)", "complete market (ch. 1)", "event variance (ch. 8)", "Heston model (ch. 10)"],
             tutorial="Price under Merton and variance gamma through their characteristic functions, fit both to a short-dated smile, and compare their short-expiry skew with Heston's.",
             build="`firm.jumps`: characteristic functions of Merton, Kou, Bates and variance gamma behind one interface consumed by the transform engine of chapter 24.",
             problem="The binary event — named result: the jump size and probability implied by a one-week smile around a scheduled announcement, and the error of the delta hedge across it.",
             facts=["Merton 1976 JFE", "Kou 2002 Management Science", "Bates 1996 RFS", "Madan, Carr, Chang 1998 variance gamma", "Carr, Geman, Madan, Yor 2002 CGMY", "Carr-Wu 2003 JF 'What type of process underlies options?'"]),
        dict(slug="14-variance-swaps-and-volatility-derivatives", title="Variance Swaps and Volatility Derivatives",
             hook="A contract with no strike in price, only one in volatility squared; its hedge is a strip of every out-of-the-money option on the index, each weighted by one over its strike squared.",
             sections=["Variance swaps and their replication", "The log contract and the volatility-index formula", "Volatility swaps and convexity", "Futures and options on the volatility index", "Skew, jumps and the limits of replication"],
             defines=["variance swap", "variance notional", "vega notional", "log contract", "volatility swap", "corridor variance swap", "gamma swap", "variance risk premium", "VIX option"],
             uses=["volatility index, VIX future, realised volatility, variance (Book 1 ch. 25)", "convexity adjustment (Book 2 ch. 8)", "Itô's formula (Book 4 ch. 3)", "Black model (ch. 3)", "forward variance (ch. 12)", "Heston model (ch. 10)"],
             tutorial="Replicate a variance swap from a strip of options on a synthetic surface, compute the fair strike and the index-style number, and simulate the hedge's P&L on paths with and without jumps.",
             build="`firm.varswap`: variance- and volatility-swap pricer (strip replication, discrete-monitoring and jump corrections) and a variance-swap mark-to-market.",
             problem="Vol or variance — named result: the convexity adjustment between the one-year variance-swap and volatility-swap strikes on the chapter's surface under Heston dynamics.",
             facts=["Cboe VIX methodology white paper (current version)", "VIX futures launch 2004, VIX options 2006 (Cboe)", "Demeterfi, Derman, Kamal, Zou 1999 'More than you ever wanted to know about volatility swaps'", "Carr-Wu 2009 RFS variance risk premia", "2008 single-stock variance market (Risk / papers)", "Carr-Lee 2009 volatility derivatives survey"]),
    ]),
    ("part.dv.exotics", [
        dict(slug="15-barriers-and-digitals", title="Barriers and Digitals",
             hook="A digital pays 10 million if the index closes above 5,000; with the index at 4,999.9 and one minute to the close, its delta is larger than the desk's whole index position.",
             sections=["Digitals and their hedge", "Barriers by reflection", "Static hedging", "Discrete monitoring and the barrier shift", "Gap risk at the barrier"],
             defines=["digital option", "one-touch option", "no-touch option", "double-barrier option", "barrier rebate", "call-spread overhedge", "static hedging", "barrier shift", "gap risk"],
             uses=["barrier option, knock-out option, knock-in option (Book 2 ch. 19)", "reflection principle (Book 4 ch. 2)", "Black--Scholes formula (ch. 3)", "vanna, volga (ch. 4)", "local volatility (ch. 9)"],
             tutorial="Price a down-and-out call in closed form, with discrete monitoring by Monte Carlo and with the barrier shift; hedge a digital with a call spread; build a static hedge of a barrier from vanillas.",
             build="`firm.barrier`: barrier and digital pricer (closed forms with rebates, the discrete-monitoring shift, double barriers by series) and a static-hedge builder.",
             problem="The digital at expiry — named result: the call-spread width that caps the hedger's loss at 50,000 on a 10-million digital, and the overhedge cost it charges the client.",
             facts=["Reiner-Rubinstein 1991 barrier closed forms", "Broadie, Glasserman, Kou 1997 continuity correction (0.5826)", "Derman, Ergener, Kani 1995 static hedging", "Carr, Ellis, Gupta 1998 static hedging", "SNB removal of the EURCHF floor, 15 January 2015 (gap)"]),
        dict(slug="16-asians-lookbacks-cliquets-and-forward-starts", title="Asians, Lookbacks, Cliquets and Forward-Starts",
             hook="A corporate treasurer is quoted an option on the monthly average price, 30% cheaper than the vanilla; nobody on the call can say where the 30% went.",
             sections=["Averaging: Asians", "Extremes: lookbacks", "Forward-starts and the forward smile", "Cliquets", "Which model for which payoff"],
             defines=["Asian option", "lookback option", "forward-start option", "cliquet", "reverse cliquet"],
             uses=["average-price option (Book 3 ch. 12)", "forward smile, local volatility (ch. 9)", "stochastic volatility model (ch. 10)", "Bergomi model (ch. 12)", "control variate, Monte Carlo (Book 4 ch. 26)"],
             tutorial="Price an arithmetic Asian by Monte Carlo with the geometric Asian as control variate; then price a forward-start and a cliquet under Black-Scholes, local volatility and Heston calibrated to the same smile, and compare.",
             build="`firm.pathdep`: path-dependent payoff library (Asian, lookback, forward-start, cliquet with local and global caps and floors) on a common path interface.",
             problem="The cliquet that fits every vanilla — named result: the gap between the local-volatility and the Heston price of a one-year monthly cliquet when both fit the same surface.",
             facts=["Kemna-Vorst 1990 geometric control variate", "Goldman, Sosin, Gatto 1979 lookbacks", "Rubinstein 1991 forward-start options", "Bergomi on cliquets and forward skew (Risk 2004/2005)", "reverse-cliquet losses of the early 2000s (only with a source)"]),
        dict(slug="17-multi-asset-options", title="Multi-Asset Options",
             hook="A note pays its coupon only while all three of its shares stay above 70% of their start; the client sees three familiar names, the dealer a correlation position that no listed market quotes.",
             sections=["Correlation and baskets", "Worst-of and best-of", "Implied correlation, dispersion and correlation skew", "Local correlation", "Quanto and composite options"],
             defines=["basket option", "worst-of option", "best-of option", "implied correlation", "dispersion trade", "correlation swap", "correlation skew", "local correlation", "quanto option", "quanto adjustment", "composite option"],
             uses=["volatility skew (Book 1 ch. 25)", "base correlation (Book 2 ch. 24)", "Black--Scholes model (ch. 3)", "local volatility, Markovian projection (ch. 9)", "Cholesky factorisation (Book 4 ch. 25)", "Monte Carlo (Book 4 ch. 26)", "Girsanov's theorem (Book 4 ch. 5)", "cross-gamma (Book 6 ch. 3)", "copula (Book 4 ch. 15)", "Gaussian copula (Book 6 ch. 15)", "spread option (Book 6 ch. 16)"],
             tutorial="Price a basket and a worst-of by Monte Carlo against moment matching, compute the implied correlation of a synthetic index and its members at three strikes, and measure the quanto adjustment on an index forward paid in another currency.",
             build="`firm.multiasset`: correlated multi-asset path generator (Cholesky, per-asset local volatility, quanto drift) with basket, worst-of and quanto payoffs.",
             problem="The index and its members — named result: the implied correlation of a synthetic 20-stock index at three strikes, and the P&L of a dispersion trade when realised correlation comes in 15 points below implied.",
             facts=["Cboe implied correlation index methodology", "Driessen, Maenhout, Vilkov 2009 JF 'The price of correlation risk'", "CME Nikkei 225 USD futures (quanto) contract spec", "Reghai 2006 / Langnau 2010 local correlation", "Bossu 2005 correlation swaps"]),
        dict(slug="18-autocallables", title="Autocallables",
             hook="In the first months of 2024 Korean retail investors took large losses on equity-linked securities tied to the Hang Seng China Enterprises Index, sold three years earlier with a knock-in level the index had then seemed unable to reach.",
             sections=["Payoff anatomy", "Pricing: which model", "The risk profile: vega, skew, dividends, correlation", "Issuer hedging flows", "Documented market impact"],
             defines=["autocallable", "autocall trigger", "coupon barrier", "memory coupon", "protection barrier", "snowball"],
             uses=["digital option, barrier shift, gap risk (ch. 15)", "worst-of option, correlation skew (ch. 17)", "dividend risk (ch. 5)", "local volatility (ch. 9)", "vega, vanna, volga (ch. 4)", "knock-in option (Book 2 ch. 19)", "dealer gamma (Book 1 ch. 26)"],
             tutorial="Price a three-year single-underlying Phoenix autocallable by Monte Carlo under local volatility; compute its vega by expiry bucket and its dividend and skew sensitivities; simulate the issuer's delta-hedge flow as spot falls through the protection barrier.",
             build="`firm.autocall`: autocallable term-sheet object and Monte Carlo pricer (single and worst-of, memory, knock-in put) with bucketed Greeks and a hedge-flow simulator.",
             problem="The knock-in cliff — named result: the quantity of underlying the issuer sells per 1% fall when spot is 1% above the protection barrier one month before maturity, per 100 million of notes.",
             facts=["Korean HSCEI-linked ELS 2015-16 episode (Bank of Korea / FSS / BIS)", "Korean HSCEI ELS losses 2024 (FSS press releases, amounts)", "Chinese snowball products and the 2024 knock-ins (regulator or quality press)", "BIS Quarterly Review on autocallable hedging flows", "Japanese Nikkei-linked Uridashi notes and hedging flows (BoJ or papers)", "structured-products market size (industry association data)", "Natixis 2018 Asian equity-derivatives loss (company release)"]),
        dict(slug="19-the-structured-products-business", title="The Structured-Products Business",
             hook="A private-bank client buys a two-year capital-protected note on an index with 70% participation; the issuer's funding spread, not the option, decides whether 70 was possible.",
             sections=["Products and wrappers", "Anatomy of a note: a bond plus options", "Distribution, margins and regulation", "Issuer funding and the product lifecycle", "Systematic-strategy indices and options on them"],
             defines=["structured product", "structured note", "capital-protected note", "reverse convertible", "participation rate", "structuring margin", "systematic strategy index", "volatility-target index", "decrement index"],
             uses=["funding spread (Book 1 ch. 17)", "credit spread (Book 2 ch. 21)", "zero-coupon rate (Book 2 ch. 3)", "exchange-traded fund (Book 1 ch. 14)", "total return swap (Book 1 ch. 6)", "autocallable (ch. 18)", "dividend risk (ch. 5)", "local volatility (ch. 9)"],
             tutorial="Decompose a capital-protected note into a zero-coupon bond and a call spread, solve for the maximum participation given an issuer spread and a margin, and price a call on a 10% volatility-target index against a call on the raw index.",
             build="`firm.termsheet`: term-sheet decomposer (bond and option legs), margin and participation solver, and a volatility-target and decrement index calculator.",
             problem="Seventy percent participation — named result: the issuer funding spread at which a two-year 100%-protected note can offer 70% participation after a 1.5% margin.",
             facts=["EU PRIIPs regulation 1286/2014 (key information document)", "FINRA regulatory notices on structured products", "structured-products volumes (industry associations, e.g. SSPA, EUSIPA)", "decrement index methodology (index provider)", "risk-control index methodology (index provider)"]),
        dict(slug="20-fx-derivatives", title="FX Derivatives",
             hook="In August 2015 the renminbi's central fixing moved by nearly 2% in one day, and companies across Asia holding target-redemption forwards on the dollar-renminbi rate found the sign of their exposure had turned.",
             sections=["Pricing conventions revisited", "The vanna-volga method", "Barriers and target-redemption forwards", "Stochastic-local volatility", "An FX exotic book"],
             defines=["Garman--Kohlhagen model", "vanna--volga method", "target redemption forward", "accumulator", "stochastic-local volatility model", "leverage function"],
             uses=["spot delta, forward delta, premium-adjusted delta, delta-neutral straddle, risk reversal, butterfly, barrier option (Book 2 ch. 19)", "currency pair, base currency, quote currency (Book 2 ch. 14)", "one-touch option, barrier shift (ch. 15)", "local volatility, Markovian projection (ch. 9)", "Heston model (ch. 10)", "vanna, volga (ch. 4)"],
             tutorial="Price a one-touch and a double-no-touch by vanna-volga from ATM, RR and BF quotes (building on Book 2's `firm.fxsmile`), then a target-redemption forward by Monte Carlo under local volatility and under SLV with a calibrated leverage function.",
             build="`firm.fxvol`: vanna-volga pricer, target-redemption-forward Monte Carlo, SLV leverage function calibrated by the particle method.",
             problem="The TARF — named result: the expected number of fixings before redemption and the client's expected loss per million when spot moves 10% against it in the first quarter.",
             facts=["PBoC 11 August 2015 fixing change (PBoC statement)", "CNH TRF losses 2015-16 (HKMA / SFC / quality press)", "2008 accumulator losses (HK regulators)", "Castagna-Mercurio 2007 Risk, vanna-volga", "Guyon, Henry-Labordère 2011 particle method", "Garman-Kohlhagen 1983 JIMF", "FX options turnover share (reuse Book 2 ledger)"]),
        dict(slug="21-convertibles-and-the-credit-equity-link", title="Convertibles and the Credit--Equity Link",
             hook="With the share at 30 and the conversion price at 40 a convertible trades like a bond; with the share at 60, like the share; a convertible desk lives in the region between, hedged with the share and a credit default swap.",
             sections=["The instrument", "Bond floor, conversion value and the convex region", "Equity-to-credit models", "What a convertible desk hedges", "Convertible arbitrage and its crises"],
             defines=["convertible bond", "conversion ratio", "conversion price", "conversion value", "conversion premium", "bond floor", "soft call", "equity-to-credit model", "convertible arbitrage"],
             uses=["credit spread, recovery rate (Book 2 ch. 21)", "hazard rate, credit default swap (Book 2 ch. 23)", "contingent convertible bond (Book 2 ch. 26)", "callable bond (Book 2 ch. 13)", "exercise boundary (ch. 6)", "Black--Scholes equation (ch. 3)", "finite differences (Book 4 ch. 27)", "jump-to-default risk (Book 6 ch. 13)", "structural model (Book 6 ch. 14)"],
             tutorial="Price a convertible on a one-dimensional grid with a hazard rate that rises as the share falls, compare it with the constant-hazard model, and compute the delta, the credit sensitivity and the hedge a convertible-arbitrage book holds.",
             build="`firm.convertible`: convertible-bond pricer (Crank-Nicolson grid, issuer calls with soft-call trigger, investor puts, equity-to-credit hazard) with delta, gamma and credit sensitivities.",
             problem="The spring of 2005 — named result: the loss of a delta-hedged convertible-arbitrage position when the issuer's credit spread widens by 300 bp while its share falls 20%.",
             facts=["Tsiveriotis-Fernandes 1998 J. Fixed Income", "Ayache, Forsyth, Vetzal 2003", "Andersen-Buffum 2003 equity-to-credit", "2005 convertible-arbitrage drawdown (Mitchell, Pedersen, Pulvino 2007)", "2008 convertible-arbitrage crisis (Mitchell-Pulvino 2012 JFE)", "global convertible issuance (dated)"]),
    ]),
    ("part.dv.numerical", [
        dict(slug="22-trees-and-finite-difference-pricers-in-practice", title="Trees and Finite-Difference Pricers in Practice",
             hook="A pricer returns 5.4817 for an American put with 200 time steps and 5.4839 with 201; the trader asks which to trust, and the answer is neither.",
             sections=["The pricing equation on a grid", "Discrete dividends and jump conditions", "Barriers and grid alignment", "American exercise", "Accuracy against speed"],
             defines=["trinomial tree", "jump condition", "payoff smoothing", "Brennan--Schwartz algorithm"],
             uses=["theta scheme, Crank--Nicolson scheme, Rannacher start-up, stability (Book 4 ch. 27)", "Richardson extrapolation (Book 4 ch. 25 or 27)", "binomial model, Cox--Ross--Rubinstein tree (ch. 2)", "escrowed dividend model (ch. 5)", "exercise boundary (ch. 6)", "barrier option (Book 2 ch. 19)"],
             tutorial="Build a Crank-Nicolson pricer on a stretched log-spot grid with Rannacher start-up, discrete-dividend jump conditions and American exercise by Brennan-Schwartz; plot error against run time for the tree and the grid.",
             build="`firm.fdpricer`: one-dimensional finite-difference pricing engine (Python, C++20, Rust): non-uniform grids, Crank-Nicolson with Rannacher start-up, dividends, barriers, American exercise.",
             problem="Neither 200 nor 201 — named result: the grid size and run time at which the American put is within 0.1 cent, for the tree and for the grid, and the speed-up of the grid.",
             facts=["Brennan-Schwartz 1977 JF", "Rannacher 1984", "Pooley, Vetzal, Forsyth 2003 convergence remedies", "Tavella-Randall 2000 book"]),
        dict(slug="23-monte-carlo-pricers-in-practice", title="Monte Carlo Pricers in Practice",
             hook="A Bermudan option on a basket of five shares has no grid that fits in memory; a Monte Carlo engine prices it in a second and gets the exercise decision wrong by design, which is why its answer is a lower bound.",
             sections=["Simulating the models", "Early exercise by regression", "Greeks: pathwise, likelihood ratio, adjoint", "Bridges and quasi-random numbers", "Engineering a Monte Carlo pricer"],
             defines=["Longstaff--Schwartz method", "dual upper bound", "pathwise Greek", "likelihood-ratio Greek", "quadratic-exponential scheme"],
             uses=["Monte Carlo, variance reduction, control variate, antithetic variates, low-discrepancy sequence, Euler scheme, multilevel Monte Carlo (Book 4 ch. 26)", "Brownian bridge (Book 4 ch. 2 or 26)", "algorithmic differentiation, adjoint mode (Book 4 ch. 28)", "Bermudan exercise (ch. 6)", "Heston model (ch. 10)", "digital option (ch. 15)", "worst-of option (ch. 17)"],
             tutorial="Price a Bermudan put by Longstaff-Schwartz and bound it above by the Andersen-Broadie dual; compute the delta and vega of a digital pathwise, by likelihood ratio and by adjoint differentiation, and compare their variances.",
             build="`firm.mcpricer`: Monte Carlo engine (path generators for Black-Scholes, local volatility and Heston-QE; payoffs from `pathdep` and `autocall`; Longstaff-Schwartz; pathwise and likelihood-ratio Greeks; common random numbers across bumps).",
             problem="The Bermudan bounds — named result: the gap between the Longstaff-Schwartz lower bound and the dual upper bound for a three-asset Bermudan max-call, and its sensitivity to the regression basis.",
             facts=["Longstaff-Schwartz 2001 RFS", "Andersen-Broadie 2004 Management Science", "Andersen 2008 J. Computational Finance, QE scheme", "Broadie-Glasserman 1996 Management Science, Greeks", "Giles-Glasserman 2006 Risk 'Smoking adjoints'", "Glasserman 2003 book"]),
        dict(slug="24-fourier-pricing-and-calibration-engineering", title="Fourier Pricing and Calibration Engineering",
             hook="Every morning at seven a job fits a Heston model to 600 quotes; one Tuesday the volatility of volatility jumped from 0.6 to 1.4 with the fit error unchanged, and every exotic on the book moved.",
             sections=["Pricing by transform", "Calibration as a pipeline", "Objective, weights and constraints", "Stability from day to day", "Testing a calibration"],
             defines=["Carr--Madan formula", "Lewis formula", "vega weighting", "recalibration P\\&L"],
             uses=["fast Fourier transform, COS method (Book 4 ch. 28)", "characteristic function (Book 4 ch. 1)", "Levenberg--Marquardt, regularisation (Book 4 ch. 16, 24)", "calibration (Book 4 ch. 24)", "Heston model (ch. 10)", "Bates model, variance gamma model (ch. 13)"],
             tutorial="Price a full Heston strike grid by the Carr-Madan FFT and by the COS method, then run a daily calibration over 60 synthetic days with and without a penalty on parameter changes and plot the parameter paths.",
             build="`firm.calib`: calibration pipeline (quote filter, weights, bounded Levenberg-Marquardt with regularisation, warm start, diagnostics, parameter-jump alarms) for any model with a characteristic function.",
             problem="The Tuesday jump — named result: the regularisation weight at which the day-to-day moves of the volatility of volatility fall below 0.1 while the fit error rises by less than 0.1 volatility point.",
             facts=["Carr-Madan 1999 J. Computational Finance", "Lewis 2001 (Fourier pricing)", "Fang-Oosterlee 2008 COS method", "Cont-Ben Hamida 2005 ill-posed calibration", "Mikhailov-Nögel 2003 Heston calibration"]),
    ]),
    ("part.dv.desk", [
        dict(slug="25-trading-volatility", title="Trading Volatility",
             hook="A trader buys one-month straddles at 18 volatility because the share has realised 25 for two months; four weeks later it has realised 24 and the position has lost money: the big moves came on days when the gamma was small.",
             sections=["Gamma scalping", "Volatility carry and the roll-down", "Skew and term trades", "Attributing a volatility book's P&L", "The variance risk premium in practice"],
             defines=["gamma scalping", "implied--realised spread", "volatility roll-down"],
             uses=["P\\&L attribution, carry (Book 1 ch. 7)", "risk reversal (Book 2 ch. 19)", "straddle, hedging P\\&L, vega, theta, vanna, volga (ch. 4)", "sticky strike, sticky delta (ch. 7)", "variance risk premium (ch. 14)", "stochastic volatility model (ch. 10)", "delta--gamma approximation (Book 6 ch. 21)"],
             tutorial="Run a gamma-scalping book on simulated paths with stochastic volatility and attribute its daily P&L into delta, gamma, theta, vega, vanna, volga and unexplained; show how the attribution changes between sticky-strike and sticky-delta marking.",
             build="`firm.volpnl`: volatility-book P&L attribution (Greek-based explain against full revaluation, sticky-strike and sticky-delta marking, unexplained P&L).",
             problem="The wrong days — named result: the gamma P&L of a long straddle when the same realised volatility comes in moves concentrated on low-gamma days, against uniformly spread moves.",
             facts=["Bakshi-Kapadia 2003 RFS delta-hedged gains", "Carr-Wu 2009 variance risk premium size", "Cboe PUT and BXM index methodology", "5 February 2018 (reuse Book 1 ledger)", "Israelov-Nielsen 2015 on covered calls"]),
        dict(slug="26-options-market-making-in-practice", title="Options Market Making in Practice",
             hook="At 09:30:00 the opening auction prints; by 09:30:01 the market maker has refitted its surface for 3,000 series twice and re-sent every quote.",
             sections=["Fitting a live surface", "Theoretical value and quote widths", "Delta-hedging policies", "Pin risk, dividends and early exercise", "Bucketed limits"],
             defines=["theoretical value", "hedging band", "dividend play", "vega bucket"],
             uses=["options market maker, quoting obligation (Book 1 ch. 24)", "pin risk, assignment (Book 1 ch. 23)", "adverse selection, bid--ask spread (Book 1 ch. 1)", "mark-out (Book 2 ch. 15)", "edge (Book 2 ch. 29)", "width (Book 2 ch. 30)", "SVI parametrisation (ch. 8)", "sticky strike (ch. 7)", "early-exercise premium (ch. 6)", "gamma, vega"],
             tutorial="Run a toy options market maker on a simulated underlying and order flow: refit an SVI surface every second, quote widths set by vega and mark-outs, hedge inside a band, and report P&L by source and vega by bucket.",
             build="`firm.optmm`: options quoting engine (theoretical value from a live surface, width model, band delta hedger, bucketed vega and gamma limits).",
             problem="The dividend-play morning — named result: the expected profit of a dividend play on one call series when a given share of holders fails to exercise, net of fees.",
             facts=["Pool, Stoll, Whaley 2008 dividend-play profits", "exchange fee caps for dividend strategies (fee schedules, dated)", "Whalley-Wilmott 1997 hedging bands", "OCC exercise statistics", "market-maker obligations (reuse Book 1 ledger)"]),
        dict(slug="27-managing-an-exotic-book", title="Managing an Exotic Book",
             hook="A desk books a new structure with a day-one profit of 2 million; the valuation-control group recognises 400,000 and holds the rest until the model's key input can be observed.",
             sections=["What an exotic book owns", "Reserves and parameter bid-offer", "Model risk on the desk", "Stress and concentration", "Day-one P&L and its release"],
             defines=["valuation reserve", "bid--offer reserve", "model reserve", "parameter bid--offer", "day-one P\\&L"],
             uses=["P\\&L attribution (Book 1 ch. 7)", "model risk, model validation (Book 6 ch. 26)", "independent price verification, prudent valuation (Book 6 ch. 27)", "autocallable (ch. 18)", "correlation skew (ch. 17)", "recalibration P\\&L (ch. 24)"],
             tutorial="Compute bid-offer, model and parameter reserves for a small exotic book (autocallables, barriers, cliquets) by repricing under alternative models and parameter bounds, then run a stress grid.",
             build="`firm.reserves`: reserve calculator (bid-offer by Greek bucket, model reserve from a model set, parameter-uncertainty reserve, day-one P&L release schedule).",
             problem="The deferred profit — named result: the day-one P&L recognised at inception on a three-year worst-of autocallable, and the amount released after one year as the correlation input becomes observable.",
             facts=["IFRS 13 fair-value hierarchy; IFRS 9 B5.1.2A day-one gains", "US GAAP ASC 820", "EBA prudent-valuation RTS (model-risk and concentration adjustments)", "Fed/OCC SR 11-7 model-risk guidance", "documented exotic-book losses from regulator or company records (e.g. Natixis 2018)"]),
        dict(slug="28-build-a-pricing-library", title="Build: A Pricing Library",
             hook="A risk manager asks for the book's vega to the one-year 90% strike; the answer needs every pricer the firm owns to accept the same bumped surface, and half of them cannot.",
             sections=["Instruments, models and engines", "Market data as an immutable snapshot", "Greeks, bumps and scenarios", "Testing a pricer", "Build: the library"],
             defines=["pricing engine", "market-data snapshot", "reference pricer"],
             uses=["bump-and-reprice (ch. 4)", "P\\&L attribution (Book 1 ch. 7)", "the curve of Book 2 ch. 9 (`firm.curve`)", "stress test, historical scenario, hypothetical scenario (Book 6 ch. 22)", "risk engine (Book 6 ch. 29)", "every component of chapters 1-27"],
             tutorial="Wire the book's components into one library: price a small book (vanilla, American, barrier, variance swap, autocallable) through one call, produce bucketed vega by bump-and-reprice with common random numbers, and run a ten-scenario grid.",
             build="`firm.pricing`: the pricing library (Instrument, MarketData, Model, Engine, registry, price(), greeks(), scenario hooks) in Python; core types with the Black-Scholes and finite-difference engines also in C++20 and Rust; Book 6 ch. 29's risk engine runs on it.",
             problem="The vega nobody could compute — named result: the book's bucketed vega at the one-year 90% strike, and the Monte Carlo noise in it with and without common random numbers.",
             facts=["QuantLib architecture (Instrument, PricingEngine, Handle; quantlib.org documentation)", "Open Source Risk Engine design (ORE documentation)", "trade representation standards (FpML, ISDA CDM)"]),
    ]),
]
