"""Book 7 (Research Craft: Predictors, Backtests, Measurement, Portfolios)
chapter briefs: data for tools/make_briefs.py --book 7.

`uses` lists terms defined elsewhere that the chapter relies on: they are NOT
redefined (a term is defined once in the series); the text points to the
defining chapter in prose. Owners in parentheses: (B1.7) = One Quant Book 1,
chapter 7 (checked against the harvested \\index{} entries of Books 1-6 on
2026-09-24); (ch3) = an earlier chapter of this book.

Ownership: Books 1-6 keep their terms. Book 4 owns the statistics (Sharpe
ratio, deflated Sharpe ratio, multiple testing, cross-validation, shrinkage,
factor model, the QP solver); Book 2 owns mark-out, drawdown and the Kelly
criterion; Book 1 owns alpha, benchmark, tracking error, information ratio,
symbology, adjustment factor. This book owns the research-method terms:
predictor and its measurement, point-in-time data and the biases, the four
backtest fidelity levels, performance and execution measurement, risk models
as research tools, portfolio construction, capacity and crowding. Books 8 and
9 own the named strategies: this book's predictor cards (short-term reversal,
12-1 momentum, ...) are labelled pred: but do NOT define strategy names as
terms. Book 10 (microstructure and execution, written later) will use the
execution terms first needed here (VWAP, market impact, implementation
shortfall, square-root impact law, percentage of volume).

Running project (code/firm/, all new and unique):
  researchlog (ch1)  tape, bars (ch2)  pit (ch3)  secmaster (ch4)  synthmkt (ch5)
  predictor (ch6)  features (ch7)  lobfeat (ch8, C++20 + Rust twin)  tradeflow (ch9)
  leadlag (ch10)  fundpit (ch11)  vendoreval (ch12)  decay (ch13)  combine (ch14)
  forecast (ch15)  vecbt (ch16)  evbt (ch17)  lobreplay (ch18, C++20 + Rust twin)
  simlive (ch19)  overfit (ch20)  abtest (ch21)  perf (ch22)  markout (ch23)
  riskmodel (ch24)  portcons (ch25)  allocation (ch26)  tcost (ch27)
  capacity (ch28)  workflow (ch29)
Books 8 and 9 run on synthmkt, predictor, vecbt/evbt/lobreplay, perf,
riskmodel, portcons and tcost (code/firm/INTERFACES.md section 4).
"""
SLUG = "research"
PFX = "rs"
HEAD = "One Quant Book 7 — Research Craft: Predictors, Backtests, Measurement, Portfolios"

PARTS = [
    ("part.rs.process", [
        dict(slug="01-the-research-process", title="The Research Process",
             hook="A researcher shows a backtest with a Sharpe ratio of 2.4 on Friday; on Monday the head of research asks how many variants were tried, and which came first, the hypothesis or the chart. Nobody wrote it down.",
             sections=["Hypothesis first", "The research log and the trial count", "What counts as evidence", "From idea to production", "Research as a portfolio of bets"],
             defines=["research hypothesis", "economic rationale", "research log", "trial count", "pre-registration", "holdout set", "stage gate", "kill criterion", "research review"],
             uses=["alpha (B1.1)", "Sharpe ratio (B4.11)", "multiple testing (B4.12)", "data snooping (B4.12)", "garden of forking paths (B4.12)", "deflated Sharpe ratio (B4.12)", "p-value (B4.12)", "power of a test (B4.12)"],
             tutorial="Create a research log with firm.researchlog, log a 50-variant search of a planted-noise signal, and watch the logged trial count move the deflated Sharpe ratio of the winner; then replay the same search unlogged.",
             build="`firm.researchlog`: append-only, hash-chained experiment registry (hypothesis, family, code hash, data snapshot id, parameters, metrics, timestamps) with trial counting per hypothesis family; Python.",
             problem="The Friday backtest — named result: the probability that a researcher with no edge who tries twenty variants a week shows a Sharpe ratio of at least 2 within a year, and the deflated Sharpe ratio of that backtest once the log's trial count is used.",
             facts=["Bailey, Borwein, Lopez de Prado, Zhu 2014, Pseudo-mathematics and financial charlatanism (Notices AMS)", "Nosek et al. 2018, The preregistration revolution (PNAS)", "Harvey, Liu, Zhu 2016 (RFS) t > 3 hurdle", "Arnott, Harvey, Markowitz 2019, A backtesting protocol in the era of machine learning (JFDS)", "Lopez de Prado 2018, The 10 reasons most machine learning funds fail (JPM)"]),
        dict(slug="02-market-data-for-research", title="Market Data for Research",
             hook="Two researchers measure the same stock's five-minute volatility on the same day and disagree by thirty per cent: one used trade prices, the other midquotes.",
             sections=["What a message feed contains", "Sampling clocks: time, tick, volume and value bars", "What each representation destroys", "Continuous futures series", "Volumes, storage and formats"],
             defines=["bar", "time bar", "tick bar", "volume bar", "dollar bar", "imbalance bar", "volume-weighted average price", "midquote series", "continuous futures series", "back-adjustment", "ratio adjustment"],
             uses=["level 1 (B1.28)", "level 2 (B1.28)", "level 3 (B1.28)", "market-by-order (B1.19)", "market-by-price (B1.19)", "trade condition (B1.28)", "exchange timestamp (B1.28)", "receive timestamp (B1.28)", "sequence number (B1.28)", "roll (B1.21)", "front month (B1.18)", "bid--ask bounce (B4.21)", "microstructure noise (B4.21)", "realised variance (B4.18)", "Hawkes process (B4.7)"],
             tutorial="Generate a day of message-level data with firm.tape (a latent efficient price, a queue-reactive book, Hawkes-clustered trades and a news burst); build time, tick, volume and dollar bars; compare the kurtosis and autocorrelation of bar returns and the realised variance from trades and from mids.",
             build="`firm.tape`: the book's synthetic message-level market for one or two instruments (ITCH-like add/cancel/execute events, known trade signs, informed and noise flow, deterministic seeds) and `firm.bars` (time, tick, volume, dollar and imbalance bars, VWAP, midquote sampling, continuous futures with back- and ratio-adjustment); Python.",
             problem="Which clock? — named result: the kurtosis of five-minute time-bar returns against dollar-bar returns on a simulated day with a news burst, and the trade-versus-mid volatility gap.",
             facts=["Ane and Geman 2000, order flow, transaction clock and normality (JF)", "Clark 1973 subordinated process (Econometrica)", "Easley, Lopez de Prado, O'Hara 2012, The volume clock (JPM)", "Nasdaq TotalView-ITCH message counts per day (dated)", "roll methods for continuous futures (data-vendor documentation)"]),
        dict(slug="03-point-in-time-data-and-the-biases", title="Point-in-Time Data and the Biases",
             hook="The first estimate of US nonfarm payrolls for a month and the figure in today's database for the same month differ by more than a hundred thousand jobs; a macro signal backtested on today's figures trades on numbers nobody had.",
             sections=["Look-ahead bias and timestamp semantics", "Survivorship bias", "Restatements, revisions and vintages", "As-of joins and bitemporal storage", "A catalogue of the other biases"],
             defines=["look-ahead bias", "survivorship bias", "point-in-time data", "bitemporal data", "valid time", "knowledge time", "as-of join", "restatement", "data vintage", "backfill bias"],
             uses=["exchange timestamp (B1.28)", "receive timestamp (B1.28)", "consensus forecast (B2.31)", "data snooping (B4.12)", "research log (ch1)"],
             tutorial="Download the real-time vintages of US payrolls (ALFRED, public), build a bitemporal table, run an as-of join, and compare a payroll-surprise signal computed with first releases against one computed with the latest vintage.",
             build="`firm.pit`: bitemporal store (valid time, knowledge time) with as-of queries, as-of joins with tolerance, and a leakage guard that fails when a feature reads knowledge after its decision time; Python.",
             problem="The survivors' premium — named result: the annual return inflation of an equal-weighted universe that drops delisted names, in a synthetic market with a known delisting rate and delisting return, against the closed-form approximation.",
             facts=["ALFRED real-time vintages of PAYEMS (St. Louis Fed)", "Croushore and Stark 2001, a real-time data set for macroeconomists (J. Econometrics)", "Shumway 1997, the delisting bias in CRSP data (JF)", "Brown, Goetzmann, Ibbotson, Ross 1992, survivorship bias in performance studies (RFS)", "Elton, Gruber, Blake 1996 survivorship bias and mutual fund performance (RFS)", "Banz and Breen 1986, sample-dependent results using accounting and market data (JF)", "BLS revision practice for payrolls (benchmark revisions)"]),
        dict(slug="04-universe-symbology-and-corporate-actions", title="Universe, Symbology and Corporate Actions",
             hook="On 9 June 2022 a large technology company's shares began trading under a new ticker; a backtest that joins prices on tickers silently splices two histories, or loses one.",
             sections=["A tradable universe through time", "Identifiers that change", "The security master", "Adjusting without leaking", "Delistings and the delisting return"],
             defines=["tradable universe", "universe membership", "liquidity filter", "security master", "permanent identifier", "identifier mapping", "ticker change", "delisting return"],
             uses=["symbology (B1.28)", "reference data (B1.28)", "adjustment factor (B1.8)", "stock split (B1.8)", "dividend (B1.8)", "spin-off (B1.8)", "rights issue (B1.8)", "free float (B1.8)", "market capitalisation (B1.8)", "index reconstitution (B1.15)", "buffer rule (B1.15)", "point-in-time data (ch3)", "survivorship bias (ch3)", "as-of join (ch3)", "look-ahead bias (ch3)"],
             tutorial="Build a security master from a synthetic event history (ticker changes and reuse, mergers, spin-offs, delistings), construct a liquidity universe with buffers through time, and show the returns a ticker join mis-attributes.",
             build="`firm.secmaster`: permanent identifiers with dated identifier mappings, as-of symbol resolution, universe construction with entry and exit buffers, point-in-time adjustment factors (imports firm.corpactions and firm.pit); Python.",
             problem="The ticker that changed hands — named result: the error in a ten-year momentum backtest caused by joining on tickers instead of permanent identifiers in a synthetic universe with ticker reuse, and the share of names affected.",
             facts=["ticker change FB to META on 9 June 2022 (company press release)", "ISIN standard ISO 6166", "FIGI standard (OMG / X9.145) and OpenFIGI", "CUSIP (CUSIP Global Services)", "CRSP permanent numbers PERMNO/PERMCO (CRSP documentation)", "Shumway 1997 delisting returns (JF)"]),
        dict(slug="05-stylised-facts-of-returns", title="Stylised Facts of Returns",
             hook="On 19 October 1987 the Dow Jones Industrial Average fell 22.6 per cent in one session: under a normal law fitted to the preceding years, a move of more than twenty standard deviations.",
             sections=["Heavy tails and aggregational Gaussianity", "Volatility clustering and long memory in size", "The leverage effect and gain--loss asymmetry", "Intraday seasonality", "Cross-sectional structure"],
             defines=["stylised fact", "aggregational Gaussianity", "gain--loss asymmetry", "Taylor effect", "intraday seasonality", "intraday volume profile", "exceedance correlation", "correlation asymmetry"],
             uses=["heavy-tailed distribution (B4.15)", "tail index (B4.15)", "Hill estimator (B4.15)", "volatility clustering (B4.18)", "leverage effect (B4.18)", "GARCH model (B4.18)", "long memory (B4.17)", "autocorrelation function (B4.17)", "principal component analysis (B4.22)", "Marchenko--Pastur law (B4.22)", "realised volatility (B1.25)", "market-on-close order (B1.13)"],
             tutorial="Compute the stylised facts from summary statistics of a century of daily US market factor returns (derived from the Fama--French data library) and from firm.tape and firm.synthmkt, and score the simulators against the data.",
             build="`firm.synthmkt`: the book's synthetic daily equity universe (factor structure with GARCH-t factors and leverage, heterogeneous specific volatility, earnings jumps, listings and delistings, corporate actions, point-in-time fundamentals with restatements, planted predictors with known information coefficients); Python.",
             problem="Is the simulator realistic? — named result: the stylised-fact scorecard of firm.synthmkt against the real daily data (tail index, autocorrelation of absolute returns at lags 1 and 20, leverage correlation, first eigenvalue share).",
             facts=["Cont 2001, Empirical properties of asset returns: stylized facts (Quantitative Finance)", "Dow Jones fall of 22.6% on 19 October 1987 (Federal Reserve History)", "Mandelbrot 1963 (J. Business)", "Black 1976 leverage effect", "Ang and Chen 2002 asymmetric correlations (JFE); Longin and Solnik 2001 (JF)", "Wood, McInish, Ord 1985 intraday U-shape (JF); Andersen and Bollerslev 1997 intraday periodicity (JEF)", "Taylor 1986 (book) absolute-return autocorrelation", "Kenneth French data library, daily factors (copyright; derived statistics only)"]),
    ]),
    ("part.rs.predictors", [
        dict(slug="06-anatomy-of-a-predictor", title="Anatomy of a Predictor",
             hook="Two researchers report the information coefficient of the same signal: 0.05 and 0.01. One used raw five-day returns and z-scores across the whole market; the other sector-neutral residual returns.",
             sections=["The target", "Normalisation", "Neutralisation", "The information coefficient and its standard error", "The predictor card"],
             defines=["predictor", "prediction target", "forecast horizon", "residual return", "cross-sectional z-score", "rank transform", "neutralisation", "information coefficient", "rank information coefficient", "IC information ratio", "quantile spread", "predictor card"],
             uses=["Spearman's rank correlation (B4.15)", "winsorisation (B4.15)", "HAC estimator (B4.11)", "standard error (B4.11)", "Fama--MacBeth regression (B4.16)", "factor model (B4.22)", "Sharpe ratio (B4.11)", "synthmkt (ch5)"],
             tutorial="On firm.synthmkt, measure a planted signal's IC, rank IC and ICIR raw, normalised and neutralised, with the overlapping-target correction, and fill in its predictor card.",
             build="`firm.predictor`: normalisers, neutralisation by cross-sectional regression, IC engine (by date, pooled, rank, quantile spreads, Newey--West t-statistics for overlapping targets) and the PredictorCard record every later predictor fills; Python.",
             problem="Two ICs for one signal — named result: the ratio of the naive to the HAC-corrected t-statistic of the IC for overlapping 20-day targets, and the IC lost or gained by neutralisation.",
             facts=["Grinold and Kahn 2000, Active Portfolio Management (2nd ed.)", "Qian, Hua, Sorensen 2007, Quantitative Equity Portfolio Management", "Newey and West 1987 (Econometrica)", "Fama and MacBeth 1973 (JPE)"]),
        dict(slug="07-price-and-volume-features", title="Price and Volume Features",
             hook="A momentum signal built on the last twelve months of returns earns less than one that skips the most recent month: the last month reverses.",
             sections=["Returns at many scales", "Volatility and range", "Volume and liquidity", "Technical families as linear filters", "Predictor cards"],
             defines=["return feature", "skip period", "range-based volatility estimator", "Parkinson estimator", "Garman--Klass estimator", "Yang--Zhang estimator", "volume surprise", "Amihud illiquidity", "turnover ratio", "moving-average crossover", "linear filter"],
             uses=["realised variance (B4.18)", "EWMA volatility (B4.18)", "half-life (B4.4)", "predictor (ch6)", "information coefficient (ch6)", "predictor card (ch6)", "bar (ch2)", "look-ahead bias (ch3)"],
             tutorial="Compute the bar-feature family on firm.synthmkt, verify that no feature reads the future (a perturbation test), and draw the IC of each feature against horizon.",
             build="`firm.features`: vectorised, point-in-time-safe bar-feature library (returns at scales with skips, range estimators, volume surprise, Amihud, filters) with a leakage test that perturbs future data; Python.",
             problem="The range-estimator race — named result: the variance efficiency of the Parkinson, Garman--Klass, Rogers--Satchell and Yang--Zhang estimators relative to close-to-close, with and without drift and opening jumps.",
             facts=["Parkinson 1980 (J. Business)", "Garman and Klass 1980 (J. Business)", "Rogers and Satchell 1991 (Annals of Applied Probability)", "Yang and Zhang 2000 (J. Business)", "Amihud 2002 (J. Financial Markets)", "Jegadeesh 1990 (JF); Jegadeesh and Titman 1993 (JF)", "De Bondt and Thaler 1985 (JF)", "Gervais, Kaniel, Mingelgrin 2001 high-volume return premium (JF)", "Brock, Lakonishok, LeBaron 1992 technical rules (JF)"]),
        dict(slug="08-order-book-features", title="Order-Book Features",
             hook="Three lots rest at the best bid and forty at the best ask. Which way does the next mid-price change go, and with what probability?",
             sections=["Imbalance at the touch", "Depth beyond the touch", "Order-flow imbalance", "The microprice", "Queue depletion and cancellations", "Predictor cards"],
             defines=["queue imbalance", "depth imbalance", "depth profile", "order-flow imbalance", "microprice", "weighted mid price", "queue depletion rate", "cancellation rate"],
             uses=["mid price (B1.1)", "bid--ask spread (B1.1)", "market-by-order (B1.19)", "level 2 (B1.28)", "birth--death process (B4.8)", "hitting probability (B4.8)", "Hawkes process (B4.7)", "predictor card (ch6)", "information coefficient (ch6)", "tape (ch2)"],
             tutorial="On firm.tape, estimate the probability of an up-move against queue imbalance and compare it with the birth--death race; regress mid changes on order-flow imbalance; compare the microprice and the mid as forecasts of the mid a second later.",
             build="`firm.lobfeat`: streaming order-book feature engine (imbalances, OFI, microprice, depletion and cancellation rates) updated per message, in C++20 with a Rust twin and a Python reference, all three checked on one shared message fixture.",
             problem="Three lots against forty — named result: the empirical up-move probability at each imbalance bucket against the birth--death model's prediction, and the OFI regression's R-squared.",
             facts=["Cont, Kukanov, Stoikov 2014, the price impact of order book events (J. Financial Econometrics)", "Stoikov 2018, The micro-price (Quantitative Finance)", "Gould and Bonart 2016, queue imbalance as a one-tick-ahead price predictor (Market Microstructure and Liquidity)", "Cont, Stoikov, Talreja 2010 (Operations Research)", "Huang, Lehalle, Rosenbaum 2015 queue-reactive model (JASA)", "Cartea, Donnelly, Jaimungal 2018 order-book signals (Applied Mathematical Finance)"]),
        dict(slug="09-trade-flow-features", title="Trade-Flow Features",
             hook="In May 2010 a measure of order-flow toxicity was reported to have reached a historical high an hour before the flash crash; four years later another study found it did not forecast volatility once volume was controlled for.",
             sections=["Signing trades", "Order-sign autocorrelation", "Flow toxicity", "Fitted excitation intensities", "Large-trade and metaorder detection", "Predictor cards"],
             defines=["trade sign", "tick rule", "quote rule", "Lee--Ready algorithm", "bulk volume classification", "order-sign autocorrelation", "metaorder", "flow toxicity", "VPIN", "Kyle's lambda"],
             uses=["adverse selection (B1.1)", "mark-out (B2.15)", "flash crash (B1.31)", "Hawkes process (B4.7)", "branching ratio (B4.7)", "long memory (B4.17)", "Hurst exponent (B4.17)", "order-flow imbalance (ch8)", "tape (ch2)", "volume bar (ch2)"],
             tutorial="Sign the trades of firm.tape by the tick, quote, Lee--Ready and bulk-volume rules against the simulator's true signs; measure the sign autocorrelation; compute VPIN and a mark-out toxicity measure through a planted toxic episode; fit a two-dimensional Hawkes process to buys and sells.",
             build="`firm.tradeflow`: trade classifiers, bulk volume classification, VPIN on volume bars, Kyle's lambda by rolling regression, Hawkes-intensity features (imports firm.hawkes); Python.",
             problem="Did VPIN see it coming? — named result: VPIN's lead time and false-alarm rate against the mark-out toxicity measure on a synthetic tape with a toxic episode.",
             facts=["Lee and Ready 1991 (JF)", "Ellis, Michaely, O'Hara 2000 classification accuracy (JFQA)", "Easley, Lopez de Prado, O'Hara 2011, The microstructure of the flash crash (JPM)", "Easley, Lopez de Prado, O'Hara 2012 VPIN (RFS)", "Andersen and Bondarenko 2014 VPIN critique (J. Financial Markets)", "Lillo and Farmer 2004 long memory of order signs (SNDE)", "Kyle 1985 (Econometrica)", "Chakrabarty, Pascual, Shkilko 2015 BVC accuracy (J. Financial Markets)"]),
        dict(slug="10-cross-sectional-and-cross-asset-features", title="Cross-Sectional and Cross-Asset Features",
             hook="When a customer firm reports bad news, its main supplier's stock falls — but on average a month later, not the same day.",
             sections=["Peer and sector residuals", "Lead--lag at daily horizons", "Futures-to-cash and cross-venue", "Cross-asset signals", "Predictor cards"],
             defines=["peer group", "peer-relative return", "lead--lag relationship", "lead--lag estimator", "economic link", "futures-to-cash lead", "cross-asset feature"],
             uses=["Hayashi--Yoshida estimator (B4.21)", "Epps effect (B4.21)", "non-synchronous trading (B4.21)", "Granger causality (B4.20)", "vector autoregression (B4.20)", "principal component analysis (B4.22)", "fair value (B1.21)", "exchange-traded fund (B1.14)", "residual return (ch6)", "neutralisation (ch6)", "tape (ch2)", "synthmkt (ch5)"],
             tutorial="Estimate the lead of a future over an ETF on two firm.tape instruments with a planted latency by the Hayashi--Yoshida cross-correlation at lags; then recover the planted economic links of firm.synthmkt at daily horizons.",
             build="`firm.leadlag`: lead--lag estimator on asynchronous data (Hayashi--Yoshida at lags, argmax and confidence band), peer-residual engine and a lagged-peer feature builder; Python.",
             problem="Who moves first? — named result: the estimated lead against the planted latency, and the share of cross-venue predictability left at each sampling interval.",
             facts=["Cohen and Frazzini 2008, Economic links and predictable returns (JF)", "Menzly and Ozbas 2010 (JF)", "Hou 2007 industry information diffusion and lead-lag (RFS)", "Lo and MacKinlay 1990 (RFS)", "Kawaller, Koch, Koch 1987 futures lead cash (JF)", "Hoffmann, Rosenbaum, Yoshida 2013 lead-lag estimation (Bernoulli)", "Huth and Abergel 2014 high-frequency lead-lag (J. Empirical Finance)"]),
        dict(slug="11-fundamental-analyst-and-event-features", title="Fundamental, Analyst and Event Features",
             hook="A company closes its quarter on 31 December and files its report on 5 February. A database keyed on the period end lets a backtest trade the numbers five weeks before anyone could read them.",
             sections=["Accounting data, point-in-time", "Ratios as features", "Surprises and revisions", "Event calendars", "Predictor cards"],
             defines=["fiscal period", "filing lag", "trailing twelve months", "accounting ratio", "earnings surprise", "standardised unexpected earnings", "analyst revision", "forecast dispersion", "event calendar", "announcement window"],
             uses=["consensus forecast (B2.31)", "point-in-time data (ch3)", "restatement (ch3)", "knowledge time (ch3)", "as-of join (ch3)", "security master (ch4)", "predictor card (ch6)"],
             tutorial="Pull a few companies' XBRL facts from SEC EDGAR (public), measure filing lags and detect restated periods; build trailing-twelve-month values and an earnings-surprise feature keyed on filing dates; then measure the IC inflation when the same features are keyed on period ends in firm.synthmkt.",
             build="`firm.fundpit`: fundamental feature builder keyed on knowledge time (as-reported values, TTM, ratios, SUE with seasonal random-walk expectation, revision and dispersion features) on top of firm.pit; Python.",
             problem="The five-week head start — named result: the information-coefficient inflation of a SUE and a value signal when period-end dating replaces filing-date dating.",
             facts=["SEC periodic report deadlines by filer status (Form 10-Q, 10-K)", "SEC EDGAR XBRL companyfacts API (data.sec.gov)", "Ball and Brown 1968 (J. Accounting Research)", "Foster, Olsen, Shevlin 1984 SUE (Accounting Review)", "Bernard and Thomas 1989 PEAD (J. Accounting Research)", "Womack 1996 analyst recommendations (JF)", "Diether, Malloy, Scherbina 2002 dispersion (JF)", "Sloan 1996 accruals (Accounting Review)"]),
        dict(slug="12-alternative-and-text-data", title="Alternative and Text Data",
             hook="A vendor offers five years of card-transaction data covering four hundred retailers at an annual fee of several hundred thousand dollars; the trial file arrives with a note that the panel changed provider in its third year.",
             sections=["What the datasets are", "Text as data", "Evaluating a vendor", "Law and ethics", "The buy decision"],
             defines=["alternative data", "panel drift", "data trial", "incremental information coefficient", "dictionary method", "sentiment score", "document embedding", "material non-public information"],
             uses=["point-in-time data (ch3)", "backfill bias (ch3)", "information coefficient (ch6)", "neutralisation (ch6)", "predictor card (ch6)", "earnings surprise (ch11)"],
             tutorial="Run a vendor trial on a synthetic panel with drift and backfill: coverage through time, point-in-time check, incremental IC after orthogonalising on existing signals, and the break-even price; then score a small text corpus with a word list and compare it with a planted tone.",
             build="`firm.vendoreval`: vendor-trial harness (coverage, history, point-in-time and backfill checks, panel-drift detection, incremental IC, value of information net of fee and capacity); Python.",
             problem="Should we buy the card panel? — named result: the break-even annual price of a dataset given its incremental IC, breadth, capacity and decay.",
             facts=["Tetlock 2007, media pessimism (JF)", "Loughran and McDonald 2011 (JF)", "SEC v. App Annie, September 2021 settlement (alternative-data MNPI case)", "hiQ Labs v. LinkedIn, Ninth Circuit 2022 (scraping)", "Froot, Kang, Ozik, Sadka 2017 real-time sales data (JFE)", "Zhu 2019, Big data as a governance mechanism (RFS)", "EU GDPR personal data definition (Regulation 2016/679)"]),
        dict(slug="13-half-life-decay-and-stability", title="Half-Life, Decay and Stability",
             hook="A published anomaly returns about a quarter less out of sample than in the paper, and more than half less after publication; the question for a desk is whether its own signals are on the same path.",
             sections=["Decay across horizons", "Stability across years", "Structural breaks", "Post-publication decay", "Measuring the half-life of a predictor card"],
             defines=["IC decay curve", "signal half-life", "signal autocorrelation", "IC stability", "structural break", "CUSUM test", "post-publication decay"],
             uses=["half-life (B4.4)", "Ornstein--Uhlenbeck process (B4.4)", "autoregressive process (B4.17)", "bootstrap (B4.13)", "power of a test (B4.12)", "information coefficient (ch6)", "predictor card (ch6)"],
             tutorial="Measure the IC decay curves of the chapter 7--10 predictors, fit their half-lives with bootstrap intervals, and detect a planted break in a rolling IC with the CUSUM test.",
             build="`firm.decay`: IC decay curves, exponential and AR fits of the half-life with bootstrap intervals, signal autocorrelation and turnover link, CUSUM and sup-F break tests; Python.",
             problem="Did it die, or was it unlucky? — named result: the probability that a signal whose measured IC halved over five years has truly decayed, from a power analysis on the IC's sampling error.",
             facts=["McLean and Pontiff 2016 (JF) 26% out of sample, 58% post-publication", "Chordia, Subrahmanyam, Tong 2014 (J. Accounting and Economics)", "Brown, Durbin, Evans 1975 CUSUM (JRSS B)", "Andrews 1993 sup-F (Econometrica)", "Bai and Perron 1998 (Econometrica)", "Hou, Xue, Zhang 2020 replicating anomalies (RFS)"]),
    ]),
    ("part.rs.forecasts", [
        dict(slug="14-signal-combination", title="Signal Combination",
             hook="Forty signals each have an IC near 0.02. Their equal-weighted blend has 0.05; a regression-fitted blend has 0.08 in sample and 0.03 afterwards.",
             sections=["The geometry of a linear blend", "Weights from estimates", "Regularised combination", "Stacking", "Orthogonalisation"],
             defines=["signal combination", "composite signal", "equal-weight blend", "IC-weighted blend", "maximum-ICIR blend", "stacking", "orthogonalisation", "symmetric orthogonalisation", "forecast combination puzzle"],
             uses=["ridge regression (B4.16)", "lasso (B4.16)", "cross-validation (B4.16)", "shrinkage estimator (B4.14)", "covariance matrix (B4.22)", "principal component analysis (B4.22)", "information coefficient (ch6)", "IC information ratio (ch6)", "predictor (ch6)"],
             tutorial="Combine forty planted signals of firm.synthmkt by equal weights, IC weights, ridge and the maximum-ICIR rule; compare in-sample and out-of-sample IC and find the shrinkage that wins.",
             build="`firm.combine`: blenders (equal, IC-weighted, maximum-ICIR with shrinkage of the signal covariance, ridge and lasso on panels, stacking with time-ordered folds) and orthogonalisers (sequential, symmetric, residualise on a book); Python.",
             problem="Forty weak signals — named result: the out-of-sample IC of the best blend against equal weights, and the shrinkage intensity that maximises it.",
             facts=["Timmermann 2006, Forecast combinations (Handbook of Economic Forecasting)", "Stock and Watson 2004 (J. Forecasting)", "Smith and Wallis 2009 forecast combination puzzle (OBES)", "Wolpert 1992 stacked generalisation (Neural Networks); Breiman 1996 stacked regressions (Machine Learning)", "Lowdin 1950 symmetric orthogonalisation (J. Chemical Physics)", "Klein and Chow 2013 orthogonalized factors (QREF)"]),
        dict(slug="15-from-signal-to-forecast", title="From Signal to Forecast",
             hook="A stock's composite score is +2. Is its expected return over the next month two basis points or two hundred?",
             sections=["Calibrating a score", "Scaling across assets and horizons", "The fundamental law of active management", "Where the law breaks", "Evaluating forecasts"],
             defines=["forecast calibration", "alpha scaling rule", "calibration curve", "isotonic regression", "breadth", "effective breadth", "fundamental law of active management", "transfer coefficient"],
             uses=["alpha (B1.1)", "information ratio (B1.3)", "Mincer--Zarnowitz regression (B4.18)", "information coefficient (ch6)", "composite signal (ch14)", "forecast horizon (ch6)"],
             tutorial="Calibrate chapter 14's composite into expected returns by the scaling rule, by bins and by isotonic regression; draw the calibration curves; check the fundamental law on firm.synthmkt with known IC and breadth, then with correlated bets.",
             build="`firm.forecast`: calibrators (scaling rule, binned, isotonic by pool-adjacent-violators), volatility and horizon scaling, effective breadth from the forecast correlation, and a forecast-evaluation report; Python.",
             problem="Why is our information ratio half what the law promised? — named result: the decomposition of the shortfall into effective breadth, transfer coefficient and noise in the IC.",
             facts=["Grinold 1989, the fundamental law of active management (JPM)", "Clarke, de Silva, Thorley 2002, portfolio constraints and the fundamental law (FAJ)", "Buckle 2004, relaxing the fundamental law (Physica A)", "Ding 2010 time-series dynamics of the fundamental law (SSRN)", "Ayer et al. 1955 pool-adjacent-violators (Annals of Math. Stat.)", "Zhou 2008 estimation error in the fundamental law"]),
    ]),
    ("part.rs.backtesting", [
        dict(slug="16-vectorised-backtests", title="Vectorised Backtests",
             hook="A one-line backtest shows a Sharpe ratio of 3.1. The positions were computed from today's close and multiplied by today's return.",
             sections=["The vectorised backtest", "Four fidelity levels", "Where the vectorised backtest is right", "The lies it tells", "A checklist"],
             defines=["backtest", "fidelity level", "vectorised backtest", "decision time", "execution lag", "portfolio turnover", "linear cost model", "rebalance frequency"],
             uses=["gross exposure (B1.7)", "net exposure (B1.7)", "borrow fee (B1.6)", "locate (B1.6)", "short sale (B1.6)", "closing price (B1.13)", "Sharpe ratio (B4.11)", "look-ahead bias (ch3)", "survivorship bias (ch3)", "tradable universe (ch4)", "composite signal (ch14)"],
             tutorial="Backtest a reversal signal on firm.synthmkt in one vectorised pass, then correct its five lies one at a time (lag, universe, costs, borrow, compounding and cash) and draw the Sharpe-ratio waterfall.",
             build="`firm.vecbt`: level-1 backtester (weights or signals, enforced execution lag, universe mask, linear costs and borrow, cash and financing, per-name caps) returning the standard BacktestResult consumed by firm.perf; Python.",
             problem="Sharpe 3.1 on Monday, 0.4 on Friday — named result: the Sharpe waterfall from the naive to the honest level-1 backtest, lie by lie.",
             facts=["Bailey et al. 2014 (Notices AMS)", "Arnott, Harvey, Markowitz 2019 (JFDS)", "Novy-Marx and Velikov 2016, a taxonomy of anomalies and their trading costs (RFS)"]),
        dict(slug="17-event-driven-backtests", title="Event-Driven Backtests",
             hook="A strategy resting limit orders at the bid fills every time a bar's low touches its price, in the backtest. Live, it fills a third as often and mostly just before the price falls through.",
             sections=["Architecture: clock, events, handlers", "Orders and fills at bar level", "Decision time and latency", "Calendars and corporate actions in the loop", "Determinism"],
             defines=["event-driven backtest", "simulated clock", "fill model", "touch fill", "penetration fill", "volume participation cap", "partial fill", "order lifecycle"],
             uses=["order (B1.4)", "closing price (B1.13)", "call auction (B1.13)", "market-on-close order (B1.13)", "price-time priority (B1.19)", "trade-through (B1.9)", "decision time (ch16)", "execution lag (ch16)", "fidelity level (ch16)", "bar (ch2)"],
             tutorial="Run a limit-order mean-reversion strategy on bars in firm.evbt with touch, penetration and volume-capped fill models, and compare with the level-1 result on the same signal.",
             build="`firm.evbt`: level-2 event-driven backtester (priority event queue on a simulated clock, strategy callbacks, order manager with the order lifecycle, pluggable fill models, portfolio and cash, deterministic replay) returning BacktestResult; Python.",
             problem="The limit order that always filled — named result: the fill rate and P&L of a passive bar strategy under touch, penetration and capped fills, against the level-3 answer of chapter 18.",
             facts=["open-source event-driven backtester architectures (LEAN, Zipline documentation)", "Arnott, Harvey, Markowitz 2019 (JFDS)"]),
        dict(slug="18-order-book-replay-simulation", title="Order-Book Replay Simulation",
             hook="A market-making backtest earns money every day; the live strategy loses. The backtest had assumed that its quotes stood first in every queue they joined.",
             sections=["Replaying a market-by-order feed", "Where am I in the queue?", "Latency", "Fill logic", "The missing market impact and how to bound it", "The fourth level"],
             defines=["order-book replay", "queue position", "queue-position model", "latency model", "order-entry latency", "market-data latency", "passive fill probability", "market impact", "counterfactual impact"],
             uses=["market-by-order (B1.19)", "market-by-price (B1.19)", "price-time priority (B1.19)", "pro-rata allocation (B1.19)", "sequence number (B1.28)", "exchange timestamp (B1.28)", "adverse selection (B1.1)", "birth--death process (B4.8)", "queue imbalance (ch8)", "fill model (ch17)", "fidelity level (ch16)", "tape (ch2)"],
             tutorial="Replay a firm.tape session through firm.lobreplay with a passive quoting strategy under three queue-position models and three latencies, and draw the P&L of each.",
             build="`firm.lobreplay`: level-3 replay engine (book reconstruction from MBO messages, our orders' queue positions under pluggable models, latency queues for entry and data, fill logic, an impact bound) in Python for research with a C++20 core and a Rust twin that reproduce the Python fills on a shared fixture.",
             problem="Where did the queue go? — named result: the daily P&L of a passive strategy under each queue model and latency, and the latency at which its edge vanishes.",
             facts=["Moallemi and Yuan 2017 queue position valuation (working paper)", "Lehalle and Mounjid 2017 limit order placement, adverse selection and latency (Market Microstructure and Liquidity)", "Cont and de Larrard 2013 (SIAM J. Financial Math.)", "hftbacktest queue models (open-source documentation)", "exchange MBO feeds (CME MDP 3.0 MBO, Nasdaq ITCH) as sources of queue order"]),
        dict(slug="19-simulation-versus-live", title="Simulation versus Live",
             hook="A strategy's first live month makes forty per cent of what the simulator says it would have made on the same days, with the same signals.",
             sections=["Reconciling fills", "Reconciling P&L", "Locating the divergence", "Keeping the simulator honest"],
             defines=["sim-to-live reconciliation", "shadow trading", "implementation shortfall", "arrival price", "divergence decomposition", "replay parity test", "simulator calibration"],
             uses=["mark-out (B2.15)", "P\\&L attribution (B1.7)", "fill model (ch17)", "queue-position model (ch18)", "latency model (ch18)", "market impact (ch18)", "order-book replay (ch18)"],
             tutorial="Trade a strategy against a firm.tape market that reacts to its orders (the stand-in for live) and replay the same session in firm.lobreplay; match the fills and decompose the P&L gap into latency, queue, impact and fees; then recalibrate the fill model on the live fills.",
             build="`firm.simlive`: fill matcher (live orders to simulated orders), P&L gap decomposition, replay parity test, and fill-probability recalibration from live fills; Python.",
             problem="The forty-per-cent month — named result: the decomposition of the gap between live and simulated P&L into latency, queue position, impact and fees.",
             facts=["Perold 1988, The implementation shortfall: paper versus reality (JPM)"]),
        dict(slug="20-overfitting", title="Overfitting",
             hook="A thousand parameter settings of a trend-following system are backtested on twenty years of data. The best has an in-sample Sharpe ratio of 1.8; over the next five years it earns nothing.",
             sections=["Selection under many trials", "The probability of backtest overfitting", "Purged and embargoed cross-validation", "Walk-forward analysis", "Practical defences"],
             defines=["backtest overfitting", "in-sample", "out-of-sample", "walk-forward analysis", "minimum backtest length", "probability of backtest overfitting", "combinatorially symmetric cross-validation", "label overlap", "purging", "embargo", "combinatorial purged cross-validation"],
             uses=["deflated Sharpe ratio (B4.12)", "multiple testing (B4.12)", "data snooping (B4.12)", "cross-validation (B4.16)", "bootstrap (B4.13)", "Sharpe ratio (B4.11)", "trial count (ch1)", "holdout set (ch1)", "research log (ch1)", "vectorised backtest (ch16)"],
             tutorial="Estimate the probability of backtest overfitting by CSCV for a thousand trend systems on noise and on data with a planted trend, and compare purged, embargoed and naive cross-validation scores for an overlapping-label model.",
             build="`firm.overfit`: CSCV and PBO, purged k-fold with embargo, combinatorial purged cross-validation paths, minimum backtest length, walk-forward splitter; Python.",
             problem="One thousand trend systems — named result: the PBO of the search and the deflated out-of-sample expectation of the chosen system.",
             facts=["Bailey, Borwein, Lopez de Prado, Zhu 2017, the probability of backtest overfitting (J. Computational Finance)", "Bailey et al. 2014 minimum backtest length (Notices AMS)", "Lopez de Prado 2018, Advances in Financial Machine Learning (purging, embargo, CPCV)", "Harvey and Liu 2015, Backtesting (JPM) Sharpe haircut", "Pardo 2008, The evaluation and optimization of trading strategies (walk-forward)"]),
        dict(slug="21-live-experiments", title="Live Experiments",
             hook="A new execution algorithm handles ten per cent of the firm's orders for two weeks and saves 0.4 basis points on average, with a standard error of 0.5.",
             sections=["Paper trading and shadow mode", "Canaries and staged rollouts", "Randomised A/B tests on live flow", "Variance reduction", "Sizing and stopping an experiment"],
             defines=["paper trading", "canary deployment", "staged rollout", "A/B test", "randomisation unit", "interference", "CUPED", "minimum detectable effect", "sequential test"],
             uses=["power of a test (B4.12)", "size of a test (B4.12)", "p-value (B4.12)", "stratified sampling (B4.26)", "shadow trading (ch19)", "implementation shortfall (ch19)", "arrival price (ch19)"],
             tutorial="Simulate an A/B test of two execution algorithms on order-level costs, with randomisation by order and by day; compute power curves, the gain from CUPED and stratification, and an always-valid sequential stop.",
             build="`firm.abtest`: hash-based assignment, difference-in-means with CUPED and stratification, power and minimum detectable effect, mixture sequential probability ratio test; Python.",
             problem="Is the new algorithm better? — named result: the trading days needed to detect a 0.3 basis point improvement at 80% power with and without CUPED.",
             facts=["Deng, Xu, Kohavi, Walker 2013 CUPED (WSDM)", "Kohavi, Tang, Xu 2020, Trustworthy Online Controlled Experiments", "Johari, Koomen, Pekelis, Walsh 2017/2022 always-valid inference (KDD / Operations Research)", "Wald 1945 SPRT (Annals of Math. Stat.)", "SEC Knight Capital order, October 2013 (deployment failure, 1 August 2012)"]),
    ]),
    ("part.rs.measurement", [
        dict(slug="22-performance-measurement", title="Performance Measurement",
             hook="Two strategies have a Sharpe ratio of 1.0 over five years. One has lost 40 per cent peak to trough twice; the other sells out-of-the-money puts and has never had a losing quarter.",
             sections=["The Sharpe ratio and its standard error", "Drawdowns", "Turnover, hit rate and holding period", "The shape of outcomes", "Benchmark-relative measures"],
             defines=["annualisation", "autocorrelation-adjusted Sharpe ratio", "maximum drawdown", "drawdown duration", "Calmar ratio", "Sortino ratio", "Omega ratio", "hit rate", "profit factor", "return smoothing", "market beta"],
             uses=["Sharpe ratio (B4.11)", "standard error (B4.11)", "delta method (B4.11)", "HAC estimator (B4.11)", "drawdown (B2.29)", "information ratio (B1.3)", "tracking error (B1.3)", "benchmark (B1.3)", "alpha (B1.1)", "deflated Sharpe ratio (B4.12)", "portfolio turnover (ch16)"],
             tutorial="Compute the tear sheet of firm.perf for four synthetic return streams (trend, short volatility, a smoothed illiquid book, a market maker) and read what each number hides.",
             build="`firm.perf`: performance module on BacktestResult (Sharpe with iid, HAC and Lo standard errors, drawdown statistics, Calmar, Sortino, Omega, hit rate, profit factor, turnover and holding period, alpha and beta with HAC errors, unsmoothing), a text tear sheet; Python.",
             problem="Two Sharpe ratios of one — named result: the probability of a 30% drawdown within five years for each strategy, and the Sharpe ratio's standard error under the smoothed book's autocorrelation.",
             facts=["Lo 2002, the statistics of Sharpe ratios (FAJ)", "Getmansky, Lo, Makarov 2004 serial correlation and illiquidity (JFE)", "Magdon-Ismail, Atiya, Pratap, Abu-Mostafa 2004 maximum drawdown of Brownian motion (J. Applied Probability)", "Sortino and Price 1994 (J. Investing)", "Keating and Shadwick 2002 Omega", "Young 1991 Calmar ratio (Futures)", "Sharpe 1966 (J. Business); Sharpe 1994 (JPM)", "Goetzmann, Ingersoll, Spiegel, Welch 2007 (RFS)"]),
        dict(slug="23-measuring-market-making-and-execution", title="Measuring Market Making and Execution",
             hook="A market maker's year ends flat. Its books show spread capture of plus two million, adverse selection of minus one point seven, and inventory losses of minus three hundred thousand.",
             sections=["Mark-out curves", "Fill rates and hit ratios", "The market maker's P&L, decomposed", "Measuring execution", "Transaction cost analysis"],
             defines=["mark-out curve", "spread capture", "adverse-selection cost", "inventory P\\&L", "fill rate", "hit ratio", "transaction cost analysis", "delay cost", "opportunity cost", "VWAP slippage"],
             uses=["mark-out (B2.15)", "adverse selection (B1.1)", "effective spread (B1.10)", "realised spread (B1.10)", "microprice (ch8)", "implementation shortfall (ch19)", "arrival price (ch19)", "volume-weighted average price (ch2)", "order-book replay (ch18)", "market impact (ch18)"],
             tutorial="Run a simple market maker in firm.lobreplay, draw its mark-out curves by counterparty type, decompose its P&L into spread capture, adverse selection and inventory, and write the TCA report of a parent order.",
             build="`firm.markout`: mark-out curves (mid or microprice reference, horizons, groupings), fill and hit statistics, market-maker P&L decomposition that adds up exactly, implementation-shortfall decomposition and a TCA report; Python.",
             problem="The flat year — named result: the decomposition of a simulated market maker's annual P&L into spread capture, adverse selection, inventory and fees, and the horizon at which its mark-outs settle.",
             facts=["Perold 1988 (JPM)", "Menkveld 2013, high frequency trading and the new market makers (J. Financial Markets)", "Kissell 2013, The Science of Algorithmic Trading and Portfolio Management", "Hasbrouck 2007, Empirical Market Microstructure"]),
        dict(slug="24-risk-models", title="Risk Models",
             hook="A market-neutral book is forecast at four per cent annual volatility and realises nine. Its risk model had no factor for what the book was really exposed to.",
             sections=["Three families of factor models", "Estimating factor returns", "Factor covariance", "Specific risk", "Evaluating a risk model", "Build: an equity risk model"],
             defines=["fundamental factor model", "statistical factor model", "hybrid factor model", "factor exposure", "factor return", "specific return", "specific risk", "style factor", "industry factor", "bias statistic", "volatility regime adjustment"],
             uses=["factor model (B4.22)", "principal component analysis (B4.22)", "covariance matrix (B4.22)", "linear shrinkage (B4.22)", "eigenvalue clipping (B4.22)", "EWMA volatility (B4.18)", "weighted least squares (B4.16)", "HAC estimator (B4.11)", "residual return (ch6)", "market beta (ch22)", "synthmkt (ch5)"],
             tutorial="Build a fundamental model (style and industry factors by weighted cross-sectional regression) and a statistical model on firm.synthmkt; forecast portfolio risk out of sample and compare bias statistics, including a book exposed to a factor the model omits.",
             build="`firm.riskmodel`: equity risk model (exposures, constrained WLS factor returns, EWMA factor covariance with Newey--West and volatility-regime adjustment, shrunk specific variances, portfolio risk and its decomposition, bias-statistic evaluation); Python.",
             problem="Predicted four, realised nine — named result: the bias statistic of a model missing a planted factor, and the realised-to-predicted volatility ratio of the exposed book.",
             facts=["Rosenberg 1974 (JFQA)", "Connor 1995, the three types of factor models (FAJ)", "Fama and French 1993 (JFE)", "Menchero, Orr, Wang 2011, the Barra US equity model USE4 methodology notes (public PDF)", "Menchero, Wang, Orr 2012 eigenfactor risk adjustment", "Chen, Roll, Ross 1986 macro factors (J. Business)"]),
        dict(slug="25-portfolio-construction-i", title="Portfolio Construction I",
             hook="An unconstrained mean--variance optimiser puts forty-five per cent of a long--short book into two stocks: the two with the largest alphas and the smallest estimated specific risks.",
             sections=["Mean--variance with an alpha and a risk model", "The error maximiser", "Realistic constraints", "Turnover control", "Solving at scale"],
             defines=["mean--variance optimisation", "risk-aversion parameter", "efficient frontier", "error maximisation", "dollar neutrality", "beta neutrality", "factor-neutrality constraint", "name limit", "liquidity constraint", "turnover penalty", "130/30 portfolio"],
             uses=["quadratic programme (B4.23)", "Karush--Kuhn--Tucker conditions (B4.23)", "shadow price (B4.23)", "second-order cone programme (B4.23)", "interior-point method (B4.23)", "minimum-variance portfolio (B4.22)", "no-trade region (B4.10)", "gross exposure (B1.7)", "short sale (B1.6)", "tracking error (B1.3)", "market beta (ch22)", "risk model (ch24)", "transfer coefficient (ch15)"],
             tutorial="Optimise a long--short book on firm.synthmkt from chapter 15's forecasts and chapter 24's risk model, adding the constraints one at a time and recording the information ratio, turnover, transfer coefficient and each constraint's shadow price.",
             build="`firm.portcons`: portfolio-construction layer over firm.portopt (objective from alpha, risk model and costs; constraint builders for budget, neutralities, name, liquidity, gross and turnover limits; diagnostics of binding constraints and shadow prices; trade list); Python.",
             problem="The forty-five-per-cent portfolio — named result: the information ratio each constraint costs or earns, from the shadow-price decomposition.",
             facts=["Markowitz 1952 (JF)", "Michaud 1989, the Markowitz optimization enigma (FAJ)", "Jagannathan and Ma 2003, risk reduction by imposing the wrong constraints (JF)", "Jacobs, Levy, Starer 1998 long-short portfolio management (FAJ)", "Clarke, de Silva, Thorley 2002 (FAJ)"]),
        dict(slug="26-portfolio-construction-ii", title="Portfolio Construction II",
             hook="Move one stock's alpha by a single basis point and the optimal portfolio turns over a third of its gross.",
             sections=["Robust optimisation", "Views blended with equilibrium", "Risk parity and risk budgeting", "Hierarchical allocation", "Multi-period optimisation with costs"],
             defines=["robust portfolio optimisation", "uncertainty set", "implied equilibrium returns", "Black--Litterman model", "risk contribution", "risk budgeting", "equal risk contribution portfolio", "risk parity", "hierarchical risk parity", "aim portfolio", "multi-period optimisation"],
             uses=["second-order cone programme (B4.23)", "Euler allocation (B6.20)", "stochastic control problem (B4.9)", "no-trade region (B4.10)", "posterior distribution (B4.14)", "mean--variance optimisation (ch25)", "efficient frontier (ch25)", "turnover penalty (ch25)"],
             tutorial="Build the same book by mean--variance, robust, Black--Litterman, equal-risk-contribution and hierarchical rules; measure weight stability under a one-basis-point alpha perturbation; run the aim-portfolio trading rule with quadratic costs and compare net Sharpe ratios.",
             build="`firm.allocation`: robust mean--variance by SOCP, Black--Litterman posterior, equal risk contribution by Newton, hierarchical risk parity, aim-portfolio multi-period rule with quadratic costs; Python.",
             problem="The one-basis-point flip — named result: turnover per basis point of alpha perturbation for each method, and the net Sharpe ratio of the aim portfolio against daily re-optimisation.",
             facts=["Black and Litterman 1992 (FAJ)", "He and Litterman 1999 (Goldman Sachs working paper)", "Goldfarb and Iyengar 2003 (Math. of Operations Research)", "Ceria and Stubbs 2006 (J. Asset Management)", "Maillard, Roncalli, Teiletche 2010 ERC (JPM)", "Lopez de Prado 2016 HRP (JPM)", "Garleanu and Pedersen 2013 (JF)", "Boyd et al. 2017, multi-period trading via convex optimization (Foundations and Trends in Optimization)", "Asness, Frazzini, Pedersen 2012 leverage aversion and risk parity (FAJ)"]),
        dict(slug="27-transaction-costs-in-research", title="Transaction Costs in Research",
             hook="A daily signal has a gross Sharpe ratio of 2.5. After costs it has 0.3. Rebuilt with the costs inside the optimiser and a slower signal, it has 1.1.",
             sections=["Cost models", "Estimating costs from your own fills", "Costs inside the optimiser", "Netting across strategies", "Cost-aware signals"],
             defines=["temporary impact", "permanent impact", "square-root impact law", "percentage of volume", "cost-aware optimisation", "internal crossing", "signal smoothing", "break-even cost"],
             uses=["bid--ask spread (B1.1)", "effective spread (B1.10)", "market impact (ch18)", "implementation shortfall (ch19)", "linear cost model (ch16)", "portfolio turnover (ch16)", "mean--variance optimisation (ch25)", "turnover penalty (ch25)", "aim portfolio (ch26)", "second-order cone programme (B4.23)"],
             tutorial="Fit a square-root impact model to simulated fills, put spread and power-law impact inside firm.portcons, and compare naive, cost-penalised and smoothed-signal books by net Sharpe ratio against assets under management.",
             build="`firm.tcost`: cost model (spread, fees, square-root impact with fitted coefficients), power-cost terms for firm.portcons as cone constraints, netting engine for several strategies' trade lists with the savings allocated; Python.",
             problem="From 2.5 to 0.3 — named result: the net Sharpe ratio against the signal-smoothing half-life, and the optimal smoothing.",
             facts=["Almgren, Thum, Hauptmann, Li 2005, direct estimation of equity market impact (Risk)", "Toth et al. 2011 anomalous price impact (Physical Review X)", "Frazzini, Israel, Moskowitz 2018, Trading costs (working paper)", "Kyle and Obizhaeva 2016 market microstructure invariance (Econometrica)", "Bouchaud, Bonart, Donier, Gould 2018, Trades, Quotes and Prices", "Loeb 1983 trading cost (FAJ)"]),
        dict(slug="28-capacity-decay-and-crowding", title="Capacity, Decay and Crowding",
             hook="In the second week of August 2007 many quantitative equity market-neutral funds lost more in three days than in a normal year, with no news on the stocks they held. On the fourth day most of it came back.",
             sections=["Capacity curves", "Alpha decay in production", "Detecting crowding", "August 2007"],
             defines=["strategy capacity", "capacity curve", "profit-maximising size", "crowding", "crowded trade", "comomentum", "unwind"],
             uses=["liquidity spiral (B1.31)", "short interest (B1.16)", "days to cover (B1.16)", "market impact (ch18)", "square-root impact law (ch27)", "post-publication decay (ch13)", "IC decay curve (ch13)", "risk model (ch24)"],
             tutorial="Draw the capacity curve of chapter 27's strategy; then simulate several funds holding overlapping books when one is forced to sell, and measure the losses of the others as a function of the overlap and the fraction sold.",
             build="`firm.capacity`: capacity-curve solver (net P&L and Sharpe ratio against size under the impact model), crowding monitors (return co-movement of long and short legs, comomentum, holdings overlap) and an unwind simulator; Python.",
             problem="The week of 6 August 2007 — named result: the peak loss of the non-selling funds against the fraction of the overlapping book sold, and the size at which the strategy's net Sharpe ratio halves.",
             facts=["Khandani and Lo 2011, What happened to the quants in August 2007? (J. Financial Markets)", "Lou and Polk 2022 comomentum (RFS)", "Pedersen 2009, When everyone runs for the exit (IJCB)", "Stein 2009 presidential address (JF)", "Berk and Green 2004 (JPE)", "Fama-French factor returns in August 2007 (derived statistics)"]),
        dict(slug="29-build-a-research-workflow", title="Build: a Research Workflow",
             hook="A result from eighteen months ago cannot be reproduced: the vendor revised its history, the code moved on, and nobody kept the random seed.",
             sections=["Reproducibility", "Review", "Build: the pipeline from raw data to a reviewed result"],
             defines=["reproducible result", "data snapshot", "content-addressed storage", "pipeline stage", "environment lock", "review checklist"],
             uses=["bitwise reproducibility (B4.25)", "research log (ch1)", "trial count (ch1)", "point-in-time data (ch3)", "predictor card (ch6)", "fidelity level (ch16)", "research review (ch1)"],
             tutorial="Run the book's reference study end to end through firm.workflow (synthmkt snapshot, point-in-time store, universe, features, cards, blend, forecast, portfolio, level-1 and level-2 backtests, tear sheet, log entry), change one input and watch which stages recompute.",
             build="`firm.workflow`: pipeline runner over a DAG of cached, content-hashed stages with a manifest (inputs, code hashes, seeds, environment), bit-for-bit reproduction check, and registration of each run in firm.researchlog; Python.",
             problem="The result that could not be reproduced — named result: the stages invalidated by a vendor revision, and the manifest diff that proves the reproduction.",
             facts=["Peng 2011, Reproducible research in computational science (Science)", "Sandve, Nekrutenko, Taylor, Hovig 2013, ten simple rules for reproducible computational research (PLoS Computational Biology)", "Git object model (content-addressed storage) documentation", "Arnott, Harvey, Markowitz 2019 (JFDS)"]),
    ]),
]
