"""Book 8 (Strategies I: Equities and Futures) chapter briefs: data for
tools/make_briefs.py --book 8.

`uses` lists terms defined elsewhere that the chapter relies on (not
redefined); owners in parentheses: (B7.16) = One Quant Book 7, chapter 16,
checked against the harvested \\index{} entries of Books 1-7 on 2026-09-25;
(ch3) = an earlier chapter of this book.

Ownership: Books 1-7 keep their terms. Book 1 owns short interest, days to
cover, carry, basis, calendar spread; Book 3 owns roll yield, funding rate,
cash-and-carry trade, Commitments of Traders report; Book 7 owns the research
method (predictor, information coefficient, backtest levels, risk model,
portfolio construction, costs, capacity, crowding, risk parity). This book owns
the named equity and futures strategies and the terms of their mechanics.

Every chapter of Parts I-II carries strategy files (section 6.3 of
WRITING_A_QUANT_BOOK.md): nine fields, a strat: label, the chapter's count from
the outline's bracketed number. Numbers come from firm.synthmkt, firm.synthfut
(this book's synthetic futures universe) and free public data (Kenneth French's
library as derived statistics, EIA WTI futures, CFTC reports, FRED, SEC EDGAR).

Running project (code/firm/, all new and unique; checked against the 205 existing):
  statbook (ch1)  reversal (ch2)  residarb (ch3)  pairsel (ch4)  momstrat (ch5)
  factorlib (ch6)  earnstrat (ch7)  lendsig (ch8)  flowpress (ch9)  indexevent (ch10)
  mergerarb (ch11)  structrv (ch12)  intraday (ch13)  intraml (ch14)  optsignal (ch15)
  altstrat (ch16)  newsevent (ch17)  limitmkt (ch18)  synthfut, trendfollow (ch19)
  carrystrat (ch20)  curvestrat (ch21)  xasset (ch22)  seasonal (ch23)  posisig (ch24)
  futintraday (ch25)  voltarget (ch26)  cryptomf (ch27)  multistrat (ch28)  assetmgr (ch29)
"""
SLUG = "strategies-1"
PFX = "s1"
HEAD = "One Quant Book 8 — Strategies I: Equities and Futures"

_U_BT = ["backtest (B7.16)", "vectorised backtest (B7.16)", "information coefficient (B7.6)",
         "transaction cost analysis (B7.23)", "capacity curve (B7.28)", "fundamental factor model (B7.24)"]

PARTS = [
    ("part.s1.statarb", [
        dict(slug="01-anatomy-of-a-stat-arb-book", title="Anatomy of a Stat-Arb Book",
             hook="A book holds 1,800 stocks long and 1,800 short, each position under 0.2 per cent of capital; on its best day it makes 0.4 per cent and on its worst loses 0.6, and its annual profit is the sum of three million small bets.",
             sections=["Thousands of small bets", "Neutrality: dollar, beta, sector, factor", "Financing: cash, leverage, borrow and rebates", "What public descriptions of such books say", "The daily cycle of a stat-arb book"],
             defines=["statistical arbitrage", "stat-arb book", "hard-to-borrow list", "daily P&L attribution"],
             uses=["gross exposure (B1.7)", "net exposure (B1.7)", "short sale (B1.6)", "securities lending (B1.6)", "rebate rate (B1.6)", "borrow fee (B1.6)", "leverage (B1.6)", "general collateral (B1.16)", "dollar neutrality (B7.25)", "beta neutrality (B7.25)", "factor-neutrality constraint (B7.25)", "fundamental law of active management (B7.15)", "breadth (B7.15)"],
             strategies=[],
             tutorial="Assemble a daily stat-arb book on firm.synthmkt from Book 7's reversal and momentum predictors: build it with firm.portcons, finance it (margin, borrow fees by name, rebates on short proceeds), run the daily cycle, and attribute each day's P&L to factors, specific returns, costs and financing.",
             build="`firm.statbook`: stat-arb book accounting (positions, cash, margin and leverage, borrow fees and short rebates by name, a hard-to-borrow list) with daily P&L attribution into factor, specific, cost and financing terms that adds up; Python.",
             problem="Three million small bets — named result: the share of a year's stat-arb P&L explained by factor exposures a neutral book was not supposed to have, and the financing drag as a fraction of gross alpha.",
             facts=["Khandani and Lo 2011 (as B7.28)", "Avellaneda and Lee 2010, Statistical arbitrage in the US equities market (Quantitative Finance)", "Reg T initial margin 50 per cent (12 CFR 220, eCFR)", "FINRA Rule 4210 portfolio margin (dated)", "Pedersen 2015, Efficiently Inefficient (Princeton)"]),
        dict(slug="02-short-term-reversal", title="Short-Term Reversal",
             hook="Buy yesterday's losers and sell its winners: on the synthetic market the rank IC is 0.04 and the gross Sharpe ratio above 7; after costs in the 500 most liquid names, below zero. The whole strategy lives in how it is traded.",
             sections=["Why prices reverse: paying for immediacy", "Daily reversal: raw, residual, industry-adjusted", "Intraday and overnight reversal", "Costs: where the strategy lives or dies", "The decline of reversal profits"],
             defines=["short-term reversal", "residual reversal", "industry-adjusted reversal", "overnight reversal"],
             uses=["residual return (B7.6)", "break-even cost (B7.27)", "cost-aware optimisation (B7.27)", "signal smoothing (B7.27)"] + _U_BT,
             strategies=["daily residual reversal", "intraday reversal to the close", "overnight reversal", "reversal as a liquidity-provision overlay"],
             tutorial="Measure raw, residual and industry-adjusted reversal on firm.synthmkt, then trade residual reversal with costs inside the optimiser and a fitted square-root cost model at three fund sizes; compare with the naive book of Book 7 chapter 16.",
             build="`firm.reversal`: reversal signal family (raw, residual on firm.riskmodel factors, industry-adjusted, overnight and intraday variants) and a cost-aware daily book on firm.tcost; Python.",
             problem="Seven before costs — named result: the net Sharpe ratio of residual reversal at $100m and $1bn with costs inside the optimiser, against the naive book's.",
             facts=["Jegadeesh 1990 (JF); Lehmann 1990 (QJE)", "Nagel 2012, Evaporating liquidity (RFS)", "Da, Liu, Schaumburg 2014, A closer look at the short-term return reversal (Management Science)", "Blitz, Huij, Lansdorp, Verbeek 2013 short-term residual reversal (J. Financial Markets)"]),
        dict(slug="03-residual-and-principal-component-stat-arb", title="Residual and Principal-Component Stat Arb",
             hook="Regress each stock's returns on its industry ETF and trade the residual when it drifts two standard deviations from its mean: the method is public, the parameters are everything, and the published version's returns faded after 2002.",
             sections=["Residuals against factors or principal components", "The residual as an Ornstein--Uhlenbeck process: the s-score", "Entry, exit and the mean-reversion speed filter", "Eigenportfolios and their stability", "Where the returns went"],
             defines=["s-score", "eigenportfolio", "mean-reversion speed filter"],
             uses=["Ornstein--Uhlenbeck process (B4.4)", "principal component analysis (B4.22)", "statistical factor model (B7.24)", "specific return (B7.24)", "half-life (B4.4)"] + _U_BT,
             strategies=["ETF-residual s-score strategy", "principal-component residual strategy", "industry-neutral residual book", "volume-conditioned residual strategy"],
             tutorial="Fit 60-day OU models to residuals against the chapter 24 factors and against 15 principal components on firm.synthmkt, trade s-scores with Avellaneda and Lee's thresholds, and measure the effect of the mean-reversion-speed filter and of the planted reversal's strength.",
             build="`firm.residarb`: rolling residual extraction (factor model or PCA eigenportfolios), OU fit by AR(1) regression, s-scores with thresholds and a speed filter, and the book; Python.",
             problem="The public method — named result: the Sharpe ratio of the s-score strategy with and without the speed filter, and its sensitivity to the entry threshold.",
             facts=["Avellaneda and Lee 2010 (Quantitative Finance)", "Pole 2007, Statistical Arbitrage (Wiley)", "Khandani and Lo 2011 (as B7.28)"]),
        dict(slug="04-pairs-and-baskets", title="Pairs and Baskets",
             hook="Two stocks moved together for a year; the pair opened at two standard deviations and never closed, because one of the companies was being taken over.",
             sections=["Selection: distance, cointegration, copulas", "Trading rules and the formation window", "Why pairs died, and what replaced them", "Baskets: one stock against its synthetic twin"],
             defines=["pairs trading", "distance method", "formation period", "trading period", "synthetic twin"],
             uses=["cointegration (B4.20)", "Engle--Granger test (B4.20)", "copula (B4.15)", "multiple testing (B4.12)"] + _U_BT,
             strategies=["distance-method pairs", "cointegration pairs", "copula pairs", "stock against its synthetic basket"],
             tutorial="Select pairs on firm.synthmkt by distance and by Engle--Granger tests in a formation year and trade them in the next; count the false discoveries among the tested pairs; build a synthetic-twin basket by ridge regression and compare.",
             build="`firm.pairsel`: pair selection (distance on normalised prices, Engle--Granger with multiple-testing control, a Gaussian-copula mispricing index), trading rules, synthetic-twin baskets; Python.",
             problem="The pair that never closed — named result: the share of cointegrated pairs in the formation year that stay cointegrated in the trading year, and the pairs book's Sharpe ratio after costs.",
             facts=["Gatev, Goetzmann, Rouwenhorst 2006, Pairs trading (RFS)", "Do and Faff 2010, Does simple pairs trading still work? (FAJ)", "Vidyamurthy 2004, Pairs Trading (Wiley)", "Krauss 2017 survey (J. Economic Surveys)"]),
        dict(slug="05-momentum", title="Momentum",
             hook="From March to May 2009 the US momentum factor lost more than forty per cent, as the losers it was short rebounded from the crisis lows; its long-run Sharpe ratio had looked like the steadiest in equities.",
             sections=["Cross-sectional momentum", "Residual and industry momentum", "Intraday and time-of-day momentum", "Crashes and their management", "Implementation: turnover, skipping a month, costs"],
             defines=["cross-sectional momentum", "residual momentum", "industry momentum", "momentum crash", "volatility-scaled momentum"],
             uses=["comomentum (B7.28)", "skip period (B7.7)"] + _U_BT,
             strategies=["12-1 cross-sectional momentum", "residual momentum", "industry momentum", "intraday momentum in the last half hour", "volatility-scaled momentum"],
             tutorial="Build momentum portfolios on firm.synthmkt and measure the 2009 crash in the Kenneth French momentum factor (derived statistics); scale momentum by its own recent volatility and compare drawdowns.",
             build="`firm.momstrat`: momentum variants (12-1, residual, industry, time-of-day) and crash management (volatility scaling, dynamic weighting on market state); Python.",
             problem="Spring 2009 — named result: the momentum factor's drawdown in 2009 in the French data and the drawdown of the volatility-scaled version.",
             facts=["Jegadeesh and Titman 1993 (JF)", "Daniel and Moskowitz 2016, Momentum crashes (JFE)", "Barroso and Santa-Clara 2015, Momentum has its moments (JFE)", "Blitz, Huij, Martens 2011 residual momentum (J. Empirical Finance)", "Moskowitz and Grinblatt 1999 industry momentum (JF)", "Gao, Han, Li, Zhou 2018 market intraday momentum (JFE)", "Kenneth French data library momentum factor"]),
        dict(slug="06-value-quality-and-low-risk", title="Value, Quality and Low Risk",
             hook="From 2007 to 2020 the US value factor lost about half of its cumulative gains; the same years made profitability and low-risk books look like the only ones that worked.",
             sections=["Value: book-to-price and its cousins", "Quality and profitability", "Low risk and betting against beta", "Implementation details that decide the result", "Combining the canon"],
             defines=["book-to-price ratio", "value strategy", "quality factor", "profitability factor", "low-risk anomaly", "betting against beta", "factor timing"],
             uses=["market beta (B7.22)", "leverage (B1.6)"] + _U_BT,
             strategies=["book-to-price value", "composite value", "gross profitability", "quality minus junk", "betting against beta", "low-volatility long-only"],
             tutorial="Construct value, profitability and low-risk portfolios from point-in-time fundamentals on firm.synthmkt; measure the value factor's 2007--2020 drawdown and the profitability factor in the French data (derived statistics); show how the book-to-price lag and the rebalance date change the result.",
             build="`firm.factorlib`: factor construction by characteristic sorts and by characteristic-weighted portfolios (value composites, profitability, low beta with the BAB leverage adjustment) from firm.fundpit; Python.",
             problem="The lost decade of value — named result: the value factor's drawdown from its 2007 peak in the French data, and the correlation of value and profitability returns.",
             facts=["Fama and French 1992 (JF)", "Novy-Marx 2013, The other side of value (JFE)", "Asness, Frazzini, Pedersen 2019, Quality minus junk (Review of Accounting Studies)", "Frazzini and Pedersen 2014, Betting against beta (JFE)", "Fama and French 2015 five-factor model (JFE)", "Kenneth French data library HML and RMW"]),
        dict(slug="07-earnings", title="Earnings",
             hook="Firms announcing a surprise keep drifting in its direction for sixty days; the drift was documented in 1968 and was still there, smaller, in the 2010s.",
             sections=["Post-earnings-announcement drift", "Analyst revisions", "Guidance and pre-announcements", "The announcement-day options angle", "Implementation around event dates"],
             defines=["event study", "post-earnings-announcement drift", "earnings-revision strategy", "announcement premium", "event window"],
             uses=["standardised unexpected earnings (B7.11)", "earnings surprise (B7.11)", "implied volatility (B1.25)"] + _U_BT,
             strategies=["SUE drift", "revision momentum", "announcement premium", "straddle before announcements", "pre-announcement trading"],
             tutorial="Trade the planted post-earnings drift of firm.synthmkt with point-in-time surprises: an event-time long--short book, holding periods from 5 to 60 days, and the effect of costs and of the drift's decay after chapter 13's planted break.",
             build="`firm.earnstrat`: event calendars from firm.fundpit, SUE and revision signals, event-time portfolio construction with holding windows, and the announcement premium; Python.",
             problem="Sixty days of drift — named result: the SUE book's Sharpe ratio at holding periods of 5, 20 and 60 days, and its fall after the planted break.",
             facts=["Ball and Brown 1968 (J. Accounting Research)", "Bernard and Thomas 1989 (J. Accounting Research)", "Chan, Jegadeesh, Lakonishok 1996 momentum strategies (JF)", "Savor and Wilson 2016 earnings announcements and systematic risk (JF)", "Chordia, Goyal, Sadka, Sadka, Shivakumar 2009 liquidity and PEAD (FAJ)"]),
        dict(slug="08-short-interest-borrow-and-crowding", title="Short Interest, Borrow and Crowding",
             hook="In January 2021 a stock with short interest above its float rose twenty-fold in weeks; the short sellers' crowding became the trade.",
             sections=["Short interest as a signal", "Borrow fees and utilisation", "Recalls, squeezes and the lending market's risk", "Crowded shorts"],
             defines=["borrow-fee signal", "squeeze risk", "short-crowding measure"],
             uses=["short interest (B1.16)", "days to cover (B1.16)", "utilisation (B1.16)", "recall (B1.16)", "short squeeze (B1.16)", "lendable supply (B1.16)", "borrow fee (B1.6)", "crowded trade (B7.28)"] + _U_BT,
             strategies=["high short interest avoidance", "borrow-fee signal", "days-to-cover ranking", "crowded-short risk overlay"],
             tutorial="Add a lending layer to firm.synthmkt (borrow demand from informed and uninformed shorts, fees rising with utilisation, recalls) and measure the short-interest signal, its cost after borrow fees, and the loss distribution of crowded shorts under a squeeze.",
             build="`firm.lendsig`: synthetic stock-lending market (supply, demand, fee as a function of utilisation, recalls) and short-interest and borrow-fee signals; Python.",
             problem="January 2021 — named result: the return of the high-short-interest signal before and after borrow fees, and the loss of a crowded short book in a simulated squeeze.",
             facts=["Asquith, Pathak, Ritter 2005 short interest and institutional ownership (JFE)", "Boehmer, Jones, Zhang 2008, Which shorts are informed? (JF)", "Engelberg, Reed, Ringgenberg 2018, Short-selling risk (JF)", "SEC staff report on equity and options market structure conditions in early 2021 (October 2021)", "FINRA short interest reporting (dated)"]),
        dict(slug="09-flows", title="Flows",
             hook="Mutual funds forced to sell by redemptions push their holdings down for months; a fund-flow signal built from quarterly filings predicts it.",
             sections=["Flow-driven price pressure", "Mutual-fund redemptions and fire sales", "ETF and index-fund flows", "Quarterly holdings as a signal"],
             defines=["flow-induced trading", "price pressure", "13F holdings"],
             uses=["fire sale (B3.28)", "crowding (B7.28)"] + _U_BT,
             strategies=["fire-sale reversal", "flow-induced pressure", "ETF creation-redemption flow", "holdings-overlap signal"],
             tutorial="Simulate funds on firm.synthmkt with flows chasing past performance; compute each stock's flow-induced trading from holdings, trade the predicted pressure and its reversal; read the structure of real 13F filings from EDGAR.",
             build="`firm.flowpress`: fund holdings and flow simulation, flow-induced trading per stock (Lou 2012), pressure and reversal signals; Python.",
             problem="Forced sellers — named result: the price pressure of flow-induced trading and the share that reverses within a year.",
             facts=["Coval and Stafford 2007, Asset fire sales (JFE)", "Lou 2012, A flow-based explanation for return predictability (RFS)", "Ben-David, Franzoni, Moussawi 2018 ETFs and volatility (JF)", "SEC Form 13F instructions (EDGAR)", "Gabaix and Koijen 2021 inelastic markets hypothesis (NBER)"]),
        dict(slug="10-index-rebalancing", title="Index Rebalancing",
             hook="A stock is added to a major index and rises seven per cent between the announcement and the effective date; twenty years later the same event moves it by a fraction of that, because everyone predicts it.",
             sections=["Index rules and the calendar", "Predicting additions and deletions", "Trading the event and the reversal", "How the trade decayed"],
             defines=["index fund", "rank day", "membership prediction"],
             uses=["index reconstitution (B1.15)", "index effect (B1.15)", "buffer rule (B1.15)", "call auction (B1.13)", "price pressure (ch9)"] + _U_BT,
             strategies=["predicted additions", "predicted deletions", "effective-date close liquidity provision", "post-event reversal"],
             tutorial="Write a rank-based reconstitution rule with banding for firm.synthmkt, predict membership changes from data before the rank day, simulate index-fund demand at the close, and trade predicted additions and deletions with their reversal.",
             build="`firm.indexevent`: index rules (rank day, banding, float adjustment), membership prediction with probabilities, and event-time trading with close-auction demand; Python.",
             problem="Everyone predicts it — named result: the prediction accuracy of membership changes and the event return as index-tracking demand grows relative to arbitrage capital.",
             facts=["Shleifer 1986, Do demand curves for stocks slope down? (JF)", "Harris and Gurel 1986 (JF)", "Chen, Noronha, Singal 2004 (JF)", "Patel and Welch 2017, Extended stock returns in response to S&P 500 index changes (Review of Asset Pricing Studies)", "FTSE Russell reconstitution methodology (dated)", "S&P DJI index methodology (dated)"]),
        dict(slug="11-merger-arbitrage", title="Merger Arbitrage",
             hook="A cash deal at forty dollars trades at 38.60: a 3.6 per cent spread that pays unless the deal breaks, in which case the target falls back to thirty. The spread is an insurance premium against a break.",
             sections=["Deal spreads and their pricing", "Break risk and its correlation with the market", "Stock deals and collars", "Regulatory and financing risk", "Portfolio of deals"],
             defines=["merger arbitrage", "tender offer", "deal spread", "break price", "stock-deal collar", "implied deal probability"],
             uses=["short sale (B1.6)"] + _U_BT,
             strategies=["cash-deal spread", "stock-for-stock hedged spread", "collar deals", "diversified deal portfolio"],
             tutorial="Price deal spreads with a completion probability and a break price, simulate a portfolio of deals whose breaks cluster in market downturns, and measure its payoff against the market (a short put, as the literature found).",
             build="`firm.mergerarb`: deal-spread model (cash, stock and collar terms, implied completion probability), deal portfolio simulation with market-dependent breaks; Python.",
             problem="Selling insurance — named result: the portfolio's beta in down and up markets and its implied completion probability against realised completion.",
             facts=["Mitchell and Pulvino 2001, Characteristics of risk and return in risk arbitrage (JF)", "Baker and Savasoglu 2002 limited arbitrage in mergers and acquisitions (JFE)", "Hart-Scott-Rodino waiting period (FTC, dated)", "a documented broken deal from public filings (SEC EDGAR)"]),
        dict(slug="12-share-classes-holding-companies-closed-end-funds-spacs", title="Share Classes, Holding Companies, Closed-End Funds, Blank-Cheque Companies",
             hook="A closed-end fund holds a hundred million dollars of listed stocks and trades at eighty-five million: the discount has lasted for years, and closing it requires someone to force the issue.",
             sections=["Dual share classes", "Holding-company discounts", "Closed-end fund discounts", "Blank-cheque companies and their trust value", "Structural relative value, in general"],
             defines=["dual-class share", "holding-company discount", "closed-end fund discount", "special purpose acquisition company", "trust value"],
             uses=["net asset value (B1.14)", "mean reversion (B4.4)"] + _U_BT,
             strategies=["share-class spread", "holding-company discount trade", "closed-end fund discount mean reversion", "activist-catalyst discount trade", "SPAC trust-value floor"],
             tutorial="Model a closed-end fund discount as a mean-reverting process with catalyst jumps and a SPAC's payoff as a trust-value floor plus a call on the deal, and simulate the structural trades' returns and their tails.",
             build="`firm.structrv`: structural relative-value tools (class spreads, NAV discounts with mean reversion and catalysts, SPAC trust value with redemption option); Python.",
             problem="Eighty-five cents on the dollar — named result: the expected return and the time to close of a discount trade with and without a catalyst.",
             facts=["Lee, Shleifer, Thaler 1991, Investor sentiment and the closed-end fund puzzle (JF)", "Pontiff 1996 costly arbitrage: closed-end funds (QJE)", "Klausner, Ohlrogge, Ruan 2022 a sober look at SPACs (Yale J. on Regulation)", "SEC SPAC rules of January 2024 (dated)"]),
        dict(slug="13-intraday-patterns", title="Intraday Patterns",
             hook="Since 1993 most of the US market's return has come overnight: from the close to the open, while the exchanges are closed.",
             sections=["Overnight versus intraday returns", "The volume smile and the auctions", "End-of-day hedging flows", "Close imbalances"],
             defines=["overnight return", "intraday return", "volume smile", "end-of-day hedging flow"],
             uses=["call auction (B1.13)", "order imbalance (B1.13)", "closing price (B1.13)", "gamma (B1.26)"] + _U_BT,
             strategies=["overnight drift", "last-half-hour momentum", "close imbalance reversal", "hedging-flow timing", "open-auction reversal"],
             tutorial="Measure overnight and intraday returns in firm.tape sessions and in derived statistics of public index data, simulate end-of-day hedging flow from a short-gamma dealer book and its footprint on the last half hour.",
             build="`firm.intraday`: intraday return decomposition, volume curves, close-imbalance signals and a dealer-hedging flow model; Python.",
             problem="The market makes its money at night — named result: the share of the cumulative return earned overnight and the last-half-hour predictability with and without hedging flow.",
             facts=["Cliff, Cooper, Gulen 2008 return differences between trading and non-trading hours (working paper)", "Lou, Polk, Skouras 2019, A tug of war: overnight versus intraday expected returns (JFE)", "Baltussen, Da, Lammers, Martens 2021 hedging demand and market intraday momentum (JFE)", "Nasdaq closing cross documentation (dated)"]),
        dict(slug="14-intraday-machine-learned-alphas", title="Intraday Machine-Learned Alphas",
             hook="A gradient-boosted model on order-book features predicts the next thirty seconds with an R-squared of one per cent; that is enough to pay the spread only if execution is part of the model.",
             sections=["Targets and horizons", "Features from the book and the tape", "Models and their validation", "Coupling the alpha to execution"],
             defines=["intraday alpha", "prediction horizon", "execution coupling"],
             uses=["order-flow imbalance (B7.8)", "microprice (B7.8)", "purging (B7.20)", "embargo (B7.20)", "mark-out curve (B7.23)"] + _U_BT,
             strategies=["book-imbalance alpha", "trade-flow alpha", "cross-asset lead alpha", "alpha-driven execution"],
             tutorial="Train linear and tree models on firm.tape order-book features for 5-, 30- and 120-second mid returns with purged cross-validation, then trade them through the chapter 18 replay with and without passive execution.",
             build="`firm.intraml`: feature matrices from firm.lobfeat and firm.tradeflow, horizon targets, purged walk-forward training (ridge and a small gradient-boosted tree ensemble in NumPy), and alpha-driven order placement; Python.",
             problem="One per cent is a lot — named result: out-of-sample R-squared by horizon and the P&L per share after the spread, aggressive against passive.",
             facts=["Cont, Kukanov, Stoikov 2014 (J. Financial Econometrics)", "Kolm, Turiel, Westray 2023, Deep order flow imbalance (Mathematical Finance)", "Sirignano and Cont 2019 universal features of price formation (Quantitative Finance)", "Friedman 2001 gradient boosting (Annals of Statistics)"]),
        dict(slug="15-options-implied-signals-for-stocks", title="Options-Implied Signals for Stocks",
             hook="When a stock's out-of-the-money puts become expensive relative to its calls, the stock underperforms over the next weeks: someone is buying protection who knows something.",
             sections=["Skew as a signal", "Implied minus realised volatility", "Option volume and the put--call ratio", "Where informed traders trade"],
             defines=["implied volatility spread", "option-to-stock volume ratio", "put--call ratio", "informed options trading"],
             uses=["implied volatility (B1.25)", "volatility skew (B1.25)"] + _U_BT,
             strategies=["skew signal", "implied-volatility spread signal", "option volume signal", "implied-minus-realised volatility signal"],
             tutorial="Add an options layer to firm.synthmkt in which informed traders buy puts or calls ahead of planted news, compute skew, volatility spread and option-volume signals, and measure their predictive power for the stock.",
             build="`firm.optsignal`: synthetic option-market layer (implied volatilities with informed demand), skew, put--call volatility spread and volume signals; Python.",
             problem="Someone is buying protection — named result: the IC of the skew and volatility-spread signals and their decay with horizon.",
             facts=["Xing, Zhang, Zhao 2010, What does the individual option volatility smirk tell us? (JFQA)", "Cremers and Weinbaum 2010 deviations from put--call parity (JFQA)", "Pan and Poteshman 2006 information in option volume (RFS)", "Johnson and So 2012 option-to-stock volume ratio (JFE)"]),
        dict(slug="16-alternative-data-strategies", title="Alternative-Data Strategies",
             hook="Satellite counts of cars in retailers' car parks predicted their revenue surprises; by the time the data were sold widely, the prices already knew.",
             sections=["From dataset to position", "What has been documented to work", "Decay as the data spread", "Operating an alternative-data strategy"],
             defines=["nowcast", "data decay", "alternative-data strategy"],
             uses=["alternative data (B7.12)", "backfill bias (B7.3)", "earnings surprise (B7.11)", "post-publication decay (B7.13)"] + _U_BT,
             strategies=["revenue nowcast trade", "web-traffic signal", "sentiment signal", "supply-chain linkage signal"],
             tutorial="Take Book 7 chapter 12's synthetic card-panel through to a strategy: a revenue nowcast, trades ahead of announcements, and the decay of its IC as a growing share of the market buys the same data.",
             build="`firm.altstrat`: nowcast models for fundamentals from alternative panels, pre-announcement positions, and a data-diffusion model of decay; Python.",
             problem="By the time it is sold — named result: the nowcast strategy's Sharpe ratio as the share of informed capital using the data grows.",
             facts=["Zhu 2019, Big data as a governance mechanism (RFS)", "Katona, Painter, Patatoukas, Zeng 2025 satellite car counts (JFQA)", "Cohen and Frazzini 2008 economic links (JF)", "Green, Huang, Wen, Zhou 2019 crowdsourced employer reviews (JFE)"]),
        dict(slug="17-news-and-events", title="News and Events",
             hook="A headline arrives at 10:32:07; machines trade on it in milliseconds, and the price's move is over before a person has read the first sentence.",
             sections=["Machine-readable news", "Scheduled events", "Unscheduled events and halts", "Reaction speed and who captures the move"],
             defines=["machine-readable news", "trading halt", "news reaction window"],
             uses=["event study (ch7)", "limit up--limit down (B1.31)"] + _U_BT,
             strategies=["headline sentiment", "scheduled-event drift", "post-halt reopening", "underreaction to low-attention news"],
             tutorial="Generate a synthetic news stream with planted tone and attention on firm.synthmkt, measure the reaction by latency bucket, and trade the drift left for slower traders; model halts and reopening auctions.",
             build="`firm.newsevent`: synthetic news stream (timestamps, tone, relevance, attention), event-time reaction by latency, and halt/reopen handling; Python.",
             problem="Before a person reads it — named result: the share of the news move captured at each latency, and the drift left for a daily trader.",
             facts=["Tetlock 2007 (JF)", "Tetlock, Saar-Tsechansky, Macskassy 2008 (JF)", "Hirshleifer, Lim, Teoh 2009 driven to distraction (JF)", "SEC and FINRA trading halt rules (dated)"]),
        dict(slug="18-asia-specific-equity-strategies", title="Asia-Specific Equity Strategies",
             hook="A Shanghai stock hits its ten per cent limit up at 10:05 and stays there all day; tomorrow it opens higher, because the buyers who could not trade today are still there.",
             sections=["Price limits and T+1 settlement", "Retail-dominated markets", "Connect flows"],
             defines=["limit-hit continuation", "magnet effect", "northbound flow"],
             uses=["price limit (B1.12)", "Stock Connect (B1.12)", "settlement cycle (B1.5)", "market-wide circuit breaker (B1.31)"] + _U_BT,
             strategies=["limit-hit continuation", "retail-attention reversal", "northbound-flow signal"],
             tutorial="Simulate a market with price limits and T+1 on firm.synthmkt's shocks, measure continuation after limit hits and the magnet effect near the limit, and study a foreign-flow signal.",
             build="`firm.limitmkt`: a price-limit and T+1 market layer (limit locks, delayed trading, magnet effect) and signals built on it; Python.",
             problem="Locked limit up — named result: the next-day return after a limit-up lock and how it changes with the limit's width.",
             facts=["Chen, Gao, He, Jiang, Xiong 2019 daily price limits and destructive market behavior (J. Econometrics)", "Shanghai Stock Exchange trading rules (dated)", "HKEX Stock Connect documentation (dated)", "Seasholes and Wu 2007 predictable behavior at price limits (J. Empirical Finance)"]),
    ]),
    ("part.s1.futures", [
        dict(slug="19-trend-following", title="Trend Following",
             hook="Over a century of futures data, a simple rule — long what went up over the last year, short what went down, sized by volatility — earned a positive return in almost every decade, and its best years were the worst years of stocks.",
             sections=["Signal families: moving averages, breakouts, returns", "A portfolio of trends", "Volatility scaling", "The long record and crisis alpha", "The recent decade"],
             defines=["trend following", "time-series momentum", "breakout rule", "crisis alpha", "volatility targeting"],
             uses=["moving-average crossover (B7.7)", "continuous futures series (B7.2)", "backtest overfitting (B7.20)", "cross-sectional momentum (ch5)"] + _U_BT,
             strategies=["time-series momentum", "moving-average crossover portfolio", "breakout system", "multi-speed trend blend", "volatility-scaled trend portfolio", "trend on WTI crude futures"],
             tutorial="Build firm.synthfut, a synthetic universe of 40 futures in four asset classes with planted persistent drifts, carry, seasonality, volatility clustering and a stock crash; run trend portfolios of several speeds, volatility-scaled, and measure crisis alpha; run the same rules on the EIA WTI series.",
             build="`firm.synthfut` (synthetic futures universe: contracts with expiries and curves, spot and carry, persistent drifts, seasonal commodities, crash episodes; deterministic) and `firm.trendfollow` (signal families, risk parity across markets, volatility scaling, portfolio of speeds); Python.",
             problem="Crisis alpha — named result: the trend portfolio's return in the simulated stock crash and its Sharpe ratio across speeds.",
             facts=["Moskowitz, Ooi, Pedersen 2012, Time series momentum (JFE)", "Hurst, Ooi, Pedersen 2017, A century of evidence on trend-following investing (JPM)", "Baltas and Kosowski 2020 demystifying time-series momentum strategies (working paper)", "EIA WTI futures data (as B3)"]),
        dict(slug="20-carry-across-asset-classes", title="Carry Across Asset Classes",
             hook="Borrow in yen, lend in Australian dollars: the carry trade paid for years, and gave back three years of gains in the autumn of 2008.",
             sections=["Carry defined everywhere", "Currencies, bonds, commodities, equity indices", "Carry crashes", "A diversified carry book"],
             defines=["carry strategy", "carry crash", "diversified carry"],
             uses=["carry (B1.7)", "roll yield (B3.10)", "forward points (B2.16)"] + _U_BT,
             strategies=["currency carry", "bond carry and roll-down", "commodity roll-yield carry", "equity index dividend carry", "diversified carry portfolio"],
             tutorial="Define carry as the futures return with prices unchanged in each asset class of firm.synthfut, build carry portfolios per class and combined, and measure crashes and their correlation with the stock crash; compute WTI carry from the EIA curve.",
             build="`firm.carrystrat`: carry per asset class from futures curves (forward discount, roll-down, roll yield, dividend carry), carry portfolios and crash diagnostics; Python.",
             problem="Autumn 2008 — named result: the diversified carry book's Sharpe ratio and its loss in the crash, against each class alone.",
             facts=["Koijen, Moskowitz, Pedersen, Vrugt 2018, Carry (JFE)", "Brunnermeier, Nagel, Pedersen 2008, Carry trades and currency crashes (NBER Macro Annual)", "Lustig, Roussanov, Verdelhan 2011 (RFS)", "Bank for International Settlements on the 2008 yen carry unwind (dated)"]),
        dict(slug="21-calendar-spreads-and-curve-trades", title="Calendar Spreads and Curve Trades",
             hook="The front-month WTI contract settled at minus thirty-seven dollars on 20 April 2020; the next month traded above twenty. A spread trade that looked safe for twenty years met a storage limit.",
             sections=["Trading the shape of a futures curve", "Mean reversion of spreads", "Storage limits and the 2020 negative price", "Curve trades in rates and volatility futures"],
             defines=["curve trade", "spread mean reversion", "storage-limit risk"],
             uses=["calendar spread (B1.19)", "contango (B1.21)", "backwardation (B1.21)", "convenience yield (B3.10)"] + _U_BT,
             strategies=["front-second spread mean reversion", "curve steepener in commodity futures", "roll-period calendar spread", "volatility futures curve trade"],
             tutorial="Measure the WTI 1--2 spread's persistence in the EIA data, trade its mean reversion, and show what April 2020 did; build curve trades on firm.synthfut curves.",
             build="`firm.curvestrat`: spread construction from futures curves, mean-reversion signals with regime filters, and curve trades; Python.",
             problem="Minus thirty-seven — named result: the spread strategy's Sharpe ratio before 2020 and its loss in April 2020.",
             facts=["EIA WTI futures c1-c4 (as B3)", "CFTC interim staff report on 20 April 2020 WTI (November 2020)", "Gorton, Hayashi, Rouwenhorst 2013 fundamentals of commodity futures returns (Review of Finance)"]),
        dict(slug="22-cross-asset-lead-lag", title="Cross-Asset Lead-Lag",
             hook="Bond futures react to a surprise in the payrolls report within a second; small-cap stocks take days. The information is the same.",
             sections=["Intermarket signals at daily horizons", "Intraday lead-lag between futures", "Slow diffusion and who is slow", "Trading it"],
             defines=["intermarket signal", "slow diffusion"],
             uses=["lead--lag relationship (B7.10)", "lead--lag estimator (B7.10)", "futures-to-cash lead (B7.10)", "Hayashi--Yoshida estimator (B4.21)"] + _U_BT,
             strategies=["bond-to-equity signal", "commodity-to-producer signal", "futures-to-cash intraday lead", "currency-to-exporter signal"],
             tutorial="Plant diffusion lags between firm.synthfut markets and firm.synthmkt industries, detect them with Book 7's lead-lag tools, and trade intermarket signals at daily and intraday horizons.",
             build="`firm.xasset`: intermarket signal construction on firm.leadlag, with lag estimation, stability tests and portfolio construction; Python.",
             problem="Same information, different speeds — named result: the lead detected at each horizon and the strategy's Sharpe ratio after costs.",
             facts=["Hong, Torous, Valkanov 2007, Do industries lead stock markets? (JFE)", "Menzly and Ozbas 2010 market segmentation and cross-predictability (JF)", "Hou 2007 industry information diffusion (RFS)"]),
        dict(slug="23-seasonality-and-calendar-effects", title="Seasonality and Calendar Effects",
             hook="Hundreds of calendar effects have been published; a handful survive out of sample, and they are the ones with a reason.",
             sections=["Commodity seasonality with a physical reason", "Turn-of-the-month and holiday effects", "Same-month seasonality in stock returns", "What survives out of sample"],
             defines=["calendar effect", "turn-of-the-month effect", "return seasonality"],
             uses=["multiple testing (B4.12)", "deflated Sharpe ratio (B4.12)"] + _U_BT,
             strategies=["natural-gas seasonal spread", "turn-of-the-month", "same-calendar-month seasonality", "pre-holiday effect"],
             tutorial="Test a hundred calendar rules on firm.synthfut and firm.synthmkt, of which a few are planted with a mechanism, and show which the multiple-testing corrections keep; measure seasonal patterns in the EIA natural-gas and WTI series.",
             build="`firm.seasonal`: calendar-rule generator and tester with multiple-testing control, seasonal decomposition of futures curves; Python.",
             problem="A handful survive — named result: the planted effects found and the false discoveries at each correction.",
             facts=["Heston and Sadka 2008, Seasonality in the cross-section of stock returns (JFE)", "Lakonishok and Smidt 1988 (RFS)", "Ariel 1987 monthly effect (JFE)", "Sullivan, Timmermann, White 2001 dangers of data mining: calendar effects (J. Econometrics)", "EIA natural gas data (as B3)"]),
        dict(slug="24-positioning-and-sentiment", title="Positioning and Sentiment",
             hook="When speculators are at record long positions in a commodity, the next quarter's return is lower on average; the report that shows it is public every Friday.",
             sections=["Positioning reports", "Surveys and sentiment indices", "Options positioning"],
             defines=["positioning signal", "sentiment index", "hedging pressure"],
             uses=["Commitments of Traders report (B3.9)", "managed money (B3.9)", "put--call ratio (ch15)"] + _U_BT,
             strategies=["hedging-pressure signal", "extreme-positioning contrarian", "options-positioning signal"],
             tutorial="Measure the CFTC corn positioning series from Book 3 as a signal for futures returns, simulate hedging pressure in firm.synthfut, and test contrarian positioning rules with Book 7's tools.",
             build="`firm.posisig`: positioning and sentiment signals from COT data (on firm.cot) and synthetic positioning, with publication lags; Python.",
             problem="Record long — named result: the IC of the positioning signal and the effect of the Tuesday-to-Friday publication lag.",
             facts=["de Roon, Nijman, Veld 2000 hedging pressure (JF)", "Bessembinder 1992 (RFS)", "CFTC COT explanatory notes (dated)", "Baker and Wurgler 2006 investor sentiment (JF)"]),
        dict(slug="25-short-term-futures-strategies", title="Short-Term Futures Strategies",
             hook="On days with a scheduled macro announcement, the S&P futures drift upward in the hours before it; the drift was documented, then partly traded away.",
             sections=["Intraday mean reversion and momentum", "Opening ranges", "The pre-announcement drift", "Execution at short horizons"],
             defines=["opening range breakout", "pre-announcement drift", "intraday mean reversion"],
             uses=["market impact (B7.18)", "mark-out curve (B7.23)"] + _U_BT,
             strategies=["opening range breakout", "intraday futures mean reversion", "pre-FOMC drift", "post-announcement momentum", "overnight gap fade"],
             tutorial="Simulate futures sessions with firm.tape (a scheduled announcement with a planted pre-drift, opening volatility) and test opening-range, mean-reversion and announcement strategies with the level-2 backtester.",
             build="`firm.futintraday`: intraday futures strategy toolkit (opening ranges, gap statistics, announcement windows) on firm.tape and firm.evbt; Python.",
             problem="Before the announcement — named result: the pre-announcement drift's Sharpe ratio before and after the planted crowding.",
             facts=["Lucca and Moench 2015, The pre-FOMC announcement drift (JF)", "Crabb, Holt, Kirkpatrick 2014 opening range breakout (J. of Trading)", "Federal Reserve FOMC calendar (dated)"]),
        dict(slug="26-volatility-targeting-and-risk-managed-portfolios", title="Volatility Targeting and Risk-Managed Portfolios",
             hook="When volatility spikes, trillions of dollars of volatility-targeting funds sell at the same time; the selling is mechanical, predictable, and part of the spike.",
             sections=["The mechanics of volatility targeting", "Does it improve the Sharpe ratio?", "The industry's footprint"],
             defines=["volatility-managed portfolio", "leverage rebalancing flow"],
             uses=["volatility targeting (ch19)", "EWMA volatility (B4.18)", "risk parity (B7.26)"] + _U_BT,
             strategies=["volatility-managed equity", "volatility-targeted multi-asset", "trading against deleveraging flow"],
             tutorial="Apply volatility targeting to the firm.synthmkt market and firm.synthfut portfolios, measure Sharpe and drawdown effects, and simulate the aggregate selling of many targeting funds after a volatility spike and its price impact.",
             build="`firm.voltarget`: volatility forecasting and targeting with leverage caps and rebalancing bands, and an aggregate-flow simulator for many targeting funds; Python.",
             problem="Mechanical selling — named result: the Sharpe improvement from volatility management and the aggregate flow as a fraction of volume after a spike.",
             facts=["Moreira and Muir 2017, Volatility-managed portfolios (JF)", "Cederburg, O'Doherty, Wang, Yan 2020 on the performance of volatility-managed portfolios (JFE)", "Harvey, Hoyle, Korgaonkar, Rattray, Sargaison, van Hemert 2018 impact of volatility targeting (JPM)"]),
        dict(slug="27-crypto-medium-frequency-strategies", title="Crypto Medium-Frequency Strategies",
             hook="In 2021 the Bitcoin perpetual paid longs' funding to shorts at thirty per cent a year; a book long spot and short the perpetual collected it, until the exchange it traded on failed.",
             sections=["Funding and basis carry", "Cross-sectional momentum in coins", "On-chain data signals", "Venue and custody risk"],
             defines=["funding carry", "basis carry", "on-chain signal", "venue risk"],
             uses=["perpetual future (B3.17)", "funding rate (B3.17)", "cash-and-carry trade (B3.10)", "funding arbitrage (B3.17)"] + _U_BT,
             strategies=["perpetual funding carry", "dated-futures basis carry", "coin cross-sectional momentum", "on-chain flow signal", "funding-rate mean reversion", "venue-diversified carry"],
             tutorial="Measure funding-carry returns from Book 3's Binance funding statistics, simulate a coin universe with momentum and venue failures, and size a carry book across venues with a failure probability.",
             build="`firm.cryptomf`: funding and basis carry accounting, coin cross-sectional momentum, on-chain signal scaffolding and venue-failure risk; Python.",
             problem="Until the exchange failed — named result: the funding carry's yearly return and the venue-diversified book's loss when one venue fails.",
             facts=["Binance funding statistics (as B3)", "Liu and Tsyvinski 2021, Risks and returns of cryptocurrency (RFS)", "Liu, Tsyvinski, Wu 2022 common risk factors in cryptocurrency (JF)", "FTX bankruptcy filings (as B3)", "Schmeling, Schrimpf, Todorov 2023 crypto carry (BIS working paper)"]),
    ]),
    ("part.s1.running", [
        dict(slug="28-running-a-multi-strategy-book", title="Running a Multi-Strategy Book",
             hook="A multi-strategy firm runs forty teams; in a bad month five of them lose at once, because three of their books were the same trade under different names.",
             sections=["Allocation across strategies", "Netting and shared risk", "Turning strategies off", "Capital, drawdown limits and the pod model"],
             defines=["multi-strategy book", "pod", "drawdown limit", "strategy correlation"],
             uses=["risk budgeting (B7.26)", "internal crossing (B7.27)", "capacity curve (B7.28)", "deflated Sharpe ratio (B4.12)"],
             strategies=[],
             tutorial="Run ten of this book's strategies together on the synthetic markets: allocate by risk budgets, net their trades, apply drawdown limits and stop rules, and measure the hidden overlap and the cost of stopping too early and too late.",
             build="`firm.multistrat`: multi-strategy allocation (risk budgets, correlation-aware sizing), netting on firm.tcost, drawdown limits and stop rules with their false-stop rates; Python.",
             problem="Five at once — named result: the firm's drawdown with and without overlap detection, and the false-stop rate of a 5 per cent drawdown limit.",
             facts=["Pedersen 2015 (as ch1)", "Grossman and Zhou 1993 optimal investment strategies for controlling drawdowns (Mathematical Finance)", "public descriptions of the pod model (dated)"]),
        dict(slug="29-the-asset-managers-strategies", title="The Asset Manager's Strategies",
             hook="An index fund charging three basis points tracks its benchmark to within one basis point a year; its manager's craft is invisible when it works.",
             sections=["Indexing: replication and sampling", "Factor products", "Benchmark-relative management", "Transition management"],
             defines=["full replication", "sampled replication", "factor product", "transition management"],
             uses=["tracking error (B1.3)", "information ratio (B1.3)", "index fund (ch10)", "implementation shortfall (B7.19)"],
             strategies=[],
             tutorial="Replicate a cap-weighted index of firm.synthmkt fully and by sampling with a risk-model optimiser, measure tracking error and costs, build a factor product, and plan a portfolio transition that minimises shortfall.",
             build="`firm.assetmgr`: index replication (full and sampled via firm.portcons), tracking-error budgeting, factor-product construction and a transition planner; Python.",
             problem="Invisible craft — named result: the tracking error of sampled replication against the number of names held, and the transition's shortfall.",
             facts=["Frino and Gallagher 2001 tracking S&P 500 index funds (J. Portfolio Management)", "SEC Form N-1A tracking disclosures (dated)", "Grinold and Kahn 2000 Active Portfolio Management (McGraw-Hill)"]),
    ]),
]
