"""firm.wirecodec generator (build of One Quant Book 13, chapter 16).

One schema, several codecs, no hand-written layout:
  1. code/firm/exchsim/schema.json (Book 10's simulator, big-endian)  ->  cpp/firm_wirecodec.hpp and
     rust/src/generated.rs: flyweights over the wire bytes, a reader and a writer per message, and a dispatcher.
  2. the same feed messages  ->  sbe/feed_sbe.xml, an SBE-style message schema (little-endian, 8-byte SBE message
     header, natural field sizes: u48 widened to u64);
  3. sbe/feed_sbe.xml  ->  cpp/firm_wirecodec_sbe.hpp: little-endian flyweights generated from the XML alone.
The generated files are committed; the tests regenerate them and require no difference.

    python gen_wirecodec.py            write every generated file
    python gen_wirecodec.py --check    exit 1 if any generated file differs from what the generator writes
"""
import json
import pathlib
import sys
import xml.etree.ElementTree as ET

HERE = pathlib.Path(__file__).resolve().parent
SCHEMA = HERE.parent / "exchsim" / "schema.json"
PROTOS = ("feed", "in", "out", "ctl")
INT = {"u16": ("std::uint16_t", "u16", 2), "u32": ("std::uint32_t", "u32", 4), "u48": ("std::uint64_t", "u64", 6),
       "u64": ("std::uint64_t", "u64", 8), "i64": ("std::int64_t", "i64", 8)}
SBE_TYPES = {"char": ("char", 1), "u16": ("uint16", 2), "u32": ("uint32", 4), "u48": ("uint64", 8),
             "u64": ("uint64", 8), "i64": ("int64", 8)}
SBE_CPP = {"uint16": "std::uint16_t", "uint32": "std::uint32_t", "uint64": "std::uint64_t", "int64": "std::int64_t"}
HEADER = "// GENERATED by code/firm/wirecodec/gen_wirecodec.py from {src}: do not edit.\n"


def schema():
    return json.loads(SCHEMA.read_text())


def cname(proto, typ):
    return f"{proto.capitalize()}{typ}"


def cpp_be(s):
    out = [HEADER.format(src="code/firm/exchsim/schema.json"),
           "// Big-endian flyweights over the simulator's wire formats (PROTOCOL.md): a reader holds a pointer to a\n"
           "// message and decodes a field only when it is asked for; a writer encodes fields in place. No copy, no\n"
           "// allocation, no virtual call.\n",
           "#pragma once\n#include <cstddef>\n#include <cstdint>\n#include <cstring>\n#include <string>\n"
           "#include <string_view>\n\n",
           "namespace firm::wire {\n\n",
           "// Text of a fixed-width field without its padding (for tests and tools, not the hot path).\n"
           "inline std::string trimmed(std::string_view v) {\n"
           "    while (!v.empty() && v.back() == ' ') v.remove_suffix(1);\n"
           "    return std::string(v);\n}\n\n",
           "inline std::uint64_t be(const std::uint8_t* p, std::size_t n) {\n"
           "    std::uint64_t v = 0;\n    std::memcpy(reinterpret_cast<std::uint8_t*>(&v) + 8 - n, p, n);\n"
           "    return __builtin_bswap64(v);\n}\n",
           "inline void put_be(std::uint8_t* p, std::uint64_t v, std::size_t n) {\n"
           "    v = __builtin_bswap64(v);\n"
           "    std::memcpy(p, reinterpret_cast<const std::uint8_t*>(&v) + 8 - n, n);\n}\n",
           "// Fixed-width text, left-justified and space-padded.\n"
           "inline void put_text(std::uint8_t* p, std::string_view v, std::size_t n) {\n"
           "    const std::size_t k = v.size() < n ? v.size() : n;\n    std::memcpy(p, v.data(), k);\n"
           "    std::memset(p + k, ' ', n - k);\n}\n",
           "inline std::uint16_t be16(const std::uint8_t* p) { std::uint16_t v; std::memcpy(&v, p, 2); "
           "return __builtin_bswap16(v); }\n",
           "inline std::uint32_t be32(const std::uint8_t* p) { std::uint32_t v; std::memcpy(&v, p, 4); "
           "return __builtin_bswap32(v); }\n",
           "inline std::uint64_t be64(const std::uint8_t* p) { std::uint64_t v; std::memcpy(&v, p, 8); "
           "return __builtin_bswap64(v); }\n\n"]
    getters = {2: "be16(p + {o})", 4: "be32(p + {o})", 8: "be64(p + {o})", 6: "be(p + {o}, 6)"}
    for proto in PROTOS:
        for typ, m in s["protocols"][proto].items():
            n, L = cname(proto, typ), m["length"]
            out.append(f"// {proto} {typ}: {L} bytes\nstruct {n} {{\n"
                       f"    static constexpr char kType = '{typ}';\n    static constexpr std::size_t kLength = {L};\n"
                       "    const std::uint8_t* p;\n")
            w = [f"struct {n}Writer {{\n    std::uint8_t* p;\n"
                 f"    explicit {n}Writer(std::uint8_t* q) : p(q) {{ std::memset(p, 0, {L}); p[0] = '{typ}'; }}\n"]
            for f in m["fields"][1:]:
                o, ty, nm = f["offset"], f["type"], f["name"]
                if ty in INT:
                    ct, _, ln = INT[ty]
                    g = getters[ln].format(o=o)
                    cast = g if ct == "std::uint64_t" else f"static_cast<{ct}>({g})"
                    out.append(f"    {ct} {nm}() const {{ return {cast}; }}\n")
                    w.append(f"    {n}Writer& {nm}({ct} v) {{ put_be(p + {o}, static_cast<std::uint64_t>(v), {ln}); "
                             "return *this; }\n")
                elif ty == "char":
                    out.append(f"    char {nm}() const {{ return static_cast<char>(p[{o}]); }}\n")
                    w.append(f"    {n}Writer& {nm}(char v) {{ p[{o}] = static_cast<std::uint8_t>(v); "
                             "return *this; }\n")
                else:                                          # alphaN, numN: fixed text
                    ln = f["length"]
                    out.append(f"    std::string_view {nm}() const {{ return {{reinterpret_cast<const char*>(p + {o}), "
                               f"{ln}}}; }}\n")
                    w.append(f"    {n}Writer& {nm}(std::string_view v) {{ put_text(p + {o}, v, {ln}); "
                             "return *this; }\n")
            out.append("};\n")
            out.extend(w)
            out.append("};\n")
            out.append(cpp_extras(n, m))
        out.append(f"// Calls v(<{proto} message>) for one message of the {proto} protocol; false if the type is\n"
                   f"// unknown or the length does not match it.\ntemplate <class V>\n"
                   f"bool dispatch_{proto}(const std::uint8_t* p, std::size_t n, V&& v) {{\n"
                   "    if (n == 0) return false;\n    switch (p[0]) {\n")
        for typ in s["protocols"][proto]:
            nm = cname(proto, typ)
            out.append(f"        case '{typ}': if (n != {nm}::kLength) return false; v({nm}{{p}}); return true;\n")
        out.append("        default: return false;\n    }\n}\n\n")
    out.append("// MoldUDP64 packet header: session alpha10, sequence number of the first message u64, count u16.\n"
               "struct MoldHeader {\n    static constexpr std::size_t kLength = 20;\n    const std::uint8_t* p;\n"
               "    std::string_view session() const { return {reinterpret_cast<const char*>(p), 10}; }\n"
               "    std::uint64_t seq() const { return be64(p + 10); }\n"
               "    std::uint16_t count() const { return be16(p + 18); }\n};\n\n"
               "// Calls f(message pointer, length) for each message block of a packet; false if the packet is short.\n"
               "template <class F>\nbool for_each_block(const std::uint8_t* p, std::size_t n, F&& f) {\n"
               "    if (n < MoldHeader::kLength) return false;\n    const std::uint16_t c = MoldHeader{p}.count();\n"
               "    if (c == 0 || c == 0xFFFF) return true;\n    std::size_t i = MoldHeader::kLength;\n"
               "    for (std::uint16_t k = 0; k < c; ++k) {\n        if (i + 2 > n) return false;\n"
               "        const std::size_t len = be16(p + i);\n        if (i + 2 + len > n) return false;\n"
               "        f(p + i + 2, len);\n        i += 2 + len;\n    }\n    return true;\n}\n\n"
               "}  // namespace firm::wire\n")
    return "".join(out)


def cpp_extras(n, m):
    """csv(): the fields in schema order as the golden CSVs print them; rewrite(): the message encoded again."""
    parts, sets = [], []
    for f in m["fields"][1:]:
        nm, ty = f["name"], f["type"]
        if ty in INT:
            parts.append(f"std::to_string(m.{nm}())")
        elif ty == "char":
            parts.append(f"std::string(1, m.{nm}())")
        else:
            parts.append(f"trimmed(m.{nm}())")
        sets.append(f".{nm}(m.{nm}())")
    body = ' + "," + '.join(parts)
    return (f"inline std::string csv(const {n}& m) {{ return {body}; }}\n"
            f"inline void rewrite(const {n}& m, std::uint8_t* out) {{ {n}Writer(out){''.join(sets)}; }}\n\n")


def rust_be(s):
    out = [HEADER.format(src="code/firm/exchsim/schema.json"),
           "//! Big-endian flyweights over the simulator's wire formats, the twin of firm_wirecodec.hpp.\n\n",
           "#[inline]\nfn be(b: &[u8], o: usize, n: usize) -> u64 {\n    let mut v = [0u8; 8];\n"
           "    v[8 - n..].copy_from_slice(&b[o..o + n]);\n    u64::from_be_bytes(v)\n}\n\n"]
    for proto in PROTOS:
        for typ, m in s["protocols"][proto].items():
            n, L = cname(proto, typ), m["length"]
            out.append(f"/// {proto} {typ}: {L} bytes\n#[derive(Clone, Copy)]\npub struct {n}<'a>(pub &'a [u8]);\n\n"
                       f"impl<'a> {n}<'a> {{\n    pub const TYPE: u8 = b'{typ}';\n    pub const LENGTH: usize = {L};\n")
            for f in m["fields"][1:]:
                o, ty, nm = f["offset"], f["type"], f["name"]
                nm_r = "r#match" if nm == "match" else ("r#ref" if nm == "ref" else nm)
                if ty in INT:
                    _, rt, ln = INT[ty]
                    out.append(f"    pub fn {nm_r}(&self) -> {rt} {{\n        be(self.0, {o}, {ln}) as {rt}\n    }}\n")
                elif ty == "char":
                    out.append(f"    pub fn {nm_r}(&self) -> u8 {{\n        self.0[{o}]\n    }}\n")
                else:
                    ln = f["length"]
                    out.append(f"    pub fn {nm_r}(&self) -> &'a [u8] {{\n        &self.0[{o}..{o + ln}]\n    }}\n")
            out.append(rust_csv(m))
            out.append("}\n\n")
    for proto in PROTOS:
        out.append(f"/// The CSV text of one {proto} message (type and length checked), or None.\n"
                   f"pub fn csv_{proto}(m: &[u8]) -> Option<String> {{\n    match (m.first()?, m.len()) {{\n")
        for typ, msg in s["protocols"][proto].items():
            n = cname(proto, typ)
            out.append(f"        (b'{typ}', {msg['length']}) => Some({n}(m).csv()),\n")
        out.append("        _ => None,\n    }\n}\n\n")
    out.append("/// MoldUDP64 packet header.\npub struct MoldHeader<'a>(pub &'a [u8]);\n\nimpl MoldHeader<'_> {\n"
               "    pub const LENGTH: usize = 20;\n    pub fn seq(&self) -> u64 {\n        be(self.0, 10, 8)\n    }\n"
               "    pub fn count(&self) -> u16 {\n        be(self.0, 18, 2) as u16\n    }\n}\n")
    return "".join(out)


def rust_csv(m):
    parts = []
    for f in m["fields"][1:]:
        nm, ty = f["name"], f["type"]
        nm_r = "r#match" if nm == "match" else ("r#ref" if nm == "ref" else nm)
        if ty in INT:
            parts.append(f"self.{nm_r}().to_string()")
        elif ty == "char":
            parts.append(f"(self.{nm_r}() as char).to_string()")
        else:
            parts.append(f"String::from_utf8_lossy(self.{nm_r}()).trim_end_matches(' ').to_string()")
    items = ",\n            ".join(parts)
    return ("    /// The fields in schema order, as the golden CSVs print them.\n"
            f"    pub fn csv(&self) -> String {{\n        [\n            {items},\n        ]\n"
            "        .join(\",\")\n    }\n")


def bridge(s):
    """BE feed message -> SBE-style LE message: one generated function over both generated headers."""
    out = [HEADER.format(src="code/firm/exchsim/schema.json and sbe/feed_sbe.xml"),
           "// Converts one big-endian feed message into the little-endian SBE-style layout; returns the SBE size\n"
           "// (0 for an unknown type). Used to build the chapter's benchmark input and in the round-trip tests.\n",
           "#pragma once\n#include <type_traits>\n\n"
           "#include \"firm_wirecodec.hpp\"\n#include \"firm_wirecodec_sbe.hpp\"\n\n",
           "namespace firm::wire {\n\n"
           "inline std::size_t to_sbe(const std::uint8_t* p, std::size_t n, std::uint8_t* out) {\n"
           "    std::size_t k = 0;\n    dispatch_feed(p, n, [&](auto m) {\n        using M = decltype(m);\n"]
    first = True
    for typ, m in s["protocols"]["feed"].items():
        n = cname("feed", typ)
        sets = "".join(f".{f['name']}(m.{f['name']}())" for f in m["fields"][1:])
        kw = "if" if first else "} else if"
        first = False
        out.append(f"        {kw} constexpr (std::is_same_v<M, {n}>) {{\n"
                   f"            firm::sbe::{n}Writer(out){sets};\n            k = firm::sbe::{n}Writer::kSize;\n")
    out.append("        }\n    });\n    return k;\n}\n\n}  // namespace firm::wire\n")
    return "".join(out)


def sbe_xml(s):
    root = ET.Element("sbe:messageSchema", {"xmlns:sbe": "http://fixprotocol.io/2016/sbe", "package": "firm.wire",
                                            "id": "13", "version": "1", "byteOrder": "littleEndian",
                                            "description": "The simulator's feed messages in an SBE-style layout"})
    types = ET.SubElement(root, "types")
    hdr = ET.SubElement(types, "composite", {"name": "messageHeader"})
    for nm in ("blockLength", "templateId", "schemaId", "version"):
        ET.SubElement(hdr, "type", {"name": nm, "primitiveType": "uint16"})
    for n in sorted({f["length"] for m in s["protocols"]["feed"].values() for f in m["fields"]
                     if f["type"].startswith("alpha")}):
        ET.SubElement(types, "type", {"name": f"alpha{n}", "primitiveType": "char", "length": str(n)})
    for typ, m in s["protocols"]["feed"].items():
        msg = ET.SubElement(root, "sbe:message", {"name": f"Feed{typ}", "id": str(ord(typ))})
        off = 0
        for f in m["fields"][1:]:
            if f["type"].startswith("alpha"):
                t, ln = f["type"], f["length"]
            else:
                t, ln = SBE_TYPES[f["type"]]
            ET.SubElement(msg, "field", {"name": f["name"], "id": str(len(msg) + 1), "type": t, "offset": str(off)})
            off += ln
        msg.set("blockLength", str(off))
    ET.indent(root)
    return ('<?xml version="1.0" encoding="UTF-8"?>\n<!-- GENERATED by code/firm/wirecodec/gen_wirecodec.py from '
            'code/firm/exchsim/schema.json: do not edit. -->\n' + ET.tostring(root, encoding="unicode") + "\n")


def cpp_sbe(xml_text):
    root = ET.fromstring(xml_text)
    ns = {"sbe": "http://fixprotocol.io/2016/sbe"}
    alpha = {t.get("name"): int(t.get("length")) for t in root.find("types").findall("type")}
    out = [HEADER.format(src="code/firm/wirecodec/sbe/feed_sbe.xml"),
           "// Little-endian (SBE-style) flyweights: an 8-byte message header (blockLength, templateId, schemaId,\n"
           "// version), then the root block at natural field sizes. On x86-64 a field read is one load.\n",
           "#pragma once\n#include <cstddef>\n#include <cstdint>\n#include <cstring>\n#include <string>\n"
           "#include <string_view>\n\n",
           "namespace firm::sbe {\n\n",
           "inline std::string trimmed(std::string_view v) {\n"
           "    while (!v.empty() && v.back() == ' ') v.remove_suffix(1);\n    return std::string(v);\n}\n",
           "template <class T>\ninline T le(const std::uint8_t* p) {\n    T v;\n    std::memcpy(&v, p, sizeof v);\n"
           "    return v;\n}\ntemplate <class T>\n"
           "inline void put_le(std::uint8_t* p, T v) { std::memcpy(p, &v, sizeof v); }\n"
           "inline void put_text(std::uint8_t* p, std::string_view v, std::size_t n) {\n"
           "    const std::size_t k = v.size() < n ? v.size() : n;\n    std::memcpy(p, v.data(), k);\n"
           "    std::memset(p + k, ' ', n - k);\n}\n\n",
           f"constexpr std::uint16_t kSchemaId = {root.get('id')}, kVersion = {root.get('version')};\n"
           "constexpr std::size_t kHeader = 8;\n\n"
           "struct Header {\n    const std::uint8_t* p;\n"
           "    std::uint16_t block_length() const { return le<std::uint16_t>(p); }\n"
           "    std::uint16_t template_id() const { return le<std::uint16_t>(p + 2); }\n"
           "    std::uint16_t schema_id() const { return le<std::uint16_t>(p + 4); }\n"
           "    std::uint16_t version() const { return le<std::uint16_t>(p + 6); }\n};\n\n"]
    for msg in root.findall("sbe:message", ns):
        n, tid, bl = msg.get("name"), msg.get("id"), msg.get("blockLength")
        out.append(f"struct {n} {{\n    static constexpr std::uint16_t kTemplateId = {tid};\n"
                   f"    static constexpr std::size_t kBlockLength = {bl};\n"
                   "    const std::uint8_t* p;   // the root block\n")
        w = [f"struct {n}Writer {{\n    std::uint8_t* p;   // the message header; fields follow it\n"
             f"    explicit {n}Writer(std::uint8_t* q) : p(q) {{\n"
             f"        put_le<std::uint16_t>(p, {bl});\n        put_le<std::uint16_t>(p + 2, {tid});\n"
             "        put_le<std::uint16_t>(p + 4, kSchemaId);\n        put_le<std::uint16_t>(p + 6, kVersion);\n"
             f"        std::memset(p + kHeader, 0, {bl});\n    }}\n"]
        for f in msg.findall("field"):
            nm, t, o = f.get("name"), f.get("type"), int(f.get("offset"))
            if t in SBE_CPP:
                ct = SBE_CPP[t]
                out.append(f"    {ct} {nm}() const {{ return le<{ct}>(p + {o}); }}\n")
                w.append(f"    {n}Writer& {nm}({ct} v) {{ put_le<{ct}>(p + kHeader + {o}, v); return *this; }}\n")
            elif t == "char":
                out.append(f"    char {nm}() const {{ return static_cast<char>(p[{o}]); }}\n")
                w.append(f"    {n}Writer& {nm}(char v) {{ p[kHeader + {o}] = static_cast<std::uint8_t>(v); "
                         "return *this; }\n")
            else:
                ln = alpha[t]
                out.append(f"    std::string_view {nm}() const {{ return {{reinterpret_cast<const char*>(p + {o}), "
                           f"{ln}}}; }}\n")
                w.append(f"    {n}Writer& {nm}(std::string_view v) {{ put_text(p + kHeader + {o}, v, {ln}); "
                         "return *this; }\n")
        out.append("};\n")
        out.extend(w)
        out.append(f"    static constexpr std::size_t kSize = kHeader + {bl};\n}};\n")
        parts = []
        for f in msg.findall("field"):
            nm, t = f.get("name"), f.get("type")
            parts.append(f"std::to_string(m.{nm}())" if t in SBE_CPP else
                         f"std::string(1, m.{nm}())" if t == "char" else f"trimmed(m.{nm}())")
        joined = ' + "," + '.join(parts)
        out.append(f"inline std::string csv(const {n}& m) {{ return {joined}; }}\n\n")
    out.append("}  // namespace firm::sbe\n")
    return "".join(out)


def outputs():
    s = schema()
    xml = sbe_xml(s)
    return {HERE / "cpp/firm_wirecodec.hpp": cpp_be(s), HERE / "rust/src/generated.rs": rust_be(s),
            HERE / "sbe/feed_sbe.xml": xml, HERE / "cpp/firm_wirecodec_sbe.hpp": cpp_sbe(xml),
            HERE / "cpp/firm_wirecodec_bridge.hpp": bridge(s)}


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    stale = []
    for path, text in outputs().items():
        if "--check" in argv:
            if not path.exists() or path.read_text() != text:
                stale.append(str(path))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    if stale:
        print("stale generated files:", *stale, sep="\n  ")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
