[package]
name = "firm_ticktotrade"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
firm_feedhandler = { path = "../../feedhandler/rust" }
firm_stratengine = { path = "../../stratengine/rust" }
firm_riskgate = { path = "../../riskgate/rust" }
firm_ordergw = { path = "../../ordergw/rust" }
