"""Build the parity fixture shared by the Python, C++20 and Rust implementations: a LightGBM forest of 300 trees and an
int8 multilayer perceptron fitted to a synthetic 16-feature problem, their exported forms in data/, 200 test vectors
with the reference predictions, and the generated C++ branches in cpp/forest_branches.hpp. Deterministic: running it
again leaves every file unchanged."""
from __future__ import annotations

import pathlib
import sys

import numpy as np

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent / "gbdt"))
import firm_mlinfer as mi  # noqa: E402
from firm_gbdt import make  # noqa: E402

K, N = 16, 20000


def problem(seed=0, n=N):
    rng = np.random.default_rng(seed)
    X = rng.standard_normal((n, K))
    y = (0.3 * np.tanh(X[:, 0] * X[:, 1]) + 0.2 * X[:, 2] - 0.15 * np.abs(X[:, 3]) + 0.1 * X[:, 4] * (X[:, 5] > 0)
         + rng.standard_normal(n))
    return X, y


def models():
    X, y = problem()
    forest = make({"n_estimators": 300, "num_leaves": 15, "learning_rate": 0.03, "min_child_samples": 100}, seed=1)
    forest.fit(X, y)
    mlp = mi.fit_mlp(mi.MLP(K), X, y, epochs=40, seed=0)
    return forest, mlp, X, y


def main():
    forest, mlp, X, _ = models()
    f = mi.export_forest(forest)
    mi.write_forest(f, HERE / "data" / "forest.txt")
    q = mi.quantise(mlp, X[:2000])
    mi.write_mlp(q, HERE / "data" / "mlp.txt")
    V, _ = problem(seed=9, n=200)
    pf, pm = forest.predict(V), mi.int8_forward(q, V)
    with open(HERE / "data" / "vectors.csv", "w") as fh:
        for x, a, b in zip(V, pf, pm, strict=True):
            fh.write(",".join(repr(float(v)) for v in x) + f",{float(a)!r},{float(b)!r}\n")
    head = "// Generated by make_mlinfer_fixture.py from data/forest.txt: do not edit.\n#pragma once\n\n"
    (HERE / "cpp" / "forest_branches.hpp").write_text(head + mi.cpp_branches(f))


if __name__ == "__main__":
    main()
