// GENERATED by code/firm/wirecodec/gen_wirecodec.py from code/firm/exchsim/schema.json and sbe/feed_sbe.xml: do not edit.
// Converts one big-endian feed message into the little-endian SBE-style layout; returns the SBE size
// (0 for an unknown type). Used to build the chapter's benchmark input and in the round-trip tests.
#pragma once
#include <type_traits>

#include "firm_wirecodec.hpp"
#include "firm_wirecodec_sbe.hpp"

namespace firm::wire {

inline std::size_t to_sbe(const std::uint8_t* p, std::size_t n, std::uint8_t* out) {
    std::size_t k = 0;
    dispatch_feed(p, n, [&](auto m) {
        using M = decltype(m);
        if constexpr (std::is_same_v<M, FeedA>) {
            firm::sbe::FeedAWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).ref(m.ref()).side(m.side()).shares(m.shares()).stock(m.stock()).price(m.price());
            k = firm::sbe::FeedAWriter::kSize;
        } else if constexpr (std::is_same_v<M, FeedE>) {
            firm::sbe::FeedEWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).ref(m.ref()).shares(m.shares()).match(m.match());
            k = firm::sbe::FeedEWriter::kSize;
        } else if constexpr (std::is_same_v<M, FeedX>) {
            firm::sbe::FeedXWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).ref(m.ref()).shares(m.shares());
            k = firm::sbe::FeedXWriter::kSize;
        } else if constexpr (std::is_same_v<M, FeedD>) {
            firm::sbe::FeedDWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).ref(m.ref());
            k = firm::sbe::FeedDWriter::kSize;
        } else if constexpr (std::is_same_v<M, FeedP>) {
            firm::sbe::FeedPWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).ref(m.ref()).side(m.side()).shares(m.shares()).stock(m.stock()).price(m.price()).match(m.match());
            k = firm::sbe::FeedPWriter::kSize;
        } else if constexpr (std::is_same_v<M, FeedU>) {
            firm::sbe::FeedUWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).ref(m.ref()).new_ref(m.new_ref()).shares(m.shares()).price(m.price());
            k = firm::sbe::FeedUWriter::kSize;
        } else if constexpr (std::is_same_v<M, FeedC>) {
            firm::sbe::FeedCWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).ref(m.ref()).shares(m.shares()).match(m.match()).printable(m.printable()).price(m.price());
            k = firm::sbe::FeedCWriter::kSize;
        } else if constexpr (std::is_same_v<M, FeedQ>) {
            firm::sbe::FeedQWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).shares(m.shares()).stock(m.stock()).price(m.price()).match(m.match()).cross_type(m.cross_type());
            k = firm::sbe::FeedQWriter::kSize;
        } else if constexpr (std::is_same_v<M, FeedI>) {
            firm::sbe::FeedIWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).paired(m.paired()).imbalance(m.imbalance()).direction(m.direction()).stock(m.stock()).far(m.far()).near(m.near()).ref_price(m.ref_price()).cross_type(m.cross_type()).variation(m.variation());
            k = firm::sbe::FeedIWriter::kSize;
        } else if constexpr (std::is_same_v<M, FeedS>) {
            firm::sbe::FeedSWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).event(m.event());
            k = firm::sbe::FeedSWriter::kSize;
        } else if constexpr (std::is_same_v<M, FeedH>) {
            firm::sbe::FeedHWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).stock(m.stock()).state(m.state()).reserved(m.reserved()).reason(m.reason());
            k = firm::sbe::FeedHWriter::kSize;
        } else if constexpr (std::is_same_v<M, FeedR>) {
            firm::sbe::FeedRWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).stock(m.stock()).tick(m.tick()).lot(m.lot()).matching(m.matching());
            k = firm::sbe::FeedRWriter::kSize;
        } else if constexpr (std::is_same_v<M, FeedG>) {
            firm::sbe::FeedGWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).seq(m.seq()).orders(m.orders());
            k = firm::sbe::FeedGWriter::kSize;
        } else if constexpr (std::is_same_v<M, FeedW>) {
            firm::sbe::FeedWWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).seq(m.seq()).crc(m.crc());
            k = firm::sbe::FeedWWriter::kSize;
        }
    });
    return k;
}

}  // namespace firm::wire
