// GENERATED by code/firm/wirecodec/gen_wirecodec.py from code/firm/wirecodec/sbe/feed_sbe.xml: do not edit.
// Little-endian (SBE-style) flyweights: an 8-byte message header (blockLength, templateId, schemaId,
// version), then the root block at natural field sizes. On x86-64 a field read is one load.
#pragma once
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <string>
#include <string_view>

namespace firm::sbe {

inline std::string trimmed(std::string_view v) {
    while (!v.empty() && v.back() == ' ') v.remove_suffix(1);
    return std::string(v);
}
template <class T>
inline T le(const std::uint8_t* p) {
    T v;
    std::memcpy(&v, p, sizeof v);
    return v;
}
template <class T>
inline void put_le(std::uint8_t* p, T v) { std::memcpy(p, &v, sizeof v); }
inline void put_text(std::uint8_t* p, std::string_view v, std::size_t n) {
    const std::size_t k = v.size() < n ? v.size() : n;
    std::memcpy(p, v.data(), k);
    std::memset(p + k, ' ', n - k);
}

constexpr std::uint16_t kSchemaId = 13, kVersion = 1;
constexpr std::size_t kHeader = 8;

struct Header {
    const std::uint8_t* p;
    std::uint16_t block_length() const { return le<std::uint16_t>(p); }
    std::uint16_t template_id() const { return le<std::uint16_t>(p + 2); }
    std::uint16_t schema_id() const { return le<std::uint16_t>(p + 4); }
    std::uint16_t version() const { return le<std::uint16_t>(p + 6); }
};

struct FeedA {
    static constexpr std::uint16_t kTemplateId = 65;
    static constexpr std::size_t kBlockLength = 37;
    const std::uint8_t* p;   // the root block
    std::uint16_t locate() const { return le<std::uint16_t>(p + 0); }
    std::uint16_t tracking() const { return le<std::uint16_t>(p + 2); }
    std::uint64_t ts() const { return le<std::uint64_t>(p + 4); }
    std::uint64_t ref() const { return le<std::uint64_t>(p + 12); }
    char side() const { return static_cast<char>(p[20]); }
    std::uint32_t shares() const { return le<std::uint32_t>(p + 21); }
    std::string_view stock() const { return {reinterpret_cast<const char*>(p + 25), 8}; }
    std::uint32_t price() const { return le<std::uint32_t>(p + 33); }
};
struct FeedAWriter {
    std::uint8_t* p;   // the message header; fields follow it
    explicit FeedAWriter(std::uint8_t* q) : p(q) {
        put_le<std::uint16_t>(p, 37);
        put_le<std::uint16_t>(p + 2, 65);
        put_le<std::uint16_t>(p + 4, kSchemaId);
        put_le<std::uint16_t>(p + 6, kVersion);
        std::memset(p + kHeader, 0, 37);
    }
    FeedAWriter& locate(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 0, v); return *this; }
    FeedAWriter& tracking(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 2, v); return *this; }
    FeedAWriter& ts(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 4, v); return *this; }
    FeedAWriter& ref(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 12, v); return *this; }
    FeedAWriter& side(char v) { p[kHeader + 20] = static_cast<std::uint8_t>(v); return *this; }
    FeedAWriter& shares(std::uint32_t v) { put_le<std::uint32_t>(p + kHeader + 21, v); return *this; }
    FeedAWriter& stock(std::string_view v) { put_text(p + kHeader + 25, v, 8); return *this; }
    FeedAWriter& price(std::uint32_t v) { put_le<std::uint32_t>(p + kHeader + 33, v); return *this; }
    static constexpr std::size_t kSize = kHeader + 37;
};
inline std::string csv(const FeedA& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + std::to_string(m.ref()) + "," + std::string(1, m.side()) + "," + std::to_string(m.shares()) + "," + trimmed(m.stock()) + "," + std::to_string(m.price()); }

struct FeedE {
    static constexpr std::uint16_t kTemplateId = 69;
    static constexpr std::size_t kBlockLength = 32;
    const std::uint8_t* p;   // the root block
    std::uint16_t locate() const { return le<std::uint16_t>(p + 0); }
    std::uint16_t tracking() const { return le<std::uint16_t>(p + 2); }
    std::uint64_t ts() const { return le<std::uint64_t>(p + 4); }
    std::uint64_t ref() const { return le<std::uint64_t>(p + 12); }
    std::uint32_t shares() const { return le<std::uint32_t>(p + 20); }
    std::uint64_t match() const { return le<std::uint64_t>(p + 24); }
};
struct FeedEWriter {
    std::uint8_t* p;   // the message header; fields follow it
    explicit FeedEWriter(std::uint8_t* q) : p(q) {
        put_le<std::uint16_t>(p, 32);
        put_le<std::uint16_t>(p + 2, 69);
        put_le<std::uint16_t>(p + 4, kSchemaId);
        put_le<std::uint16_t>(p + 6, kVersion);
        std::memset(p + kHeader, 0, 32);
    }
    FeedEWriter& locate(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 0, v); return *this; }
    FeedEWriter& tracking(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 2, v); return *this; }
    FeedEWriter& ts(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 4, v); return *this; }
    FeedEWriter& ref(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 12, v); return *this; }
    FeedEWriter& shares(std::uint32_t v) { put_le<std::uint32_t>(p + kHeader + 20, v); return *this; }
    FeedEWriter& match(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 24, v); return *this; }
    static constexpr std::size_t kSize = kHeader + 32;
};
inline std::string csv(const FeedE& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + std::to_string(m.ref()) + "," + std::to_string(m.shares()) + "," + std::to_string(m.match()); }

struct FeedX {
    static constexpr std::uint16_t kTemplateId = 88;
    static constexpr std::size_t kBlockLength = 24;
    const std::uint8_t* p;   // the root block
    std::uint16_t locate() const { return le<std::uint16_t>(p + 0); }
    std::uint16_t tracking() const { return le<std::uint16_t>(p + 2); }
    std::uint64_t ts() const { return le<std::uint64_t>(p + 4); }
    std::uint64_t ref() const { return le<std::uint64_t>(p + 12); }
    std::uint32_t shares() const { return le<std::uint32_t>(p + 20); }
};
struct FeedXWriter {
    std::uint8_t* p;   // the message header; fields follow it
    explicit FeedXWriter(std::uint8_t* q) : p(q) {
        put_le<std::uint16_t>(p, 24);
        put_le<std::uint16_t>(p + 2, 88);
        put_le<std::uint16_t>(p + 4, kSchemaId);
        put_le<std::uint16_t>(p + 6, kVersion);
        std::memset(p + kHeader, 0, 24);
    }
    FeedXWriter& locate(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 0, v); return *this; }
    FeedXWriter& tracking(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 2, v); return *this; }
    FeedXWriter& ts(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 4, v); return *this; }
    FeedXWriter& ref(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 12, v); return *this; }
    FeedXWriter& shares(std::uint32_t v) { put_le<std::uint32_t>(p + kHeader + 20, v); return *this; }
    static constexpr std::size_t kSize = kHeader + 24;
};
inline std::string csv(const FeedX& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + std::to_string(m.ref()) + "," + std::to_string(m.shares()); }

struct FeedD {
    static constexpr std::uint16_t kTemplateId = 68;
    static constexpr std::size_t kBlockLength = 20;
    const std::uint8_t* p;   // the root block
    std::uint16_t locate() const { return le<std::uint16_t>(p + 0); }
    std::uint16_t tracking() const { return le<std::uint16_t>(p + 2); }
    std::uint64_t ts() const { return le<std::uint64_t>(p + 4); }
    std::uint64_t ref() const { return le<std::uint64_t>(p + 12); }
};
struct FeedDWriter {
    std::uint8_t* p;   // the message header; fields follow it
    explicit FeedDWriter(std::uint8_t* q) : p(q) {
        put_le<std::uint16_t>(p, 20);
        put_le<std::uint16_t>(p + 2, 68);
        put_le<std::uint16_t>(p + 4, kSchemaId);
        put_le<std::uint16_t>(p + 6, kVersion);
        std::memset(p + kHeader, 0, 20);
    }
    FeedDWriter& locate(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 0, v); return *this; }
    FeedDWriter& tracking(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 2, v); return *this; }
    FeedDWriter& ts(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 4, v); return *this; }
    FeedDWriter& ref(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 12, v); return *this; }
    static constexpr std::size_t kSize = kHeader + 20;
};
inline std::string csv(const FeedD& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + std::to_string(m.ref()); }

struct FeedP {
    static constexpr std::uint16_t kTemplateId = 80;
    static constexpr std::size_t kBlockLength = 45;
    const std::uint8_t* p;   // the root block
    std::uint16_t locate() const { return le<std::uint16_t>(p + 0); }
    std::uint16_t tracking() const { return le<std::uint16_t>(p + 2); }
    std::uint64_t ts() const { return le<std::uint64_t>(p + 4); }
    std::uint64_t ref() const { return le<std::uint64_t>(p + 12); }
    char side() const { return static_cast<char>(p[20]); }
    std::uint32_t shares() const { return le<std::uint32_t>(p + 21); }
    std::string_view stock() const { return {reinterpret_cast<const char*>(p + 25), 8}; }
    std::uint32_t price() const { return le<std::uint32_t>(p + 33); }
    std::uint64_t match() const { return le<std::uint64_t>(p + 37); }
};
struct FeedPWriter {
    std::uint8_t* p;   // the message header; fields follow it
    explicit FeedPWriter(std::uint8_t* q) : p(q) {
        put_le<std::uint16_t>(p, 45);
        put_le<std::uint16_t>(p + 2, 80);
        put_le<std::uint16_t>(p + 4, kSchemaId);
        put_le<std::uint16_t>(p + 6, kVersion);
        std::memset(p + kHeader, 0, 45);
    }
    FeedPWriter& locate(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 0, v); return *this; }
    FeedPWriter& tracking(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 2, v); return *this; }
    FeedPWriter& ts(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 4, v); return *this; }
    FeedPWriter& ref(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 12, v); return *this; }
    FeedPWriter& side(char v) { p[kHeader + 20] = static_cast<std::uint8_t>(v); return *this; }
    FeedPWriter& shares(std::uint32_t v) { put_le<std::uint32_t>(p + kHeader + 21, v); return *this; }
    FeedPWriter& stock(std::string_view v) { put_text(p + kHeader + 25, v, 8); return *this; }
    FeedPWriter& price(std::uint32_t v) { put_le<std::uint32_t>(p + kHeader + 33, v); return *this; }
    FeedPWriter& match(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 37, v); return *this; }
    static constexpr std::size_t kSize = kHeader + 45;
};
inline std::string csv(const FeedP& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + std::to_string(m.ref()) + "," + std::string(1, m.side()) + "," + std::to_string(m.shares()) + "," + trimmed(m.stock()) + "," + std::to_string(m.price()) + "," + std::to_string(m.match()); }

struct FeedU {
    static constexpr std::uint16_t kTemplateId = 85;
    static constexpr std::size_t kBlockLength = 36;
    const std::uint8_t* p;   // the root block
    std::uint16_t locate() const { return le<std::uint16_t>(p + 0); }
    std::uint16_t tracking() const { return le<std::uint16_t>(p + 2); }
    std::uint64_t ts() const { return le<std::uint64_t>(p + 4); }
    std::uint64_t ref() const { return le<std::uint64_t>(p + 12); }
    std::uint64_t new_ref() const { return le<std::uint64_t>(p + 20); }
    std::uint32_t shares() const { return le<std::uint32_t>(p + 28); }
    std::uint32_t price() const { return le<std::uint32_t>(p + 32); }
};
struct FeedUWriter {
    std::uint8_t* p;   // the message header; fields follow it
    explicit FeedUWriter(std::uint8_t* q) : p(q) {
        put_le<std::uint16_t>(p, 36);
        put_le<std::uint16_t>(p + 2, 85);
        put_le<std::uint16_t>(p + 4, kSchemaId);
        put_le<std::uint16_t>(p + 6, kVersion);
        std::memset(p + kHeader, 0, 36);
    }
    FeedUWriter& locate(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 0, v); return *this; }
    FeedUWriter& tracking(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 2, v); return *this; }
    FeedUWriter& ts(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 4, v); return *this; }
    FeedUWriter& ref(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 12, v); return *this; }
    FeedUWriter& new_ref(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 20, v); return *this; }
    FeedUWriter& shares(std::uint32_t v) { put_le<std::uint32_t>(p + kHeader + 28, v); return *this; }
    FeedUWriter& price(std::uint32_t v) { put_le<std::uint32_t>(p + kHeader + 32, v); return *this; }
    static constexpr std::size_t kSize = kHeader + 36;
};
inline std::string csv(const FeedU& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + std::to_string(m.ref()) + "," + std::to_string(m.new_ref()) + "," + std::to_string(m.shares()) + "," + std::to_string(m.price()); }

struct FeedC {
    static constexpr std::uint16_t kTemplateId = 67;
    static constexpr std::size_t kBlockLength = 37;
    const std::uint8_t* p;   // the root block
    std::uint16_t locate() const { return le<std::uint16_t>(p + 0); }
    std::uint16_t tracking() const { return le<std::uint16_t>(p + 2); }
    std::uint64_t ts() const { return le<std::uint64_t>(p + 4); }
    std::uint64_t ref() const { return le<std::uint64_t>(p + 12); }
    std::uint32_t shares() const { return le<std::uint32_t>(p + 20); }
    std::uint64_t match() const { return le<std::uint64_t>(p + 24); }
    char printable() const { return static_cast<char>(p[32]); }
    std::uint32_t price() const { return le<std::uint32_t>(p + 33); }
};
struct FeedCWriter {
    std::uint8_t* p;   // the message header; fields follow it
    explicit FeedCWriter(std::uint8_t* q) : p(q) {
        put_le<std::uint16_t>(p, 37);
        put_le<std::uint16_t>(p + 2, 67);
        put_le<std::uint16_t>(p + 4, kSchemaId);
        put_le<std::uint16_t>(p + 6, kVersion);
        std::memset(p + kHeader, 0, 37);
    }
    FeedCWriter& locate(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 0, v); return *this; }
    FeedCWriter& tracking(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 2, v); return *this; }
    FeedCWriter& ts(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 4, v); return *this; }
    FeedCWriter& ref(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 12, v); return *this; }
    FeedCWriter& shares(std::uint32_t v) { put_le<std::uint32_t>(p + kHeader + 20, v); return *this; }
    FeedCWriter& match(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 24, v); return *this; }
    FeedCWriter& printable(char v) { p[kHeader + 32] = static_cast<std::uint8_t>(v); return *this; }
    FeedCWriter& price(std::uint32_t v) { put_le<std::uint32_t>(p + kHeader + 33, v); return *this; }
    static constexpr std::size_t kSize = kHeader + 37;
};
inline std::string csv(const FeedC& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + std::to_string(m.ref()) + "," + std::to_string(m.shares()) + "," + std::to_string(m.match()) + "," + std::string(1, m.printable()) + "," + std::to_string(m.price()); }

struct FeedQ {
    static constexpr std::uint16_t kTemplateId = 81;
    static constexpr std::size_t kBlockLength = 41;
    const std::uint8_t* p;   // the root block
    std::uint16_t locate() const { return le<std::uint16_t>(p + 0); }
    std::uint16_t tracking() const { return le<std::uint16_t>(p + 2); }
    std::uint64_t ts() const { return le<std::uint64_t>(p + 4); }
    std::uint64_t shares() const { return le<std::uint64_t>(p + 12); }
    std::string_view stock() const { return {reinterpret_cast<const char*>(p + 20), 8}; }
    std::uint32_t price() const { return le<std::uint32_t>(p + 28); }
    std::uint64_t match() const { return le<std::uint64_t>(p + 32); }
    char cross_type() const { return static_cast<char>(p[40]); }
};
struct FeedQWriter {
    std::uint8_t* p;   // the message header; fields follow it
    explicit FeedQWriter(std::uint8_t* q) : p(q) {
        put_le<std::uint16_t>(p, 41);
        put_le<std::uint16_t>(p + 2, 81);
        put_le<std::uint16_t>(p + 4, kSchemaId);
        put_le<std::uint16_t>(p + 6, kVersion);
        std::memset(p + kHeader, 0, 41);
    }
    FeedQWriter& locate(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 0, v); return *this; }
    FeedQWriter& tracking(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 2, v); return *this; }
    FeedQWriter& ts(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 4, v); return *this; }
    FeedQWriter& shares(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 12, v); return *this; }
    FeedQWriter& stock(std::string_view v) { put_text(p + kHeader + 20, v, 8); return *this; }
    FeedQWriter& price(std::uint32_t v) { put_le<std::uint32_t>(p + kHeader + 28, v); return *this; }
    FeedQWriter& match(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 32, v); return *this; }
    FeedQWriter& cross_type(char v) { p[kHeader + 40] = static_cast<std::uint8_t>(v); return *this; }
    static constexpr std::size_t kSize = kHeader + 41;
};
inline std::string csv(const FeedQ& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + std::to_string(m.shares()) + "," + trimmed(m.stock()) + "," + std::to_string(m.price()) + "," + std::to_string(m.match()) + "," + std::string(1, m.cross_type()); }

struct FeedI {
    static constexpr std::uint16_t kTemplateId = 73;
    static constexpr std::size_t kBlockLength = 51;
    const std::uint8_t* p;   // the root block
    std::uint16_t locate() const { return le<std::uint16_t>(p + 0); }
    std::uint16_t tracking() const { return le<std::uint16_t>(p + 2); }
    std::uint64_t ts() const { return le<std::uint64_t>(p + 4); }
    std::uint64_t paired() const { return le<std::uint64_t>(p + 12); }
    std::uint64_t imbalance() const { return le<std::uint64_t>(p + 20); }
    char direction() const { return static_cast<char>(p[28]); }
    std::string_view stock() const { return {reinterpret_cast<const char*>(p + 29), 8}; }
    std::uint32_t far() const { return le<std::uint32_t>(p + 37); }
    std::uint32_t near() const { return le<std::uint32_t>(p + 41); }
    std::uint32_t ref_price() const { return le<std::uint32_t>(p + 45); }
    char cross_type() const { return static_cast<char>(p[49]); }
    char variation() const { return static_cast<char>(p[50]); }
};
struct FeedIWriter {
    std::uint8_t* p;   // the message header; fields follow it
    explicit FeedIWriter(std::uint8_t* q) : p(q) {
        put_le<std::uint16_t>(p, 51);
        put_le<std::uint16_t>(p + 2, 73);
        put_le<std::uint16_t>(p + 4, kSchemaId);
        put_le<std::uint16_t>(p + 6, kVersion);
        std::memset(p + kHeader, 0, 51);
    }
    FeedIWriter& locate(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 0, v); return *this; }
    FeedIWriter& tracking(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 2, v); return *this; }
    FeedIWriter& ts(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 4, v); return *this; }
    FeedIWriter& paired(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 12, v); return *this; }
    FeedIWriter& imbalance(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 20, v); return *this; }
    FeedIWriter& direction(char v) { p[kHeader + 28] = static_cast<std::uint8_t>(v); return *this; }
    FeedIWriter& stock(std::string_view v) { put_text(p + kHeader + 29, v, 8); return *this; }
    FeedIWriter& far(std::uint32_t v) { put_le<std::uint32_t>(p + kHeader + 37, v); return *this; }
    FeedIWriter& near(std::uint32_t v) { put_le<std::uint32_t>(p + kHeader + 41, v); return *this; }
    FeedIWriter& ref_price(std::uint32_t v) { put_le<std::uint32_t>(p + kHeader + 45, v); return *this; }
    FeedIWriter& cross_type(char v) { p[kHeader + 49] = static_cast<std::uint8_t>(v); return *this; }
    FeedIWriter& variation(char v) { p[kHeader + 50] = static_cast<std::uint8_t>(v); return *this; }
    static constexpr std::size_t kSize = kHeader + 51;
};
inline std::string csv(const FeedI& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + std::to_string(m.paired()) + "," + std::to_string(m.imbalance()) + "," + std::string(1, m.direction()) + "," + trimmed(m.stock()) + "," + std::to_string(m.far()) + "," + std::to_string(m.near()) + "," + std::to_string(m.ref_price()) + "," + std::string(1, m.cross_type()) + "," + std::string(1, m.variation()); }

struct FeedS {
    static constexpr std::uint16_t kTemplateId = 83;
    static constexpr std::size_t kBlockLength = 13;
    const std::uint8_t* p;   // the root block
    std::uint16_t locate() const { return le<std::uint16_t>(p + 0); }
    std::uint16_t tracking() const { return le<std::uint16_t>(p + 2); }
    std::uint64_t ts() const { return le<std::uint64_t>(p + 4); }
    char event() const { return static_cast<char>(p[12]); }
};
struct FeedSWriter {
    std::uint8_t* p;   // the message header; fields follow it
    explicit FeedSWriter(std::uint8_t* q) : p(q) {
        put_le<std::uint16_t>(p, 13);
        put_le<std::uint16_t>(p + 2, 83);
        put_le<std::uint16_t>(p + 4, kSchemaId);
        put_le<std::uint16_t>(p + 6, kVersion);
        std::memset(p + kHeader, 0, 13);
    }
    FeedSWriter& locate(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 0, v); return *this; }
    FeedSWriter& tracking(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 2, v); return *this; }
    FeedSWriter& ts(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 4, v); return *this; }
    FeedSWriter& event(char v) { p[kHeader + 12] = static_cast<std::uint8_t>(v); return *this; }
    static constexpr std::size_t kSize = kHeader + 13;
};
inline std::string csv(const FeedS& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + std::string(1, m.event()); }

struct FeedH {
    static constexpr std::uint16_t kTemplateId = 72;
    static constexpr std::size_t kBlockLength = 26;
    const std::uint8_t* p;   // the root block
    std::uint16_t locate() const { return le<std::uint16_t>(p + 0); }
    std::uint16_t tracking() const { return le<std::uint16_t>(p + 2); }
    std::uint64_t ts() const { return le<std::uint64_t>(p + 4); }
    std::string_view stock() const { return {reinterpret_cast<const char*>(p + 12), 8}; }
    char state() const { return static_cast<char>(p[20]); }
    char reserved() const { return static_cast<char>(p[21]); }
    std::string_view reason() const { return {reinterpret_cast<const char*>(p + 22), 4}; }
};
struct FeedHWriter {
    std::uint8_t* p;   // the message header; fields follow it
    explicit FeedHWriter(std::uint8_t* q) : p(q) {
        put_le<std::uint16_t>(p, 26);
        put_le<std::uint16_t>(p + 2, 72);
        put_le<std::uint16_t>(p + 4, kSchemaId);
        put_le<std::uint16_t>(p + 6, kVersion);
        std::memset(p + kHeader, 0, 26);
    }
    FeedHWriter& locate(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 0, v); return *this; }
    FeedHWriter& tracking(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 2, v); return *this; }
    FeedHWriter& ts(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 4, v); return *this; }
    FeedHWriter& stock(std::string_view v) { put_text(p + kHeader + 12, v, 8); return *this; }
    FeedHWriter& state(char v) { p[kHeader + 20] = static_cast<std::uint8_t>(v); return *this; }
    FeedHWriter& reserved(char v) { p[kHeader + 21] = static_cast<std::uint8_t>(v); return *this; }
    FeedHWriter& reason(std::string_view v) { put_text(p + kHeader + 22, v, 4); return *this; }
    static constexpr std::size_t kSize = kHeader + 26;
};
inline std::string csv(const FeedH& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + trimmed(m.stock()) + "," + std::string(1, m.state()) + "," + std::string(1, m.reserved()) + "," + trimmed(m.reason()); }

struct FeedR {
    static constexpr std::uint16_t kTemplateId = 82;
    static constexpr std::size_t kBlockLength = 29;
    const std::uint8_t* p;   // the root block
    std::uint16_t locate() const { return le<std::uint16_t>(p + 0); }
    std::uint16_t tracking() const { return le<std::uint16_t>(p + 2); }
    std::uint64_t ts() const { return le<std::uint64_t>(p + 4); }
    std::string_view stock() const { return {reinterpret_cast<const char*>(p + 12), 8}; }
    std::uint32_t tick() const { return le<std::uint32_t>(p + 20); }
    std::uint32_t lot() const { return le<std::uint32_t>(p + 24); }
    char matching() const { return static_cast<char>(p[28]); }
};
struct FeedRWriter {
    std::uint8_t* p;   // the message header; fields follow it
    explicit FeedRWriter(std::uint8_t* q) : p(q) {
        put_le<std::uint16_t>(p, 29);
        put_le<std::uint16_t>(p + 2, 82);
        put_le<std::uint16_t>(p + 4, kSchemaId);
        put_le<std::uint16_t>(p + 6, kVersion);
        std::memset(p + kHeader, 0, 29);
    }
    FeedRWriter& locate(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 0, v); return *this; }
    FeedRWriter& tracking(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 2, v); return *this; }
    FeedRWriter& ts(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 4, v); return *this; }
    FeedRWriter& stock(std::string_view v) { put_text(p + kHeader + 12, v, 8); return *this; }
    FeedRWriter& tick(std::uint32_t v) { put_le<std::uint32_t>(p + kHeader + 20, v); return *this; }
    FeedRWriter& lot(std::uint32_t v) { put_le<std::uint32_t>(p + kHeader + 24, v); return *this; }
    FeedRWriter& matching(char v) { p[kHeader + 28] = static_cast<std::uint8_t>(v); return *this; }
    static constexpr std::size_t kSize = kHeader + 29;
};
inline std::string csv(const FeedR& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + trimmed(m.stock()) + "," + std::to_string(m.tick()) + "," + std::to_string(m.lot()) + "," + std::string(1, m.matching()); }

struct FeedG {
    static constexpr std::uint16_t kTemplateId = 71;
    static constexpr std::size_t kBlockLength = 24;
    const std::uint8_t* p;   // the root block
    std::uint16_t locate() const { return le<std::uint16_t>(p + 0); }
    std::uint16_t tracking() const { return le<std::uint16_t>(p + 2); }
    std::uint64_t ts() const { return le<std::uint64_t>(p + 4); }
    std::uint64_t seq() const { return le<std::uint64_t>(p + 12); }
    std::uint32_t orders() const { return le<std::uint32_t>(p + 20); }
};
struct FeedGWriter {
    std::uint8_t* p;   // the message header; fields follow it
    explicit FeedGWriter(std::uint8_t* q) : p(q) {
        put_le<std::uint16_t>(p, 24);
        put_le<std::uint16_t>(p + 2, 71);
        put_le<std::uint16_t>(p + 4, kSchemaId);
        put_le<std::uint16_t>(p + 6, kVersion);
        std::memset(p + kHeader, 0, 24);
    }
    FeedGWriter& locate(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 0, v); return *this; }
    FeedGWriter& tracking(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 2, v); return *this; }
    FeedGWriter& ts(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 4, v); return *this; }
    FeedGWriter& seq(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 12, v); return *this; }
    FeedGWriter& orders(std::uint32_t v) { put_le<std::uint32_t>(p + kHeader + 20, v); return *this; }
    static constexpr std::size_t kSize = kHeader + 24;
};
inline std::string csv(const FeedG& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + std::to_string(m.seq()) + "," + std::to_string(m.orders()); }

struct FeedW {
    static constexpr std::uint16_t kTemplateId = 87;
    static constexpr std::size_t kBlockLength = 24;
    const std::uint8_t* p;   // the root block
    std::uint16_t locate() const { return le<std::uint16_t>(p + 0); }
    std::uint16_t tracking() const { return le<std::uint16_t>(p + 2); }
    std::uint64_t ts() const { return le<std::uint64_t>(p + 4); }
    std::uint64_t seq() const { return le<std::uint64_t>(p + 12); }
    std::uint32_t crc() const { return le<std::uint32_t>(p + 20); }
};
struct FeedWWriter {
    std::uint8_t* p;   // the message header; fields follow it
    explicit FeedWWriter(std::uint8_t* q) : p(q) {
        put_le<std::uint16_t>(p, 24);
        put_le<std::uint16_t>(p + 2, 87);
        put_le<std::uint16_t>(p + 4, kSchemaId);
        put_le<std::uint16_t>(p + 6, kVersion);
        std::memset(p + kHeader, 0, 24);
    }
    FeedWWriter& locate(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 0, v); return *this; }
    FeedWWriter& tracking(std::uint16_t v) { put_le<std::uint16_t>(p + kHeader + 2, v); return *this; }
    FeedWWriter& ts(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 4, v); return *this; }
    FeedWWriter& seq(std::uint64_t v) { put_le<std::uint64_t>(p + kHeader + 12, v); return *this; }
    FeedWWriter& crc(std::uint32_t v) { put_le<std::uint32_t>(p + kHeader + 20, v); return *this; }
    static constexpr std::size_t kSize = kHeader + 24;
};
inline std::string csv(const FeedW& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + std::to_string(m.seq()) + "," + std::to_string(m.crc()); }

}  // namespace firm::sbe
