// GENERATED by code/firm/wirecodec/gen_wirecodec.py from code/firm/exchsim/schema.json: do not edit.
// Big-endian flyweights over the simulator's wire formats (PROTOCOL.md): a reader holds a pointer to a
// message and decodes a field only when it is asked for; a writer encodes fields in place. No copy, no
// allocation, no virtual call.
#pragma once
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <string>
#include <string_view>

namespace firm::wire {

// Text of a fixed-width field without its padding (for tests and tools, not the hot path).
inline std::string trimmed(std::string_view v) {
    while (!v.empty() && v.back() == ' ') v.remove_suffix(1);
    return std::string(v);
}

inline std::uint64_t be(const std::uint8_t* p, std::size_t n) {
    std::uint64_t v = 0;
    std::memcpy(reinterpret_cast<std::uint8_t*>(&v) + 8 - n, p, n);
    return __builtin_bswap64(v);
}
inline void put_be(std::uint8_t* p, std::uint64_t v, std::size_t n) {
    v = __builtin_bswap64(v);
    std::memcpy(p, reinterpret_cast<const std::uint8_t*>(&v) + 8 - n, n);
}
// Fixed-width text, left-justified and space-padded.
inline void put_text(std::uint8_t* p, std::string_view v, std::size_t n) {
    const std::size_t k = v.size() < n ? v.size() : n;
    std::memcpy(p, v.data(), k);
    std::memset(p + k, ' ', n - k);
}
inline std::uint16_t be16(const std::uint8_t* p) { std::uint16_t v; std::memcpy(&v, p, 2); return __builtin_bswap16(v); }
inline std::uint32_t be32(const std::uint8_t* p) { std::uint32_t v; std::memcpy(&v, p, 4); return __builtin_bswap32(v); }
inline std::uint64_t be64(const std::uint8_t* p) { std::uint64_t v; std::memcpy(&v, p, 8); return __builtin_bswap64(v); }

// feed A: 36 bytes
struct FeedA {
    static constexpr char kType = 'A';
    static constexpr std::size_t kLength = 36;
    const std::uint8_t* p;
    std::uint16_t locate() const { return static_cast<std::uint16_t>(be16(p + 1)); }
    std::uint16_t tracking() const { return static_cast<std::uint16_t>(be16(p + 3)); }
    std::uint64_t ts() const { return be(p + 5, 6); }
    std::uint64_t ref() const { return be64(p + 11); }
    char side() const { return static_cast<char>(p[19]); }
    std::uint32_t shares() const { return static_cast<std::uint32_t>(be32(p + 20)); }
    std::string_view stock() const { return {reinterpret_cast<const char*>(p + 24), 8}; }
    std::uint32_t price() const { return static_cast<std::uint32_t>(be32(p + 32)); }
};
struct FeedAWriter {
    std::uint8_t* p;
    explicit FeedAWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 36); p[0] = 'A'; }
    FeedAWriter& locate(std::uint16_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedAWriter& tracking(std::uint16_t v) { put_be(p + 3, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedAWriter& ts(std::uint64_t v) { put_be(p + 5, static_cast<std::uint64_t>(v), 6); return *this; }
    FeedAWriter& ref(std::uint64_t v) { put_be(p + 11, static_cast<std::uint64_t>(v), 8); return *this; }
    FeedAWriter& side(char v) { p[19] = static_cast<std::uint8_t>(v); return *this; }
    FeedAWriter& shares(std::uint32_t v) { put_be(p + 20, static_cast<std::uint64_t>(v), 4); return *this; }
    FeedAWriter& stock(std::string_view v) { put_text(p + 24, v, 8); return *this; }
    FeedAWriter& price(std::uint32_t v) { put_be(p + 32, static_cast<std::uint64_t>(v), 4); return *this; }
};
inline std::string csv(const FeedA& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + std::to_string(m.ref()) + "," + std::string(1, m.side()) + "," + std::to_string(m.shares()) + "," + trimmed(m.stock()) + "," + std::to_string(m.price()); }
inline void rewrite(const FeedA& m, std::uint8_t* out) { FeedAWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).ref(m.ref()).side(m.side()).shares(m.shares()).stock(m.stock()).price(m.price()); }

// feed E: 31 bytes
struct FeedE {
    static constexpr char kType = 'E';
    static constexpr std::size_t kLength = 31;
    const std::uint8_t* p;
    std::uint16_t locate() const { return static_cast<std::uint16_t>(be16(p + 1)); }
    std::uint16_t tracking() const { return static_cast<std::uint16_t>(be16(p + 3)); }
    std::uint64_t ts() const { return be(p + 5, 6); }
    std::uint64_t ref() const { return be64(p + 11); }
    std::uint32_t shares() const { return static_cast<std::uint32_t>(be32(p + 19)); }
    std::uint64_t match() const { return be64(p + 23); }
};
struct FeedEWriter {
    std::uint8_t* p;
    explicit FeedEWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 31); p[0] = 'E'; }
    FeedEWriter& locate(std::uint16_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedEWriter& tracking(std::uint16_t v) { put_be(p + 3, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedEWriter& ts(std::uint64_t v) { put_be(p + 5, static_cast<std::uint64_t>(v), 6); return *this; }
    FeedEWriter& ref(std::uint64_t v) { put_be(p + 11, static_cast<std::uint64_t>(v), 8); return *this; }
    FeedEWriter& shares(std::uint32_t v) { put_be(p + 19, static_cast<std::uint64_t>(v), 4); return *this; }
    FeedEWriter& match(std::uint64_t v) { put_be(p + 23, static_cast<std::uint64_t>(v), 8); return *this; }
};
inline std::string csv(const FeedE& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + std::to_string(m.ref()) + "," + std::to_string(m.shares()) + "," + std::to_string(m.match()); }
inline void rewrite(const FeedE& m, std::uint8_t* out) { FeedEWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).ref(m.ref()).shares(m.shares()).match(m.match()); }

// feed X: 23 bytes
struct FeedX {
    static constexpr char kType = 'X';
    static constexpr std::size_t kLength = 23;
    const std::uint8_t* p;
    std::uint16_t locate() const { return static_cast<std::uint16_t>(be16(p + 1)); }
    std::uint16_t tracking() const { return static_cast<std::uint16_t>(be16(p + 3)); }
    std::uint64_t ts() const { return be(p + 5, 6); }
    std::uint64_t ref() const { return be64(p + 11); }
    std::uint32_t shares() const { return static_cast<std::uint32_t>(be32(p + 19)); }
};
struct FeedXWriter {
    std::uint8_t* p;
    explicit FeedXWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 23); p[0] = 'X'; }
    FeedXWriter& locate(std::uint16_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedXWriter& tracking(std::uint16_t v) { put_be(p + 3, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedXWriter& ts(std::uint64_t v) { put_be(p + 5, static_cast<std::uint64_t>(v), 6); return *this; }
    FeedXWriter& ref(std::uint64_t v) { put_be(p + 11, static_cast<std::uint64_t>(v), 8); return *this; }
    FeedXWriter& shares(std::uint32_t v) { put_be(p + 19, static_cast<std::uint64_t>(v), 4); return *this; }
};
inline std::string csv(const FeedX& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + std::to_string(m.ref()) + "," + std::to_string(m.shares()); }
inline void rewrite(const FeedX& m, std::uint8_t* out) { FeedXWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).ref(m.ref()).shares(m.shares()); }

// feed D: 19 bytes
struct FeedD {
    static constexpr char kType = 'D';
    static constexpr std::size_t kLength = 19;
    const std::uint8_t* p;
    std::uint16_t locate() const { return static_cast<std::uint16_t>(be16(p + 1)); }
    std::uint16_t tracking() const { return static_cast<std::uint16_t>(be16(p + 3)); }
    std::uint64_t ts() const { return be(p + 5, 6); }
    std::uint64_t ref() const { return be64(p + 11); }
};
struct FeedDWriter {
    std::uint8_t* p;
    explicit FeedDWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 19); p[0] = 'D'; }
    FeedDWriter& locate(std::uint16_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedDWriter& tracking(std::uint16_t v) { put_be(p + 3, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedDWriter& ts(std::uint64_t v) { put_be(p + 5, static_cast<std::uint64_t>(v), 6); return *this; }
    FeedDWriter& ref(std::uint64_t v) { put_be(p + 11, static_cast<std::uint64_t>(v), 8); return *this; }
};
inline std::string csv(const FeedD& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + std::to_string(m.ref()); }
inline void rewrite(const FeedD& m, std::uint8_t* out) { FeedDWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).ref(m.ref()); }

// feed P: 44 bytes
struct FeedP {
    static constexpr char kType = 'P';
    static constexpr std::size_t kLength = 44;
    const std::uint8_t* p;
    std::uint16_t locate() const { return static_cast<std::uint16_t>(be16(p + 1)); }
    std::uint16_t tracking() const { return static_cast<std::uint16_t>(be16(p + 3)); }
    std::uint64_t ts() const { return be(p + 5, 6); }
    std::uint64_t ref() const { return be64(p + 11); }
    char side() const { return static_cast<char>(p[19]); }
    std::uint32_t shares() const { return static_cast<std::uint32_t>(be32(p + 20)); }
    std::string_view stock() const { return {reinterpret_cast<const char*>(p + 24), 8}; }
    std::uint32_t price() const { return static_cast<std::uint32_t>(be32(p + 32)); }
    std::uint64_t match() const { return be64(p + 36); }
};
struct FeedPWriter {
    std::uint8_t* p;
    explicit FeedPWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 44); p[0] = 'P'; }
    FeedPWriter& locate(std::uint16_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedPWriter& tracking(std::uint16_t v) { put_be(p + 3, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedPWriter& ts(std::uint64_t v) { put_be(p + 5, static_cast<std::uint64_t>(v), 6); return *this; }
    FeedPWriter& ref(std::uint64_t v) { put_be(p + 11, static_cast<std::uint64_t>(v), 8); return *this; }
    FeedPWriter& side(char v) { p[19] = static_cast<std::uint8_t>(v); return *this; }
    FeedPWriter& shares(std::uint32_t v) { put_be(p + 20, static_cast<std::uint64_t>(v), 4); return *this; }
    FeedPWriter& stock(std::string_view v) { put_text(p + 24, v, 8); return *this; }
    FeedPWriter& price(std::uint32_t v) { put_be(p + 32, static_cast<std::uint64_t>(v), 4); return *this; }
    FeedPWriter& match(std::uint64_t v) { put_be(p + 36, static_cast<std::uint64_t>(v), 8); return *this; }
};
inline std::string csv(const FeedP& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + std::to_string(m.ref()) + "," + std::string(1, m.side()) + "," + std::to_string(m.shares()) + "," + trimmed(m.stock()) + "," + std::to_string(m.price()) + "," + std::to_string(m.match()); }
inline void rewrite(const FeedP& m, std::uint8_t* out) { FeedPWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).ref(m.ref()).side(m.side()).shares(m.shares()).stock(m.stock()).price(m.price()).match(m.match()); }

// feed U: 35 bytes
struct FeedU {
    static constexpr char kType = 'U';
    static constexpr std::size_t kLength = 35;
    const std::uint8_t* p;
    std::uint16_t locate() const { return static_cast<std::uint16_t>(be16(p + 1)); }
    std::uint16_t tracking() const { return static_cast<std::uint16_t>(be16(p + 3)); }
    std::uint64_t ts() const { return be(p + 5, 6); }
    std::uint64_t ref() const { return be64(p + 11); }
    std::uint64_t new_ref() const { return be64(p + 19); }
    std::uint32_t shares() const { return static_cast<std::uint32_t>(be32(p + 27)); }
    std::uint32_t price() const { return static_cast<std::uint32_t>(be32(p + 31)); }
};
struct FeedUWriter {
    std::uint8_t* p;
    explicit FeedUWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 35); p[0] = 'U'; }
    FeedUWriter& locate(std::uint16_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedUWriter& tracking(std::uint16_t v) { put_be(p + 3, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedUWriter& ts(std::uint64_t v) { put_be(p + 5, static_cast<std::uint64_t>(v), 6); return *this; }
    FeedUWriter& ref(std::uint64_t v) { put_be(p + 11, static_cast<std::uint64_t>(v), 8); return *this; }
    FeedUWriter& new_ref(std::uint64_t v) { put_be(p + 19, static_cast<std::uint64_t>(v), 8); return *this; }
    FeedUWriter& shares(std::uint32_t v) { put_be(p + 27, static_cast<std::uint64_t>(v), 4); return *this; }
    FeedUWriter& price(std::uint32_t v) { put_be(p + 31, static_cast<std::uint64_t>(v), 4); return *this; }
};
inline std::string csv(const FeedU& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + std::to_string(m.ref()) + "," + std::to_string(m.new_ref()) + "," + std::to_string(m.shares()) + "," + std::to_string(m.price()); }
inline void rewrite(const FeedU& m, std::uint8_t* out) { FeedUWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).ref(m.ref()).new_ref(m.new_ref()).shares(m.shares()).price(m.price()); }

// feed C: 36 bytes
struct FeedC {
    static constexpr char kType = 'C';
    static constexpr std::size_t kLength = 36;
    const std::uint8_t* p;
    std::uint16_t locate() const { return static_cast<std::uint16_t>(be16(p + 1)); }
    std::uint16_t tracking() const { return static_cast<std::uint16_t>(be16(p + 3)); }
    std::uint64_t ts() const { return be(p + 5, 6); }
    std::uint64_t ref() const { return be64(p + 11); }
    std::uint32_t shares() const { return static_cast<std::uint32_t>(be32(p + 19)); }
    std::uint64_t match() const { return be64(p + 23); }
    char printable() const { return static_cast<char>(p[31]); }
    std::uint32_t price() const { return static_cast<std::uint32_t>(be32(p + 32)); }
};
struct FeedCWriter {
    std::uint8_t* p;
    explicit FeedCWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 36); p[0] = 'C'; }
    FeedCWriter& locate(std::uint16_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedCWriter& tracking(std::uint16_t v) { put_be(p + 3, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedCWriter& ts(std::uint64_t v) { put_be(p + 5, static_cast<std::uint64_t>(v), 6); return *this; }
    FeedCWriter& ref(std::uint64_t v) { put_be(p + 11, static_cast<std::uint64_t>(v), 8); return *this; }
    FeedCWriter& shares(std::uint32_t v) { put_be(p + 19, static_cast<std::uint64_t>(v), 4); return *this; }
    FeedCWriter& match(std::uint64_t v) { put_be(p + 23, static_cast<std::uint64_t>(v), 8); return *this; }
    FeedCWriter& printable(char v) { p[31] = static_cast<std::uint8_t>(v); return *this; }
    FeedCWriter& price(std::uint32_t v) { put_be(p + 32, static_cast<std::uint64_t>(v), 4); return *this; }
};
inline std::string csv(const FeedC& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + std::to_string(m.ref()) + "," + std::to_string(m.shares()) + "," + std::to_string(m.match()) + "," + std::string(1, m.printable()) + "," + std::to_string(m.price()); }
inline void rewrite(const FeedC& m, std::uint8_t* out) { FeedCWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).ref(m.ref()).shares(m.shares()).match(m.match()).printable(m.printable()).price(m.price()); }

// feed Q: 40 bytes
struct FeedQ {
    static constexpr char kType = 'Q';
    static constexpr std::size_t kLength = 40;
    const std::uint8_t* p;
    std::uint16_t locate() const { return static_cast<std::uint16_t>(be16(p + 1)); }
    std::uint16_t tracking() const { return static_cast<std::uint16_t>(be16(p + 3)); }
    std::uint64_t ts() const { return be(p + 5, 6); }
    std::uint64_t shares() const { return be64(p + 11); }
    std::string_view stock() const { return {reinterpret_cast<const char*>(p + 19), 8}; }
    std::uint32_t price() const { return static_cast<std::uint32_t>(be32(p + 27)); }
    std::uint64_t match() const { return be64(p + 31); }
    char cross_type() const { return static_cast<char>(p[39]); }
};
struct FeedQWriter {
    std::uint8_t* p;
    explicit FeedQWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 40); p[0] = 'Q'; }
    FeedQWriter& locate(std::uint16_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedQWriter& tracking(std::uint16_t v) { put_be(p + 3, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedQWriter& ts(std::uint64_t v) { put_be(p + 5, static_cast<std::uint64_t>(v), 6); return *this; }
    FeedQWriter& shares(std::uint64_t v) { put_be(p + 11, static_cast<std::uint64_t>(v), 8); return *this; }
    FeedQWriter& stock(std::string_view v) { put_text(p + 19, v, 8); return *this; }
    FeedQWriter& price(std::uint32_t v) { put_be(p + 27, static_cast<std::uint64_t>(v), 4); return *this; }
    FeedQWriter& match(std::uint64_t v) { put_be(p + 31, static_cast<std::uint64_t>(v), 8); return *this; }
    FeedQWriter& cross_type(char v) { p[39] = static_cast<std::uint8_t>(v); return *this; }
};
inline std::string csv(const FeedQ& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + std::to_string(m.shares()) + "," + trimmed(m.stock()) + "," + std::to_string(m.price()) + "," + std::to_string(m.match()) + "," + std::string(1, m.cross_type()); }
inline void rewrite(const FeedQ& m, std::uint8_t* out) { FeedQWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).shares(m.shares()).stock(m.stock()).price(m.price()).match(m.match()).cross_type(m.cross_type()); }

// feed I: 50 bytes
struct FeedI {
    static constexpr char kType = 'I';
    static constexpr std::size_t kLength = 50;
    const std::uint8_t* p;
    std::uint16_t locate() const { return static_cast<std::uint16_t>(be16(p + 1)); }
    std::uint16_t tracking() const { return static_cast<std::uint16_t>(be16(p + 3)); }
    std::uint64_t ts() const { return be(p + 5, 6); }
    std::uint64_t paired() const { return be64(p + 11); }
    std::uint64_t imbalance() const { return be64(p + 19); }
    char direction() const { return static_cast<char>(p[27]); }
    std::string_view stock() const { return {reinterpret_cast<const char*>(p + 28), 8}; }
    std::uint32_t far() const { return static_cast<std::uint32_t>(be32(p + 36)); }
    std::uint32_t near() const { return static_cast<std::uint32_t>(be32(p + 40)); }
    std::uint32_t ref_price() const { return static_cast<std::uint32_t>(be32(p + 44)); }
    char cross_type() const { return static_cast<char>(p[48]); }
    char variation() const { return static_cast<char>(p[49]); }
};
struct FeedIWriter {
    std::uint8_t* p;
    explicit FeedIWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 50); p[0] = 'I'; }
    FeedIWriter& locate(std::uint16_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedIWriter& tracking(std::uint16_t v) { put_be(p + 3, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedIWriter& ts(std::uint64_t v) { put_be(p + 5, static_cast<std::uint64_t>(v), 6); return *this; }
    FeedIWriter& paired(std::uint64_t v) { put_be(p + 11, static_cast<std::uint64_t>(v), 8); return *this; }
    FeedIWriter& imbalance(std::uint64_t v) { put_be(p + 19, static_cast<std::uint64_t>(v), 8); return *this; }
    FeedIWriter& direction(char v) { p[27] = static_cast<std::uint8_t>(v); return *this; }
    FeedIWriter& stock(std::string_view v) { put_text(p + 28, v, 8); return *this; }
    FeedIWriter& far(std::uint32_t v) { put_be(p + 36, static_cast<std::uint64_t>(v), 4); return *this; }
    FeedIWriter& near(std::uint32_t v) { put_be(p + 40, static_cast<std::uint64_t>(v), 4); return *this; }
    FeedIWriter& ref_price(std::uint32_t v) { put_be(p + 44, static_cast<std::uint64_t>(v), 4); return *this; }
    FeedIWriter& cross_type(char v) { p[48] = static_cast<std::uint8_t>(v); return *this; }
    FeedIWriter& variation(char v) { p[49] = static_cast<std::uint8_t>(v); return *this; }
};
inline std::string csv(const FeedI& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + std::to_string(m.paired()) + "," + std::to_string(m.imbalance()) + "," + std::string(1, m.direction()) + "," + trimmed(m.stock()) + "," + std::to_string(m.far()) + "," + std::to_string(m.near()) + "," + std::to_string(m.ref_price()) + "," + std::string(1, m.cross_type()) + "," + std::string(1, m.variation()); }
inline void rewrite(const FeedI& m, std::uint8_t* out) { FeedIWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).paired(m.paired()).imbalance(m.imbalance()).direction(m.direction()).stock(m.stock()).far(m.far()).near(m.near()).ref_price(m.ref_price()).cross_type(m.cross_type()).variation(m.variation()); }

// feed S: 12 bytes
struct FeedS {
    static constexpr char kType = 'S';
    static constexpr std::size_t kLength = 12;
    const std::uint8_t* p;
    std::uint16_t locate() const { return static_cast<std::uint16_t>(be16(p + 1)); }
    std::uint16_t tracking() const { return static_cast<std::uint16_t>(be16(p + 3)); }
    std::uint64_t ts() const { return be(p + 5, 6); }
    char event() const { return static_cast<char>(p[11]); }
};
struct FeedSWriter {
    std::uint8_t* p;
    explicit FeedSWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 12); p[0] = 'S'; }
    FeedSWriter& locate(std::uint16_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedSWriter& tracking(std::uint16_t v) { put_be(p + 3, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedSWriter& ts(std::uint64_t v) { put_be(p + 5, static_cast<std::uint64_t>(v), 6); return *this; }
    FeedSWriter& event(char v) { p[11] = static_cast<std::uint8_t>(v); return *this; }
};
inline std::string csv(const FeedS& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + std::string(1, m.event()); }
inline void rewrite(const FeedS& m, std::uint8_t* out) { FeedSWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).event(m.event()); }

// feed H: 25 bytes
struct FeedH {
    static constexpr char kType = 'H';
    static constexpr std::size_t kLength = 25;
    const std::uint8_t* p;
    std::uint16_t locate() const { return static_cast<std::uint16_t>(be16(p + 1)); }
    std::uint16_t tracking() const { return static_cast<std::uint16_t>(be16(p + 3)); }
    std::uint64_t ts() const { return be(p + 5, 6); }
    std::string_view stock() const { return {reinterpret_cast<const char*>(p + 11), 8}; }
    char state() const { return static_cast<char>(p[19]); }
    char reserved() const { return static_cast<char>(p[20]); }
    std::string_view reason() const { return {reinterpret_cast<const char*>(p + 21), 4}; }
};
struct FeedHWriter {
    std::uint8_t* p;
    explicit FeedHWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 25); p[0] = 'H'; }
    FeedHWriter& locate(std::uint16_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedHWriter& tracking(std::uint16_t v) { put_be(p + 3, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedHWriter& ts(std::uint64_t v) { put_be(p + 5, static_cast<std::uint64_t>(v), 6); return *this; }
    FeedHWriter& stock(std::string_view v) { put_text(p + 11, v, 8); return *this; }
    FeedHWriter& state(char v) { p[19] = static_cast<std::uint8_t>(v); return *this; }
    FeedHWriter& reserved(char v) { p[20] = static_cast<std::uint8_t>(v); return *this; }
    FeedHWriter& reason(std::string_view v) { put_text(p + 21, v, 4); return *this; }
};
inline std::string csv(const FeedH& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + trimmed(m.stock()) + "," + std::string(1, m.state()) + "," + std::string(1, m.reserved()) + "," + trimmed(m.reason()); }
inline void rewrite(const FeedH& m, std::uint8_t* out) { FeedHWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).stock(m.stock()).state(m.state()).reserved(m.reserved()).reason(m.reason()); }

// feed R: 28 bytes
struct FeedR {
    static constexpr char kType = 'R';
    static constexpr std::size_t kLength = 28;
    const std::uint8_t* p;
    std::uint16_t locate() const { return static_cast<std::uint16_t>(be16(p + 1)); }
    std::uint16_t tracking() const { return static_cast<std::uint16_t>(be16(p + 3)); }
    std::uint64_t ts() const { return be(p + 5, 6); }
    std::string_view stock() const { return {reinterpret_cast<const char*>(p + 11), 8}; }
    std::uint32_t tick() const { return static_cast<std::uint32_t>(be32(p + 19)); }
    std::uint32_t lot() const { return static_cast<std::uint32_t>(be32(p + 23)); }
    char matching() const { return static_cast<char>(p[27]); }
};
struct FeedRWriter {
    std::uint8_t* p;
    explicit FeedRWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 28); p[0] = 'R'; }
    FeedRWriter& locate(std::uint16_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedRWriter& tracking(std::uint16_t v) { put_be(p + 3, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedRWriter& ts(std::uint64_t v) { put_be(p + 5, static_cast<std::uint64_t>(v), 6); return *this; }
    FeedRWriter& stock(std::string_view v) { put_text(p + 11, v, 8); return *this; }
    FeedRWriter& tick(std::uint32_t v) { put_be(p + 19, static_cast<std::uint64_t>(v), 4); return *this; }
    FeedRWriter& lot(std::uint32_t v) { put_be(p + 23, static_cast<std::uint64_t>(v), 4); return *this; }
    FeedRWriter& matching(char v) { p[27] = static_cast<std::uint8_t>(v); return *this; }
};
inline std::string csv(const FeedR& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + trimmed(m.stock()) + "," + std::to_string(m.tick()) + "," + std::to_string(m.lot()) + "," + std::string(1, m.matching()); }
inline void rewrite(const FeedR& m, std::uint8_t* out) { FeedRWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).stock(m.stock()).tick(m.tick()).lot(m.lot()).matching(m.matching()); }

// feed G: 23 bytes
struct FeedG {
    static constexpr char kType = 'G';
    static constexpr std::size_t kLength = 23;
    const std::uint8_t* p;
    std::uint16_t locate() const { return static_cast<std::uint16_t>(be16(p + 1)); }
    std::uint16_t tracking() const { return static_cast<std::uint16_t>(be16(p + 3)); }
    std::uint64_t ts() const { return be(p + 5, 6); }
    std::uint64_t seq() const { return be64(p + 11); }
    std::uint32_t orders() const { return static_cast<std::uint32_t>(be32(p + 19)); }
};
struct FeedGWriter {
    std::uint8_t* p;
    explicit FeedGWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 23); p[0] = 'G'; }
    FeedGWriter& locate(std::uint16_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedGWriter& tracking(std::uint16_t v) { put_be(p + 3, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedGWriter& ts(std::uint64_t v) { put_be(p + 5, static_cast<std::uint64_t>(v), 6); return *this; }
    FeedGWriter& seq(std::uint64_t v) { put_be(p + 11, static_cast<std::uint64_t>(v), 8); return *this; }
    FeedGWriter& orders(std::uint32_t v) { put_be(p + 19, static_cast<std::uint64_t>(v), 4); return *this; }
};
inline std::string csv(const FeedG& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + std::to_string(m.seq()) + "," + std::to_string(m.orders()); }
inline void rewrite(const FeedG& m, std::uint8_t* out) { FeedGWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).seq(m.seq()).orders(m.orders()); }

// feed W: 23 bytes
struct FeedW {
    static constexpr char kType = 'W';
    static constexpr std::size_t kLength = 23;
    const std::uint8_t* p;
    std::uint16_t locate() const { return static_cast<std::uint16_t>(be16(p + 1)); }
    std::uint16_t tracking() const { return static_cast<std::uint16_t>(be16(p + 3)); }
    std::uint64_t ts() const { return be(p + 5, 6); }
    std::uint64_t seq() const { return be64(p + 11); }
    std::uint32_t crc() const { return static_cast<std::uint32_t>(be32(p + 19)); }
};
struct FeedWWriter {
    std::uint8_t* p;
    explicit FeedWWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 23); p[0] = 'W'; }
    FeedWWriter& locate(std::uint16_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedWWriter& tracking(std::uint16_t v) { put_be(p + 3, static_cast<std::uint64_t>(v), 2); return *this; }
    FeedWWriter& ts(std::uint64_t v) { put_be(p + 5, static_cast<std::uint64_t>(v), 6); return *this; }
    FeedWWriter& seq(std::uint64_t v) { put_be(p + 11, static_cast<std::uint64_t>(v), 8); return *this; }
    FeedWWriter& crc(std::uint32_t v) { put_be(p + 19, static_cast<std::uint64_t>(v), 4); return *this; }
};
inline std::string csv(const FeedW& m) { return std::to_string(m.locate()) + "," + std::to_string(m.tracking()) + "," + std::to_string(m.ts()) + "," + std::to_string(m.seq()) + "," + std::to_string(m.crc()); }
inline void rewrite(const FeedW& m, std::uint8_t* out) { FeedWWriter(out).locate(m.locate()).tracking(m.tracking()).ts(m.ts()).seq(m.seq()).crc(m.crc()); }

// Calls v(<feed message>) for one message of the feed protocol; false if the type is
// unknown or the length does not match it.
template <class V>
bool dispatch_feed(const std::uint8_t* p, std::size_t n, V&& v) {
    if (n == 0) return false;
    switch (p[0]) {
        case 'A': if (n != FeedA::kLength) return false; v(FeedA{p}); return true;
        case 'E': if (n != FeedE::kLength) return false; v(FeedE{p}); return true;
        case 'X': if (n != FeedX::kLength) return false; v(FeedX{p}); return true;
        case 'D': if (n != FeedD::kLength) return false; v(FeedD{p}); return true;
        case 'P': if (n != FeedP::kLength) return false; v(FeedP{p}); return true;
        case 'U': if (n != FeedU::kLength) return false; v(FeedU{p}); return true;
        case 'C': if (n != FeedC::kLength) return false; v(FeedC{p}); return true;
        case 'Q': if (n != FeedQ::kLength) return false; v(FeedQ{p}); return true;
        case 'I': if (n != FeedI::kLength) return false; v(FeedI{p}); return true;
        case 'S': if (n != FeedS::kLength) return false; v(FeedS{p}); return true;
        case 'H': if (n != FeedH::kLength) return false; v(FeedH{p}); return true;
        case 'R': if (n != FeedR::kLength) return false; v(FeedR{p}); return true;
        case 'G': if (n != FeedG::kLength) return false; v(FeedG{p}); return true;
        case 'W': if (n != FeedW::kLength) return false; v(FeedW{p}); return true;
        default: return false;
    }
}

// in O: 38 bytes
struct InO {
    static constexpr char kType = 'O';
    static constexpr std::size_t kLength = 38;
    const std::uint8_t* p;
    std::uint64_t cl_ord_id() const { return be64(p + 1); }
    std::uint16_t locate() const { return static_cast<std::uint16_t>(be16(p + 9)); }
    char side() const { return static_cast<char>(p[11]); }
    std::uint32_t qty() const { return static_cast<std::uint32_t>(be32(p + 12)); }
    std::uint32_t price() const { return static_cast<std::uint32_t>(be32(p + 16)); }
    char tif() const { return static_cast<char>(p[20]); }
    char display() const { return static_cast<char>(p[21]); }
    char post_only() const { return static_cast<char>(p[22]); }
    std::uint32_t display_qty() const { return static_cast<std::uint32_t>(be32(p + 23)); }
    std::uint32_t min_qty() const { return static_cast<std::uint32_t>(be32(p + 27)); }
    std::uint16_t stp_group() const { return static_cast<std::uint16_t>(be16(p + 31)); }
    char stp_mode() const { return static_cast<char>(p[33]); }
    std::uint32_t stop_price() const { return static_cast<std::uint32_t>(be32(p + 34)); }
};
struct InOWriter {
    std::uint8_t* p;
    explicit InOWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 38); p[0] = 'O'; }
    InOWriter& cl_ord_id(std::uint64_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 8); return *this; }
    InOWriter& locate(std::uint16_t v) { put_be(p + 9, static_cast<std::uint64_t>(v), 2); return *this; }
    InOWriter& side(char v) { p[11] = static_cast<std::uint8_t>(v); return *this; }
    InOWriter& qty(std::uint32_t v) { put_be(p + 12, static_cast<std::uint64_t>(v), 4); return *this; }
    InOWriter& price(std::uint32_t v) { put_be(p + 16, static_cast<std::uint64_t>(v), 4); return *this; }
    InOWriter& tif(char v) { p[20] = static_cast<std::uint8_t>(v); return *this; }
    InOWriter& display(char v) { p[21] = static_cast<std::uint8_t>(v); return *this; }
    InOWriter& post_only(char v) { p[22] = static_cast<std::uint8_t>(v); return *this; }
    InOWriter& display_qty(std::uint32_t v) { put_be(p + 23, static_cast<std::uint64_t>(v), 4); return *this; }
    InOWriter& min_qty(std::uint32_t v) { put_be(p + 27, static_cast<std::uint64_t>(v), 4); return *this; }
    InOWriter& stp_group(std::uint16_t v) { put_be(p + 31, static_cast<std::uint64_t>(v), 2); return *this; }
    InOWriter& stp_mode(char v) { p[33] = static_cast<std::uint8_t>(v); return *this; }
    InOWriter& stop_price(std::uint32_t v) { put_be(p + 34, static_cast<std::uint64_t>(v), 4); return *this; }
};
inline std::string csv(const InO& m) { return std::to_string(m.cl_ord_id()) + "," + std::to_string(m.locate()) + "," + std::string(1, m.side()) + "," + std::to_string(m.qty()) + "," + std::to_string(m.price()) + "," + std::string(1, m.tif()) + "," + std::string(1, m.display()) + "," + std::string(1, m.post_only()) + "," + std::to_string(m.display_qty()) + "," + std::to_string(m.min_qty()) + "," + std::to_string(m.stp_group()) + "," + std::string(1, m.stp_mode()) + "," + std::to_string(m.stop_price()); }
inline void rewrite(const InO& m, std::uint8_t* out) { InOWriter(out).cl_ord_id(m.cl_ord_id()).locate(m.locate()).side(m.side()).qty(m.qty()).price(m.price()).tif(m.tif()).display(m.display()).post_only(m.post_only()).display_qty(m.display_qty()).min_qty(m.min_qty()).stp_group(m.stp_group()).stp_mode(m.stp_mode()).stop_price(m.stop_price()); }

// in U: 25 bytes
struct InU {
    static constexpr char kType = 'U';
    static constexpr std::size_t kLength = 25;
    const std::uint8_t* p;
    std::uint64_t cl_ord_id() const { return be64(p + 1); }
    std::uint64_t new_cl_ord_id() const { return be64(p + 9); }
    std::uint32_t qty() const { return static_cast<std::uint32_t>(be32(p + 17)); }
    std::uint32_t price() const { return static_cast<std::uint32_t>(be32(p + 21)); }
};
struct InUWriter {
    std::uint8_t* p;
    explicit InUWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 25); p[0] = 'U'; }
    InUWriter& cl_ord_id(std::uint64_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 8); return *this; }
    InUWriter& new_cl_ord_id(std::uint64_t v) { put_be(p + 9, static_cast<std::uint64_t>(v), 8); return *this; }
    InUWriter& qty(std::uint32_t v) { put_be(p + 17, static_cast<std::uint64_t>(v), 4); return *this; }
    InUWriter& price(std::uint32_t v) { put_be(p + 21, static_cast<std::uint64_t>(v), 4); return *this; }
};
inline std::string csv(const InU& m) { return std::to_string(m.cl_ord_id()) + "," + std::to_string(m.new_cl_ord_id()) + "," + std::to_string(m.qty()) + "," + std::to_string(m.price()); }
inline void rewrite(const InU& m, std::uint8_t* out) { InUWriter(out).cl_ord_id(m.cl_ord_id()).new_cl_ord_id(m.new_cl_ord_id()).qty(m.qty()).price(m.price()); }

// in X: 13 bytes
struct InX {
    static constexpr char kType = 'X';
    static constexpr std::size_t kLength = 13;
    const std::uint8_t* p;
    std::uint64_t cl_ord_id() const { return be64(p + 1); }
    std::uint32_t leave_qty() const { return static_cast<std::uint32_t>(be32(p + 9)); }
};
struct InXWriter {
    std::uint8_t* p;
    explicit InXWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 13); p[0] = 'X'; }
    InXWriter& cl_ord_id(std::uint64_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 8); return *this; }
    InXWriter& leave_qty(std::uint32_t v) { put_be(p + 9, static_cast<std::uint64_t>(v), 4); return *this; }
};
inline std::string csv(const InX& m) { return std::to_string(m.cl_ord_id()) + "," + std::to_string(m.leave_qty()); }
inline void rewrite(const InX& m, std::uint8_t* out) { InXWriter(out).cl_ord_id(m.cl_ord_id()).leave_qty(m.leave_qty()); }

// in M: 4 bytes
struct InM {
    static constexpr char kType = 'M';
    static constexpr std::size_t kLength = 4;
    const std::uint8_t* p;
    std::uint16_t locate() const { return static_cast<std::uint16_t>(be16(p + 1)); }
    char side() const { return static_cast<char>(p[3]); }
};
struct InMWriter {
    std::uint8_t* p;
    explicit InMWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 4); p[0] = 'M'; }
    InMWriter& locate(std::uint16_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 2); return *this; }
    InMWriter& side(char v) { p[3] = static_cast<std::uint8_t>(v); return *this; }
};
inline std::string csv(const InM& m) { return std::to_string(m.locate()) + "," + std::string(1, m.side()); }
inline void rewrite(const InM& m, std::uint8_t* out) { InMWriter(out).locate(m.locate()).side(m.side()); }

// in Q: 27 bytes
struct InQ {
    static constexpr char kType = 'Q';
    static constexpr std::size_t kLength = 27;
    const std::uint8_t* p;
    std::uint64_t quote_id() const { return be64(p + 1); }
    std::uint16_t locate() const { return static_cast<std::uint16_t>(be16(p + 9)); }
    std::uint32_t bid_price() const { return static_cast<std::uint32_t>(be32(p + 11)); }
    std::uint32_t bid_qty() const { return static_cast<std::uint32_t>(be32(p + 15)); }
    std::uint32_t ask_price() const { return static_cast<std::uint32_t>(be32(p + 19)); }
    std::uint32_t ask_qty() const { return static_cast<std::uint32_t>(be32(p + 23)); }
};
struct InQWriter {
    std::uint8_t* p;
    explicit InQWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 27); p[0] = 'Q'; }
    InQWriter& quote_id(std::uint64_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 8); return *this; }
    InQWriter& locate(std::uint16_t v) { put_be(p + 9, static_cast<std::uint64_t>(v), 2); return *this; }
    InQWriter& bid_price(std::uint32_t v) { put_be(p + 11, static_cast<std::uint64_t>(v), 4); return *this; }
    InQWriter& bid_qty(std::uint32_t v) { put_be(p + 15, static_cast<std::uint64_t>(v), 4); return *this; }
    InQWriter& ask_price(std::uint32_t v) { put_be(p + 19, static_cast<std::uint64_t>(v), 4); return *this; }
    InQWriter& ask_qty(std::uint32_t v) { put_be(p + 23, static_cast<std::uint64_t>(v), 4); return *this; }
};
inline std::string csv(const InQ& m) { return std::to_string(m.quote_id()) + "," + std::to_string(m.locate()) + "," + std::to_string(m.bid_price()) + "," + std::to_string(m.bid_qty()) + "," + std::to_string(m.ask_price()) + "," + std::to_string(m.ask_qty()); }
inline void rewrite(const InQ& m, std::uint8_t* out) { InQWriter(out).quote_id(m.quote_id()).locate(m.locate()).bid_price(m.bid_price()).bid_qty(m.bid_qty()).ask_price(m.ask_price()).ask_qty(m.ask_qty()); }

// Calls v(<in message>) for one message of the in protocol; false if the type is
// unknown or the length does not match it.
template <class V>
bool dispatch_in(const std::uint8_t* p, std::size_t n, V&& v) {
    if (n == 0) return false;
    switch (p[0]) {
        case 'O': if (n != InO::kLength) return false; v(InO{p}); return true;
        case 'U': if (n != InU::kLength) return false; v(InU{p}); return true;
        case 'X': if (n != InX::kLength) return false; v(InX{p}); return true;
        case 'M': if (n != InM::kLength) return false; v(InM{p}); return true;
        case 'Q': if (n != InQ::kLength) return false; v(InQ{p}); return true;
        default: return false;
    }
}

// out S: 10 bytes
struct OutS {
    static constexpr char kType = 'S';
    static constexpr std::size_t kLength = 10;
    const std::uint8_t* p;
    std::uint64_t ts() const { return be64(p + 1); }
    char event() const { return static_cast<char>(p[9]); }
};
struct OutSWriter {
    std::uint8_t* p;
    explicit OutSWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 10); p[0] = 'S'; }
    OutSWriter& ts(std::uint64_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 8); return *this; }
    OutSWriter& event(char v) { p[9] = static_cast<std::uint8_t>(v); return *this; }
};
inline std::string csv(const OutS& m) { return std::to_string(m.ts()) + "," + std::string(1, m.event()); }
inline void rewrite(const OutS& m, std::uint8_t* out) { OutSWriter(out).ts(m.ts()).event(m.event()); }

// out A: 39 bytes
struct OutA {
    static constexpr char kType = 'A';
    static constexpr std::size_t kLength = 39;
    const std::uint8_t* p;
    std::uint64_t ts() const { return be64(p + 1); }
    std::uint64_t cl_ord_id() const { return be64(p + 9); }
    std::uint64_t ref() const { return be64(p + 17); }
    std::uint16_t locate() const { return static_cast<std::uint16_t>(be16(p + 25)); }
    char side() const { return static_cast<char>(p[27]); }
    std::uint32_t qty() const { return static_cast<std::uint32_t>(be32(p + 28)); }
    std::uint32_t price() const { return static_cast<std::uint32_t>(be32(p + 32)); }
    char tif() const { return static_cast<char>(p[36]); }
    char display() const { return static_cast<char>(p[37]); }
    char state() const { return static_cast<char>(p[38]); }
};
struct OutAWriter {
    std::uint8_t* p;
    explicit OutAWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 39); p[0] = 'A'; }
    OutAWriter& ts(std::uint64_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 8); return *this; }
    OutAWriter& cl_ord_id(std::uint64_t v) { put_be(p + 9, static_cast<std::uint64_t>(v), 8); return *this; }
    OutAWriter& ref(std::uint64_t v) { put_be(p + 17, static_cast<std::uint64_t>(v), 8); return *this; }
    OutAWriter& locate(std::uint16_t v) { put_be(p + 25, static_cast<std::uint64_t>(v), 2); return *this; }
    OutAWriter& side(char v) { p[27] = static_cast<std::uint8_t>(v); return *this; }
    OutAWriter& qty(std::uint32_t v) { put_be(p + 28, static_cast<std::uint64_t>(v), 4); return *this; }
    OutAWriter& price(std::uint32_t v) { put_be(p + 32, static_cast<std::uint64_t>(v), 4); return *this; }
    OutAWriter& tif(char v) { p[36] = static_cast<std::uint8_t>(v); return *this; }
    OutAWriter& display(char v) { p[37] = static_cast<std::uint8_t>(v); return *this; }
    OutAWriter& state(char v) { p[38] = static_cast<std::uint8_t>(v); return *this; }
};
inline std::string csv(const OutA& m) { return std::to_string(m.ts()) + "," + std::to_string(m.cl_ord_id()) + "," + std::to_string(m.ref()) + "," + std::to_string(m.locate()) + "," + std::string(1, m.side()) + "," + std::to_string(m.qty()) + "," + std::to_string(m.price()) + "," + std::string(1, m.tif()) + "," + std::string(1, m.display()) + "," + std::string(1, m.state()); }
inline void rewrite(const OutA& m, std::uint8_t* out) { OutAWriter(out).ts(m.ts()).cl_ord_id(m.cl_ord_id()).ref(m.ref()).locate(m.locate()).side(m.side()).qty(m.qty()).price(m.price()).tif(m.tif()).display(m.display()).state(m.state()); }

// out U: 42 bytes
struct OutU {
    static constexpr char kType = 'U';
    static constexpr std::size_t kLength = 42;
    const std::uint8_t* p;
    std::uint64_t ts() const { return be64(p + 1); }
    std::uint64_t cl_ord_id() const { return be64(p + 9); }
    std::uint64_t new_cl_ord_id() const { return be64(p + 17); }
    std::uint64_t ref() const { return be64(p + 25); }
    std::uint32_t qty() const { return static_cast<std::uint32_t>(be32(p + 33)); }
    std::uint32_t price() const { return static_cast<std::uint32_t>(be32(p + 37)); }
    char priority() const { return static_cast<char>(p[41]); }
};
struct OutUWriter {
    std::uint8_t* p;
    explicit OutUWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 42); p[0] = 'U'; }
    OutUWriter& ts(std::uint64_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 8); return *this; }
    OutUWriter& cl_ord_id(std::uint64_t v) { put_be(p + 9, static_cast<std::uint64_t>(v), 8); return *this; }
    OutUWriter& new_cl_ord_id(std::uint64_t v) { put_be(p + 17, static_cast<std::uint64_t>(v), 8); return *this; }
    OutUWriter& ref(std::uint64_t v) { put_be(p + 25, static_cast<std::uint64_t>(v), 8); return *this; }
    OutUWriter& qty(std::uint32_t v) { put_be(p + 33, static_cast<std::uint64_t>(v), 4); return *this; }
    OutUWriter& price(std::uint32_t v) { put_be(p + 37, static_cast<std::uint64_t>(v), 4); return *this; }
    OutUWriter& priority(char v) { p[41] = static_cast<std::uint8_t>(v); return *this; }
};
inline std::string csv(const OutU& m) { return std::to_string(m.ts()) + "," + std::to_string(m.cl_ord_id()) + "," + std::to_string(m.new_cl_ord_id()) + "," + std::to_string(m.ref()) + "," + std::to_string(m.qty()) + "," + std::to_string(m.price()) + "," + std::string(1, m.priority()); }
inline void rewrite(const OutU& m, std::uint8_t* out) { OutUWriter(out).ts(m.ts()).cl_ord_id(m.cl_ord_id()).new_cl_ord_id(m.new_cl_ord_id()).ref(m.ref()).qty(m.qty()).price(m.price()).priority(m.priority()); }

// out C: 22 bytes
struct OutC {
    static constexpr char kType = 'C';
    static constexpr std::size_t kLength = 22;
    const std::uint8_t* p;
    std::uint64_t ts() const { return be64(p + 1); }
    std::uint64_t cl_ord_id() const { return be64(p + 9); }
    std::uint32_t decrement() const { return static_cast<std::uint32_t>(be32(p + 17)); }
    char reason() const { return static_cast<char>(p[21]); }
};
struct OutCWriter {
    std::uint8_t* p;
    explicit OutCWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 22); p[0] = 'C'; }
    OutCWriter& ts(std::uint64_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 8); return *this; }
    OutCWriter& cl_ord_id(std::uint64_t v) { put_be(p + 9, static_cast<std::uint64_t>(v), 8); return *this; }
    OutCWriter& decrement(std::uint32_t v) { put_be(p + 17, static_cast<std::uint64_t>(v), 4); return *this; }
    OutCWriter& reason(char v) { p[21] = static_cast<std::uint8_t>(v); return *this; }
};
inline std::string csv(const OutC& m) { return std::to_string(m.ts()) + "," + std::to_string(m.cl_ord_id()) + "," + std::to_string(m.decrement()) + "," + std::string(1, m.reason()); }
inline void rewrite(const OutC& m, std::uint8_t* out) { OutCWriter(out).ts(m.ts()).cl_ord_id(m.cl_ord_id()).decrement(m.decrement()).reason(m.reason()); }

// out E: 46 bytes
struct OutE {
    static constexpr char kType = 'E';
    static constexpr std::size_t kLength = 46;
    const std::uint8_t* p;
    std::uint64_t ts() const { return be64(p + 1); }
    std::uint64_t cl_ord_id() const { return be64(p + 9); }
    std::uint32_t qty() const { return static_cast<std::uint32_t>(be32(p + 17)); }
    std::uint32_t price() const { return static_cast<std::uint32_t>(be32(p + 21)); }
    std::uint64_t match() const { return be64(p + 25); }
    char liquidity() const { return static_cast<char>(p[33]); }
    std::int64_t fee() const { return static_cast<std::int64_t>(be64(p + 34)); }
    std::uint32_t leaves() const { return static_cast<std::uint32_t>(be32(p + 42)); }
};
struct OutEWriter {
    std::uint8_t* p;
    explicit OutEWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 46); p[0] = 'E'; }
    OutEWriter& ts(std::uint64_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 8); return *this; }
    OutEWriter& cl_ord_id(std::uint64_t v) { put_be(p + 9, static_cast<std::uint64_t>(v), 8); return *this; }
    OutEWriter& qty(std::uint32_t v) { put_be(p + 17, static_cast<std::uint64_t>(v), 4); return *this; }
    OutEWriter& price(std::uint32_t v) { put_be(p + 21, static_cast<std::uint64_t>(v), 4); return *this; }
    OutEWriter& match(std::uint64_t v) { put_be(p + 25, static_cast<std::uint64_t>(v), 8); return *this; }
    OutEWriter& liquidity(char v) { p[33] = static_cast<std::uint8_t>(v); return *this; }
    OutEWriter& fee(std::int64_t v) { put_be(p + 34, static_cast<std::uint64_t>(v), 8); return *this; }
    OutEWriter& leaves(std::uint32_t v) { put_be(p + 42, static_cast<std::uint64_t>(v), 4); return *this; }
};
inline std::string csv(const OutE& m) { return std::to_string(m.ts()) + "," + std::to_string(m.cl_ord_id()) + "," + std::to_string(m.qty()) + "," + std::to_string(m.price()) + "," + std::to_string(m.match()) + "," + std::string(1, m.liquidity()) + "," + std::to_string(m.fee()) + "," + std::to_string(m.leaves()); }
inline void rewrite(const OutE& m, std::uint8_t* out) { OutEWriter(out).ts(m.ts()).cl_ord_id(m.cl_ord_id()).qty(m.qty()).price(m.price()).match(m.match()).liquidity(m.liquidity()).fee(m.fee()).leaves(m.leaves()); }

// out J: 18 bytes
struct OutJ {
    static constexpr char kType = 'J';
    static constexpr std::size_t kLength = 18;
    const std::uint8_t* p;
    std::uint64_t ts() const { return be64(p + 1); }
    std::uint64_t cl_ord_id() const { return be64(p + 9); }
    char reason() const { return static_cast<char>(p[17]); }
};
struct OutJWriter {
    std::uint8_t* p;
    explicit OutJWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 18); p[0] = 'J'; }
    OutJWriter& ts(std::uint64_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 8); return *this; }
    OutJWriter& cl_ord_id(std::uint64_t v) { put_be(p + 9, static_cast<std::uint64_t>(v), 8); return *this; }
    OutJWriter& reason(char v) { p[17] = static_cast<std::uint8_t>(v); return *this; }
};
inline std::string csv(const OutJ& m) { return std::to_string(m.ts()) + "," + std::to_string(m.cl_ord_id()) + "," + std::string(1, m.reason()); }
inline void rewrite(const OutJ& m, std::uint8_t* out) { OutJWriter(out).ts(m.ts()).cl_ord_id(m.cl_ord_id()).reason(m.reason()); }

// Calls v(<out message>) for one message of the out protocol; false if the type is
// unknown or the length does not match it.
template <class V>
bool dispatch_out(const std::uint8_t* p, std::size_t n, V&& v) {
    if (n == 0) return false;
    switch (p[0]) {
        case 'S': if (n != OutS::kLength) return false; v(OutS{p}); return true;
        case 'A': if (n != OutA::kLength) return false; v(OutA{p}); return true;
        case 'U': if (n != OutU::kLength) return false; v(OutU{p}); return true;
        case 'C': if (n != OutC::kLength) return false; v(OutC{p}); return true;
        case 'E': if (n != OutE::kLength) return false; v(OutE{p}); return true;
        case 'J': if (n != OutJ::kLength) return false; v(OutJ{p}); return true;
        default: return false;
    }
}

// ctl L: 8 bytes
struct CtlL {
    static constexpr char kType = 'L';
    static constexpr std::size_t kLength = 8;
    const std::uint8_t* p;
    std::uint16_t session() const { return static_cast<std::uint16_t>(be16(p + 1)); }
    std::uint32_t firm() const { return static_cast<std::uint32_t>(be32(p + 3)); }
    char cod() const { return static_cast<char>(p[7]); }
};
struct CtlLWriter {
    std::uint8_t* p;
    explicit CtlLWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 8); p[0] = 'L'; }
    CtlLWriter& session(std::uint16_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 2); return *this; }
    CtlLWriter& firm(std::uint32_t v) { put_be(p + 3, static_cast<std::uint64_t>(v), 4); return *this; }
    CtlLWriter& cod(char v) { p[7] = static_cast<std::uint8_t>(v); return *this; }
};
inline std::string csv(const CtlL& m) { return std::to_string(m.session()) + "," + std::to_string(m.firm()) + "," + std::string(1, m.cod()); }
inline void rewrite(const CtlL& m, std::uint8_t* out) { CtlLWriter(out).session(m.session()).firm(m.firm()).cod(m.cod()); }

// ctl D: 3 bytes
struct CtlD {
    static constexpr char kType = 'D';
    static constexpr std::size_t kLength = 3;
    const std::uint8_t* p;
    std::uint16_t session() const { return static_cast<std::uint16_t>(be16(p + 1)); }
};
struct CtlDWriter {
    std::uint8_t* p;
    explicit CtlDWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 3); p[0] = 'D'; }
    CtlDWriter& session(std::uint16_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 2); return *this; }
};
inline std::string csv(const CtlD& m) { return std::to_string(m.session()); }
inline void rewrite(const CtlD& m, std::uint8_t* out) { CtlDWriter(out).session(m.session()); }

// ctl P: 8 bytes
struct CtlP {
    static constexpr char kType = 'P';
    static constexpr std::size_t kLength = 8;
    const std::uint8_t* p;
    std::uint16_t locate() const { return static_cast<std::uint16_t>(be16(p + 1)); }
    char phase() const { return static_cast<char>(p[3]); }
    std::string_view reason() const { return {reinterpret_cast<const char*>(p + 4), 4}; }
};
struct CtlPWriter {
    std::uint8_t* p;
    explicit CtlPWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 8); p[0] = 'P'; }
    CtlPWriter& locate(std::uint16_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 2); return *this; }
    CtlPWriter& phase(char v) { p[3] = static_cast<std::uint8_t>(v); return *this; }
    CtlPWriter& reason(std::string_view v) { put_text(p + 4, v, 4); return *this; }
};
inline std::string csv(const CtlP& m) { return std::to_string(m.locate()) + "," + std::string(1, m.phase()) + "," + trimmed(m.reason()); }
inline void rewrite(const CtlP& m, std::uint8_t* out) { CtlPWriter(out).locate(m.locate()).phase(m.phase()).reason(m.reason()); }

// ctl X: 4 bytes
struct CtlX {
    static constexpr char kType = 'X';
    static constexpr std::size_t kLength = 4;
    const std::uint8_t* p;
    std::uint16_t locate() const { return static_cast<std::uint16_t>(be16(p + 1)); }
    char cross_type() const { return static_cast<char>(p[3]); }
};
struct CtlXWriter {
    std::uint8_t* p;
    explicit CtlXWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 4); p[0] = 'X'; }
    CtlXWriter& locate(std::uint16_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 2); return *this; }
    CtlXWriter& cross_type(char v) { p[3] = static_cast<std::uint8_t>(v); return *this; }
};
inline std::string csv(const CtlX& m) { return std::to_string(m.locate()) + "," + std::string(1, m.cross_type()); }
inline void rewrite(const CtlX& m, std::uint8_t* out) { CtlXWriter(out).locate(m.locate()).cross_type(m.cross_type()); }

// ctl I: 4 bytes
struct CtlI {
    static constexpr char kType = 'I';
    static constexpr std::size_t kLength = 4;
    const std::uint8_t* p;
    std::uint16_t locate() const { return static_cast<std::uint16_t>(be16(p + 1)); }
    char cross_type() const { return static_cast<char>(p[3]); }
};
struct CtlIWriter {
    std::uint8_t* p;
    explicit CtlIWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 4); p[0] = 'I'; }
    CtlIWriter& locate(std::uint16_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 2); return *this; }
    CtlIWriter& cross_type(char v) { p[3] = static_cast<std::uint8_t>(v); return *this; }
};
inline std::string csv(const CtlI& m) { return std::to_string(m.locate()) + "," + std::string(1, m.cross_type()); }
inline void rewrite(const CtlI& m, std::uint8_t* out) { CtlIWriter(out).locate(m.locate()).cross_type(m.cross_type()); }

// ctl R: 15 bytes
struct CtlR {
    static constexpr char kType = 'R';
    static constexpr std::size_t kLength = 15;
    const std::uint8_t* p;
    std::uint16_t locate() const { return static_cast<std::uint16_t>(be16(p + 1)); }
    std::uint32_t ref_price() const { return static_cast<std::uint32_t>(be32(p + 3)); }
    std::uint32_t band_lo() const { return static_cast<std::uint32_t>(be32(p + 7)); }
    std::uint32_t band_hi() const { return static_cast<std::uint32_t>(be32(p + 11)); }
};
struct CtlRWriter {
    std::uint8_t* p;
    explicit CtlRWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 15); p[0] = 'R'; }
    CtlRWriter& locate(std::uint16_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 2); return *this; }
    CtlRWriter& ref_price(std::uint32_t v) { put_be(p + 3, static_cast<std::uint64_t>(v), 4); return *this; }
    CtlRWriter& band_lo(std::uint32_t v) { put_be(p + 7, static_cast<std::uint64_t>(v), 4); return *this; }
    CtlRWriter& band_hi(std::uint32_t v) { put_be(p + 11, static_cast<std::uint64_t>(v), 4); return *this; }
};
inline std::string csv(const CtlR& m) { return std::to_string(m.locate()) + "," + std::to_string(m.ref_price()) + "," + std::to_string(m.band_lo()) + "," + std::to_string(m.band_hi()); }
inline void rewrite(const CtlR& m, std::uint8_t* out) { CtlRWriter(out).locate(m.locate()).ref_price(m.ref_price()).band_lo(m.band_lo()).band_hi(m.band_hi()); }

// ctl E: 4 bytes
struct CtlE {
    static constexpr char kType = 'E';
    static constexpr std::size_t kLength = 4;
    const std::uint8_t* p;
    std::uint16_t locate() const { return static_cast<std::uint16_t>(be16(p + 1)); }
    char tif() const { return static_cast<char>(p[3]); }
};
struct CtlEWriter {
    std::uint8_t* p;
    explicit CtlEWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 4); p[0] = 'E'; }
    CtlEWriter& locate(std::uint16_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 2); return *this; }
    CtlEWriter& tif(char v) { p[3] = static_cast<std::uint8_t>(v); return *this; }
};
inline std::string csv(const CtlE& m) { return std::to_string(m.locate()) + "," + std::string(1, m.tif()); }
inline void rewrite(const CtlE& m, std::uint8_t* out) { CtlEWriter(out).locate(m.locate()).tif(m.tif()); }

// ctl F: 4 bytes
struct CtlF {
    static constexpr char kType = 'F';
    static constexpr std::size_t kLength = 4;
    const std::uint8_t* p;
    std::uint16_t locate() const { return static_cast<std::uint16_t>(be16(p + 1)); }
    char freeze() const { return static_cast<char>(p[3]); }
};
struct CtlFWriter {
    std::uint8_t* p;
    explicit CtlFWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 4); p[0] = 'F'; }
    CtlFWriter& locate(std::uint16_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 2); return *this; }
    CtlFWriter& freeze(char v) { p[3] = static_cast<std::uint8_t>(v); return *this; }
};
inline std::string csv(const CtlF& m) { return std::to_string(m.locate()) + "," + std::string(1, m.freeze()); }
inline void rewrite(const CtlF& m, std::uint8_t* out) { CtlFWriter(out).locate(m.locate()).freeze(m.freeze()); }

// ctl S: 2 bytes
struct CtlS {
    static constexpr char kType = 'S';
    static constexpr std::size_t kLength = 2;
    const std::uint8_t* p;
    char event() const { return static_cast<char>(p[1]); }
};
struct CtlSWriter {
    std::uint8_t* p;
    explicit CtlSWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 2); p[0] = 'S'; }
    CtlSWriter& event(char v) { p[1] = static_cast<std::uint8_t>(v); return *this; }
};
inline std::string csv(const CtlS& m) { return std::string(1, m.event()); }
inline void rewrite(const CtlS& m, std::uint8_t* out) { CtlSWriter(out).event(m.event()); }

// ctl N: 11 bytes
struct CtlN {
    static constexpr char kType = 'N';
    static constexpr std::size_t kLength = 11;
    const std::uint8_t* p;
    std::uint16_t locate() const { return static_cast<std::uint16_t>(be16(p + 1)); }
    std::uint32_t bid() const { return static_cast<std::uint32_t>(be32(p + 3)); }
    std::uint32_t ask() const { return static_cast<std::uint32_t>(be32(p + 7)); }
};
struct CtlNWriter {
    std::uint8_t* p;
    explicit CtlNWriter(std::uint8_t* q) : p(q) { std::memset(p, 0, 11); p[0] = 'N'; }
    CtlNWriter& locate(std::uint16_t v) { put_be(p + 1, static_cast<std::uint64_t>(v), 2); return *this; }
    CtlNWriter& bid(std::uint32_t v) { put_be(p + 3, static_cast<std::uint64_t>(v), 4); return *this; }
    CtlNWriter& ask(std::uint32_t v) { put_be(p + 7, static_cast<std::uint64_t>(v), 4); return *this; }
};
inline std::string csv(const CtlN& m) { return std::to_string(m.locate()) + "," + std::to_string(m.bid()) + "," + std::to_string(m.ask()); }
inline void rewrite(const CtlN& m, std::uint8_t* out) { CtlNWriter(out).locate(m.locate()).bid(m.bid()).ask(m.ask()); }

// Calls v(<ctl message>) for one message of the ctl protocol; false if the type is
// unknown or the length does not match it.
template <class V>
bool dispatch_ctl(const std::uint8_t* p, std::size_t n, V&& v) {
    if (n == 0) return false;
    switch (p[0]) {
        case 'L': if (n != CtlL::kLength) return false; v(CtlL{p}); return true;
        case 'D': if (n != CtlD::kLength) return false; v(CtlD{p}); return true;
        case 'P': if (n != CtlP::kLength) return false; v(CtlP{p}); return true;
        case 'X': if (n != CtlX::kLength) return false; v(CtlX{p}); return true;
        case 'I': if (n != CtlI::kLength) return false; v(CtlI{p}); return true;
        case 'R': if (n != CtlR::kLength) return false; v(CtlR{p}); return true;
        case 'E': if (n != CtlE::kLength) return false; v(CtlE{p}); return true;
        case 'F': if (n != CtlF::kLength) return false; v(CtlF{p}); return true;
        case 'S': if (n != CtlS::kLength) return false; v(CtlS{p}); return true;
        case 'N': if (n != CtlN::kLength) return false; v(CtlN{p}); return true;
        default: return false;
    }
}

// MoldUDP64 packet header: session alpha10, sequence number of the first message u64, count u16.
struct MoldHeader {
    static constexpr std::size_t kLength = 20;
    const std::uint8_t* p;
    std::string_view session() const { return {reinterpret_cast<const char*>(p), 10}; }
    std::uint64_t seq() const { return be64(p + 10); }
    std::uint16_t count() const { return be16(p + 18); }
};

// Calls f(message pointer, length) for each message block of a packet; false if the packet is short.
template <class F>
bool for_each_block(const std::uint8_t* p, std::size_t n, F&& f) {
    if (n < MoldHeader::kLength) return false;
    const std::uint16_t c = MoldHeader{p}.count();
    if (c == 0 || c == 0xFFFF) return true;
    std::size_t i = MoldHeader::kLength;
    for (std::uint16_t k = 0; k < c; ++k) {
        if (i + 2 > n) return false;
        const std::size_t len = be16(p + i);
        if (i + 2 + len > n) return false;
        f(p + i + 2, len);
        i += 2 + len;
    }
    return true;
}

}  // namespace firm::wire
