[package]
name = "ll_rust"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "ll_rust_bench"
path = "src/bin/ll_rust_bench.rs"

[dependencies]
firm_arena = { path = "../../../firm/arena/rust" }
firm_feed = { path = "../../../firm/feed/rust" }
firm_ubench = { path = "../../../firm/ubench/rust" }

[profile.release]
debug = false
