"""Chapter 5 of Book 6: SABR in rates and the volatility cube. A negative-rate smile fitted with
shifted SABR at several shifts and with normal SABR; the implied density of a long-expiry smile;
and a synthetic euro cube (4 expiries x 4 tenors x 7 strikes) calibrated section by section and
interpolated to a missing section. The market smiles are generated by normal SABR with smooth
parameters plus seeded noise (illustrative, not market data)."""
import datetime as dt
import math
import pathlib
import sys

import numpy as np

ROOT = pathlib.Path(__file__).resolve().parents[4]
sys.path.insert(0, str(ROOT / "code/firm/sabrcube"))
sys.path.insert(0, str(ROOT / "code/firm/capfloor"))
sys.path.insert(0, str(ROOT / "code/rates-credit-risk/02-multi-curve-and-collateral-discounting/python"))
import rc_multicurve as mc  # noqa: E402
from firm_capfloor import forward_swap  # noqa: E402
from firm_multicurve import add_months  # noqa: E402
from firm_sabrcube import Cube, Sabr, calibrate_section, density, hagan_normal_beta0, normal_vol, price  # noqa: E402

# ---- a negative-rate smile (a one-year option on a two-year swap, 2020-style) -------------------------
NEG_F, NEG_T = -0.0030, 1.0
NEG_TRUE = Sabr(0.0025, 0.0, 0.10, 0.60)
NEG_OFFSETS = [-50, -25, 0, 25, 50, 100]


def neg_quotes():
    ks = [NEG_F + d * 1e-4 for d in NEG_OFFSETS]
    return ks, [hagan_normal_beta0(NEG_F, k, NEG_T, NEG_TRUE) for k in ks]


def neg_fits(shifts=(0.01, 0.03)):
    ks, q = neg_quotes()
    out = {f"shift{s}": calibrate_section(NEG_F, NEG_T, ks, q, 0.5, s) for s in shifts}
    out["normal"] = calibrate_section(NEG_F, NEG_T, ks, q, 0.0, 0.0, "normal")
    return out


def deep_receiver(strike: float = -0.0090) -> dict[str, float]:
    """Price per unit annuity (bp) of a receiver struck deep below the quoted strikes."""
    fits = neg_fits()
    return {name: 1e4 * price(NEG_F, strike, NEG_T, p, payer=False, model="normal" if name == "normal" else "shifted")
            for name, (p, _) in fits.items()}


def smallest_positive_shift(grid_lo: float = -0.0080, shifts=(0.0085, 0.009, 0.0095, 0.01)) -> float:
    """Smallest shift (from a list) whose calibrated smile has a positive density from grid_lo to 1%."""
    ks, q = neg_quotes()
    grid = [x * 1e-4 for x in range(round(grid_lo * 1e4), 101)]
    for s in shifts:
        p, _ = calibrate_section(NEG_F, NEG_T, ks, q, 0.5, s)
        if min(density(NEG_F, NEG_T, p, grid)) > 0:
            return s
    return float("nan")


# ---- a long-expiry smile and its density ------------------------------------------------------------------
LONG_F, LONG_T = 0.025, 10.0
LONG_TRUE = Sabr(0.0080, 0.0, -0.10, 0.30)
LONG_OFFSETS = [-200, -100, -50, 0, 50, 100, 200]


def long_fits(shifts=(0.01, 0.03)):
    ks = [LONG_F + d * 1e-4 for d in LONG_OFFSETS]
    q = [hagan_normal_beta0(LONG_F, k, LONG_T, LONG_TRUE) for k in ks]
    return {s: calibrate_section(LONG_F, LONG_T, ks, q, 0.5, s) for s in shifts}


def density_table(step_bp: int = 5):
    fits = long_fits()
    rows = []
    for x in range(-95, 701, step_bp):
        k = x * 1e-4
        row = [x / 100]
        for s, (p, _) in fits.items():
            row.append(density(LONG_F, LONG_T, p, [k])[0] if k > -s else float("nan"))
        row.append(density(LONG_F, LONG_T, LONG_TRUE, [k], model="normal")[0])
        rows.append(row)
    return rows


# ---- the cube -------------------------------------------------------------------------------------------------
EXPIRIES = [1.0, 2.0, 5.0, 10.0]
TENORS = [2, 5, 10, 30]
OFFSETS = [-200, -100, -50, 0, 50, 100, 200]
SHIFT = 0.03


def true_params(e: float, n: float) -> Sabr:
    """Smooth 'market' normal-SABR parameters by expiry and tenor (illustrative)."""
    atm = 0.0060 + 0.0028 * (1 - math.exp(-e / 3)) - 0.0006 * math.log(n / 2)
    return Sabr(atm, 0.0, -0.05 - 0.02 * e - 0.004 * n, 0.15 + 0.55 * math.exp(-e / 6), 0.0)


def forward(e: float, n: int) -> float:
    ex = add_months(mc.SPOT, int(round(12 * e)))
    return forward_swap(PROJ, DISC, ex, n)[0]


DISC = mc.discount()
PROJ = mc.projection(DISC)


def market_quotes(e: float, n: int, seed: int = 5):
    rng = np.random.default_rng(seed + int(100 * e) + n)
    f = forward(e, n)
    ks = [f + d * 1e-4 for d in OFFSETS]
    tp = true_params(e, n)
    return f, ks, [hagan_normal_beta0(f, k, e, tp) + float(rng.normal(0, 0.3e-4)) for k in ks]


def build_cube() -> tuple[Cube, dict]:
    sections, forwards, errors = {}, {}, {}
    for e in EXPIRIES:
        for n in TENORS:
            f, ks, q = market_quotes(e, n)
            p, err = calibrate_section(f, e, ks, q, 0.5, SHIFT)
            sections[(e, float(n))], forwards[(e, float(n))], errors[(e, n)] = p, f, err
    return Cube(EXPIRIES, [float(n) for n in TENORS], sections, forwards), errors


def missing_section(e: float = 3.0, n: int = 7) -> dict:
    """Interpolated versus 'true' normal volatilities of a section that is not quoted."""
    cube, _ = build_cube()
    f = forward(e, n)
    tp = true_params(e, n)
    rows = [(d, 1e4 * cube.normal_vol(e, n, f + d * 1e-4, f), 1e4 * hagan_normal_beta0(f, f + d * 1e-4, e, tp))
            for d in OFFSETS]
    return {"f": f, "rows": rows, "max_err": max(abs(a - b) for _, a, b in rows)}


def matrix_table():
    cube, _ = build_cube()
    return [(e, *[1e4 * cube.normal_vol(e, n, cube.forwards[(e, float(n))]) for n in TENORS]) for e in EXPIRIES]


__all__ = ["dt", "normal_vol"]
