#!/usr/bin/env python3
"""Phase A generator: chapter briefs (top of each source ledger), the
definition map, part.tex / solutions.tex and empty chapter files.

    python3 tools/make_briefs.py --book 2

The data of book N lives in tools/briefs/book<N>.py (SLUG, PFX, HEAD, PARTS).
Idempotent for the skeleton: it never overwrites an existing chapter,
solutions or ledger file. part.tex, solutions.tex and DEFINITIONS.md are
regenerated -- do not re-run it for a finished book whose map was edited by
hand (Book 1's was). Run from the repository root.
"""
import argparse
import collections
import importlib
import os
import sys


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--book", type=int, required=True)
    args = ap.parse_args()
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    data = importlib.import_module("briefs.book%d" % args.book)
    SLUG, PFX, PARTS = data.SLUG, data.PFX, data.PARTS
    os.makedirs(f"sources/{SLUG}", exist_ok=True)
    os.makedirs(f"parts/{SLUG}/solutions", exist_ok=True)
    part_lines = [f"% {data.HEAD}. Parts and chapters, in reading order.",
                  "% Generated by tools/make_briefs.py (order only; edit there)."]
    sol_lines = []
    defs = collections.defaultdict(list)
    n = 0
    for key, chapters in PARTS:
        part_lines += ["", f"\\part{{\\omstr{{{key}}}}}"]
        for ch in chapters:
            n += 1
            slug = ch["slug"]
            label = slug.split("-", 1)[1]
            part_lines.append(f"\\ominput{{{SLUG}}}{{{slug}}}")
            sol_lines.append(f"\\ominputsol{{{SLUG}}}{{{slug}}}")
            for d in ch["defines"]:
                defs[d].append(slug)
            led = f"sources/{SLUG}/{slug}.md"
            if not os.path.exists(led):
                with open(led, "w", encoding="utf8") as f:
                    f.write(f"# {n}. {ch['title']} — brief and source ledger\n\n## Brief\n\n")
                    f.write(f"- **Hook.** {ch['hook']}\n")
                    f.write("- **Sections.** " + "; ".join(ch["sections"]) + ".\n")
                    f.write("- **Defines.** " + (", ".join(ch["defines"]) or "nothing (uses only)") + ".\n")
                    if ch.get("uses"):
                        f.write("- **Uses (defined earlier).** " + ", ".join(ch["uses"]) + ".\n")
                    if ch.get("strategies"):
                        f.write("- **Strategy files.** " + "; ".join(ch["strategies"]) + ".\n")
                    if ch.get("tutorial"):
                        f.write(f"- **Tutorial.** {ch['tutorial']}\n")
                    if ch.get("build"):
                        f.write(f"- **Build.** {ch['build']}\n")
                    if ch.get("problem"):
                        f.write(f"- **Weekend problem.** {ch['problem']}\n")
                    if ch.get("bank"):
                        f.write(f"- **Question bank.** {ch['bank']}\n")
                    f.write("- **Facts to verify.** " + "; ".join(ch.get("facts", [])) + ".\n")
                    if ch.get("data"):
                        f.write(f"- **Data.** {ch['data']}\n")
                    f.write("\n")
                    f.write("## Ledger\n\n| id | claim | source | URL | accessed | evidence | used in |\n|---|---|---|---|---|---|---|\n\n## EXCLUDED\n\n")
            cfile = f"parts/{SLUG}/{slug}.tex"
            if not os.path.exists(cfile):
                with open(cfile, "w", encoding="utf8") as f:
                    f.write(f"\\chapter{{{ch['title']}}}\\label{{ch:{PFX}:{label}}}\n\n% TODO\n")
            sfile = f"parts/{SLUG}/solutions/{slug}.tex"
            if not os.path.exists(sfile):
                with open(sfile, "w", encoding="utf8") as f:
                    f.write(f"\\section*{{Chapter \\ref{{ch:{PFX}:{label}}} --- {ch['title']}}}\n\\mbox{{}}\n\n% TODO\n")
    open(f"parts/{SLUG}/part.tex", "w", encoding="utf8").write("\n".join(part_lines) + "\n")
    open(f"parts/{SLUG}/solutions/solutions.tex", "w", encoding="utf8").write("\n".join(sol_lines) + "\n")
    with open(f"sources/{SLUG}/DEFINITIONS.md", "w", encoding="utf8") as f:
        f.write(f"# Book {args.book} definition map (term -> defining chapter)\n\n| term | chapter |\n|---|---|\n")
        for d in sorted(defs, key=str.lower):
            f.write(f"| {d} | {', '.join(defs[d])} |\n")
    dup = {d: c for d, c in defs.items() if len(c) > 1}
    print(f"{n} chapters, {len(defs)} terms, duplicates: {dup or 'none'}")


if __name__ == "__main__":
    main()
