// GENERATED by code/firm/wirecodec/gen_wirecodec.py from code/firm/exchsim/schema.json: do not edit.
//! Big-endian flyweights over the simulator's wire formats, the twin of firm_wirecodec.hpp.

#[inline]
fn be(b: &[u8], o: usize, n: usize) -> u64 {
    let mut v = [0u8; 8];
    v[8 - n..].copy_from_slice(&b[o..o + n]);
    u64::from_be_bytes(v)
}

/// feed A: 36 bytes
#[derive(Clone, Copy)]
pub struct FeedA<'a>(pub &'a [u8]);

impl<'a> FeedA<'a> {
    pub const TYPE: u8 = b'A';
    pub const LENGTH: usize = 36;
    pub fn locate(&self) -> u16 {
        be(self.0, 1, 2) as u16
    }
    pub fn tracking(&self) -> u16 {
        be(self.0, 3, 2) as u16
    }
    pub fn ts(&self) -> u64 {
        be(self.0, 5, 6) as u64
    }
    pub fn r#ref(&self) -> u64 {
        be(self.0, 11, 8) as u64
    }
    pub fn side(&self) -> u8 {
        self.0[19]
    }
    pub fn shares(&self) -> u32 {
        be(self.0, 20, 4) as u32
    }
    pub fn stock(&self) -> &'a [u8] {
        &self.0[24..32]
    }
    pub fn price(&self) -> u32 {
        be(self.0, 32, 4) as u32
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.locate().to_string(),
            self.tracking().to_string(),
            self.ts().to_string(),
            self.r#ref().to_string(),
            (self.side() as char).to_string(),
            self.shares().to_string(),
            String::from_utf8_lossy(self.stock()).trim_end_matches(' ').to_string(),
            self.price().to_string(),
        ]
        .join(",")
    }
}

/// feed E: 31 bytes
#[derive(Clone, Copy)]
pub struct FeedE<'a>(pub &'a [u8]);

impl<'a> FeedE<'a> {
    pub const TYPE: u8 = b'E';
    pub const LENGTH: usize = 31;
    pub fn locate(&self) -> u16 {
        be(self.0, 1, 2) as u16
    }
    pub fn tracking(&self) -> u16 {
        be(self.0, 3, 2) as u16
    }
    pub fn ts(&self) -> u64 {
        be(self.0, 5, 6) as u64
    }
    pub fn r#ref(&self) -> u64 {
        be(self.0, 11, 8) as u64
    }
    pub fn shares(&self) -> u32 {
        be(self.0, 19, 4) as u32
    }
    pub fn r#match(&self) -> u64 {
        be(self.0, 23, 8) as u64
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.locate().to_string(),
            self.tracking().to_string(),
            self.ts().to_string(),
            self.r#ref().to_string(),
            self.shares().to_string(),
            self.r#match().to_string(),
        ]
        .join(",")
    }
}

/// feed X: 23 bytes
#[derive(Clone, Copy)]
pub struct FeedX<'a>(pub &'a [u8]);

impl<'a> FeedX<'a> {
    pub const TYPE: u8 = b'X';
    pub const LENGTH: usize = 23;
    pub fn locate(&self) -> u16 {
        be(self.0, 1, 2) as u16
    }
    pub fn tracking(&self) -> u16 {
        be(self.0, 3, 2) as u16
    }
    pub fn ts(&self) -> u64 {
        be(self.0, 5, 6) as u64
    }
    pub fn r#ref(&self) -> u64 {
        be(self.0, 11, 8) as u64
    }
    pub fn shares(&self) -> u32 {
        be(self.0, 19, 4) as u32
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.locate().to_string(),
            self.tracking().to_string(),
            self.ts().to_string(),
            self.r#ref().to_string(),
            self.shares().to_string(),
        ]
        .join(",")
    }
}

/// feed D: 19 bytes
#[derive(Clone, Copy)]
pub struct FeedD<'a>(pub &'a [u8]);

impl<'a> FeedD<'a> {
    pub const TYPE: u8 = b'D';
    pub const LENGTH: usize = 19;
    pub fn locate(&self) -> u16 {
        be(self.0, 1, 2) as u16
    }
    pub fn tracking(&self) -> u16 {
        be(self.0, 3, 2) as u16
    }
    pub fn ts(&self) -> u64 {
        be(self.0, 5, 6) as u64
    }
    pub fn r#ref(&self) -> u64 {
        be(self.0, 11, 8) as u64
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.locate().to_string(),
            self.tracking().to_string(),
            self.ts().to_string(),
            self.r#ref().to_string(),
        ]
        .join(",")
    }
}

/// feed P: 44 bytes
#[derive(Clone, Copy)]
pub struct FeedP<'a>(pub &'a [u8]);

impl<'a> FeedP<'a> {
    pub const TYPE: u8 = b'P';
    pub const LENGTH: usize = 44;
    pub fn locate(&self) -> u16 {
        be(self.0, 1, 2) as u16
    }
    pub fn tracking(&self) -> u16 {
        be(self.0, 3, 2) as u16
    }
    pub fn ts(&self) -> u64 {
        be(self.0, 5, 6) as u64
    }
    pub fn r#ref(&self) -> u64 {
        be(self.0, 11, 8) as u64
    }
    pub fn side(&self) -> u8 {
        self.0[19]
    }
    pub fn shares(&self) -> u32 {
        be(self.0, 20, 4) as u32
    }
    pub fn stock(&self) -> &'a [u8] {
        &self.0[24..32]
    }
    pub fn price(&self) -> u32 {
        be(self.0, 32, 4) as u32
    }
    pub fn r#match(&self) -> u64 {
        be(self.0, 36, 8) as u64
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.locate().to_string(),
            self.tracking().to_string(),
            self.ts().to_string(),
            self.r#ref().to_string(),
            (self.side() as char).to_string(),
            self.shares().to_string(),
            String::from_utf8_lossy(self.stock()).trim_end_matches(' ').to_string(),
            self.price().to_string(),
            self.r#match().to_string(),
        ]
        .join(",")
    }
}

/// feed U: 35 bytes
#[derive(Clone, Copy)]
pub struct FeedU<'a>(pub &'a [u8]);

impl<'a> FeedU<'a> {
    pub const TYPE: u8 = b'U';
    pub const LENGTH: usize = 35;
    pub fn locate(&self) -> u16 {
        be(self.0, 1, 2) as u16
    }
    pub fn tracking(&self) -> u16 {
        be(self.0, 3, 2) as u16
    }
    pub fn ts(&self) -> u64 {
        be(self.0, 5, 6) as u64
    }
    pub fn r#ref(&self) -> u64 {
        be(self.0, 11, 8) as u64
    }
    pub fn new_ref(&self) -> u64 {
        be(self.0, 19, 8) as u64
    }
    pub fn shares(&self) -> u32 {
        be(self.0, 27, 4) as u32
    }
    pub fn price(&self) -> u32 {
        be(self.0, 31, 4) as u32
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.locate().to_string(),
            self.tracking().to_string(),
            self.ts().to_string(),
            self.r#ref().to_string(),
            self.new_ref().to_string(),
            self.shares().to_string(),
            self.price().to_string(),
        ]
        .join(",")
    }
}

/// feed C: 36 bytes
#[derive(Clone, Copy)]
pub struct FeedC<'a>(pub &'a [u8]);

impl<'a> FeedC<'a> {
    pub const TYPE: u8 = b'C';
    pub const LENGTH: usize = 36;
    pub fn locate(&self) -> u16 {
        be(self.0, 1, 2) as u16
    }
    pub fn tracking(&self) -> u16 {
        be(self.0, 3, 2) as u16
    }
    pub fn ts(&self) -> u64 {
        be(self.0, 5, 6) as u64
    }
    pub fn r#ref(&self) -> u64 {
        be(self.0, 11, 8) as u64
    }
    pub fn shares(&self) -> u32 {
        be(self.0, 19, 4) as u32
    }
    pub fn r#match(&self) -> u64 {
        be(self.0, 23, 8) as u64
    }
    pub fn printable(&self) -> u8 {
        self.0[31]
    }
    pub fn price(&self) -> u32 {
        be(self.0, 32, 4) as u32
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.locate().to_string(),
            self.tracking().to_string(),
            self.ts().to_string(),
            self.r#ref().to_string(),
            self.shares().to_string(),
            self.r#match().to_string(),
            (self.printable() as char).to_string(),
            self.price().to_string(),
        ]
        .join(",")
    }
}

/// feed Q: 40 bytes
#[derive(Clone, Copy)]
pub struct FeedQ<'a>(pub &'a [u8]);

impl<'a> FeedQ<'a> {
    pub const TYPE: u8 = b'Q';
    pub const LENGTH: usize = 40;
    pub fn locate(&self) -> u16 {
        be(self.0, 1, 2) as u16
    }
    pub fn tracking(&self) -> u16 {
        be(self.0, 3, 2) as u16
    }
    pub fn ts(&self) -> u64 {
        be(self.0, 5, 6) as u64
    }
    pub fn shares(&self) -> u64 {
        be(self.0, 11, 8) as u64
    }
    pub fn stock(&self) -> &'a [u8] {
        &self.0[19..27]
    }
    pub fn price(&self) -> u32 {
        be(self.0, 27, 4) as u32
    }
    pub fn r#match(&self) -> u64 {
        be(self.0, 31, 8) as u64
    }
    pub fn cross_type(&self) -> u8 {
        self.0[39]
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.locate().to_string(),
            self.tracking().to_string(),
            self.ts().to_string(),
            self.shares().to_string(),
            String::from_utf8_lossy(self.stock()).trim_end_matches(' ').to_string(),
            self.price().to_string(),
            self.r#match().to_string(),
            (self.cross_type() as char).to_string(),
        ]
        .join(",")
    }
}

/// feed I: 50 bytes
#[derive(Clone, Copy)]
pub struct FeedI<'a>(pub &'a [u8]);

impl<'a> FeedI<'a> {
    pub const TYPE: u8 = b'I';
    pub const LENGTH: usize = 50;
    pub fn locate(&self) -> u16 {
        be(self.0, 1, 2) as u16
    }
    pub fn tracking(&self) -> u16 {
        be(self.0, 3, 2) as u16
    }
    pub fn ts(&self) -> u64 {
        be(self.0, 5, 6) as u64
    }
    pub fn paired(&self) -> u64 {
        be(self.0, 11, 8) as u64
    }
    pub fn imbalance(&self) -> u64 {
        be(self.0, 19, 8) as u64
    }
    pub fn direction(&self) -> u8 {
        self.0[27]
    }
    pub fn stock(&self) -> &'a [u8] {
        &self.0[28..36]
    }
    pub fn far(&self) -> u32 {
        be(self.0, 36, 4) as u32
    }
    pub fn near(&self) -> u32 {
        be(self.0, 40, 4) as u32
    }
    pub fn ref_price(&self) -> u32 {
        be(self.0, 44, 4) as u32
    }
    pub fn cross_type(&self) -> u8 {
        self.0[48]
    }
    pub fn variation(&self) -> u8 {
        self.0[49]
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.locate().to_string(),
            self.tracking().to_string(),
            self.ts().to_string(),
            self.paired().to_string(),
            self.imbalance().to_string(),
            (self.direction() as char).to_string(),
            String::from_utf8_lossy(self.stock()).trim_end_matches(' ').to_string(),
            self.far().to_string(),
            self.near().to_string(),
            self.ref_price().to_string(),
            (self.cross_type() as char).to_string(),
            (self.variation() as char).to_string(),
        ]
        .join(",")
    }
}

/// feed S: 12 bytes
#[derive(Clone, Copy)]
pub struct FeedS<'a>(pub &'a [u8]);

impl<'a> FeedS<'a> {
    pub const TYPE: u8 = b'S';
    pub const LENGTH: usize = 12;
    pub fn locate(&self) -> u16 {
        be(self.0, 1, 2) as u16
    }
    pub fn tracking(&self) -> u16 {
        be(self.0, 3, 2) as u16
    }
    pub fn ts(&self) -> u64 {
        be(self.0, 5, 6) as u64
    }
    pub fn event(&self) -> u8 {
        self.0[11]
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.locate().to_string(),
            self.tracking().to_string(),
            self.ts().to_string(),
            (self.event() as char).to_string(),
        ]
        .join(",")
    }
}

/// feed H: 25 bytes
#[derive(Clone, Copy)]
pub struct FeedH<'a>(pub &'a [u8]);

impl<'a> FeedH<'a> {
    pub const TYPE: u8 = b'H';
    pub const LENGTH: usize = 25;
    pub fn locate(&self) -> u16 {
        be(self.0, 1, 2) as u16
    }
    pub fn tracking(&self) -> u16 {
        be(self.0, 3, 2) as u16
    }
    pub fn ts(&self) -> u64 {
        be(self.0, 5, 6) as u64
    }
    pub fn stock(&self) -> &'a [u8] {
        &self.0[11..19]
    }
    pub fn state(&self) -> u8 {
        self.0[19]
    }
    pub fn reserved(&self) -> u8 {
        self.0[20]
    }
    pub fn reason(&self) -> &'a [u8] {
        &self.0[21..25]
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.locate().to_string(),
            self.tracking().to_string(),
            self.ts().to_string(),
            String::from_utf8_lossy(self.stock()).trim_end_matches(' ').to_string(),
            (self.state() as char).to_string(),
            (self.reserved() as char).to_string(),
            String::from_utf8_lossy(self.reason()).trim_end_matches(' ').to_string(),
        ]
        .join(",")
    }
}

/// feed R: 28 bytes
#[derive(Clone, Copy)]
pub struct FeedR<'a>(pub &'a [u8]);

impl<'a> FeedR<'a> {
    pub const TYPE: u8 = b'R';
    pub const LENGTH: usize = 28;
    pub fn locate(&self) -> u16 {
        be(self.0, 1, 2) as u16
    }
    pub fn tracking(&self) -> u16 {
        be(self.0, 3, 2) as u16
    }
    pub fn ts(&self) -> u64 {
        be(self.0, 5, 6) as u64
    }
    pub fn stock(&self) -> &'a [u8] {
        &self.0[11..19]
    }
    pub fn tick(&self) -> u32 {
        be(self.0, 19, 4) as u32
    }
    pub fn lot(&self) -> u32 {
        be(self.0, 23, 4) as u32
    }
    pub fn matching(&self) -> u8 {
        self.0[27]
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.locate().to_string(),
            self.tracking().to_string(),
            self.ts().to_string(),
            String::from_utf8_lossy(self.stock()).trim_end_matches(' ').to_string(),
            self.tick().to_string(),
            self.lot().to_string(),
            (self.matching() as char).to_string(),
        ]
        .join(",")
    }
}

/// feed G: 23 bytes
#[derive(Clone, Copy)]
pub struct FeedG<'a>(pub &'a [u8]);

impl<'a> FeedG<'a> {
    pub const TYPE: u8 = b'G';
    pub const LENGTH: usize = 23;
    pub fn locate(&self) -> u16 {
        be(self.0, 1, 2) as u16
    }
    pub fn tracking(&self) -> u16 {
        be(self.0, 3, 2) as u16
    }
    pub fn ts(&self) -> u64 {
        be(self.0, 5, 6) as u64
    }
    pub fn seq(&self) -> u64 {
        be(self.0, 11, 8) as u64
    }
    pub fn orders(&self) -> u32 {
        be(self.0, 19, 4) as u32
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.locate().to_string(),
            self.tracking().to_string(),
            self.ts().to_string(),
            self.seq().to_string(),
            self.orders().to_string(),
        ]
        .join(",")
    }
}

/// feed W: 23 bytes
#[derive(Clone, Copy)]
pub struct FeedW<'a>(pub &'a [u8]);

impl<'a> FeedW<'a> {
    pub const TYPE: u8 = b'W';
    pub const LENGTH: usize = 23;
    pub fn locate(&self) -> u16 {
        be(self.0, 1, 2) as u16
    }
    pub fn tracking(&self) -> u16 {
        be(self.0, 3, 2) as u16
    }
    pub fn ts(&self) -> u64 {
        be(self.0, 5, 6) as u64
    }
    pub fn seq(&self) -> u64 {
        be(self.0, 11, 8) as u64
    }
    pub fn crc(&self) -> u32 {
        be(self.0, 19, 4) as u32
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.locate().to_string(),
            self.tracking().to_string(),
            self.ts().to_string(),
            self.seq().to_string(),
            self.crc().to_string(),
        ]
        .join(",")
    }
}

/// in O: 38 bytes
#[derive(Clone, Copy)]
pub struct InO<'a>(pub &'a [u8]);

impl<'a> InO<'a> {
    pub const TYPE: u8 = b'O';
    pub const LENGTH: usize = 38;
    pub fn cl_ord_id(&self) -> u64 {
        be(self.0, 1, 8) as u64
    }
    pub fn locate(&self) -> u16 {
        be(self.0, 9, 2) as u16
    }
    pub fn side(&self) -> u8 {
        self.0[11]
    }
    pub fn qty(&self) -> u32 {
        be(self.0, 12, 4) as u32
    }
    pub fn price(&self) -> u32 {
        be(self.0, 16, 4) as u32
    }
    pub fn tif(&self) -> u8 {
        self.0[20]
    }
    pub fn display(&self) -> u8 {
        self.0[21]
    }
    pub fn post_only(&self) -> u8 {
        self.0[22]
    }
    pub fn display_qty(&self) -> u32 {
        be(self.0, 23, 4) as u32
    }
    pub fn min_qty(&self) -> u32 {
        be(self.0, 27, 4) as u32
    }
    pub fn stp_group(&self) -> u16 {
        be(self.0, 31, 2) as u16
    }
    pub fn stp_mode(&self) -> u8 {
        self.0[33]
    }
    pub fn stop_price(&self) -> u32 {
        be(self.0, 34, 4) as u32
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.cl_ord_id().to_string(),
            self.locate().to_string(),
            (self.side() as char).to_string(),
            self.qty().to_string(),
            self.price().to_string(),
            (self.tif() as char).to_string(),
            (self.display() as char).to_string(),
            (self.post_only() as char).to_string(),
            self.display_qty().to_string(),
            self.min_qty().to_string(),
            self.stp_group().to_string(),
            (self.stp_mode() as char).to_string(),
            self.stop_price().to_string(),
        ]
        .join(",")
    }
}

/// in U: 25 bytes
#[derive(Clone, Copy)]
pub struct InU<'a>(pub &'a [u8]);

impl<'a> InU<'a> {
    pub const TYPE: u8 = b'U';
    pub const LENGTH: usize = 25;
    pub fn cl_ord_id(&self) -> u64 {
        be(self.0, 1, 8) as u64
    }
    pub fn new_cl_ord_id(&self) -> u64 {
        be(self.0, 9, 8) as u64
    }
    pub fn qty(&self) -> u32 {
        be(self.0, 17, 4) as u32
    }
    pub fn price(&self) -> u32 {
        be(self.0, 21, 4) as u32
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.cl_ord_id().to_string(),
            self.new_cl_ord_id().to_string(),
            self.qty().to_string(),
            self.price().to_string(),
        ]
        .join(",")
    }
}

/// in X: 13 bytes
#[derive(Clone, Copy)]
pub struct InX<'a>(pub &'a [u8]);

impl<'a> InX<'a> {
    pub const TYPE: u8 = b'X';
    pub const LENGTH: usize = 13;
    pub fn cl_ord_id(&self) -> u64 {
        be(self.0, 1, 8) as u64
    }
    pub fn leave_qty(&self) -> u32 {
        be(self.0, 9, 4) as u32
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.cl_ord_id().to_string(),
            self.leave_qty().to_string(),
        ]
        .join(",")
    }
}

/// in M: 4 bytes
#[derive(Clone, Copy)]
pub struct InM<'a>(pub &'a [u8]);

impl<'a> InM<'a> {
    pub const TYPE: u8 = b'M';
    pub const LENGTH: usize = 4;
    pub fn locate(&self) -> u16 {
        be(self.0, 1, 2) as u16
    }
    pub fn side(&self) -> u8 {
        self.0[3]
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.locate().to_string(),
            (self.side() as char).to_string(),
        ]
        .join(",")
    }
}

/// in Q: 27 bytes
#[derive(Clone, Copy)]
pub struct InQ<'a>(pub &'a [u8]);

impl<'a> InQ<'a> {
    pub const TYPE: u8 = b'Q';
    pub const LENGTH: usize = 27;
    pub fn quote_id(&self) -> u64 {
        be(self.0, 1, 8) as u64
    }
    pub fn locate(&self) -> u16 {
        be(self.0, 9, 2) as u16
    }
    pub fn bid_price(&self) -> u32 {
        be(self.0, 11, 4) as u32
    }
    pub fn bid_qty(&self) -> u32 {
        be(self.0, 15, 4) as u32
    }
    pub fn ask_price(&self) -> u32 {
        be(self.0, 19, 4) as u32
    }
    pub fn ask_qty(&self) -> u32 {
        be(self.0, 23, 4) as u32
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.quote_id().to_string(),
            self.locate().to_string(),
            self.bid_price().to_string(),
            self.bid_qty().to_string(),
            self.ask_price().to_string(),
            self.ask_qty().to_string(),
        ]
        .join(",")
    }
}

/// out S: 10 bytes
#[derive(Clone, Copy)]
pub struct OutS<'a>(pub &'a [u8]);

impl<'a> OutS<'a> {
    pub const TYPE: u8 = b'S';
    pub const LENGTH: usize = 10;
    pub fn ts(&self) -> u64 {
        be(self.0, 1, 8) as u64
    }
    pub fn event(&self) -> u8 {
        self.0[9]
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.ts().to_string(),
            (self.event() as char).to_string(),
        ]
        .join(",")
    }
}

/// out A: 39 bytes
#[derive(Clone, Copy)]
pub struct OutA<'a>(pub &'a [u8]);

impl<'a> OutA<'a> {
    pub const TYPE: u8 = b'A';
    pub const LENGTH: usize = 39;
    pub fn ts(&self) -> u64 {
        be(self.0, 1, 8) as u64
    }
    pub fn cl_ord_id(&self) -> u64 {
        be(self.0, 9, 8) as u64
    }
    pub fn r#ref(&self) -> u64 {
        be(self.0, 17, 8) as u64
    }
    pub fn locate(&self) -> u16 {
        be(self.0, 25, 2) as u16
    }
    pub fn side(&self) -> u8 {
        self.0[27]
    }
    pub fn qty(&self) -> u32 {
        be(self.0, 28, 4) as u32
    }
    pub fn price(&self) -> u32 {
        be(self.0, 32, 4) as u32
    }
    pub fn tif(&self) -> u8 {
        self.0[36]
    }
    pub fn display(&self) -> u8 {
        self.0[37]
    }
    pub fn state(&self) -> u8 {
        self.0[38]
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.ts().to_string(),
            self.cl_ord_id().to_string(),
            self.r#ref().to_string(),
            self.locate().to_string(),
            (self.side() as char).to_string(),
            self.qty().to_string(),
            self.price().to_string(),
            (self.tif() as char).to_string(),
            (self.display() as char).to_string(),
            (self.state() as char).to_string(),
        ]
        .join(",")
    }
}

/// out U: 42 bytes
#[derive(Clone, Copy)]
pub struct OutU<'a>(pub &'a [u8]);

impl<'a> OutU<'a> {
    pub const TYPE: u8 = b'U';
    pub const LENGTH: usize = 42;
    pub fn ts(&self) -> u64 {
        be(self.0, 1, 8) as u64
    }
    pub fn cl_ord_id(&self) -> u64 {
        be(self.0, 9, 8) as u64
    }
    pub fn new_cl_ord_id(&self) -> u64 {
        be(self.0, 17, 8) as u64
    }
    pub fn r#ref(&self) -> u64 {
        be(self.0, 25, 8) as u64
    }
    pub fn qty(&self) -> u32 {
        be(self.0, 33, 4) as u32
    }
    pub fn price(&self) -> u32 {
        be(self.0, 37, 4) as u32
    }
    pub fn priority(&self) -> u8 {
        self.0[41]
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.ts().to_string(),
            self.cl_ord_id().to_string(),
            self.new_cl_ord_id().to_string(),
            self.r#ref().to_string(),
            self.qty().to_string(),
            self.price().to_string(),
            (self.priority() as char).to_string(),
        ]
        .join(",")
    }
}

/// out C: 22 bytes
#[derive(Clone, Copy)]
pub struct OutC<'a>(pub &'a [u8]);

impl<'a> OutC<'a> {
    pub const TYPE: u8 = b'C';
    pub const LENGTH: usize = 22;
    pub fn ts(&self) -> u64 {
        be(self.0, 1, 8) as u64
    }
    pub fn cl_ord_id(&self) -> u64 {
        be(self.0, 9, 8) as u64
    }
    pub fn decrement(&self) -> u32 {
        be(self.0, 17, 4) as u32
    }
    pub fn reason(&self) -> u8 {
        self.0[21]
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.ts().to_string(),
            self.cl_ord_id().to_string(),
            self.decrement().to_string(),
            (self.reason() as char).to_string(),
        ]
        .join(",")
    }
}

/// out E: 46 bytes
#[derive(Clone, Copy)]
pub struct OutE<'a>(pub &'a [u8]);

impl<'a> OutE<'a> {
    pub const TYPE: u8 = b'E';
    pub const LENGTH: usize = 46;
    pub fn ts(&self) -> u64 {
        be(self.0, 1, 8) as u64
    }
    pub fn cl_ord_id(&self) -> u64 {
        be(self.0, 9, 8) as u64
    }
    pub fn qty(&self) -> u32 {
        be(self.0, 17, 4) as u32
    }
    pub fn price(&self) -> u32 {
        be(self.0, 21, 4) as u32
    }
    pub fn r#match(&self) -> u64 {
        be(self.0, 25, 8) as u64
    }
    pub fn liquidity(&self) -> u8 {
        self.0[33]
    }
    pub fn fee(&self) -> i64 {
        be(self.0, 34, 8) as i64
    }
    pub fn leaves(&self) -> u32 {
        be(self.0, 42, 4) as u32
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.ts().to_string(),
            self.cl_ord_id().to_string(),
            self.qty().to_string(),
            self.price().to_string(),
            self.r#match().to_string(),
            (self.liquidity() as char).to_string(),
            self.fee().to_string(),
            self.leaves().to_string(),
        ]
        .join(",")
    }
}

/// out J: 18 bytes
#[derive(Clone, Copy)]
pub struct OutJ<'a>(pub &'a [u8]);

impl<'a> OutJ<'a> {
    pub const TYPE: u8 = b'J';
    pub const LENGTH: usize = 18;
    pub fn ts(&self) -> u64 {
        be(self.0, 1, 8) as u64
    }
    pub fn cl_ord_id(&self) -> u64 {
        be(self.0, 9, 8) as u64
    }
    pub fn reason(&self) -> u8 {
        self.0[17]
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.ts().to_string(),
            self.cl_ord_id().to_string(),
            (self.reason() as char).to_string(),
        ]
        .join(",")
    }
}

/// ctl L: 8 bytes
#[derive(Clone, Copy)]
pub struct CtlL<'a>(pub &'a [u8]);

impl<'a> CtlL<'a> {
    pub const TYPE: u8 = b'L';
    pub const LENGTH: usize = 8;
    pub fn session(&self) -> u16 {
        be(self.0, 1, 2) as u16
    }
    pub fn firm(&self) -> u32 {
        be(self.0, 3, 4) as u32
    }
    pub fn cod(&self) -> u8 {
        self.0[7]
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.session().to_string(),
            self.firm().to_string(),
            (self.cod() as char).to_string(),
        ]
        .join(",")
    }
}

/// ctl D: 3 bytes
#[derive(Clone, Copy)]
pub struct CtlD<'a>(pub &'a [u8]);

impl<'a> CtlD<'a> {
    pub const TYPE: u8 = b'D';
    pub const LENGTH: usize = 3;
    pub fn session(&self) -> u16 {
        be(self.0, 1, 2) as u16
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.session().to_string(),
        ]
        .join(",")
    }
}

/// ctl P: 8 bytes
#[derive(Clone, Copy)]
pub struct CtlP<'a>(pub &'a [u8]);

impl<'a> CtlP<'a> {
    pub const TYPE: u8 = b'P';
    pub const LENGTH: usize = 8;
    pub fn locate(&self) -> u16 {
        be(self.0, 1, 2) as u16
    }
    pub fn phase(&self) -> u8 {
        self.0[3]
    }
    pub fn reason(&self) -> &'a [u8] {
        &self.0[4..8]
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.locate().to_string(),
            (self.phase() as char).to_string(),
            String::from_utf8_lossy(self.reason()).trim_end_matches(' ').to_string(),
        ]
        .join(",")
    }
}

/// ctl X: 4 bytes
#[derive(Clone, Copy)]
pub struct CtlX<'a>(pub &'a [u8]);

impl<'a> CtlX<'a> {
    pub const TYPE: u8 = b'X';
    pub const LENGTH: usize = 4;
    pub fn locate(&self) -> u16 {
        be(self.0, 1, 2) as u16
    }
    pub fn cross_type(&self) -> u8 {
        self.0[3]
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.locate().to_string(),
            (self.cross_type() as char).to_string(),
        ]
        .join(",")
    }
}

/// ctl I: 4 bytes
#[derive(Clone, Copy)]
pub struct CtlI<'a>(pub &'a [u8]);

impl<'a> CtlI<'a> {
    pub const TYPE: u8 = b'I';
    pub const LENGTH: usize = 4;
    pub fn locate(&self) -> u16 {
        be(self.0, 1, 2) as u16
    }
    pub fn cross_type(&self) -> u8 {
        self.0[3]
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.locate().to_string(),
            (self.cross_type() as char).to_string(),
        ]
        .join(",")
    }
}

/// ctl R: 15 bytes
#[derive(Clone, Copy)]
pub struct CtlR<'a>(pub &'a [u8]);

impl<'a> CtlR<'a> {
    pub const TYPE: u8 = b'R';
    pub const LENGTH: usize = 15;
    pub fn locate(&self) -> u16 {
        be(self.0, 1, 2) as u16
    }
    pub fn ref_price(&self) -> u32 {
        be(self.0, 3, 4) as u32
    }
    pub fn band_lo(&self) -> u32 {
        be(self.0, 7, 4) as u32
    }
    pub fn band_hi(&self) -> u32 {
        be(self.0, 11, 4) as u32
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.locate().to_string(),
            self.ref_price().to_string(),
            self.band_lo().to_string(),
            self.band_hi().to_string(),
        ]
        .join(",")
    }
}

/// ctl E: 4 bytes
#[derive(Clone, Copy)]
pub struct CtlE<'a>(pub &'a [u8]);

impl<'a> CtlE<'a> {
    pub const TYPE: u8 = b'E';
    pub const LENGTH: usize = 4;
    pub fn locate(&self) -> u16 {
        be(self.0, 1, 2) as u16
    }
    pub fn tif(&self) -> u8 {
        self.0[3]
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.locate().to_string(),
            (self.tif() as char).to_string(),
        ]
        .join(",")
    }
}

/// ctl F: 4 bytes
#[derive(Clone, Copy)]
pub struct CtlF<'a>(pub &'a [u8]);

impl<'a> CtlF<'a> {
    pub const TYPE: u8 = b'F';
    pub const LENGTH: usize = 4;
    pub fn locate(&self) -> u16 {
        be(self.0, 1, 2) as u16
    }
    pub fn freeze(&self) -> u8 {
        self.0[3]
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.locate().to_string(),
            (self.freeze() as char).to_string(),
        ]
        .join(",")
    }
}

/// ctl S: 2 bytes
#[derive(Clone, Copy)]
pub struct CtlS<'a>(pub &'a [u8]);

impl<'a> CtlS<'a> {
    pub const TYPE: u8 = b'S';
    pub const LENGTH: usize = 2;
    pub fn event(&self) -> u8 {
        self.0[1]
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            (self.event() as char).to_string(),
        ]
        .join(",")
    }
}

/// ctl N: 11 bytes
#[derive(Clone, Copy)]
pub struct CtlN<'a>(pub &'a [u8]);

impl<'a> CtlN<'a> {
    pub const TYPE: u8 = b'N';
    pub const LENGTH: usize = 11;
    pub fn locate(&self) -> u16 {
        be(self.0, 1, 2) as u16
    }
    pub fn bid(&self) -> u32 {
        be(self.0, 3, 4) as u32
    }
    pub fn ask(&self) -> u32 {
        be(self.0, 7, 4) as u32
    }
    /// The fields in schema order, as the golden CSVs print them.
    pub fn csv(&self) -> String {
        [
            self.locate().to_string(),
            self.bid().to_string(),
            self.ask().to_string(),
        ]
        .join(",")
    }
}

/// The CSV text of one feed message (type and length checked), or None.
pub fn csv_feed(m: &[u8]) -> Option<String> {
    match (m.first()?, m.len()) {
        (b'A', 36) => Some(FeedA(m).csv()),
        (b'E', 31) => Some(FeedE(m).csv()),
        (b'X', 23) => Some(FeedX(m).csv()),
        (b'D', 19) => Some(FeedD(m).csv()),
        (b'P', 44) => Some(FeedP(m).csv()),
        (b'U', 35) => Some(FeedU(m).csv()),
        (b'C', 36) => Some(FeedC(m).csv()),
        (b'Q', 40) => Some(FeedQ(m).csv()),
        (b'I', 50) => Some(FeedI(m).csv()),
        (b'S', 12) => Some(FeedS(m).csv()),
        (b'H', 25) => Some(FeedH(m).csv()),
        (b'R', 28) => Some(FeedR(m).csv()),
        (b'G', 23) => Some(FeedG(m).csv()),
        (b'W', 23) => Some(FeedW(m).csv()),
        _ => None,
    }
}

/// The CSV text of one in message (type and length checked), or None.
pub fn csv_in(m: &[u8]) -> Option<String> {
    match (m.first()?, m.len()) {
        (b'O', 38) => Some(InO(m).csv()),
        (b'U', 25) => Some(InU(m).csv()),
        (b'X', 13) => Some(InX(m).csv()),
        (b'M', 4) => Some(InM(m).csv()),
        (b'Q', 27) => Some(InQ(m).csv()),
        _ => None,
    }
}

/// The CSV text of one out message (type and length checked), or None.
pub fn csv_out(m: &[u8]) -> Option<String> {
    match (m.first()?, m.len()) {
        (b'S', 10) => Some(OutS(m).csv()),
        (b'A', 39) => Some(OutA(m).csv()),
        (b'U', 42) => Some(OutU(m).csv()),
        (b'C', 22) => Some(OutC(m).csv()),
        (b'E', 46) => Some(OutE(m).csv()),
        (b'J', 18) => Some(OutJ(m).csv()),
        _ => None,
    }
}

/// The CSV text of one ctl message (type and length checked), or None.
pub fn csv_ctl(m: &[u8]) -> Option<String> {
    match (m.first()?, m.len()) {
        (b'L', 8) => Some(CtlL(m).csv()),
        (b'D', 3) => Some(CtlD(m).csv()),
        (b'P', 8) => Some(CtlP(m).csv()),
        (b'X', 4) => Some(CtlX(m).csv()),
        (b'I', 4) => Some(CtlI(m).csv()),
        (b'R', 15) => Some(CtlR(m).csv()),
        (b'E', 4) => Some(CtlE(m).csv()),
        (b'F', 4) => Some(CtlF(m).csv()),
        (b'S', 2) => Some(CtlS(m).csv()),
        (b'N', 11) => Some(CtlN(m).csv()),
        _ => None,
    }
}

/// MoldUDP64 packet header.
pub struct MoldHeader<'a>(pub &'a [u8]);

impl MoldHeader<'_> {
    pub const LENGTH: usize = 20;
    pub fn seq(&self) -> u64 {
        be(self.0, 10, 8)
    }
    pub fn count(&self) -> u16 {
        be(self.0, 18, 2) as u16
    }
}
